### ISSUE TITLE
Cannot connect to ratbagd

### ISSUE THREAD

**Issue by JohnnyMorbo** [libratbag/libratbag#1004]
I'm pretty sure ratbagd is working, but piper just shows me the trap.

`sudo ratbagctl list`
warbling-mara:       Logitech G300s Optical Gaming Mouse
hollering-marmot:    Logitech G512 Carbon Tactile
`sudo ratbagctl warbling-mara info`
warbling-mara - Logitech G300s Optical Gaming Mouse
Model: usb:046d:c246:0
Number of Buttons: 9
Number of Leds: 1
Number of Profiles: 3
Profile 0: (active)
< yattayattayatta >

`piper`
![image](https://user-images.githubusercontent.com/8323502/84095565-a16ebb80-a9cd-11ea-818f-8d317d0b44d9.png)

piper 0.4-2.1
libratbag-0.14-1.2
python 3.8.3
kernel 5.6.14-1-default
openSUSE Tumbleweed

What is the required group?

**Comment by FFY00** [comment]
`ratbagctl` works because it is running as sudo. How did you install? It seems like the DBus permissions are not correct, this should not happen.

**Comment by JohnnyMorbo** [comment]
It seems I had a stale ~/.dbus file.  It had an entry from 2018!
I deleted that .dbus file and piper is working as expected now.
Thank you for your help.

**Comment by JohnnyMorbo** [comment]
Well, it's doing the same thing again.  I had to re-install linux (because _reasons_) so I re-installed ratbagd and piper.  Now I have piper 0.5-1.1
When I start piper from the command line I get an error because ratbagd isn't running yet:
`File "/usr/lib/python3.8/site-packages/piper/ratbagd.py", line 268, in _on_properties_changed
object_paths = [d._object_path for d in self._devices]
AttributeError: 'Ratbagd' object has no attribute '_devices'`
If I wait a few seconds for ratbagd to start, and try piper again I get the trap:
![1_ntV90C5eUGtAz8DahpT9Ng](https://user-images.githubusercontent.com/8323502/84598169-bc5e8700-ae36-11ea-9e00-0c59003bb3f7.jpeg)
dbus-daemon throws a message:
`Jun 14 11:56:04 linux-wavy dbus-daemon[1054]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.137" (uid=1000 pid=10112 comm="/usr/bin/python3 /usr/bin/piper>`
There aren't any .dbus files in my home directory this time.  I don't understand how I could have broken my permissions.
I realize it's not really your job to debug my dbus problems, but I would really appreciate it if you could help point me in the right direction.

**Comment by FFY00** [comment]
How did you install?

**Comment by JohnnyMorbo** [comment]
The usual way for openSUSE:
sudo zypper install ratbagd piper
