### ISSUE TITLE
ratbag error: Unknown driver roccat-kone-pure in roccat-kone-pure.device persists

### ISSUE THREAD

**Issue by Vectrex** [libratbag/libratbag#1006]
#999 persists for me on both Ubuntu 18.04 and 20.04.
I installed the most recent packages from 
https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git
The roccat-kone-pure.device file was updated with the new USB signatures and I assume the repo reflects the most recent commits but the driver is still not found and thus results in

```
gregor@leia:~$ sudo service ratbagd status
● ratbagd.service - Daemon to introspect and modify configurable mice
   Loaded: loaded (/lib/systemd/system/ratbagd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-06-10 10:18:12 CEST; 1min 8s ago
 Main PID: 15127 (ratbagd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/ratbagd.service
           └─15127 /usr/bin/ratbagd

Jun 10 10:18:12 leia systemd[1]: Starting Daemon to introspect and modify configurable mice...
Jun 10 10:18:12 leia systemd[1]: Started Daemon to introspect and modify configurable mice.
Jun 10 10:18:12 leia ratbagd[15127]: ratbag error: Unknown driver roccat-kone-pure in roccat-kone-pure.device
Jun 10 10:18:12 leia ratbagd[15127]: ratbag error: Unknown driver roccat-kone-pure in roccat-kone-pure.device
```

**Comment by stephanlachnit** [comment]
> #999 persists for me on both Ubuntu 18.04 and 20.04.
> I installed the most recent packages from
> https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git
> The roccat-kone-pure.device file was updated with the new USB signatures and I assume the repo reflects the most recent commits but the driver is still not found

Can you verify it by running: `apt list --installed *ratbag*`?

**Comment by stephanlachnit** [comment]
Ah nevermind, the problem is that the driver is missing the entry here: https://github.com/libratbag/libratbag/blob/88a60f55b441c5c8484c7845e0dcf4a7ad0715f0/src/libratbag-data.c#L44

**Comment by Hag3nL** [comment]
Issue still persists in release 0.15 and the package using Linux Mint 20. Maybe because there is a roccat driver and a roccat-cone-pure driver but only the roccat is defined in libratbag-data.c?

I got it working by switching the driver-roccat.c and the driver-roccat-kone-pure.c and changing the driver to "roccat" in the roccat-kone-pure.device file (for a quick dirty cheap fix). But now I'm getting invalid dpi list error and ratbagctl can't find the device.

<details>
  <summary>Here's the ratbagd --verbose=raw output.</summary>

  ```
 Initializing libratbag
ratbag debug: New device: ROCCAT ROCCAT Kone Pure
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: device assigned driver roccat
ratbag debug: hidraw info: bus 0x03 vendor 0x1e7d product 0x2dbe
ratbag debug: ROCCAT ROCCAT Kone Pure is device '/dev/hidraw7'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 05
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 08
ratbag debug: - HID report ID 09
ratbag debug: - HID report ID 0a
ratbag debug: - HID report ID 0c
ratbag debug: - HID report ID 0d
ratbag debug: - HID report ID 0e
ratbag debug: - HID report ID 0f
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 1a
ratbag debug: - HID report ID 1b
ratbag debug: - HID report ID 1c
ratbag error: libratbag bug: ROCCAT ROCCAT Kone Pure: invalid dpi list
ratbag debug: New device: ROCCAT ROCCAT Kone Pure
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: device assigned driver roccat
ratbag debug: hidraw info: bus 0x03 vendor 0x1e7d product 0x2dbe
ratbag debug: ROCCAT ROCCAT Kone Pure is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: New device: UGTABLET 11.6 inch PenDisplay
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 28bd:091f
ratbag debug: New device: UGTABLET 11.6 inch PenDisplay
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 28bd:091f
ratbag debug: New device: UGTABLET 11.6 inch PenDisplay
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 28bd:091f
ratbag debug: New device: SteelSeries SteelSeries Apex M500 Gaming Keyboard
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 1038:1607
ratbag debug: New device: SteelSeries SteelSeries Apex M500 Gaming Keyboard
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 1038:1607
ratbag debug: New device: SteelSeries SteelSeries Apex M500 Gaming Keyboard
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 1038:1607
ratbag debug: New device: SteelSeries SteelSeries Apex M500 Gaming Keyboard
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 1038:1607
DBus server ready
  ```
</details>

To be honest the invalid dpi list might be a problem with my mouse and not the ratbagd. I'm going to check the mouse with the windows drivers if this is the case.

**Comment by Sethox** [comment]
I noticed that there is a "ROCCAT Kone Pure SEL" Mouse that has the name "ROCCAT KONE PURE" (on the mouse). A lsusb confirms it (Verbose):

`Bus 002 Device 009: ID 1e7d:2dcb ROCCAT Kone Pure SE(L) Mouse`
`idVendor` `0x1e7d ROCCAT`
`idProduct`          `0x2dcb Kone Pure SE(L) Mouse`
`bcdDevice            1.01`
`iManufacturer`           `1 ROCCAT`
`iProduct`                `2 ROCCAT Kone Pure SEL`
`iSerial                 3 000000000000`

For the longest time I thought I had a regular (not a SEL), thus always installing the none SEL version, stupid me. Also ratbag doesn't have this specific version. According to [Roccat themselves](https://en.roccat.org/Support/Product/Kone-Pure-SEL) it's a budget version.

**Comment by FFY00** [comment]
That USB PID is not in the .device file, can you open a PR adding it to https://github.com/libratbag/libratbag/blob/master/data/devices/roccat-kone-pure.device?

**Comment by Sethox** [comment]
> That USB PID is not in the .device file, can you open a PR adding it to https://github.com/libratbag/libratbag/blob/master/data/devices/roccat-kone-pure.device?

Alright but I'll open a new issue specific to my situation (since it might not be the authors problem).

**Comment by Sethox** [comment]
> That USB PID is not in the .device file, can you open a PR adding it to https://github.com/libratbag/libratbag/blob/master/data/devices/roccat-kone-pure.device?

Done #1152.
