### ISSUE TITLE
Glorious Model O support

### ISSUE THREAD

**Issue by aindriu80** [libratbag/libratbag#1007]
Can you please add support for the Glorious Model O mouse

Glorious Model O Website:
https://www.pcgamingrace.com/products/glorious-model-o-black

**Comment by aindriu80** [comment]
oh ok.  I have it in front of me.  What needs to be done with it?

**Comment by stephanlachnit** [comment]
> oh ok. I have it in front of me. What needs to be done with it?

You need to write a driver for it. Here are some things to help you get started:
https://github.com/libratbag/libratbag/wiki/Adding-a-device
https://www.youtube.com/watch?v=PSaRhC2hCO0
https://fosdem.org/2020/schedule/event/libratbag/

**Comment by enkore** [comment]
I reverse engineered the protocol a while ago, some C code is here: https://github.com/enkore/gloriousctl

I'm probably maybe going to add it to libratbag.

**Comment by stephanlachnit** [comment]
> I'm probably maybe going to add it to libratbag.

That would be pretty cool! If you need help somewhere, let me know it.

**Comment by staticssleever668** [comment]
Issue is fixed and should be closed.
