### ISSUE TITLE
Logitech G915 TKL is not recognized

### ISSUE THREAD

**Issue by zasran** [libratbag/libratbag#1008]
**Is your feature request related to a problem? Please describe.**

Logitech G915 TKL is not recognized ratbagctl (from ratbagd 0.13-1 which is part of Ubuntu 20.04). It's the new (released June 2020) smaller version of full size G915. It seems like G915 is recognized, judging by presence of /usr/share/libratbag/logitech-g915.device (also read that it was added to libratbag).

**Describe the solution you'd like**

Would like for G915 TKL to be recognized (all connections: lightspeed, bluetooth, wired) and to be able to set LEDs etc.

**Describe alternatives you've considered**

Tried lightspeed and wired connections, ran ratbagctl with and without sudo. None of those help.

**Additional context**

Output of ratbagctl (I do have MX Master 2S connected via bluetooth):

```
$ ratbagctl list
hooting-chinchilla:  MX Master 2S           
```         

When I connect the keyboard via USB cable I get following /var/log/syslog messages:
```
Jun 12 01:33:49 jozinko kernel: [12280.948661] usb 1-2: new full-speed USB device number 14 using xhci_hcd
Jun 12 01:33:49 jozinko kernel: [12281.100717] usb 1-2: New USB device found, idVendor=046d, idProduct=c343, bcdDevice=14.00
Jun 12 01:33:49 jozinko kernel: [12281.100725] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jun 12 01:33:49 jozinko kernel: [12281.100729] usb 1-2: Product: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
Jun 12 01:33:49 jozinko kernel: [12281.100732] usb 1-2: Manufacturer: Logitech
Jun 12 01:33:49 jozinko kernel: [12281.100735] usb 1-2: SerialNumber: BA346238
Jun 12 01:33:49 jozinko kernel: [12281.107039] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:046D:C343.000E/input/input41
Jun 12 01:33:49 jozinko kernel: [12281.169801] hid-generic 0003:046D:C343.000E: input,hidraw0: USB HID v1.11 Keyboard [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-2/input0
Jun 12 01:33:49 jozinko kernel: [12281.171862] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C343.000F/input/input42
Jun 12 01:33:49 jozinko kernel: [12281.228990] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C343.000F/input/input43
Jun 12 01:33:49 jozinko kernel: [12281.229368] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C343.000F/input/input44
Jun 12 01:33:49 jozinko kernel: [12281.229782] hid-generic 0003:046D:C343.000F: input,hidraw1: USB HID v1.11 Mouse [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-2/input1
Jun 12 01:33:49 jozinko kernel: [12281.231341] hid-generic 0003:046D:C343.0010: hiddev0,hidraw2: USB HID v1.11 Device [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-2/input2
```

**Comment by FFY00** [comment]
This is just a matter of adding the ID :smile:.

Can you try #1009? You can add the .device locally to test if you want.

To add support over Bluetooth, I need the ID. For Lightspeed it is probably gonna take a while since it needs changes in the kernel.

**Comment by FFY00** [comment]
Actually, sorry. That .device file should work for Ligtspeed, but is not the best way to handle it, we should add the receiver to the kernel driver. Can you tell me the USB ID when connected directly?

**Comment by zasran** [comment]
Here's all relevant info for all three connections (USB cable, lightspeed dongle, bluetooth). Hope that's what you need, let me know if there's anything else i can provide.

usb-devices output when G915 TKL is connected via USB cable:

T:  Bus=01 Lev=01 Prnt=01 Port=01 Cnt=01 Dev#= 16 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=046d ProdID=c343 Rev=14.00
S:  Manufacturer=Logitech
S:  Product=G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
S:  SerialNumber=BA346238
C:  #Ifs= 3 Cfg#= 1 Atr=e0 MxPwr=500mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=01 Driver=usbhid
I:  If#=0x1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
I:  If#=0x2 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid

syslog output when G915 TKL is connected via USB cable:

Jun 13 00:48:24 jozinko kernel: [95955.746223] usb 1-1: new full-speed USB device number 18 using xhci_hcd
Jun 13 00:48:24 jozinko kernel: [95955.897788] usb 1-1: New USB device found, idVendor=046d, idProduct=c343, bcdDevice=14.00
Jun 13 00:48:24 jozinko kernel: [95955.897796] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jun 13 00:48:24 jozinko kernel: [95955.897800] usb 1-1: Product: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
Jun 13 00:48:24 jozinko kernel: [95955.897804] usb 1-1: Manufacturer: Logitech
Jun 13 00:48:24 jozinko kernel: [95955.897807] usb 1-1: SerialNumber: BA346238
Jun 13 00:48:24 jozinko kernel: [95955.904655] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:046D:C343.001C/input/input63
Jun 13 00:48:24 jozinko kernel: [95955.963425] hid-generic 0003:046D:C343.001C: input,hidraw0: USB HID v1.11 Keyboard [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-1/input0
Jun 13 00:48:24 jozinko kernel: [95955.966058] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:046D:C343.001D/input/input64
Jun 13 00:48:24 jozinko kernel: [95956.026492] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:046D:C343.001D/input/input65
Jun 13 00:48:24 jozinko kernel: [95956.026932] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:046D:C343.001D/input/input66
Jun 13 00:48:24 jozinko kernel: [95956.027530] hid-generic 0003:046D:C343.001D: input,hidraw1: USB HID v1.11 Mouse [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-1/input1
Jun 13 00:48:24 jozinko kernel: [95956.029562] hid-generic 0003:046D:C343.001E: hiddev0,hidraw2: USB HID v1.11 Device [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-1/input2
Jun 13 00:48:24 jozinko mtp-probe: checking bus 1, device 18: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
Jun 13 00:48:24 jozinko mtp-probe: bus: 1, device: 18 was not an MTP device
Jun 13 00:48:24 jozinko mtp-probe: checking bus 1, device 18: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
Jun 13 00:48:24 jozinko mtp-probe: bus: 1, device: 18 was not an MTP device

When I connect it via lightspeed dongle then only dongle is visible via usb-devices:

T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#= 19 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=046d ProdID=c545 Rev=02.00
S:  Manufacturer=Logitech
S:  Product=USB Receiver
C:  #Ifs= 3 Cfg#= 1 Atr=a0 MxPwr=98mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
I:  If#=0x1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=01 Driver=usbhid
I:  If#=0x2 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid

syslog output when G915 TKL is connected via lightspeed dongle (when I connect the dongle):

Jun 13 00:51:12 jozinko kernel: [96123.720806] usb 1-1: new full-speed USB device number 20 using xhci_hcd
Jun 13 00:51:12 jozinko kernel: [96123.871433] usb 1-1: New USB device found, idVendor=046d, idProduct=c545, bcdDevice= 2.00
Jun 13 00:51:12 jozinko kernel: [96123.871438] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jun 13 00:51:12 jozinko kernel: [96123.871440] usb 1-1: Product: USB Receiver
Jun 13 00:51:12 jozinko kernel: [96123.871442] usb 1-1: Manufacturer: Logitech
Jun 13 00:51:12 jozinko kernel: [96123.875701] input: Logitech USB Receiver as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:046D:C545.0022/input/input71
Jun 13 00:51:12 jozinko kernel: [96123.876177] hid-generic 0003:046D:C545.0022: input,hidraw0: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:00:14.0-1/input0
Jun 13 00:51:12 jozinko kernel: [96123.878108] input: Logitech USB Receiver Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:046D:C545.0023/input/input72
Jun 13 00:51:12 jozinko kernel: [96123.937893] input: Logitech USB Receiver Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:046D:C545.0023/input/input73
Jun 13 00:51:12 jozinko kernel: [96123.938280] input: Logitech USB Receiver System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:046D:C545.0023/input/input74
Jun 13 00:51:12 jozinko kernel: [96123.938633] hid-generic 0003:046D:C545.0023: input,hidraw1: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:00:14.0-1/input1
Jun 13 00:51:12 jozinko kernel: [96123.940496] hid-generic 0003:046D:C545.0024: hiddev0,hidraw2: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:14.0-1/input2
Jun 13 00:51:12 jozinko mtp-probe: checking bus 1, device 20: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
Jun 13 00:51:12 jozinko mtp-probe: bus: 1, device: 20 was not an MTP device
Jun 13 00:51:12 jozinko mtp-probe: checking bus 1, device 20: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
Jun 13 00:51:12 jozinko mtp-probe: bus: 1, device: 20 was not an MTP device

bluetoothctl info for G915 TKL:

Device E0:C7:86:78:39:FC (random)
	Name: G915 TKL
	Alias: G915 TKL
	Appearance: 0x03c1
	Icon: input-keyboard
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
	UUID: Human Interface Device    (00001812-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (00010000-0000-1000-8000-011f2000046d)
	Modalias: usb:v046DpB35Fd0017
	RSSI: -42
	TxPower: 6

syslog output when G915 TKL is connected via bluetooth:

Jun 13 00:53:02 jozinko kernel: [96234.345363] input: G915 TKL Keyboard as /devices/virtual/misc/uhid/0005:046D:B35F.0025/input/input75
Jun 13 00:53:02 jozinko kernel: [96234.346501] input: G915 TKL Mouse as /devices/virtual/misc/uhid/0005:046D:B35F.0025/input/input76
Jun 13 00:53:02 jozinko kernel: [96234.347056] input: G915 TKL Consumer Control as /devices/virtual/misc/uhid/0005:046D:B35F.0025/input/input77
Jun 13 00:53:02 jozinko kernel: [96234.347391] hid-generic 0005:046D:B35F.0025: input,hidraw7: BLUETOOTH HID v0.17 Keyboard [G915 TKL] on 94:b8:6d:1e:e4:1f

**Comment by zasran** [comment]
Tried #1009, it works when keyboard is connected via USB cable (lightspeed, bluetooth do not work, keyboard is not recognized). BTW I also have Logitech MX Master 2S connected via bluetooth and it's recognized so I guess bluetooth and lightspeed need different ids or something? I added all the info I could think of in the other comment so maybe that will help.

Not sure if it's working as intended or not, here's output of ratbagctl info:

$ /usr/local/bin/ratbagctl hollering-marmot info
hollering-marmot - Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
             Model: usb:046d:c343:0
 Number of Buttons: 15
    Number of Leds: 2
Number of Profiles: 3
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Button: 0 is mapped to macro '↕F1'
  Button: 1 is mapped to macro '↕F2'
  Button: 2 is mapped to macro '↕F3'
  Button: 3 is mapped to macro '↕F4'
  Button: 4 is mapped to macro '↕F5'
  Button: 5 is mapped to macro '↕F6'
  Button: 6 is mapped to macro '↕F7'
  Button: 7 is mapped to macro '↕F8'
  Button: 8 is mapped to macro '↕F9'
  Button: 9 is mapped to macro '↕F10'
  Button: 10 is mapped to macro '↕F11'
  Button: 11 is mapped to macro '↕F12'
  Button: 12 is mapped to 'unknown'
  Button: 13 is mapped to 'unknown'
  Button: 14 is mapped to 'unknown'
  LED: 0, depth: rgb, mode: cycle, duration: 0, brightness: 255
  LED: 1, depth: rgb, mode: breathing, color: 44d424, duration: 0, brightness: 255
Profile 1: (disabled)
Profile 2: (disabled)

Here's what I figured out so far:

LED 0 is Logitech logo (big G in the left upper corner).
LED 1 is the rest of the keyboard (i.e. all the keys).

It seems that setting leds to solid color works, e.g. I can set logo to solid orange: /usr/local/bin/ratbagctl hollering-marmot led 0 set color e35f12

However setting modes doesn't have any effect, e.g. this does nothing visible /usr/local/bin/ratbagctl hollering-marmot led 0 set mode cycle (also tried other modes, no visible change).

Not sure where this setting is stored, the keyboard has few presets accessible via light key plus numbers 1 through 6 and two custom setting accessible via light key and 7, 8. However when I set colors they are not accessible via any of those shortcuts. So if I go to a different preset (e.g. press light key and 1 to go to first default preset) I cannot get back to my custom preset. Didn't find out how to store my setting in one of the custom settings either (light key plus 7, 8).

Is there any documentation about what should work and how for this keyboard (assuming it should work pretty much like full size G915, except of not having all the keys)? I looked at https://github.com/libratbag/libratbag/wiki/Devices but that only lists the devices.

**Comment by FFY00** [comment]
Sorry for the delay! I have added the bluetooth ID to #1009. For lightspeed, we need to add the receiver to the kernel driver and then add support for the device here. Would you be up to test a kernel patch?

**Comment by zasran** [comment]
Yes, I can test kernel patch, thanks!

What about the other functionality? Storing the given light settings under lightKey+7/8 would be very useful.

**Comment by FFY00** [comment]
Hi, I asked Logitech directly about this and it seems like this receiver does not support the DJ interface (for which we have a kernel driver), so we will have to make libratbag able to distinguish between devices when they are connected via the receiver. So it looks like Lightspeed support will still take a while :confused:. You can add the receiver ID directly to your .device file, but that is not suitable for distribution. You won't have issues as long as you don't have more (different) devices connected to a receiver with the same ID.

**Comment by FFY00** [comment]
> What about the other functionality? Storing the given light settings under lightKey+7/8 would be very useful.

You want to change the lighting for specific keys? Is this what you mean?

**Comment by zasran** [comment]
> > What about the other functionality? Storing the given light settings under lightKey+7/8 would be very useful.
> 
> You want to change the lighting for specific keys? Is this what you mean?

I mean that this keyboard has ability to store custom keyboards configuration (e.g. I have green keys and orange logo) so that it's recalled when I hit light key and 7 or 8 (i.e. two custom configs). It's just save and recall whatever the settings are.

It's useful because if I change settings I can easily get back to my stored settings or I can switch between two custom settings.

There are 6 preset settings accessible using lightspeed key + numbers 1-6 and two user settings accessible using lightspeed key and 7, 8.

**Comment by FFY00** [comment]
Ah, if they implement this via the onboard profiles it should already be possible by changing the different profiles. I have a G915 and G815 and I can change profiles (which include illumination settings) using the M-Keys. Does this work on your device?

**Comment by zasran** [comment]
> Ah, if they implement this via the onboard profiles it should already be possible by changing the different profiles. I have a G915 and G815 and I can change profiles (which include illumination settings) using the M-Keys. Does this work on your device?

Note: I referred to lightspeed+7/8 keyboard shortcuts in previous comments, it's really brightness+7/8 shortcuts (i.e. brightness key plus number 7 or 8).

Tried the profiles, I can set profiles 1 and 2 and then switch between them using 'ratbagctl $G915_ID profile active set 1' (or 2) where $G915_ID is from ratbatctl list. Seems that profiles are set correctly, i.e. when I set one or the other active the colors change appropriately (profile 1: orange/green, profile 2: red/blue).

However neither of these is what's accessible using brightness+7/8 keyboard shortcuts. Both keyboard shortcuts set some other color combination (blue, breathing) and don't affect active profile (ratbagctl $G915_ID profile active get).

Here's what I used to set profiles:

G915_ID=`ratbagctl list | grep 'Logitech G915 TKL' | cut -d ':' -f 1`
LOGO_LED=0
KEYS_LED=1
COLOR_ORANGE=f26d09
COLOR_GREEN=44d424
COLOR_RED=81031d
COLOR_BLUE=4424d4

ratbagctl $G915_ID profile 1 enable
ratbagctl $G915_ID profile 1 led $LOGO_LED set mode on      # solid color (not breathing, blinking etc.)
ratbagctl $G915_ID profile 1 led $LOGO_LED set color $COLOR_ORANGE
ratbagctl $G915_ID profile 1 led $KEYS_LED set mode on      # solid color (not breathing, blinking etc.)
ratbagctl $G915_ID profile 1 led $KEYS_LED set color $COLOR_GREEN
ratbagctl $G915_ID profile active set 1
ratbagctl $G915_ID profile active get # trust but verify ;)

ratbagctl $G915_ID profile 2 enable
ratbagctl $G915_ID profile 2 led $LOGO_LED set mode on      # solid color (not breathing, blinking etc.)
ratbagctl $G915_ID profile 2 led $LOGO_LED set color $COLOR_RED
ratbagctl $G915_ID profile 2 led $KEYS_LED set mode on      # solid color (not breathing, blinking etc.)
ratbagctl $G915_ID profile 2 led $KEYS_LED set color $COLOR_BLUE
ratbagctl $G915_ID profile active set 2
ratbagctl $G915_ID profile active get # trust but verify ;)

Not sure how to figure out what those keyboard shortcut activate or how to store settings there.It looks like it's not profiles. Any ideas what I can do to troubleshoot this further?
