### ISSUE TITLE
Logitech M720 Thriatlon not detected by ratbag

### ISSUE THREAD

**Issue by rurickdev** [libratbag/libratbag#1012]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.14
- Distribution: Endeavour Os (Arch based)
- Kernel version (ex. `uname -srmo`): `Linux 5.7.3-arch1-1 x86_64 GNU/Linux`

Device info (if applicable):
```
$ ratbagctl M720 Triathlon info
usage: /usr/bin/ratbagctl <device> {info,name,profile,resolution,dpi,rate,button,led} ...
/usr/bin/ratbagctl <device>: error: invalid choice: 'Triathlon' (choose from 'info', 'name', 'profile', 'resolution', 'dpi', 'rate', 'button', 'led')

$ ratbagctl "M720 Triathlon" info
Unable to find device M720 Triathlon
```

**Describe the bug**
A logitech Thriatlon (M720) conected with bluetooth is not detected by ratbag neither piper

**To Reproduce**
1. just connect the mouse by bluetooth

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw

Initializing libratbag
ratbag debug: New device: ELAN469D:00 04F3:304B
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04f3:304b
ratbag debug: New device: M720 Triathlon
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:b015
DBus server ready
```

**Comment by stephanlachnit** [comment]
Two issues here:
1. the USB-ID `046d:b015` is not known to libratbag, needs to be added (I push a PR once github stops having server errors^^)
2. you use `ratbagctl` wrong.

Here is an example on how to use it:
```
$ ratbagctl list
> cheering-viscacha:   Logitech G Pro Gaming Mouse     
$ ratbagctl cheering-viscacha info
> cheering-viscacha - Logitech G Pro Gaming Mouse
>              Model: usb:046d:c085:0
> [...]
```

**Comment by stephanlachnit** [comment]
@rurickdev can you try the changes from #1013? Simply edit `/usr/share/libratbag/logitech-M720.device` in the same way.
