### ISSUE TITLE
Cannot find any devices Logitech G203

### ISSUE THREAD

**Issue by robfrancken** [libratbag/libratbag#1014]
**Information**

- `ratbagd` version (`ratbagd --version`): (0.13):
- Distribution: Ubuntu 20.04
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-37-generic x86_64 GNU/Linux

Device info (if applicable):
Bus 005 Device 002: ID 046d:c092 Logitech, Inc. G203 LIGHTSYNC Gaming Mouse
```
$ ratbagctl 'Logitech G203' info                                                                                                                                                       
Unable to find device Logitech G203
```

**Describe the bug**
Upon launching the Piper application I get "Cannot find any devices"
![Screenshot from 2020-06-21 09-26-00](https://user-images.githubusercontent.com/14947976/85213414-7149f400-b3a1-11ea-8d0b-2ac694814323.png)

**To Reproduce**
1. Connect device via USB
2. `sudo apt install piper`
3. launch Piper

**Logs**
```
$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Logitech G203 LIGHTSYNC Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c092
ratbag debug: New device: Logitech G203 LIGHTSYNC Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c092
ratbag debug: New device: SHANWAN PS3 GamePad
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 054c:0268
ratbag debug: New device: Logitech Gaming Keyboard G610
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c333
ratbag debug: New device: Logitech Gaming Keyboard G610
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c333
DBus server ready

```

**Comment by FFY00** [comment]
Seems like your device has a different ID, you should be able to just add it to the .device file and get it to work :smile:. Do you want to submit a PR?

https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-g102-g203.device

**Comment by FFY00** [comment]
Btw, the G610 should also work with our driver, you can add a .device file for it. I am not sure if you will be able to configure much though, given the device limitations.

**Comment by robfrancken** [comment]
Thanks for the quick reply. I'm unable to build libratbag from source (dependency issue when I run `meson builddir`). Been Googling for a while but haven't found a solution, so I can't confirm that it works.

```sh
meson builddir                                                                                                                                        
The Meson build system
Version: 0.54.3
Source dir: /home/rob/Downloads/libratbag
Build dir: /home/rob/Downloads/libratbag/builddir
Build type: native build
Project name: libratbag
Project version: 0.14
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libudev found: YES 245
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency libevdev found: NO (tried pkgconfig and cmake)

meson.build:73:0: ERROR: Dependency "libevdev" not found, tried pkgconfig and cmake

```

**Comment by FFY00** [comment]
Since you are only changing the .device files, you can do that directly on disk. Otherwise, you need to install libevdev (including the headers), should be `libevdev-dev` on Debian/Ubuntu.

**Comment by robfrancken** [comment]
Sorry for being a noob, but where do I edit the device files if I installed via apt? Can't seem to find any info in the docs about it.

**Comment by robfrancken** [comment]
Alright, had something to eat and re-read the docs. Got it working and sent a PR :)

Thanks very much for helping out!

On a side note the device image seems to return a 404.

![Screenshot from 2020-06-21 15-59-04](https://user-images.githubusercontent.com/14947976/85217908-94dc6100-b3d8-11ea-8c69-7d531f2d0364.png)

**Comment by FFY00** [comment]
Ah, you should be able to edit the files in `/usr/share/libratbag/`.

**Comment by FFY00** [comment]
If you want, you can also send a PR to piper for it to use the correct SVG.

**Comment by robfrancken** [comment]
I have some work to do this week, but I'll try over the weekend.

**Comment by camilomarino** [comment]
I have exactly the same problem. Can you explain in more detail how I solve it? I'm a newbie and I don't know what to do with changing .device files

Thank you!

**Comment by robfrancken** [comment]
I'm presuming your device ID is the same as mine. You should check with `lsusb`

I'm on Ubuntu and did the following:

1. Locate the device file in `/usr/share/libratbag`
2. `sudo nano /usr/share/libratbag/logitech-g102-g203.device`
3. Copy/paste below in the file
```
# G102 and G203 (USB)
[Device]
Name=Logitech Gaming Mouse G102/G103
DeviceMatch=usb:046d:c084;usb:046d:c092
Driver=hidpp20
LedTypes=logo;side;
```
4. Save and exit (ctrl + x)
5. Restart piper

**Comment by camilomarino** [comment]
Thanks, this worked for me.

**Comment by mksime** [comment]
> I'm presuming your device ID is the same as mine. You should check with `lsusb`
> 
> I'm on Ubuntu and did the following:
> 
>     1. Locate the device file in `/usr/share/libratbag`
> 
>     2. `sudo nano /usr/share/libratbag/logitech-g102-g203.device`
> 
>     3. Copy/paste below in the file
> 
> 
> ```
> # G102 and G203 (USB)
> [Device]
> Name=Logitech Gaming Mouse G102/G103
> DeviceMatch=usb:046d:c084;usb:046d:c092
> Driver=hidpp20
> LedTypes=logo;side;
> ```
> 
>     1. Save and exit (ctrl + x)
> 
>     2. Restart piper

Thanks, I had the same problem and it worked for me too. I think it's worth nothing that, in order to get it working, I had to restart ratbagd too. So:
`sudo killall ratbagd
sudo systemctl start ratbagd.service`

**Comment by cesarbuendia** [comment]
> I'm presuming your device ID is the same as mine. You should check with `lsusb`
> 
> I'm on Ubuntu and did the following:
> 
> 1. Locate the device file in `/usr/share/libratbag`
> 2. `sudo nano /usr/share/libratbag/logitech-g102-g203.device`
> 3. Copy/paste below in the file
> 
> ```
> # G102 and G203 (USB)
> [Device]
> Name=Logitech Gaming Mouse G102/G103
> DeviceMatch=usb:046d:c084;usb:046d:c092
> Driver=hidpp20
> LedTypes=logo;side;
> ```
> 
> 4. Save and exit (ctrl + x)
> 5. Restart piper



> > I'm presuming your device ID is the same as mine. You should check with `lsusb`
> > I'm on Ubuntu and did the following:
> > ```
> > 1. Locate the device file in `/usr/share/libratbag`
> > 
> > 2. `sudo nano /usr/share/libratbag/logitech-g102-g203.device`
> > 
> > 3. Copy/paste below in the file
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > # G102 and G203 (USB)
> > [Device]
> > Name=Logitech Gaming Mouse G102/G103
> > DeviceMatch=usb:046d:c084;usb:046d:c092
> > Driver=hidpp20
> > LedTypes=logo;side;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 1. Save and exit (ctrl + x)
> > 
> > 2. Restart piper
> > ```
> 
> Thanks, I had the same problem and it worked for me too. I think it's worth nothing that, in order to get it working, I had to restart ratbagd too. So: `sudo killall ratbagd` `sudo systemctl start ratbagd.service`

thanks
it worked for me

**Comment by Marrluxia** [comment]
> I'm presuming your device ID is the same as mine. You should check with `lsusb`
> 
> I'm on Ubuntu and did the following:
> 
> 1. Locate the device file in `/usr/share/libratbag`
> 2. `sudo nano /usr/share/libratbag/logitech-g102-g203.device`
> 3. Copy/paste below in the file
> 
> ```
> # G102 and G203 (USB)
> [Device]
> Name=Logitech Gaming Mouse G102/G103
> DeviceMatch=usb:046d:c084;usb:046d:c092
> Driver=hidpp20
> LedTypes=logo;side;
> ```
> 
> 4. Save and exit (ctrl + x)
> 5. Restart piper

The file now contains (and still does not work for Ubuntu 22.04 LTS)
```
# G102, G103 and G203 (USB)
[Device]
Name=Logitech Gaming Mouse G102/G103/G203
DeviceMatch=usb:046d:c084;usb:046d:c092
Driver=hidpp20
LedTypes=logo;side;
```

I tried changing the file + restarting piper and it did not work. Piper was installed with ```sudo apt install  piper```

**Comment by staticssleever668** [comment]
>  restarting piper

You actually have to restart ratbagd after making changes to device files - the service that actually talks to the mice, Piper is just a frontend.
`systemctl restart ratbagd`

**Comment by opensourcecheemsburgers** [comment]
For those with the purple G203, it has a different USB ID of: `046d:c09d`.

```
# G102, G103 and G203 (USB)
[Device]
Name=Logitech Gaming Mouse G102/G103/G203
DeviceMatch=usb:046d:c084;usb:046d:c092;usb:046d:c09d
Driver=hidpp20
LedTypes=logo;side;
```
