### ISSUE TITLE
Latest flake8 fails

### ISSUE THREAD

**Issue by stephanlachnit** [libratbag/libratbag#1017]
The latest version of flake8 fails for `ratbagd.py`
```
ratbagd.py:196:33: F523 '...'.format(...) has unused arguments at position(s): 0
```
This is the relevant function:
https://github.com/libratbag/libratbag/blob/ceaa3c3ad5c7b4b7ebe1bc5ca8ae1c1a30ecb006/tools/ratbagd.py#L187-L203

/cc @FFY00 can you add flake8 to the arch CI in Piper and libratbag? Then we would have noticed it earlier, currently it only is used in Piper on Fedora and Ubuntu.

**Comment by whot** [comment]
fwiw, note that `ratbagd.py` can flow both ways, feel free to fix this in piper and then merge back to here.
