### ISSUE TITLE
Svive Titan V Pro Gaming Mouse

### ISSUE THREAD

**Issue by ktpx** [libratbag/libratbag#1032]
I have a Svive Titan V Pro, wonder if anyone have gotten this to work with libratbagd.

**Comment by FFY00** [comment]
Unfortunately, there is no support, I'd have to reverse engineer the protocol and write a driver.

**Comment by ktpx** [comment]
Not a widely used piece of hardware.  :D Thanks,

**Comment by FFY00** [comment]
Sure, but if you happen to have time sometime, I think it would be an interesting project :grin:.

**Comment by ktpx** [comment]
Sure.  Have not reverse engineered mouse drivers, so I'd need some pointers. :D
