### ISSUE TITLE
Kensington expert mouse wired trackball support

### ISSUE THREAD

**Issue by tillarnold** [libratbag/libratbag#1039]
I was wondering if it would be possible to add support for the Kensington expert mouse wired trackball. 
I followed https://blog.flozz.fr/2016/03/27/steelseries-rival-100-reverse-engineering-dun-peripherique-usb/:
I setup a Windows 10 VM and installed KensigntonWorks and used Wireshark to capture the USB data. 
The`dmesg` command only listed one HID interface when pluging the mouse in as opposed to the two listed in the tutorial.

When moving the trackball in the VM captured data appears in Wireshark however when changing button mappings (or anything else) in the KensigntonWorks software (moving the cursor with another mouse as not to create unnecessary output in Wireshark ) no data appears in Wireshark. The changed button mappings did work within the VM. Am I correct in my assumption that this means that the button mappings are done in software and thus the Kensignton trackball cannot be supported in libratbag? 

Thank you for your hard work on this amazing project!

P.S. using the exact same VM/wireshark setup I do see changes made to a Logitech MX Master 3 through Logitech options. Which leads me to believe that my setup is working.

**Comment by FFY00** [comment]
Yes, it looks like the configurations are done in software :/

**Comment by tillarnold** [comment]
Are devices like this (where there is no hardware support for configuration) in scope for libratbag? Or does libratbag focus only on devices with hardware support and doing configuration in software (emulating macros, remapping buttons) is better left to other tools?

**Comment by FFY00** [comment]
No, libratbag only configures hardware.

**Comment by tillarnold** [comment]
OK so then this issue can be closed as this device is out of scope for libratbag.
Thank you for your time.

**Comment by PadreAdamo** [comment]
This is on my list after the C18 project.

You can see my current work with the Kensington Expert Mouse trackball (wired) here:
https://github.com/padreadamo/kexpertmousetrackball
