### ISSUE TITLE
Piper can't acess ratbagd - permissions 

### ISSUE THREAD

**Issue by andrerodr** [libratbag/libratbag#1040]
Hello 
I reported it as well to the piper team
    ratbagd version 0.14
    Piper version: 0.5.1
    Distribution: Opensuse Tumbleweed
    Device: G703, MX518 Legendary (2018), MX Master 2S
    Kernel version Linux 5.8.0-1-default x86_64 GNU/Linux
    (5.7.x, 5.6.x)

Describe the bug
Piper can't connect to ratbagd as regular user, only as root. Also valid for ratbagctl.

Workaround
Add user account to games group "sudo usermod -a -G games 'YourUserName'
and reboot, as logout and login is not enough.

also :
https://github.com/libratbag/piper/issues/379#issuecomment-529874661
https://github.com/libratbag/libratbag/issues/802#issuecomment-525754861
I have the exact same output
```
andre@asus:~> cat /usr/share/dbus-1/system.d/org.freedesktop.ratbag1.conf
<?xml version="1.0"?> <!--*-nxml-*-->
<!DOCTYPE busconfig PUBLIC
        "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
        "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">

<busconfig>

        <policy user="root">
                <allow own="org.freedesktop.ratbag1"/>
                <allow send_destination="org.freedesktop.ratbag1"/>
                <allow receive_sender="org.freedesktop.ratbag1"/>
        </policy>

        <policy group="games">
                <allow send_destination="org.freedesktop.ratbag1"/>
                <allow receive_sender="org.freedesktop.ratbag1"/>
        </policy>

</busconfig>
andre@asus:~> 
```

```
# which ratbagd
/usr/sbin/ratbagd
# which ratbagctl
/usr/bin/ratbagctl
#
```

**Comment by staticssleever668** [comment]
By default access is given to everyone - see https://github.com/libratbag/libratbag/blob/98eec0941ac6af989369d90e4bbd4db642ec187d/meson.build#L463.
Package maintainers on your distro chose to use the `games` group to allow access, which is perfectly fine and they probably mention somewhere that you need to be in the group.
