### ISSUE TITLE
Is there any way to assign ENTER on mice?

### ISSUE THREAD

**Issue by chocosaj** [libratbag/libratbag#1041]
Using 0.5.1 and trying to assign enter/return on G600, but it's impossible to assign enter in macro mode. Is there any possible to add enter into fix button function option?

**Comment by staticssleever668** [comment]
Maybe this the case with older Piper versions, but it is possible to assign enter in the macro creation dialog now.
You can also do this through ratbagctl (the command line utility for libratbag):
`ratbagctl <device name> button <button index> action set macro KEY_ENTER`
