### ISSUE TITLE
cmake build precheck error: meson.build:369:1: Preliminary CMake check failed. meson.build:369:1: ERROR: Dependency "check" not found

### ISSUE THREAD

**Issue by blackweta** [libratbag/libratbag#1044]
**Information**

Not Applicable

Device info (if applicable):
```
$ ratbagctl <device> info
NA
```

**Describe the bug**
Build error following instructions on https://github.com/libratbag/libratbag
**To Reproduce**
cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

install required libraries
sudo apt install --install-recommends -y libsystemd0 libsystemd-dev  libunistring-dev gfortran libjson-glib-dev

git clone https://github.com/libratbag/libratbag.git
cd libratbag
meson builddir

**Logs**
Please start the daemon with verbosity and reproduce the issue.
Uploading build log
CONSOLE OUPUT:

black@xpslx:~/build$ cd /home/black/build/libratbag/
black@xpslx:~/build/libratbag$ meson builddir 
The Meson build system
Version: 0.53.2
Source dir: /home/black/build/libratbag
Build dir: /home/black/build/libratbag/builddir
Build type: native build
Project name: libratbag
Project version: 0.14
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libudev found: YES 245
Run-time dependency libevdev found: YES 1.9.0
Run-time dependency glib-2.0 found: YES 2.64.3
Run-time dependency json-glib-1.0 found: YES 1.4.4
Library m found: YES
Library unistring found: YES
Run-time dependency libsystemd found: YES 245
Run-time dependency systemd found: YES 245
WARNING: Project targeting '>= 0.40.0' but tried to use feature introduced in '0.50.0': install arg in configure_file
Configuring lur-command.1 using configuration
Program /home/black/build/libratbag/data/devices/data-parse-test.py found: YES (/home/black/build/libratbag/data/devices/data-parse-test.py)
Program /home/black/build/libratbag/data/devices/duplicate-check.py found: YES (/home/black/build/libratbag/data/devices/duplicate-check.py)
Program /home/black/build/libratbag/data/devices/receiver-check.py found: YES (/home/black/build/libratbag/data/devices/receiver-check.py)
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency check found: NO (tried pkgconfig and cmake)

meson.build:369:1: ERROR: Dependency "check" not found, tried pkgconfig and cmake

A full log can be found at /home/black/build/libratbag/builddir/meson-logs
[meson-log.txt](https://github.com/libratbag/libratbag/files/5106685/meson-log.txt)
/meson-log.txt

**Additional context**

**Comment by mercster** [comment]
Sorry... on Fedora 43 I have installed "check":

```
merc@quanta:~/mouse/libratbag$ rpm -q check
check-0.15.2-19.fc43.x86_64
```

and the meson builddir from libratbag is still giving me this error.

EDIT: also whoever named "check" deserves torture.  Try googling around for this.

EDIT: Ugh, it was check-devel... which, I know to install -dev packages, but whatever dnf listing I was giving didn't list it.  Sorry,
