### ISSUE TITLE
Add support for UtechSmart

### ISSUE THREAD

**Issue by tiotrom** [libratbag/libratbag#1047]
You can find all of the drivers here http://utechsmart.com/download. This is a very cheap and good mouse. Would be fantastic to add support for it :D.

**Comment by tiotrom** [comment]
Totally understand. I do not have the skills or the time to do it. Ideally would be for me to get involved and help with this. I am doing a lot of work when it comes to free education and open source, so I can't dedicate to this. But I appreciate your work a lot! Maybe someone else can do this if they find these mice good enough, so maybe leave this thread open if you wish.

**Comment by Queuecumber** [comment]
I have one of these in the mail, could you walk me through what needs to be done?

**Comment by andythedude** [comment]
I might take this up, I have two of these mice and haven’t been able to really program them easily since moving to Linux. Never written a driver before but I am a software engineer so I imagine I could figure it out with all the other stuff I’ve dabbled in. Any links to some general docs on how one might get started with reverse engineering the protocol?

**Comment by FFY00** [comment]
Hi, thank you for the interest!

See my reply here https://github.com/libratbag/libratbag/issues/1130#issuecomment-777924159

**Comment by FFY00** [comment]
For reverse engineering, you can pick up a recent copy of Wireshark and record the traffic between the mouse and the Windows driver. I generally spin up a Windows VM and run Wireshark from Linux but you can do it from Windows too, which may be useful if you don't want to use a VM.
If you start recording in Wiresahrk before plugging in the mouse, Wireshark will capture the HID descriptor and will be able to dissect the data. If it does, you can filter the relevant data with the `usbhid.data.vendor` filter.

After you are able to see the traffic, my general approach is to change something like a DPI value, see the traffic, and then change it with a different value. You can compare the two packets and try to figure out how configuring that field works, usually it's just a static value in the packet.
One thing to keep in mind when trying to interpret the data is that it is often in little endian.

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.

**Comment by Es00bac** [comment]
I Made a separate configuration utility for this mouse. The protocol is pretty close to being completely reverse engineered, but it supports macros and binding keys with modifiers, some RGB functionality, and the project has a ton of usbpcap's and mouse memory dumps. The protocol is documented fairly well.

https://github.com/Es00bac/UtechSmart-Venus-Pro-Linux-MMO-Mouse-Utility
