### ISSUE TITLE
Logitech G203 Unsupported Error

### ISSUE THREAD

**Issue by BobbyJackT** [libratbag/libratbag#1056]
I recently got the new color variant of the Logitech G203 mouse in lilac. I was excited to be able to control the mouse lighting and features on Linux. I checked the support page for supported mice and I saw the G103/203 were supported in a section together. The error I am getting is that there is no supported mouse plugged in. I tried unplugging and replugging the mouse as well as restarting my computer. The mouse works fine functionality wise besides not showing as supported.

**Comment by Chofoteddy** [comment]
Same, I have connected the mouse:

    Bus 003 Device 003: ID 046d:c092 Logitech, Inc. G203 LIGHTSYNC Gaming Mouse

But `ratbagctl list` shows me:

    screaming-acouchy:   Logitech Wireless Mouse MX Master 3

**Comment by kkartaltepe** [comment]
I have one of the `046d:c092 Logitech, Inc. G203 LIGHTSYNC Gaming Mouse` mice and its working fine here. Are you sure you see it in your devices list? (normally `/usr/share/libratbag/`).

**Comment by camic** [comment]
my G203  is not recognized

ratbagctl list
No devices available.

lsusb
Bus 001 Device 004: ID 046d:c092 Logitech, Inc. 

so I changed /usr/share/libratbag/devices/logitech-g102-g203.device
DeviceMatch=usb:046d:c092

inside the file comment says G203, but device name say G103

# G102 and G203 (USB)
[Device]
Name=Logitech Gaming Mouse G102/G103

Logitech Gaming Mouse G102/G103  
??  G103 or G203 ??

filename   logitech-g102-g203.device

thanks, but it does not work here.

**Comment by camic** [comment]
sudo ratbagd --verbose
ratbag debug: Logitech G203 LIGHTSYNC Gaming Mouse is device '/dev/hidraw2'.
ratbag debug: Logitech G203 LIGHTSYNC Gaming Mouse is device '/dev/hidraw3'.
ratbag debug: report ID 01
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag error:     USB error: Connection timed out (110)
write: Success

can you help:
  USB error: Connection timed out (110) ???

**Comment by camic** [comment]
ratbag raw: hidpp write: 10 ff 0f 08 00 00 00
ratbag raw: hidpp read:  11 ff 0f 08 01 04 01 01 01 06 10 00 ff 0a 01 00 00 00 00 00
ratbag error: Profile layout not supported: 0x04.
ratbag error: Logitech G203 LIGHTSYNC Gaming Mouse: error opening hidraw node (Operation not supported)

**Comment by staticssleever668** [comment]
If this is still the problem on the latest version of libratbag, please, open a new issue following the issue template.
