### ISSUE TITLE
Logitech G203 Issue

### ISSUE THREAD

**Issue by BobbyJackT** [libratbag/libratbag#1057]
I recently got the new color variant of the Logitech G203 mouse in lilac. I was excited to be able to control the mouse lighting and features on Linux. I checked the support page for supported mice and I saw the G103/203 were supported in a section together. The error I am getting is that there is no supported mouse plugged in. I tried unplugging and replugging the mouse as well as restarting my computer. The mouse works fine functionality wise besides not showing as supported.

**Comment by perigoso** [comment]
You should consider closing #1056, no need to create duplicates.

**Comment by staticssleever668** [comment]
1:1 duplicate of #1056.
