### ISSUE TITLE
Model O not detected by libratbag

### ISSUE THREAD

**Issue by cj360** [libratbag/libratbag#1060]
- `ratbagd` version (0.14):
- Distribution: Arch Linux
- Kernel version (5.8.10-17-tkg-pds) (custom kernel built from [tkg](https://github.com/Frogging-Family/linux-tkg/tree/master/linux58-tkg) scripts)

`sudo ratbagd --verbose=raw` 

Can detect the mouse

```
ratbag debug: New device: Glorious Model O
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 258a:0036
```

But `ratbagctl` can't

```
sudo systemctl enable ratbagd.service
reboot

$ ratbagctl list
No devices available.
```

**Comment by FFY00** [comment]
The Model O will only be supported in the next release.

**Comment by cj360** [comment]
Oh sorry I thought it was merged and in the current release.
