### ISSUE TITLE
Add Gaming-Maus GM-300 - Nacon.

### ISSUE THREAD

**Issue by NilsNews** [libratbag/libratbag#1074]
I wanted to manage my gaming mouse with the piper tool, but unfortunately that doesn't work by default. That's why I did some research and tried it out, but I know my way around so much and wanted to ask you what exactly I have to do.

My mouse:
[https://www.nacongaming.com/souris-gaming-gm-300](https://www.nacongaming.com/souris-gaming-gm-300)

lsusb:
Bus 001 Device 003: ID 04d9: a09f Holtek Semiconductor, Inc.

I have already read through this "[https://github.com/libratbag/libratbag/wiki/Adding-a-device](https://github.com/libratbag/libratbag/wiki/Adding-a-device)" page but I am somehow not smart about it.
Maybe someone can help me or explain briefly how to do it.

Many thanks.

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.
Also, this mouse's VID:PID are also mentioned here: #460.
