### ISSUE TITLE
Mad Catz R.A.T. 5

### ISSUE THREAD

**Issue by lexrms** [libratbag/libratbag#1084]
Hi guys,

I tried to create a device file for my mouse and I couldn't.
Can someone help me?

Mad Catz R.A.T. 5

Lsusb output:
Bus 001 Device 004: ID 0738: 1705 Mad Catz, Inc.

Output lsusb -v -d 0738: 1705:
Bus 001 Device 004: ID 0738:1705 Mad Catz, Inc. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x0738 Mad Catz, Inc.
  idProduct          0x1705 
  bcdDevice            2.22
  iManufacturer           1 Mad Catz
  iProduct                2 Mad Catz R.A.T.5 Mouse
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      64
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)

**Comment by lexrms** [comment]
Output ratbagd --verbose=raw

Initializing libratbag
ratbag debug: New device: Lite-On Technology Corp. USB Multimedia Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04ca:0027
ratbag debug: New device: Lite-On Technology Corp. USB Multimedia Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04ca:0027
ratbag debug: New device: Mad Catz Mad Catz R.A.T.5 Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp10
ratbag debug: hidraw info: bus 0x03 vendor 0x738 product 0x1705
ratbag debug: Mad Catz Mad Catz R.A.T.5 Mouse is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: New device: HID 413c:8161
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 413c:8161
DBus server ready

**Comment by lexrms** [comment]
This repository I tested and works. You may be able to implement from here: https://github.com/MayeulC/Saitek

**Comment by lexrms** [comment]
This repository I tested and works to change the profile and dpi. You may be able to implement from here: https://github.com/MayeulC/Saitek

**Comment by lexrms** [comment]
This repository I tested and works to change the profile and dpi.
You may be able to implement from here: https://github.com/MayeulC/Saitek

**Comment by stephanlachnit** [comment]
You need to reverse engineer the driver and implement it in libratbag. Only someone with the mouse can do it, so if you have some basic C knowledge, give it a shot.

**Comment by FFY00** [comment]
It will be very difficult to add support for it here because it appears that mouse uses USB control requests for configuration, while libratbag is currently only meant to configure devices over HID requests. Sorry :confused:

**Comment by lexrms** [comment]
Hi Filipe,

Thanks for your answer. Very nice of you.
I will close the issue.
But if you can point me where I can understand better about HID Requests and USB Control Requests I would appreciate it.
Thank You.

**Comment by FFY00** [comment]
Hey @lexrms. USB is a bit of a mess and can be hard to get into :sweat_smile: but I would say https://www.beyondlogic.org/usbnutshell is a decent, although naturally very technical, tutorial. You would be looking for https://www.beyondlogic.org/usbnutshell/usb6.shtml regarding the USB requests.
I would actually highly recomend you to look at the packets with Wireshark, I think it makes them much easier to digest. If you do, please plug the device while recording so that Wireshark has access to all USB descriptors and can interpret all of the data, this mostly impacts (if only?) HID.

I think if you have a look at Wireshark and the code of the project you mentioned, you might be able to get a good feel of how it works. If you want to look at some HID data, you can find some dumps [here](https://github.com/libratbag/ratbag-toolbox/tree/master/dumps).

Hope that helps :blush:

**Comment by lexrms** [comment]
Nice!
Thank you @FFY00 !
I will try your suggestions.
