### ISSUE TITLE
Add device for Logitech G703 w Hero in Wireless mode

### ISSUE THREAD

**Issue by HenrikHolst** [libratbag/libratbag#1088]
libratbag already have support for the G703 when connected with the wire, but not when used in wireless mode.

I have made a device file that made it work for me in wireless mode, however considering [https://github.com/libratbag/libratbag/issues/805](url) my device file is not correct since I'm pointing it to the receiver and not the mouse. It does work however and piper even does a proper detection of the mouse so I guess that there have to be something else in the device file to let libratbag distinguish between this mouse and others using the same receiver, this [https://github.com/libratbag/libratbag/issues/579](url) seems to indicate that it's something called WPID that is needed.

So if any one could let me know how to find what I should put where and we could add proper support for this mouse.

`[Device]
Name=Logitech G703 LIGHTSPEED Wireless Gaming Mouse w/ HERO
DeviceMatch=046d:c539
Driver=hidpp20

[Driver/hidpp20]
DeviceIndex=1
`

**Comment by FFY00** [comment]
`c539` is the ID of the receiver, we don't want that. The kernel driver exports a HID device with the actual device ID, that is what we want.

Which kernel are you running?

**Comment by HenrikHolst** [comment]
5.2 (the one from ubuntu 20.04)

Den lör 31 okt. 2020 15:32Filipe Laíns <notifications@github.com> skrev:

**Comment by FFY00** [comment]
Can you post the output of `dmesg | grep logitech`?

**Comment by HenrikHolst** [comment]
henrik@ubuntu:~$ dmesg | grep logitech
[    2.228402] logitech-djreceiver 0003:046D:C539.0008: hidraw7: USB HID
v1.11 Keyboard [Logitech USB Receiver] on usb-0000:02:00.0-11/input0
[    2.288436] logitech-djreceiver 0003:046D:C539.000A: hiddev6,hidraw9:
USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:02:00.0-11/input2
[    2.350051] logitech-djreceiver 0003:046D:C539.000A: device of type
eQUAD Lightspeed 1 (0x0c) connected on slot 1
[    2.360403] logitech-djreceiver 0003:046D:C539.0009: hiddev5,hidraw8:
USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:02:00.0-11/input1
[    2.557577] logitech-hidpp-device 0003:046D:4086.000F: input,hidraw10:
USB HID v1.11 Keyboard [Logitech G703 LS] on usb-0000:02:00.0-11/input2:1
[   22.583683] logitech-hidpp-device 0003:046D:4086.000F: HID++ 4.2 device
connected.
henrik@ubuntu:~$

Den lör 31 okt. 2020 kl 17:07 skrev Filipe Laíns <notifications@github.com>:

**Comment by HenrikHolst** [comment]
So I changed to 046d:4086 and piper still works so this seems to be the
correct one to use. Never saw that one before since lsusb doesn't list it

Den lör 31 okt. 2020 kl 17:53 skrev Henrik Holst <
henrik.holst@millistream.com>:

**Comment by HenrikHolst** [comment]
which is strange since that is the value already used for the
/usr/share/libratbag/logitech-g703-hero.device and that didn't work
initially... But I removed my custom file and restarted ratbagd and piper
still works so that it didn't work initially must just have been a fluke,
sorry for bothering about this when it clearly works out of the box...

Den lör 31 okt. 2020 kl 17:56 skrev Henrik Holst <
henrik.holst@millistream.com>:

**Comment by FFY00** [comment]
That ID should already be enabled, not sure why it wasn't working.

https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-g703-hero.device
