### ISSUE TITLE
Extra SteelSeries ID's

### ISSUE THREAD

**Issue by The-Repo-Club** [libratbag/libratbag#1090]
SteelSeries Kana v2:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Kana v2                                          | 1038:137a |

SteelSeries Kinzu v2:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Kinzu v2                                         | 1038:1366 |
| SteelSeries Kinzu v2                                         | 1038:1378 |

SteelSeries Rival 100 / SteelSeries Rival 105:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 100                                        | 1038:1702 |
| SteelSeries Rival 100 (Dell China)                           | 1038:170a |
| SteelSeries Rival 100 Dota 2 Edition (retail)                | 1038:170b |
| SteelSeries Rival 100 Dota 2 Edition (Lenovo)                | 1038:170c |
| SteelSeries Rival 105                                        | 1038:1814 |

SteelSeries Rival 110 / SteelSeries Rival 106:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 110                                        | 1038:1729 |
| SteelSeries Rival 106                                        | 1038:1816 |

SteelSeries Rival 3:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 3                                          | 1038:1824 |

SteelSeries Rival 300 / SteelSeries Rival:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival                                            | 1038:1384 |
| SteelSeries Rival Dota 2 Edition                             | 1038:1392 |
| SteelSeries Rival 300                                        | 1038:1710 |
| SteelSeries Rival 300 Fallout 4 Edition                      | 1038:1712 |
| SteelSeries Rival 300 Evil Geniuses Edition                  | 1038:171c |
| SteelSeries Rival 300 CS:GO Fade Edition                     | 1038:1394 |
| SteelSeries Rival 300 CS:GO Hyper Beast Edition              | 1038:171a |
| SteelSeries Rival 300 CS:GO Fade Edition (stm32)             | 1038:1716 |
| SteelSeries Rival 300 Acer Predator Edition                  | 1038:1714 |
| SteelSeries Rival 300 HP OMEN Edition                        | 1038:1718 |

SteelSeries Rival 300S:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 300S                                       | 1038:1810 |

SteelSeries Rival 310:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 310                                        | 1038:1720 |
| SteelSeries Rival 310 CS:GO Howl Edition                     | 1038:171e |
| SteelSeries Rival 310 PUBG Edition                           | 1038:1736 |

SteelSeries Rival 500:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 500                                        | 1038:170e |

SteelSeries Rival 600:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 600                                        | 1038:1724 |
| SteelSeries Rival 600 Dota 2 Edition                         | 1038:172e |

SteelSeries Rival 700 / SteelSeries Rival 710:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 700                                        | 1038:1700 |
| SteelSeries Rival 710                                        | 1038:1730 |

SteelSeries Rival 95 / SteelSeries Rival 100 PC Bang:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Rival 95                                         | 1038:1706 |
| SteelSeries Rival 95 MSI Edition                             | 1038:1707 |
| SteelSeries Rival 95 PC Bang                                 | 1038:1704 |
| SteelSeries Rival 100 PC Bang                                | 1038:1708 |

SteelSeries Sensei 310:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Sensei 310                                       | 1038:1722 |

SteelSeries Sensei [RAW]:

| Version | ID |
|--------------------------------------------------------------|-----------|
| SteelSeries Sensei [RAW]                                     | 1038:1369 |
| SteelSeries Sensei [RAW] Diablo III Edition                  | 1038:1362 |
| SteelSeries Sensei [RAW] Guild Wars 2 Edition                | 1038:136d |
| SteelSeries Sensei [RAW] CoD Black Ops II Edition            | 1038:136f |
| SteelSeries Sensei [RAW] World of Tanks Edition              | 1038:1380 |
| SteelSeries Sensei [RAW] Heroes of the Storm Edition         | 1038:1390 |

**Comment by JJRcop** [comment]
SteelSeries Rival 3's ID changes to `1038:184c` if you update to firmware `0.37.0.0`.

The ID remains `1038:1824` on firmware `0.36.0.0`, which is still valid.

**Comment by staticssleever668** [comment]
This is useful info, but there is no point in keeping this open.
If any of the listed here IDs are not in libratbag yet, and making a device file with them works - please, make a PR or a new issue.
