### ISSUE TITLE
Mac OS support bundled package or installation guide.

### ISSUE THREAD

**Issue by sealvessel** [libratbag/libratbag#1092]
I wish for a bundled package for mac os.

To create a bundled installer with the gtk+ library, and libgratbag all precompiled into a single .app software.

Perhaps provide instruction on how to build the software on mac os if you do not have sufficient time to write for mac os.
Confusing it is to use this software with my logitech gaming mouse. Also I dislike LGhub's invasiveness.

**Comment by staticssleever668** [comment]
Closing in favor of #1194
