### ISSUE TITLE
ratbag error: Error: Broken pipe (32)

### ISSUE THREAD

**Issue by ViacheslavUKR** [libratbag/libratbag#1100]
Hello, developers. I have add a device, restart service and receive error. Also my Piper don't see a daemon. Can you help me? What going wrong?
![Screenshot from 2020-11-23 01 13 59](https://user-images.githubusercontent.com/20413407/99920222-bb594c00-2d2a-11eb-9dfb-be04cfb17f17.png)

**Comment by staticssleever668** [comment]
Oh wow this is stale,.
The problem here is most likely in a driver incompatible with the mouse. Either way, we don't have support for A4Tech mice as of now.
