### ISSUE TITLE
Debouncing rapid clicks.

### ISSUE THREAD

**Issue by fuzebox1** [libratbag/libratbag#1103]
Now im not entierly sure this is the place for this issue, if it can be implemented in ratbag, or if i have to go straight to libinput. It seems to be a problem mainly with lightspeed mice tough.

**Is your feature request related to a problem? Please describe.**
My G305 double clicks more than half the time when i single click.

**Describe the solution you'd like**
Libinput and evdev have a debouncing option, tough i libinput it is hardcoded to 25ms. Rather not use evdev.
Would it be possible to add a range for double click detection?
I.e. any 2 clicks under X (say 125ms) are read as one, and any 2 clicks in X time are read as a double click.  

**Describe alternatives you've considered**
The alternatives right now are to pull the PKGBUILD of libinput and patch the values in evdev-debounce.c and compile.
Or possibly use evdev with the Xorg config options they provide (have not tried, possible they are deprecated).
And to make an issue with libinput about this.

**Additional context**
Iv'e seen a lot of posts on this double click issue, some where resolved with libinput adding debounce, but it seems it persists for many there the hardware switch bounces slower than 25ms. It needs to be modifyable to a higher value.
Windows and mac have other debounce implementations that works better, or maybe it is in the mice drivers.

**Comment by FFY00** [comment]
libratbag only consfigures settings on the hardware, it only talks to the hardware, it has nothing to do with input even handling.

The correct place should be libinput but I doubt they will allow you to configure this :confused:

**Comment by fuzebox1** [comment]
Ok, kinda suspected this.
Yeah i doubt libinput would care enough. They just grabbed the code for debouncing off of evdev.
Guessing i will have to grab the PKGBUILD and add a patch to hackily solve this.
