### ISSUE TITLE
Custom Device files or device file documentation

### ISSUE THREAD

**Issue by thomasfinstad** [libratbag/libratbag#1110]
First of, thanks for this great project it is exactly what I needed.

**Is your feature request related to a problem? Please describe.**
Due to the logitech g915-tkl lightspeed dongle having the same ID for multiple keyboards you can not include it in the repo ad a recognized device with the ID the dongle reports, as I only have 1 keyboard it is fine for me to edit my local device file, but this will probably get overridden during the next apt upgrade of the libratbag package.

**Describe the solution you'd like**
If there were a blessed way to _override_ the devices files, possibly `/etc/libratbag/devices.d/my-device-name.device` that will load in custom devices files this will not be an issue.

Maybe there could be an **added** inheritance system so that I could use the included configs for mine (or any matching keyboard) with a new section in the file, maybe something like this:
```
[Inherit]
Name=Logitech G915 TKL

[Device]
Name=Logitech G915 TKL Lightspeed
DeviceMatch=usb:046d:c545
```
This would allow for a simple adding of my own keyboard to another existing matching keyboard. Or the normal device file config, or a mix of inheritance with overrides.

**Describe alternatives you've considered**
Currently I am just creating a new local file:
```
$ cat /usr/share/libratbag/logitech-g915-tkl-lightspeed.device 
[Device]
Name=Logitech G915 TKL Lightspeed
DeviceMatch=usb:046d:c545
LedTypes=logo;switches
Driver=hidpp20

[Driver/hidpp20]
DeviceIndex=1
```

I wish there were some documentation on where these files have been placed as it is not obvious, and with a doc in the wiki on where they are and how to add an identifier that might be just as good. And which way a custom device file should be added.

**Additional context**
It is my understanding that a kernal patch for the lightspeed dongle might solve this issue for logitech keyboards (as discussed in https://github.com/libratbag/libratbag/issues/1008#issuecomment-662754044 ), I am not able to locate the status of said patch or if it has already been included.

**Comment by staticssleever668** [comment]
> Due to the logitech g915-tkl lightspeed dongle having the same ID for multiple keyboards you can not include it in the repo ad a recognized device with the ID the dongle reports

AFAIK you just can not talk to the receiver the same way you would talk to a device, so having the same ID for several devices is not the real problem.
A few times I told people to try using the receiver ID, and it gave completely different output than when connected by wire.

> Maybe there could be an added inheritance system so that I could use the included configs for mine (or any matching keyboard) with a new section in the file, maybe something like this:

I believe this won't do any help, as device files are not meant to be customized. Ideally all changes should be upstreamed. Anyway, you can always just copy an existing file.

As for creating new device files, you can follow the wiki, which also links an example device file with descriptions of some fields.
https://github.com/libratbag/libratbag/wiki/Adding-a-device/
