### ISSUE TITLE
Add support for Pictek PC255A Wireless Gaming Mouse

### ISSUE THREAD

**Issue by KibSquib48** [libratbag/libratbag#1142]
**Describe the solution you'd like**
I'd like support for the Pictek PC255A wireless mouse, to configure mouse buttons and RGB and view the battery percentage if possible.

**Describe alternatives you've considered**
I've tried using the official config software through wine, which as expected didn't work, and also through a KVM with USB passthrough, which did work, but was a bit much just for some mouse configuration software, since I have to wait for the entire OS to load and all that.

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.
