### ISSUE TITLE
Steelseries Rival 650 Wireless Support

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [libratbag/libratbag#1148]
The Steelseries Rival 650 has yet to be supported beyond basic functionality on linux. I have one and would be willing to do any packet capturing necessary to get this device supported.

**Comment by elderwolf123** [comment]
I agree, I have a 650 Rival and I'm happy to help out however I can

**Comment by staticssleever668** [comment]
Fixed by #1420.
