### ISSUE TITLE
Please allow me to use the HID++ defines

### ISSUE THREAD

**Issue by hughsie** [libratbag/libratbag#115]
I'm using a tiny subset of hid++ in the fwupd unifying updater plugin in fwupd: https://github.com/hughsie/fwupd/blob/master/plugins/unifying/unifying-dongle.c#L34

It would be really good to either have a file we can share, or include in either build. I'm happy just merging your file into mine, but a better solution might be to have a hidpp-constants.h in libratbag that I can copy into fwupd.

One prerequisite is that the HID++ constants need a HIDPP_ prefix to avoid things like ERR_BUSY conflicting with other things in fwupd.

Comments welcome, thanks.

**Comment by Hjdskes** [comment]
Since #116 is closed and "given that fwupd already took the files it needed from this PR" (https://github.com/libratbag/libratbag/pull/116#issuecomment-307310944), can this issue be closed?

**Comment by whot** [comment]
Yep, closing. @hughsie please reopen if you need something more
