### ISSUE TITLE
[Question] Possible to loop/repeat macro while holding?

### ISSUE THREAD

**Issue by Open24Hours** [libratbag/libratbag#1153]
I'm looking to bind one of my buttons to send a keystroke but would like that keystroke to repeat while holding. For instance a left click keystroke that would repeatedly send the macro with a certain delay while holding down whatever button it is bound to. Maybe this is already possible and cannot figure it out. Thanks

**Comment by wytr** [comment]
How do i configure looping/repeating macros? I am using a MX518 (The newer version) And would like to use an autoclicker on mousewheel press (bind to space) with a delay of 20-50ms? Is this feature even implemented now?
I found the following defines in

**hidpp10.h:**
`
#define HIDPP10_MACRO_REPEAT_UNTIL_BUTTON_RELEASE	0x02
`
`
#define HIDPP10_MACRO_REPEAT				0x03
`
**hidpp20.h:**
`
#define HIDPP20_MACRO_REPEAT_WHILE_PRESSED	0x02
`
`
#define HIDPP20_MACRO_REPEAT_UNTIL_CANCELED	0x03
`

Those look like what i am looking for, but i have no clue how to configure this using ratbagctl.
Could you help me out?
