### ISSUE TITLE
Ability to Add more than 5 Profiles

### ISSUE THREAD

**Issue by ThanosPlanetSmasher** [libratbag/libratbag#1166]
This Software is AMAZING!!  All I am wondering is if there is a way to get more than 5 Profiles (0-4) ?

I just want a few more profiles added to the Software. 

I've used the Logitech Gaming Software, but it doesnt work worth a hoot on Linux.

**Comment by FFY00** [comment]
I assume you have one of the recent Logitech devices. We support the maximum number of profiles allowed by the hardware.

**Comment by ThanosPlanetSmasher** [comment]
Filip bro, you are absolutely right - Logitech G604 Mouse to be exact. 

That totally makes sense regarding the number of profiles.  

I really appreciate your help!
