### ISSUE TITLE
Redragon mouse support (opendragon)

### ISSUE THREAD

**Issue by GrbavaCigla** [libratbag/libratbag#1195]
Hi, I am the author of https://github.com/GrbavaCigla/opendragon and I would like to add redragon support to libratbag. Can you give me directions on source code so I can add it? Thanks in advance.

**Comment by perigoso** [comment]
Sorry no one got to you, at the moment we have a problem with lack of maintainers, or better said, maintainers with time.

I think the best approach is to take an  existing driver and modify it to work with redragon, the most feature complete driver is the `hidpp20` I believe, this also means its probably more complicated though.

Sorry I can't get much indepth help I'm still getting familiar with the code base myself, but feel free to ask specific questions about anything.

**Comment by amfern** [comment]
This is excellent work, your PR will be appreciated.
As @perigoso said `src/driver-hidpp20.c` would be the best place to start, you can also look at `src/driver-steelseries.c`.

In general each driver exports a drive structure `struct ratbag_driver`. 
```
struct ratbag_driver hidpp20_driver = {
	.name = "Logitech HID++2.0",
	.id = "hidpp20",
	.probe = hidpp20drv_probe,
	.remove = hidpp20drv_remove,
	.commit = hidpp20drv_commit,
	.set_active_profile = hidpp20drv_set_current_profile,
};
```
We would read all the settings in the `.probe` function and then write all the settings in the `.commit` function.

To reading and writing to a device we have.
`ratbag_hidraw_output_report` and `ratbag_hidraw_read_input_report` 
or 
`ratbag_hidraw_get_feature_report` and `ratbag_hidraw_set_feature_report`

Please feel free to ask if you have anymore questions

**Comment by GrbavaCigla** [comment]
Thanks for the directions :D

Since redragon mice are partially reversed engineered and every mouse seems to be a little bit different, how should I structure it?

**Comment by perigoso** [comment]
If they are all similar with slight differences, I think a single driver with "quirks" is the best approach, take a look at the `src/driver-steelseries.c` driver, that deals with problems like these

**Comment by staticssleever668** [comment]
I'll close this for now as it doesn't seem like there is any work being done at the moment.
For Redragon mice also see #1217.
