### ISSUE TITLE
Support for Mars Gaming MM4

### ISSUE THREAD

**Issue by Qjammer** [libratbag/libratbag#1199]
**Describe the solution you'd like**
Add support for Mars Gaming MM4, with enough flexibility for possible support for other Mars Gaming mice.

**Describe alternatives you've considered**
I have reverse engineered the communication protocol between the mouse and the windows configurator.
I have implemented most of the functionality at [Qjammer/libratbag@marsgaming-mm4](https://github.com/Qjammer/libratbag/tree/marsgaming-mm4). 

**Additional context**
I will be opening a PR soon with support for this mouse.
Related: https://github.com/libratbag/piper/issues/676

**Comment by Qjammer** [comment]
I have a few questions. Is my understanding correct that the `key` functionality is deprecated in favor of parsing macros and converting them to whatever the mouse uses? I ask this because this mouse supports both `single key`, `combo key` (2 keys + modifiers) and `macro` functionality. This means I would have to inspect the macros coming from ratbag and choose whether to store them in the mouse as single key, combo key, or dedicated macro, right?

**Comment by FFY00** [comment]
> I have a few questions. Is my understanding correct that the `key` functionality is deprecated in favor of parsing macros and converting them to whatever the mouse uses?

Yes. We have some helpers for that.

>  I ask this because this mouse supports both `single key`, `combo key` (2 keys + modifiers) and `macro` functionality. This means I would have to inspect the macros coming from ratbag and choose whether to store them in the mouse as single key, combo key, or dedicated macro, right?

https://github.com/libratbag/libratbag/blob/abcec1d3499c538fea4803eda311ece2d9cef1f2/src/libratbag.c#L1947

>  And the same for the inverse case, I'll have to transform the stored single and combo keys to ratbag macros?

https://github.com/libratbag/libratbag/blob/abcec1d3499c538fea4803eda311ece2d9cef1f2/src/libratbag.c#L1872

**Comment by perigoso** [comment]
Hey, what's stopping the PR? are there still changes to be made?

**Comment by Qjammer** [comment]
I have yet to implement the macro functionality of the mouse. We could merge what I currently have and open a different issue that addresses the macros.
