### ISSUE TITLE
Additional information about sinowealth

### ISSUE THREAD

**Issue by araghon007** [libratbag/libratbag#1200]
So I did some reverse engineering of an off-brand mice I got which uses the sinowealth controller (and the inferior PixArt 3212, so no lift cutoff).
I could try forking this, adding the changes and making a pull request, but I'm not experienced enough with Linux and C and I'm scared I'd screw something up.

I'm not sure how far you got into reverse engineering the button remapping, but for it, the `command_id` is `0x12`. You can also get current button configuration by doing the same thing as getting config, but with `0x12` instead of `0x11`. The beginning of the report is similar to the one for config, so it seems that the first 8 bytes are specific to information about the report. Also `config_write` seems to be the length of the structure you're sending, which would be either `0x7B` for config, or `0x50` for button mapping. The buttons seem to be 4 bytes, the latter 2 of which seem to be used for key combinations, and there's up to 20 of them. I could try getting all the key values if necessary.
My mouse also seems to have 4 HID devices, 2 of which support setting feature reports. The way I'm differentiating between them is by checking which of them has report length of 520 for config, and which one has 6 for CMD. Not sure how you're handling that, if at all.

There's also an interesting thing I found out while downloading dubious software and that is that the mouse actually supports 2 modes/profiles between which you can switch. Switching is done through the CMD report ID, followed by `0x02`, profile ID and 3 bytes, so the resulting report would be `05 02 01 00 00 00` and `05 02 02 00 00 00`. Though you have to set up the second profile first or you'll face the wrath of undefined behavior. Turns out the first, uhh, nibble of the `command_id` is the ID of the profile you're setting. So for config, it would be `0x11` and `0x21`, and for button bindings, it would be `0x12` and `0x22`. Once they're set up, you can set a button binding on the mouse to switch between them (don't forget to set it for both profiles) and you even get a visual indication on the mouse that you're switching between them. The key code for that button is `50 06 00 00`. Also oddly enough, I can get binding config from both profiles, but normal config from only the first profile. 

One more thing, the same way you can switch between profiles, you can also set button debouncing time. The software that came with my mouse said not to change that without reading the readme, but there was no readme, so I have no idea how much of an effect it has. The reports are:
```
05 1A 02 00 00 00 - 4 ms
05 1A 03 00 00 00 - 6 ms
05 1A 04 00 00 00 - 8 ms
05 1A 05 00 00 00 - 10 ms
05 1A 06 00 00 00 - 12 ms
05 1A 07 00 00 00 - 14 ms
05 1A 08 00 00 00 - 16 ms
```
I'm wondering if there are more features hidden away, but that's all I got from all the software I found.

**Comment by staticssleever668** [comment]
Actually, I somehow missed a part of your story where you told us about profile selection. Thank you so much, I've been trying to understand what command meant all this time! I'm surprised I didn't try setting that value myself.

Also, I think your mouse is already supported by our Sinowealth driver implementation, you just have to make a device file. If you wish to do so, feel free to open a new issue.

**Comment by araghon007** [comment]
Glad to hear you found some use for it. I found out about this stuff as I was trying to reverse engineer my mouse so I could switch between profiles on a key press, since none of the software I found had such a feature. I currently mainly use Windows, so I don't have much use for libratbag, nor the knowledge needed to make a device file.
Also, should this issue be closed now?

**Comment by staticssleever668** [comment]
By the way, have you found any other key bindings other than second profile selection?

**Comment by araghon007** [comment]
Not as far as I can remember.

**Comment by araghon007** [comment]
Also, not sure if you've added a way to set config and bindings for the second profile, but keep in mind that you need to use 0x21 and 0x22 for that. That might either require some code changes to make that first nibble be set based on profile ID, or just add another enum for profile 2 commands. It's very likely most mice don't have profile 2 set up from factory, so if you just switch to it without setting it up, you'd be stuck on DPI 0 with no button bindings.

**Comment by cybersphinx** [comment]
I have a Sinowealth mouse (says PC257A on the bottom, software calls it T18) that has two profiles in its software (I think they were both set to the same default settings when I got it) and a button on the bottom to switch between those two profiles. The button isn't exposed in the software, but it might be set to the profile switch code automatically in both profiles. Thought that might be interesting also in regards to  #1395.

**Comment by staticssleever668** [comment]
> has two profiles in its software

Oh, so there actually are some Sinowealth mice that do support switching profiles officially!

> (I think they were both set to the same default settings when I got it)

The problem with the second profile on Glorious Model O and G-Wolves Hati HT-M is that it's empty by default.
The comment above basically describes it: `It's very likely most mice don't have profile 2 set up from factory, so if you just switch to it without setting it up, you'd be stuck on DPI 0 with no button bindings.`.
Also, trying it out from time to time, I have a feeling that the second profile may not persist in memory?.. because for some reason the profile may become empty again when I try to use it.

> The button isn't exposed in the software, but it might be set to the profile switch code automatically in both profiles.

We could check that by adding support for it to libratbag. Would you trying this out?
