### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by jacobaklein** [libratbag/libratbag#1203]
Trying to run "meson builddir" and I get this:

The Meson build system
Version: 0.59.2
Source dir: /home/jacob/packages/libratbag
Build dir: /home/jacob/packages/libratbag/builddir
Build type: native build
Project name: libratbag
Project version: 0.16
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libudev found: YES 245
Run-time dependency libevdev found: YES 1.9.0
Run-time dependency glib-2.0 found: YES 2.9.6
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency json-glib-1.0 found: NO (tried pkgconfig)

meson.build:75:0: ERROR: Dependency "json-glib-1.0" not found, tried pkgconfig

A full log can be found at /home/jacob/packages/libratbag/builddir/meson-logs/meson-log.txt

I was able to work through the first three dependencies but 'json-glib-1.0' is kickin' my rear...what am I doing wrong?

**Comment by FFY00** [comment]
Which distribution are you using?

Debian/Ubuntu: https://launchpad.net/ubuntu/+source/json-glib
Arch Linux/Manjaro: https://archlinux.org/packages/extra/x86_64/json-glib/

**Comment by jacobaklein** [comment]
Mint 20.2 Uma

Sorry for leaving that off...

**Comment by FFY00** [comment]
Did you install `libjson-glib-dev`?

**Comment by jacobaklein** [comment]
Did that and at least got a different error...


Run-time dependency json-glib-1.0 found: NO 

meson.build:75:0: ERROR: Could not generate cargs for json-glib-1.0:
Package 'json-glib-1.0' requires 'gobject-2.0 >= 2.44.0' but version of gobject-2.0 is 2.9.6

**Comment by jacobaklein** [comment]
ERROR: C shared or static library 'unistring' not found


On to hunting for unistring library...guess I just got to hunt them down one by one.

**Comment by jacobaklein** [comment]
Got through them all!  I am good now.

Thanks for the help, Filipe.

**Comment by enkore** [comment]
It's not linked from the README it seems, but here are detailed instructions for building from source, including a list of dependencies: https://github.com/libratbag/libratbag/wiki/Building-from-source
