### ISSUE TITLE
G303 (and probably others) DPI is not bounds-checked, can confuse ratbag-command

### ISSUE THREAD

**Issue by roothorick** [libratbag/libratbag#121]
Somehow, ratbag-command happily pushed 13000dpi onto my mouse, and then wasn't able to change it back until I switched to a different profile and set it by reference (i.e. profile 0 resolution 1 dpi set 800). Then I was able to change it directly again.

**Comment by whot** [comment]
any chance you can try and look for the bug (and fix it :). We're all a bit strapped for time atm

**Comment by bentiss** [comment]
To give some hints to solve the bug:
- ratbag-command is not aware of the min/max capabilities (by choice, currently), so the driver should be the one rejecting the erroneous value
- I think the driver is driver-hidpp20.c in your case which calls hidpp20.c in a lot of various places
- so I think in driver-hidpp20.c there should be a check on the incoming dpi to be sure we do not try to send something wrong in the mouse

Actually, after second thoughts, I think you would need a little bit more insights of the mice to fix that. The feature 0x8100 doesn't export the min/max DPI, so I think we would need to either rely on yet unimplemented functions of 0x8100 if any, or maybe in the adjustable_dpi feature (0x2201)...
