### ISSUE TITLE
Redragon mouse support (mouse_m908)

### ISSUE THREAD

**Issue by matteoturini** [libratbag/libratbag#1217]
[mouse_m908](https://github.com/dokutan/mouse_m908) is an open-source Redragon mice control project, and I believe both projects and their users could benefit from this integration.

**Comment by perigoso** [comment]
There was a previous Redragon support suggestion in #1195 using a different existing implementation, which is also in GPLv3. Just commenting to link the issues and help keep track.

I don't think the legal is really an issue, it would just need to be completely reimplemented in libratbag, no ported code. It would need to anyway to work with the current codebase.

**Comment by perigoso** [comment]
There was a previous Redragon support suggestion in #1195 using a different existing implementation, which is also in GPLv3. Just commenting to link the issues and help keep track.

**Comment by perigoso** [comment]
I think copying code cannot be done by anyone but the owner of the copyright (they can legally commit it as MIT to libratbag). Everyone else cannot re-implement code either for copyright reasons.

**Comment by matteoturini** [comment]
@dokutan can you dual-license the code with permission from other contributors?

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.
For now the application mentioned in the top message can be used.
