### ISSUE TITLE
Wouldn't it be helpful to have the build dependencies listed in the install instructions?

### ISSUE THREAD

**Issue by darth-crunchus** [libratbag/libratbag#1229]
**Is your feature request related to a problem? Please describe.**
I'm new to building from source, so I don't know what dependencies I need to build with.  I see something in instructions, I assume that's all I need, but invariably, there's always more, and people expect you to just *know* what is needed to do it.  That's unrealistic.  For example, I'm trying to install libratbag.  I've been at this for 3 hours now, and still have unresolved dependencies, like the wonderfully named "check".  Where do I get that?  Do you know how many hits you get that aren't a linux package when searching "install check ubuntu"?

**Describe the solution you'd like**
I would like to see a list of package dependencies that are required to build libratbag in the install instructions.

**Comment by perigoso** [comment]
https://github.com/libratbag/libratbag/wiki/Building-from-source

Is this what you're looking for? I'm not sure if every dependency is list, but they should.

**Comment by darth-crunchus** [comment]
Agreed.  With an ambiguous name like "check", I *never* would have found that.  Not in a million years.
