### ISSUE TITLE
CTRL key isnt able to be mapped 

### ISSUE THREAD

**Issue by ThanosPlanetSmasher** [libratbag/libratbag#1232]
The left and right CTRL ( KEY_LEFTCTRL/KEY_RIGHTCTRL) cant be mapped without a macro.  The only way it can be mapped is if you were to CTRL+C or CTRL+V but the keys by themselves will not be mapped.  I have tried with Piper, I have tried with sudo in terminal, but it just isnt happening.

**Comment by bluemner** [comment]
As you have not specified a device model / manufacture I will assume you are using a Logitech as this issue sound like it is related to https://github.com/libratbag/libratbag/issues/710

Unfortunately this is a limitation of the device and needs to have macro pattern of:  modifier down, button press,  modifier up
example:
`+KEY_LEFTSHIFT KEY_RESERVED -KEY_LEFTSHIFT `

> ` KEY_LEFTSHIFT` can be replaced with any modifier  key like `Ctrl` or `Alt`.  There a work around by using `KEY_RESERVED` or some other key you don’t care about can be used on some to kinda of get the functionality you are looking for however there a polling issues with this approach and it may not register correctly.  

It may be a better to use a key mapping program. Use libratbag  to set the macro value to  `KEY_HIRAGANA`  then use the 3rd party program to map `KEY_HIRAGANA`  → `KEY_LEFTSHIFT`  or any other modifier.

**Comment by ThanosPlanetSmasher** [comment]
My model is Logitech G602. 

I will try this workaround. 

Thanks for the help!
