### ISSUE TITLE
meson.build:1:0: ERROR: Compiler cc can not compile programs.

### ISSUE THREAD

**Issue by Okasdsdf** [libratbag/libratbag#1240]
Hi, just installed for the first time a GNU/linux distribution so I'm pretty sure I am doing something very stupid, but I couldn't solve this problem on my own so I need your help.
- `ratbagd` version (`ratbagd --version`): 0.13
- Distribution: Liunanux Mint 20.1
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-91-generic x86_64 GNU/Linux

Device info (if applicable):
```
$ ratbagctl <device> info
Unable to find device logitech-g102-g203
```

**Describe the bug**
meson.build:1:0: ERROR: Compiler cc can not compile programs.

**To Reproduce**
```
git clone https://github.com/libratbag/libratbag.git
cd libratbag
meson builddir
ninja -C builddir
sudo ninja -C builddir install
```

**Logs**
`Build started at 2021-12-04T13:08:03.381537
Main binary: /usr/bin/python3
Build Options: 
Python system: Linux
The Meson build system
Version: 0.53.2
Source dir: /home/superidol/libratbag/libratbag
Build dir: /home/superidol/libratbag/libratbag/builddir
Build type: native build
Project name: libratbag
Project version: 0.16
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/superidol/libratbag/libratbag/builddir/meson-private/sanitycheckc.c -o /home/superidol/libratbag/libratbag/builddir/meson-private/sanitycheckc.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status

-----

meson.build:1:0: ERROR: Compiler cc can not compile programs.`

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
ratbagd error: Failed to start ratbagd: Permission denied
```

**Additional context**

**Comment by enkore** [comment]
Seems like you have a compiler but no devel libraries installed. Try installing `build-essential` and the dependencies from the wiki: https://github.com/libratbag/libratbag/wiki/Building-from-source
