### ISSUE TITLE
Musl Libc Incompatibility

### ISSUE THREAD

**Issue by kwhat** [libratbag/libratbag#1253]
**Information**
- `ratbagd` version (`ratbagd --version`): 0.16
- Distribution: Gentoo
- Kernel version (ex. `uname -srmo`): `Linux 5.15.11-gentoo x86_64 GNU/Linux`

**Describe the bug**

../libratbag-0.16/tools/hidpp20-reset.c:26:10: fatal error: error.h: No such file or directory

**To Reproduce**
1. Compile against musl libc

**Logs**
N/A

**Additional context**
This may already be fixed in master, if not, it should be a pretty simple fix.  Just need to do something like this.  Having meson detect musl libc is a little more difficult.  I'll leave that part up to someone that knows meson better than I do. 

    #ifdef HAVE_ERROR_H
    #include "error.h"
    #else
    #include "err.h"
    #define error(status, errno, ...) err(status, __VA_ARGS__)
    #endif

**Comment by whot** [comment]
Best I can tell we're not making huge use of `error()` anyway, might as well just rewrite the code to provide our own little function to do this. Pull requests accepted :)

**Comment by listout** [comment]
> Best I can tell we're not making huge use of `error()` anyway, might as well just rewrite the code to provide our own little function to do this. Pull requests accepted :)

Hey, @whot is @kwhat's initial idea still acceptable? It would fix building for musl or other libc that doesn't provide error.h. Or is rewriting the error only acceptable idea for a PR. I've a patch for the first implementation i.e. using meson to detect if error.h is present on system.

**Comment by whot** [comment]
There are only 5 invocations of `error()` in the code, afaict (`tools/hidpp20-dump-page.c` and `tools/hidpp20-reset.c`, both are developer utils, not even the main code). It's just a convenience function, those cases should be rewritten to `fprintf` and `exit`, there's no need to clutter up the code with ifdefs and meson conditions, that's counterproductive IMO.

**Comment by listout** [comment]
@whot what if we check for error.h and if not present then we redefine error to use the err function?

Something like this?

```diff
--- a/meson.build
+++ b/meson.build
@@ -74,8 +74,13 @@ dep_libevdev = dependency('libevdev')
 dep_glib = dependency('glib-2.0')
 dep_json_glib = dependency('json-glib-1.0')
 dep_lm = cc.find_library('m')
+error_exists = cc.has_header('error.h')
 dep_unistring = cc.find_library('unistring')

+if error_exists
+	add_global_arguments('-DHAVE_ERROR_H', language : 'c')
+endif
+
 if get_option('logind-provider') == 'elogind'
 	dep_logind = dependency('libelogind', version : '>=227')
 else
--- a/tools/hidpp10-dump-page.c
+++ b/tools/hidpp10-dump-page.c
@@ -23,7 +23,12 @@

 #include <config.h>
 #include <errno.h>
+#ifdef HAVE_ERROR_H
 #include <error.h>
+#else
+#include <err.h>
+#define error(status, errno, ...) err(status, __VA_ARGS__)
+#endif
 #include <fcntl.h>
```

**Comment by staticssleever668** [comment]
Judging by what's already in the code base, I'd say the error should formatted and put at the end, so it would be like so `fprintf(stderr, "Failed to open path '%s': %s", path, strerror(errno))`.

**Comment by listout** [comment]
@staticssleever668 thanks. I'll start on creating a patch then

**Comment by listout** [comment]
@staticssleever668 Thanks. I've created MR

**Comment by staticssleever668** [comment]
Merged, thanks!
By the way, this was initially suggested by whot, not me. :)

**Comment by listout** [comment]
Hehe, it's alright. Thanks to you @staticssleever668 and @whot
