### ISSUE TITLE
GamePowerPC URSA mouse support (258a:0017 SINOWEALTH Game Mouse)

### ISSUE THREAD

**Issue by erdincay** [libratbag/libratbag#1254]
**Is your feature request related to a problem? Please describe.**
The GamePowerPC URSA - mouse [1] is not supported, it is a Sinowealth "Gamemouse" [2]. I found an Github - Repository [3] that states, that it might have written some commands, that would also make it work for Sinowealth - devices. 

Will there be support for the GamePowerPC URSA - mouse?

Based on some hardware statistics [4] I assume that at least ~ 30.000 people who use Linux have this mouse. The factor of hardware probe entries multiplied by 1000, which is based on my current empirical data of the data-sets on Linux-Hardware - website compared with usual device amounts sold multiplied by average actual percentage of Linux users worldwide.
[gloriousctl-latest.zip](https://github.com/libratbag/libratbag/files/7832032/gloriousctl-latest.zip)

**Describe the solution you'd like**
I would love to see support for the GamePowerPC URSA - mouse (Sinowealth "Gamemouse").

**Describe alternatives you've considered**
I have tried to configure the mouse buttons through Gnome Settings, Gnome Tweaks, DConf-Editor without results. 

**Additional context**
[1] https://gamepowerpc.com/gaming-mouse/ursa
[2] based upon lsusb information
[3] https://github.com/enkore/gloriousctl
[4] https://linux-hardware.org/index.php?id=usb:258a-0017

**Comment by staticssleever668** [comment]
Hello, have you tried making a device file?

If not, try this one:
```dosini
[Device]
Name=GamePowerPC URSA
DeviceMatch=usb:258a:0017
Driver=sinowealth
```

You have to add it to the folder where other device files are installed, usually it's `/usr/share/libratbag` or `/usr/local/share/libratbag`. The file must have `.device` suffix.

If it doesn't work, start `ratbagd` in verbose mode (`ratbagd --verbose=debug`), and send the output here.
Then replace the `Driver=sinowealth` line in devicefile with `Driver=sinowealth_nubwo` and repeat the step above.

If libratbag finds the mouse successfully, you should check if it reads mouse configuration correctly, and if there's something incorrect, do not change anything and do not save configuration. If you do save configuration, you may need a second mouse and access to official software to reset it's configuration.

Also, if you are familiar with building software from sources, you should try compiling libratbag yourself from the `master` branch and using it, as there have been some compatibility changes in `sinowealth` driver.

**Comment by erdincay** [comment]
> Hello, have you tried making a device file?
> 
> If not, try this one:
> 
> ```ini
> [Device]
> Name=GamePowerPC URSA
> DeviceMatch=usb:258a:0017
> Driver=sinowealth
> ```
> 
> You have to add it to the folder where other device files are installed, usually it's `/usr/share/libratbag` or `/usr/local/share/libratbag`. The file must have `.device` suffix.
> 
> If it doesn't work, start `ratbagd` in verbose mode (`ratbagd --verbose=debug`), and send the output here. Then replace the `Driver=sinowealth` line in devicefile with `Driver=sinowealth_nubwo` and repeat the step above.
> 
> If libratbag finds the mouse successfully, you should check if it reads mouse configuration correctly, and if there's something incorrect, do not change anything and do not save configuration. If you do save configuration, you may need a second mouse and access to official software to reset it's configuration.
> 
> Also, if you are familiar with building software from sources, you should try compiling libratbag yourself from the `master` branch and using it, as there have been some compatibility changes in `sinowealth` driver.

thank you i will try it, when i have access to the mouse again (it's a friends device)

**Comment by Markaos** [comment]
I have a mouse with the same USB ID but branded as Evogear, lsusb calls it just "SINOWEALTH Game Mouse". I tried both `sinowealth` and `sinowealth_nubwo` and neither works (Piper shows no connected devices).

Using `sinowealth` driver:
````
Initializing libratbag
ratbag debug: New device: SINOWEALTH Game Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver sinowealth
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x17
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x17
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw9'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 05
ratbag error: Error while sending read firmware version command: -110
ratbag debug: New device: SINOWEALTH Game Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver sinowealth
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x17
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x17
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw9'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 05
ratbag error: Error while sending read firmware version command: -110
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Burr-Brown from TI               USB Audio CODEC 
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 08bb:2902
ratbag debug: New device: Fnatic Gear RUSH Mechanical Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2029
ratbag debug: New device: Fnatic Gear RUSH Mechanical Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2029
DBus server ready
````
Using `sinowealth_nubwo` driver:
````
Initializing libratbag
ratbag debug: New device: SINOWEALTH Game Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver sinowealth_nubwo
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x17
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x17
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw9'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 05
ratbag debug: New device: SINOWEALTH Game Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver sinowealth_nubwo
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x17
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x17
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw9'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 05
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Burr-Brown from TI               USB Audio CODEC 
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 08bb:2902
ratbag debug: New device: Fnatic Gear RUSH Mechanical Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2029
ratbag debug: New device: Fnatic Gear RUSH Mechanical Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2029
DBus server ready
````

**Comment by staticssleever668** [comment]
@Markaos, hi, thank you so much for trying this. Is there any chance you could take a USB data dump while interacting with official mouse software?
I myself use [USBPcap](https://desowin.org/usbpcap/) for that purpose. [A short guide](https://desowin.org/usbpcap/tour.html). You would only have to follow steps one and two, then change some options in mouse software and close USBPcap. In step one, your mouse may look like this:
 ![Untitled](https://user-images.githubusercontent.com/64694940/117254353-d383da00-ae37-11eb-8b08-1b61b520c776.png)

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.
As I have experience with some Sinowealth mice, if someone sends a packet capture of interacting with official software, I could try taking a look at it, so feel free to tag me.
