### ISSUE TITLE
Glorious Model O not working (0 Buttons

### ISSUE THREAD

**Issue by 321Proteus** [libratbag/libratbag#1271]
**Information**
- `ratbagd` version: `0.16`
- Distribution: `Ubuntu 20.04`
- Kernel version: `Linux 5.13.0-27-generic x86_64 GNU/Linux`

Device info (if applicable):
```
$ ratbagctl <device> info
cheering-viscacha - Glorious Model O
             Model: usb:258a:0036:0
 Number of Buttons: 0
    Number of Leds: 1
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 400x400dpi
    1: 800x800dpi
    2: 1600x1600dpi (active) (default)
    3: 2700x2700dpi
    4: <disabled>
    5: <disabled>
    6: <disabled>
    7: <disabled>
  LED: 0, depth: rgb, mode: cycle, duration: 500, brightness: 255

```

**Describe the bug**
When I try to bind left-side buttons to click keys on keyboard, it says the button index is wrong. Button list also shows that the mouse has 0 buttons.

**To Reproduce**

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
OUTPUT HERE
```

**Additional context**
I'm new at Ubuntu. I used @enkore 's gloriousctl - worked well. IDK what's wrong, i need additional mouse buttons to click Minecraft hotkeys.

**Comment by staticssleever668** [comment]
Hi, changing buttons is not yet supported. This was worked on in #1065, but that patch set is stale and I'm currently remaking it.
I think you can expect this functionality in the next release, though it's probably not going to be too soon.
