### ISSUE TITLE
Make FLATPAK: For everyones simplification of life

### ISSUE THREAD

**Issue by vonschutter** [libratbag/libratbag#1272]
**Is your feature request related to a problem? Please describe.**
I suggest creating a flatpak limiting the need to support multiple distros yourself. 

**Describe the solution you'd like**
Make package available in flatpak instead of PPA, and various distro specific packages.

**Describe alternatives you've considered**
Painful install and configuration with complex instructions that do not survive upgrades. 

**Additional context**
Using Ubuntu.

**Comment by whot** [comment]
ratbag needs access to `/dev/hidraw` devices which is not possible under flatpak and there are no portals that allow for this either. Until we have that in flatpak, there's nothing we can do.
