### ISSUE TITLE
Bloody A60

### ISSUE THREAD

**Issue by wbswbs** [libratbag/libratbag#1289]
Hi, my sun has a  Bloody A60 Gaming Mouse and wanted to use and configure it on Ubuntu.

Which informationen do I need to add a Piper driver?

Do you have a manual for doing it?

**Comment by amfern** [comment]
You can try adding the .device under each protocol, and if none worked that you will have to reverse-engineering the device-specific protocol
[I don't think](https://github.com/libratbag/libratbag#adding-devices-to-libratbag)

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.

**Comment by ProbablyNotToxicity** [comment]
so there wont be bloody a60 support?
