### ISSUE TITLE
Lexip NP93

### ISSUE THREAD

**Issue by rohitpid** [libratbag/libratbag#1290]
Hey, I was wondering if I could get some help writing a driver for the Lexip NP93 mouse. I'm trying to use it for accessibility purposes as it would be ideal to play games with for people who only have use of one hand. Currently the mouse is using the hid-generic kernel driver when I plug it in. The mouse in question is a special mouse that has:

1) a dpi toggle button (doesn't work with hid-generic)
2) a joystick (Instead of analog input, it is mapped to button events when I use xev. Is this because hid-generic doesn't allow for extra analog input?)
3) RGB LED control
4) Regular mouse stuff like analog input for moving around and many buttons

Ideally this mouse would behave like a mouse with a joystick input. When I use wireshark on the usbmon device that is created I can see the bits that change when I press each button. However, the joystick seems to be registered as a button that only changes bits. I would love to get some help understanding which bits correspond to what when I'm looking at wireshark data.

I was wondering if someone could point me to an explanation of the interactions between the mouse kernel driver, the ratbagd c userspace driver and the ratbagd device config file. To get the functionality I want (analog input from the joystick) would I need to write a kernel driver as well as a ratbag userspace driver? What would the the process look like? I would love to contribute more if someone can help me get started.

I saw that you need more maintainers and would love to contribute/help if someone could mentor me to get started.

Is there an IRC channel? I know it's asking a lot but a few questions and answers might get me going.

**Comment by amfern** [comment]
ratbag is not a driver in a sense like kernel driver, it's more of a configuration tool for setting configs on the mouse side using its proprietary protocol.
Most of The protocols implemented on top of hid interface (https://www.kernel.org/doc/html/latest/hid/hidraw.html#the-hidraw-api).
The ratbag user space driver.

> would I need to write a kernel driver as well as a ratbag userspace driver?

I don't know, but we can do some checks to answer this questions, my guess is that NP93 is storing the configuration on board and just identifies as a regular HID device to the computer. It is similar to other mouse on the market.

1. How does it work on Windows, did you install some proprietary driver to make the DPI toggle button and joystick work?
2. I am wondering if the LED control, DPI and joystick stored on the onboard memory of the mouse. Can you configure the LEDs on Windows machine and then plug it to Linux, does the LED, dpi, Joysitck configuration stay?
If the answer is yes, then the LED configs probably stored on the onboard mouse memory.
3. I am not sure how the joystick, but judging by this [video](https://www.youtube.com/watch?v=638tpjJdgXM) i would guess it can identify as joystick, arrow keys, or mouse.

The best thing to do is to install their software in a Windows VM, and passthrough the mouse to the VM, then you can observe what HID commands are coming in and out of the mouse using wireshark+usbmon.

**Comment by rohitpid** [comment]
I think I have a better understanding of what is going on and can answer some of those questions.

You install some proprietary software which seems to:
1) Set the mode of the mouse (this changes what data I capture when using wireshark. For example if the joystick directions are set to digital mode, they register as 4 buttons and you get the corresponding bits set in wireshark dumps. If the joystick is in analog mode, you get much more granular data in wireshark associated with the analog bits (I think it's 10bit 1024 values per axis but I need to double check). There is a separate handshake from normal operation to set the mode for the joystick and other functionality like DPI, LED colour etc of the mouse.
2) Yes, the LED and joystick configuration stays the same after reboot into Linux
3) exactly right, I think this relates back to my answer in (1)

Let's start with the easiest mode which is digital mode for the joystick buttons. How would I go about writing a ratbag plugin/driver to do this? Can you help me get started?

The next step would be to write the parts to do the mode switching to analog mode etc.

**Comment by amfern** [comment]
Have a look at [steelseries driver](https://github.com/libratbag/libratbag/blob/master/src/driver-steelseries.c), this is pretty simple driver and should give you an idea how to implement one yourself.
- Generally, you would use `ratbag_hidraw_get_feature_report()/ratbag_hidraw_set_feature_report()` to read and write and commands from and to the mouse.
- define `struct ratbag_driver steelseries_driver` and define the driver methods
  - .probe - find and read data from mouse into an internal structure(drv_data), i believe this mouse has only one profile
  - .commit - write the internal structure to the mouse

Keep in mind, libratbag is only for setting the mouse configurations, and it doesn't handle the mouse input. The input is handled by kernel + [libinput](https://gitlab.freedesktop.org/libinput/libinput/), so I would expect the analog joystick to work on Linux, but I am not sure how one can validate it, maybe run a game that is able or try this website https://gamepad-tester.com/
Also, please upload the Wireshark records of changing the mouse settings, it would help for reverse engineering effort and maybe I would be able to help somehow too

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.

> I was wondering if I could get some help writing a driver for the Lexip NP93 mouse
If you ever get motivated to work on this again, feel free to ask anything, I'd try my best to help.
