### ISSUE TITLE
Razer DeathAdder V2

### ISSUE THREAD

**Issue by Sailor1545** [libratbag/libratbag#1292]
Hi,
Can you please add support for razer mice, especially for the DeathAdder V2, I'd really appreciate that. My current Programm can't handle the middle mouse button.
Thanks
Sailor1547

**Comment by MightyCreak** [comment]
I have a Rzer DeathAdder V2 Pro, it would also be nice to support this one (I guess it's not so far from the non-pro version).

That said, @Sailor1545 my middle mouse button works perfectly fine by default with my mouse on all the applications I've tested.

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/libratbag/libratbag/issues/103

**Comment by staticssleever668** [comment]
Closing in favor of #103
