### ISSUE TITLE
Logitech MX518 - very old version

### ISSUE THREAD

**Issue by DiPQ** [libratbag/libratbag#1301]
**Info**
* ratbagd --version  0.16
* distro                    SteamOS release rolling (Holo) BUILD_ID=20220419.100
* kernel                   Linux version 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8 (linux-neptune@archlinux)

I've got a very old version of a mx518 which is not detected by ratbag, as it has a different identifier from the one in the .device. 
I would like to help in adding support for it, but looking at the wiki I'm quite unsure if it shoud use the HID++ 1.0 or the HID++ 2.0 format, and if I shoud edit the existing .device or if it must be on a separate file.

lsusb sees the device as **Bus 001 Device 006: ID 046d:c051 Logitech, Inc. G3 (MX518) Optical Mouse**

full output:

> (deck@steamdeck ~)$ sudo lsusb -d 046d:c051 --verbose 
> [sudo] password for deck: 
> 
> Bus 001 Device 006: ID 046d:c051 Logitech, Inc. G3 (MX518) Optical Mouse
> Device Descriptor:
>   bLength                18
>   bDescriptorType         1
>   bcdUSB               2.00
>   bDeviceClass            0 
>   bDeviceSubClass         0 
>   bDeviceProtocol         0 
>   bMaxPacketSize0         8
>   idVendor           0x046d Logitech, Inc.
>   idProduct          0xc051 G3 (MX518) Optical Mouse
>   bcdDevice           30.00
>   iManufacturer           1 Logitech
>   iProduct                2 USB-PS/2 Optical Mouse
>   iSerial                 0 
>   bNumConfigurations      1
>   Configuration Descriptor:
>     bLength                 9
>     bDescriptorType         2
>     wTotalLength       0x0022
>     bNumInterfaces          1
>     bConfigurationValue     1
>     iConfiguration          0 
>     bmAttributes         0xa0
>       (Bus Powered)
>       Remote Wakeup
>     MaxPower               98mA
>     Interface Descriptor:
>       bLength                 9
>       bDescriptorType         4
>       bInterfaceNumber        0
>       bAlternateSetting       0
>       bNumEndpoints           1
>       bInterfaceClass         3 Human Interface Device
>       bInterfaceSubClass      1 Boot Interface Subclass
>       bInterfaceProtocol      2 Mouse
>       iInterface              0 
>         HID Device Descriptor:
>           bLength                 9
>           bDescriptorType        33
>           bcdHID               1.10
>           bCountryCode            0 Not supported
>           bNumDescriptors         1
>           bDescriptorType        34 Report
>           wDescriptorLength      77
>          Report Descriptors: 
>            ** UNAVAILABLE **
>       Endpoint Descriptor:
>         bLength                 7
>         bDescriptorType         5
>         bEndpointAddress     0x81  EP 1 IN
>         bmAttributes            3
>           Transfer Type            Interrupt
>           Synch Type               None
>           Usage Type               Data
>         wMaxPacketSize     0x0008  1x 8 bytes
>         bInterval              10
> Device Status:     0x0000
>   (Bus Powered)
Thank you!

**Comment by anohren** [comment]
It'd be nice if it were supported. As mentioned in https://github.com/libratbag/libratbag/issues/1000#issuecomment-757373101 the protocol would have to be reverse-engineered.

**Comment by staticssleever668** [comment]
Duplicate #1000.
