### ISSUE TITLE
> hello my mouse is giving me this error and my mouse is working inverted pls fix this error ![Screenshot (64)](https://user-images.githubusercontent.com/101107913/158517551-b9f21820-597a-4c07-aa4b-eaf42c7edf4c.png) and ![Screenshot (65)](https://user-images.githubusercontent.com/101107913/158517580-e2a312e2-2fca-4001-bf0d-3fab6468a837.png) i am clicking but it is not working pls help

### ISSUE THREAD

**Issue by skdas123** [libratbag/libratbag#1305]
> hello my mouse is giving me this error and my mouse is working inverted pls fix this error ![Screenshot (64)](https://user-images.githubusercontent.com/101107913/158517551-b9f21820-597a-4c07-aa4b-eaf42c7edf4c.png) and ![Screenshot (65)](https://user-images.githubusercontent.com/101107913/158517580-e2a312e2-2fca-4001-bf0d-3fab6468a837.png) i am clicking but it is not working pls help

meee tooo same problem

_Originally posted by @RohanRoy49984 in https://github.com/libratbag/libratbag/issues/1038#issuecomment-1069128111_

**Comment by skdas123** [comment]
plz any body help to slove this one

**Comment by DashkillerZ** [comment]
this error even had my mouse reverse and some keybindings are changed as well

**Comment by DashkillerZ** [comment]
this error even had my mouse reverse and some keybindings are changed as well

**Comment by Deepparalikar** [comment]
even my mouse cursor has been reversed and all additional key bindings have been removed

**Comment by r-v-g-7** [comment]
Did You solve it anyways ?? Same issue
