### ISSUE TITLE
Support for HyperX Pulsefire Core

### ISSUE THREAD

**Issue by Remisence** [libratbag/libratbag#1317]
So I've been trying to make a .device file for HyperX Pulsefire Core from scratch, but to no avail. The Piper GUI doesn't detect a device. And here's what my .device file looks like:

```dosini
[Device]
Name=Pulsefire Core
DeviceMatch=usb:0951:16de
Driver=hidpp10

[Driver/hidpp10]
Buttons=5
Leds=1
DpiRange=400:6200@100
```

The output of dmesg | grep Kingston shows:

```
[    1.300091] usb 3-1: Manufacturer: Kingston
[    1.305517] input: Kingston HyperX Pulsefire Core as /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:0951:16DE.0001/input/input2
[    1.305581] hid-generic 0003:0951:16DE.0001: input,hidraw0: USB HID v1.11 Mouse [Kingston HyperX Pulsefire Core] on usb-0000:00:14.0-1/input0
[    1.306287] input: Kingston HyperX Pulsefire Core Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1/0003:0951:16DE.0002/input/input3
[    1.362356] hid-generic 0003:0951:16DE.0002: input,hiddev96,hidraw1: USB HID v1.11 Keyboard [Kingston HyperX Pulsefire Core] on usb-0000:00:14.0-1/input1
[    1.362691] hid-generic 0003:0951:16DE.0003: hiddev97,hidraw2: USB HID v1.11 Device [Kingston HyperX Pulsefire Core] on usb-0000:00:14.0-1/input2
```

And in lsusb the mouse is listed as:

`Bus 003 Device 002: ID 0951:16de Kingston Technology HyperX Pulsefire Core`

I am out of my depth and don't know how to make it work, so some help would be greatly appreciated.

**Comment by staticssleever668** [comment]
> Driver=hidpp10
hidpp10 is a driver for older Logitech mice.
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one. :)
