### ISSUE TITLE
Logitech G102 mice not getting detected

### ISSUE THREAD

**Issue by BhaskarJoshi-01** [libratbag/libratbag#1318]
After piper is installed on ubuntu 20.04 I found that device G102 cannot be detected by it. I cross-checked it by connecting G502 and it was working perfectly. 
Please look into it !

**Comment by Emvo10** [comment]
It is fixed.
`sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git`
`sudo apt update`
`sudo apt install piper`

**Comment by Emvo10** [comment]
> After piper is installed on ubuntu 20.04 I found that device G102 cannot be detected by it. I cross-checked it by connecting G502 and it was working perfectly. Please look into it !

It is fixed.

`sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git`
`sudo apt update`
`sudo apt install piper`

**Comment by staticssleever668** [comment]
Please, remake this following the issue template.
