### ISSUE TITLE
Is there a way to install all the dependencies at once? Or list them somewhere?

### ISSUE THREAD

**Issue by TrySpace** [libratbag/libratbag#1319]
I've been trying to run the simple command `meson builddir` but I keep having to install missing dependencies one by one...

There must be a better way?

**Comment by TrySpace** [comment]
Or add this: `sudo apt install cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig` to the readme

**Comment by perigoso** [comment]
https://github.com/libratbag/libratbag/wiki/Building-from-source
