### ISSUE TITLE
Glorious Model I support?

### ISSUE THREAD

**Issue by AlexP11223** [libratbag/libratbag#1327]
Any ideas if Glorious Model I is supported or how difficult it would be to add?

**Comment by staticssleever668** [comment]
Run `lsusb` in the terminal and post the output. There is a chance current driver supports the mouse, but doesn't know it's device ID.

**Comment by RagingBuracku** [comment]
yeah static,  I also own a Glorious model I, and when I ran lsusb it was recognized

output from lsusb: "Bus 003 Device 004: ID 22d4:1503 Laview Technology Glorious Model I"

**Comment by AlexP11223** [comment]
> Laview

Could be related to https://github.com/libratbag/libratbag/issues/487, https://github.com/libratbag/libratbag/pull/498

**Comment by AlexP11223** [comment]
Got this mouse. `lsusb` outputs the same.

`sinowealth` driver does not work. [output](https://gist.github.com/AlexP11223/489fa3551966a73398578c9f656a74c1)

I thought I will be able to rebind the additional keys in a Windows VM but somehow they do not work in Linux. 
Did they manage to somehow send keys in a Windows-only way? :thinking:
I am simply binding for example a single letter `A` to a button. Also tried Esc, Enter.
It works fine in a clean Windows VM without the Glorious software.

On Logitech key binds work even in BIOS.

**Comment by AlexP11223** [comment]
I ended up returning the mouse for now, because I have no experience in reverse engineering such things, and no time currently.

There are these related requests on the Glorious website, maybe it would be a good idea to vote/comment there:

- https://gloriouspcgaming.featureupvote.com/suggestions/303622/linux-mintubuntudebian
- https://gloriouspcgaming.featureupvote.com/suggestions/320258/make-glorious-core-compatible-with-wine-a-windows-emulator

**Comment by jeffwheeless** [comment]
I've posted this in bountysource because I cannot return my mouse and I would greatly like it to work so I can use the 2 extra side buttons that arent the currently accessible forward and back buttons.
https://app.bountysource.com/issues/111361739-glorious-model-i-support

**Comment by vernonchaney** [comment]
I had assumed I would be able to rebind the extra keys in a Windows virtual machine, but for some reason they do not function in Linux.

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one, as currently no one in libratbag team is going to work on this.

**Comment by RabidWallaby** [comment]
> Since this mouse would require writing a new driver, let's close this until someone volunteers to write one, as currently no one in libratbag team is going to work on this.

What is involved with writing a driver for it?  I don't have any experience with this (or much coding at all), but I have a Model I and am willing to pull whatever details are necessary to get started, and I'm a quick learner.
Is there someone I can work with to do this?

**Comment by staticssleever668** [comment]
I mean a libratbag driver - something that would translate libratbag options into device-specific data.

**Comment by RabidWallaby** [comment]
Ok.  What info is needed for that?  Should I hop into Windows and use Wireshark to get a list of all commands my mouse sends when I press different buttons, move the cursor, etc?

**Comment by staticssleever668** [comment]
Only the data sent by official configuration software and how mouse responds to it is what would actually be needed (captured the same way)

**Comment by RabidWallaby** [comment]
Ok.  So, I need to start up Wireshark with filters for anything sending to Device 2.6.0 and start changing things in the Glorious Core settings to find the corresponding info and then adjust my filters for anything to & from the mouse and software?

**Comment by RabidWallaby** [comment]
[Model-I-Win-Glorious.pcapng.txt](https://github.com/libratbag/libratbag/files/13721086/Model-I-Win-Glorious.pcapng.txt)

Captured some config changes using Glorious Core.  Sadly, the software doesn't let you control it with a keyboard.  EVERYTHING is done with a mouse, so all of the inputs from moving & clicking are recorded too. :(

**Comment by nyabinary** [comment]
> Captured some config changes using Glorious Core. Sadly, the software doesn't let you control it with a keyboard. EVERYTHING is done with a mouse, so all of the inputs from moving & clicking are recorded too. :(
> 
> BUT, I discovered something while playing with Wireshark. The extra buttons are on a separate ID. In my case, the main mouse functions are on 2.6.1 in Windows, and the extra buttons are on 2.6.2
> 
> Here's that file: [Model-I-Win-Glorious-BOTH-IDs.pcapng.txt](https://github.com/libratbag/libratbag/files/13721146/Model-I-Win-Glorious-BOTH-IDs.pcapng.txt)

some nice progress at least :3

**Comment by zackmagic42** [comment]
If anyone is still working on this I have a Model I 2 wireless and would be willing to do some legwork to get this running. If there's a way I can help just let me know.
