### ISSUE TITLE
Add feature to allow setting nothing as macro

### ISSUE THREAD

**Issue by cooke769** [libratbag/libratbag#1334]
It would be nice if you could have an option to set a key to nothing - I have a logitech g915 kb and the g1-g5 macro keys are just in an annoying area on the left side of the keyboard where all the important keys are shift, ctrl, esc, etc.

I have been using piper to set them to be not active, however I've had to set them to be a not relevant to me setting like numlock.

Is this possible?

**Comment by staticssleever668** [comment]
Fixed by #953.
Usage: `ratbagctl <device name> button <button id> action set disabled`.
(NOTE: this is not in a release yet).
