### ISSUE TITLE
Logitech G915 - Piper not displaying correct macro window

### ISSUE THREAD

**Issue by cooke769** [libratbag/libratbag#1335]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Distribution: 
- Kernel version (ex. `uname -srmo`): Linux 5.15.0-43-generic x86_64 GNU/Linux

Device info (if applicable):
```
$ ratbagctl <device> info
thundering-gerbil:   Logitech G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
```

**Describe the bug**
When using Piper 0.7, the macro keys G1-G2 are not able to be set, they instead pop the dialog window to change the left or right handedness instead of the macro keys window.

**To Reproduce**
as above decription.

**Comment by staticssleever668** [comment]
libratbag/piper#536. :)
