### ISSUE TITLE
Logitech M500s not recognized in version 0.16 despite being supported

### ISSUE THREAD

**Issue by bbutler3** [libratbag/libratbag#1337]
This same mouse plugged into an identical machine which was running version 0.13 was recognized fine. I can't figure out why it isn't recognized now. The device file is the same on both machines. I've tried different USB ports and restarted Ubuntu 20.04 with no luck. Any ideas? I'm just running `ratbagtcl` from the command line (`No devices available.`)

My computer recognizes the mouse as plugged in (it's listed in the output of `lsusb`), and shows it appropriately as an M500s.

**Comment by staticssleever668** [comment]
Hi. Please, remake the issue following suggested template.
