### ISSUE TITLE
Glorious Model D unrecognized

### ISSUE THREAD

**Issue by liquidfree** [libratbag/libratbag#1338]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.15
- Distribution: Debian
- Kernel version (ex. `uname -srmo`): `Linux 5.10.120-16471-g167ad2e5dcba x86_64 GNU/Linux`

Device info (if applicable): 
```
$ ratbagctl <device> info
OUTPUT HERE
```

**Describe the bug**
When I have my Glorious Model D connected to my Chromebook via the USB port, it shows the error, "Cannot find any devices." I even reinstalled Piper, and restarted my device several times. This is the first time I have ever used Piper, and I have only been using Linux for a day or so.

**To Reproduce**
1. Plug in Glorious Model D mouse on Chromebook build vers. 104.0.5112.105
2. Enable Linux development environment and set it up
3. Go to Linux terminal and run `sudo apt-get install piper`
4. When Piper is installed, open it
5. The mouse should not be recognized

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
liquidfreewater@penguin:~$ sudo ratbagd --verbose=raw
Initializing libratbag
DBus server ready
```

**Additional context**
![image](https://user-images.githubusercontent.com/111734942/185876576-cbabe54d-ef72-467d-8e5c-50e22ba23ddd.png)

**Comment by lfinbob** [comment]
We are also on Debian and had the same problem. Solved it by compiling the latest version from source. 
`ratbagd --version`: 0.16
Piper Version: 0.7

Now Piper does show the mouse and we can set resolution, buttons and the LED.

![image](https://user-images.githubusercontent.com/99162861/194747263-53a990ec-0ae5-4329-bd5a-57d02a17ae1d.png)

**Comment by staticssleever668** [comment]
Looks like this was caused by an outdated version of libratbag.
