### ISSUE TITLE
Logitech G715 and G705 Support

### ISSUE THREAD

**Issue by 0ddfactory** [libratbag/libratbag#1341]
Please consider adding support for Logitech G715 and G705 keyboard/mouse. This along with issue #1340 will cover the rest of the Logitech Aurora collection. I was hoping that I could just add the device off of the g915 device file but no dice. 

![61yaqyiUMvL _AC_SY450_](https://user-images.githubusercontent.com/25939455/187797315-01494194-55fb-45b6-9310-f786174b0d9d.jpg)

**Comment by staticssleever668** [comment]
Hello, if you have one of these devices, you can try creating a device file for them.

First, find the id of the device with `lsusb`, then create a file like so:

```dosini
[Device]
Name=Logitech GSomething
DeviceMatch=usb:<the id you found>
# If it doesn't work, retry with `hidpp10`.
Driver=hidpp20
```

and put it where other `.device` files are, usually under `/usr/share/libratbag` or `/usr/local/share/libratbag`.
