### ISSUE TITLE
Error: libudev not found

### ISSUE THREAD

**Issue by gregorypiro** [libratbag/libratbag#1342]
What am I suposse to do in easy steps? Im a new user. Thank you.

```
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Found CMake: /usr/bin/cmake (3.20.2)
Run-time dependency libudev found: NO (tried pkgconfig and cmake)

meson.build:72:0: ERROR: Dependency "libudev" not found, tried pkgconfig and cmake

A full log can be found at /home/gpiro/libratbag/builddir/meson-logs/meson-log.txt
```

**Comment by gregorypiro** [comment]
And now it somehow started to "work" and I see:

File "/usr/lib/python3.9/site-packages/mesonbuild/cmake/toolchain.py", line 73, in write
    self.toolchain_file.write_text(self.generate(), encoding='utf-8')
  File "/usr/lib64/python3.9/pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib64/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib64/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/gpiro/libratbag/builddir/meson-private/cmake_libudev/CMakeMesonToolchainFile.cmake'

Just to keep you updated. I understand it may be silly what I ask. :/

**Comment by gregorypiro** [comment]
Thats what its log says:

Target machine cpu family: x86_64
Target machine cpu: x86_64
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Determining dependency 'libudev' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion libudev` -> 1

CMake binary for MachineChoice.HOST is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Found CMake: /usr/bin/cmake (3.20.2)
Extracting basic cmake information
Try CMake generator: auto
Calling CMake (['/usr/bin/cmake']) in /home/gpiro/libratbag/builddir/meson-private/cmake_libudev with:
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-DCMAKE_TOOLCHAIN_FILE=/home/gpiro/libratbag/builddir/meson-private/cmake_libudev/CMakeMesonToolchainFile.cmake"
  - "."
  -- Module search paths:    ['/', '/opt', '/usr', '/usr/local']
  -- CMake root:             /usr/share/cmake
  -- CMake architectures:    []
  -- CMake lib search paths: ['lib', 'lib32', 'lib64', 'libx32', 'share']
Preliminary CMake check failed. Aborting.
Run-time dependency libudev found: NO (tried pkgconfig and cmake)

meson.build:72:0: ERROR: Dependency "libudev" not found, tried pkgconfig and cmake

**Comment by staticssleever668** [comment]
Hi, what distribution are you on? 
If you really intend to *build* libratbag, then the error is straightforward: you are missing libudev or on some distros like Ubuntu it's development files (`libudev-dev`), which is usually a part of systemd. Some distros don't support systemd, and they usually make this one of their selling point, so if your doesn't, you would probably know.
Otherwise, usually you are just supposed to install programs through your package manager. 

For the same error also see #1096 and #495.

**Comment by gregorypiro** [comment]
Hi @staticssleever668 ! Thank you for your answer. Im on the RHEL 9 and perhaps struggling because im new. Anyway i ve done yum search libudev and installed all there is availible. Perhaps i should search for it specifically on the web im not sure, im staying on the case. Still counting on help. Thank you. Greetings.

**Comment by gregorypiro** [comment]
Hi @staticssleever668 ! Thank you for your answer. Im on the RHEL 9 and perhaps struggling because im new. Anyway i ve done yum search libudev and installed all there is availible. Perhaps i should search for it specifically on the web im not sure, im staying on the case. Still counting on help. Thank you. Greetings.

So this line from other discussion helped me.

libudev is a special case because it got absorbed by systemd years ago. so try a package systemd-devel or something like that.

100%

Now i have something like this: Im still in process of resolving this, just letting you know where i am.

Run-time dependency libudev found: YES 250
Run-time dependency libevdev found: YES 1.11.0
Found CMake: /usr/bin/cmake (3.20.2)
Run-time dependency glib-2.0 found: NO (tried pkgconfig and cmake)

meson.build:74:0: ERROR: Dependency "glib-2.0" not found, tried pkgconfig and cmake

A full log can be found at /home/gpiro/Publiczny/libratbag-master/builddir/meson-logs/meson-log.txt

**Comment by gregorypiro** [comment]
And i got to this point now:

Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency libudev found: YES 250
Run-time dependency libevdev found: YES 1.11.0
Run-time dependency glib-2.0 found: YES 2.68.4
Run-time dependency json-glib-1.0 found: YES 1.6.6
Library m found: YES

meson.build:77:0: ERROR: C shared or static library 'unistring' not found

A full log can be found at /home/gpiro/Publiczny/libratbag-master/builddir/meson-logs/meson-log.txt

**Comment by staticssleever668** [comment]
`[Errno 13] Permission denied` is a weird error. Perhaps you've ran `meson` as root (e.g. `sudo meson`) once? Anyway, try removing the build directory (called `builddir` in your case), and remaking the project.

Also, you don't necessarily need to *test* the project, you can disable tests by adding `-Dtests=false` parameter to meson when generating the project. So, considering you have removed `builddir` already, run `meson builddir -Dtests=false`.

**Comment by gregorypiro** [comment]
Hi again. Thank you @staticssleever668 for taking your time. You were right i ve ran meson as a root not once. However after disabling tests i got to the sudo ninja -C builddir install. So from README looks like its all finished. But its perhaps silly question what do i do now? What im suppose to do to open this "program"? How can i configure it?

**Comment by staticssleever668** [comment]
If everything installed correctly, you should be able to run `ratbagctl --help` in the terminal to get the list of possible actions. You don't need to start `ratbagd.service` manually as it's started automatically on-demand (and shut down too, after I think 10 minutes or so).
However, it seems like you've installed it to a different location from system files (which is done intentionally so that you don't ever collide with system's package manager). I'm not sure what the best practice is in this case as I never install anything through custom installers or build systems, only package managers. Still, if you wish I guess you can install it to the default location by setting the project up like so: `meson builddir -Dtests=false --prefix=/usr` (see the `--prefix` option). But before that remove what you have already installed by running `ninja -C  builddir uninstall`.


Also for future: put commands, logs, file lists, etc into code blocks: there is a button that looks like so `<>` above in the comment editor. :)

**Comment by gregorypiro** [comment]
So at the moment i see: 
`[gpiro@gpiro ioq3-main]$ ratbagctl list
Unable to connect to ratbagd: No one currently owns org.freedesktop.ratbag1
[gpiro@gpiro ioq3-main]$ ratbagctl info
Unable to connect to ratbagd: No one currently owns org.freedesktop.ratbag1
[gpiro@gpiro ioq3-main]$ `
 I removed builddir and used suggested `meson builddir -Dtests=false --prefix=/usr`

Further from here i believe im going same way as before.
After all im facing:
`[root@gpiro libratbag-master]# sudo ratbagd
ratbagd error: Failed to start ratbagd: Permission denied`

Maybe i should configure something first, then?

My piper doesnt work it says cannot connect to ratbagd (i dont know if i should include this program)

Otherwise @staticssleever668 tell me your way of installing things through package managers.. ;)

**Comment by staticssleever668** [comment]
Sorry, at this point I don't know what can be wrong... There are currently no active libratbag maintainers, so you probably won't get any more help at this point of time...

Regarding package managers:
On distro I use practically all applications I've seen are in official or at very least user-maintained repository. In the rare cases it's not, I know how to make a package myself. You are on a different distro, and I can't help you in that regards.

**Comment by gregorypiro** [comment]
Hi @staticssleever668 hope you have a great day. So i got here:

`[gpiro@gpiro builddir]$ sudo ratbagd
ratbagd error: Bus name is taken, another instance of ratbagd is already running.
`
I connected mouse run the piper and it works. I mean looks like it. Except i cant use any button on my device. Maybe you could help in that matter?

![Zrzut ekranu z 2022-09-12 09-42-55](https://user-images.githubusercontent.com/112812393/189600182-f26b6092-165a-42ac-b56f-8cefa08c734d.png)

Greetings.

**Comment by staticssleever668** [comment]
```
[gpiro@gpiro builddir]$ sudo ratbagd
ratbagd error: Bus name is taken, another instance of ratbagd is already running. 
```

Happy to hear it starts now! This error is fine as ratbagd is started automatically by systemd on-demand.

Since you've opened another ticket, let's continue it there: libratbag/piper#789.

**Comment by gregorypiro** [comment]
Okay @staticssleever668 . Have suprise info then. ;-)
