### ISSUE TITLE
Support for AmazonBasics Gaming Mouse

### ISSUE THREAD

**Issue by fredinj** [libratbag/libratbag#1348]
[Product Link](https://www.amazon.in/AmazonBasics-AYH-Gaming-Mouse/dp/B073VRVHBG)

The piper GUI doesn't detect the mouse and I'm not really sure how to make the device file. I'm not sure if I got the driver right (hiddev0 shows up at /dev/usb when plugging it in)
```
[Device]
Name=Acrox AmazonBasics gaming mouse
DeviceMatch=usb:3938:1110
Driver=hiddev0

[Driver/hiddev0]
DpiList=200:400:800:1000:1200:1600:2400:2800:3200
```

Output of `lsusb | grep AmazonBasics`
```
Bus 001 Device 002: ID 3938:1110 Acrox AmazonBasics gaming mouse
```

Output of `dmesg | grep AmazonBasics`
```
[    0.967912] usb 1-1: Product: AmazonBasics gaming mouse
[    0.989835] input: Acrox AmazonBasics gaming mouse as /devices/pci0000:00/0000:00:01.2/0000:01:00.0/usb1/1-1/1-1:1.0/0003:3938:1110.0001/input/input2
[    0.990042] hid-generic 0003:3938:1110.0001: input,hidraw0: USB HID v1.11 Mouse [Acrox AmazonBasics gaming mouse] on usb-0000:01:00.0-1/input0
[    1.012389] input: Acrox AmazonBasics gaming mouse Keyboard as /devices/pci0000:00/0000:00:01.2/0000:01:00.0/usb1/1-1/1-1:1.1/0003:3938:1110.0002/input/input3
[    1.065102] input: Acrox AmazonBasics gaming mouse as /devices/pci0000:00/0000:00:01.2/0000:01:00.0/usb1/1-1/1-1:1.1/0003:3938:1110.0002/input/input4
[    1.065293] hid-generic 0003:3938:1110.0002: input,hiddev96,hidraw1: USB HID v1.11 Keyboard [Acrox AmazonBasics gaming mouse] on usb-0000:01:00.0-1/input1
```

[Here](https://imgur.com/a/VX90IwC) are some screenshots of the software

I don't know the process, but I would like to help in adding support for this mouse.

**Comment by staticssleever668** [comment]
>  I'm not sure if I got the driver right
It actually relates to a libratbag driver, not a kernel driver.
Drivers in libratbag "translate" generic commands to change some mouse settings to a way a mouse can understand. 

Since this mouse would require writing a new such driver, let's close this until someone volunteers to write one. :)
