### ISSUE TITLE
Please add build prerequisites - I have trouble building it (please help)

### ISSUE THREAD

**Issue by TrygveK** [libratbag/libratbag#1349]
**Is your feature request related to a problem? Please describe.**
Please see my uber-painful build experience:  https://gist.github.com/TrygveK/ae2a799f3b683ef8dfa9311810bb515c
One at-a-time dependency needs to be installed.

then it fails at 
```
Program python3 found: YES (/usr/bin/python3)
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.

meson.build:485:2: ERROR: Python dependency not found


```

**Describe the solution you'd like**
 a clear set of dependencies would do.
- or a precompiled build.

**Comment by staticssleever668** [comment]
Hello, there is actually such a list already, it's on the wiki! :)
https://github.com/libratbag/libratbag/wiki/Building-from-source
