### ISSUE TITLE
Missing dependency when building on RHEL 8

### ISSUE THREAD

**Issue by Dom324** [libratbag/libratbag#1350]
Hi,
when trying to build `libratbag` on RHEL8, command `meson builddir` fails with:
```
$ meson builddir
The Meson build system
Version: 0.61.5
Source dir: /home/kevin/Downloads/libratbag-master
Build dir: /home/kevin/Downloads/libratbag-master/builddir
Build type: native build
Project name: libratbag
Project version: 0.16
C compiler for the host machine: cc (gcc 8.5.0 "cc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)")
C linker for the host machine: cc ld.bfd 2.30-113
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Run-time dependency libudev found: YES 239
Found CMake: /usr/bin/cmake (3.20.2)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libevdev found: NO (tried pkgconfig and cmake)

meson.build:73:0: ERROR: Dependency "libevdev" not found, tried pkgconfig and cmake
```

But when I run `sudo yum install libevdev` to install libevdev, I get the following message:
`Package libevdev-1.10.0-1.el8.x86_64 is already installed.`

Does anybody know what might be the issue?
Thanks

**Comment by staticssleever668** [comment]
Hello, depending on the distro you may need the "developer" packages for dependencies, in case of libevdev it may be called `libevdev-devel` or `libevdev-dev`.

Also, see wiki: https://github.com/libratbag/libratbag/wiki/Building-from-source.

**Comment by Dom324** [comment]
I tried those, but when installing with yum I get:
`Error: Unable to find a match: libevdev-devel`
`Error: Unable to find a match: libevdev-dev`
Also, I couldn't find those packages for RHEL8 anywhere on internet, does that mean that the only option is to build them from source?
Thanks

**Comment by staticssleever668** [comment]
To be honest, I don't have any experience with RHEL, and the idea about developer packages was the only thing I could think of. I doubt you are required to build it yourself, but I can't help about this without having RHEL installed. Could you post the output of `yum search libevdev`? Maybe I will spot the needed package. (I tried searching for RHEL package list in the net but couldn't find anytning).
If we end up finding nothing, I suggest you searching the `ERROR: Dependency "libevdev" not found, tried pkgconfig and cmake` error along with distro name and version in the web.

**Comment by jnowaczek** [comment]
I was able to build libratbag from source on RHEL 8.6, here's the `libevdev` packages I needed:

```
$ sudo dnf info libevdev-devel
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - Supplem  90 kB/s | 3.8 kB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - AppStre  89 kB/s | 4.5 kB     00:00    
Red Hat Ansible Engine 2.8 for RHEL 8 x86_64 (R  66 kB/s | 4.0 kB     00:00    
Red Hat Satellite Tools 6.10 for RHEL 8 x86_64   73 kB/s | 3.8 kB     00:00    
Red Hat Ansible Engine 2.9 for RHEL 8 x86_64 (R  69 kB/s | 4.0 kB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS   77 kB/s | 4.1 kB     00:00    
Red Hat Virtualization 4 Tools for RHEL 8 x86_6  73 kB/s | 3.8 kB     00:00    
Red Hat CodeReady Linux Builder for RHEL 8 x86_  82 kB/s | 4.5 kB     00:00    
Red Hat Satellite Tools 6.9 for RHEL 8 x86_64 (  67 kB/s | 3.8 kB     00:00    
Installed Packages
Name         : libevdev-devel
Version      : 1.10.0
Release      : 1.el8
Architecture : x86_64
Size         : 96 k
Source       : libevdev-1.10.0-1.el8.src.rpm
Repository   : @System
From repo    : codeready-builder-for-rhel-8-x86_64-rpms
Summary      : Kernel Evdev Device Wrapper Library Development Package
URL          : http://www.freedesktop.org/wiki/Software/libevdev
License      : MIT
Description  : Kernel Evdev Device Wrapper Library Development Package.

Available Packages
Name         : libevdev-devel
Version      : 1.10.0
Release      : 1.el8
Architecture : i686
Size         : 35 k
Source       : libevdev-1.10.0-1.el8.src.rpm
Repository   : codeready-builder-for-rhel-8-x86_64-rpms
Summary      : Kernel Evdev Device Wrapper Library Development Package
URL          : http://www.freedesktop.org/wiki/Software/libevdev
License      : MIT
Description  : Kernel Evdev Device Wrapper Library Development Package.
```

I believe `codeready-builder-for-rhel-8-x86_64-rpms` is a RHEL subscription managed repository, so is it possible your subscription is the issue?

**Comment by Dom324** [comment]
Many thanks @jnowaczek , thanks to you I was able to solve it - the issue wasn't in subscription, I simply didn't have the `codeready-builder-for-rhel-8-x86_64-rpms ` repo :facepalm:  After that the build worked and now ratbagd together with piper are working!

The only other issue I came across was that I needed to move `ratbagd.service` to `/usr/lib/systemd/system/` , otherwise `sudo systemctl enable ratbagd.service` did not work and ratbagd did not start automaticaly.
