### ISSUE TITLE
Glorious Model D: Port missing debounce time feature from gloriousctl

### ISSUE THREAD

**Issue by lfinbob** [libratbag/libratbag#1352]
Running Debian Bookworm/Sid
Compiled latest ratbag (0.16) and piper (0.7) from source, as Debian packages are too old for Glorious Model D.
Linux 5.19.0-1-amd64 x86_64 GNU/Linux

Device info (if applicable):
258a:0033 SINOWEALTH Wired Gaming Mouse

$ ratbagctl <device> info
ratbagctl cheering-viscacha info
cheering-viscacha - Glorious Model D
             Model: usb:258a:0033:0
 Number of Buttons: 6
    Number of Leds: 1
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 300x300dpi
    1: 800x800dpi (active) (default)
    2: 2000x2000dpi
    3: 2000x2000dpi
    4: <disabled>
    5: <disabled>
    6: <disabled>
    7: <disabled>
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 2'
  Button: 3 is mapped to 'button 2'
  Button: 4 is mapped to 'button 1'
  Button: 5 is mapped to 'button 4'
  LED: 0, depth: rgb, mode: on, color: c0bfbc

**Describe the bug**
There is no way to set the debounce time. This means there is no way to drag click in games.
This was implemented in gloriousctl in commit https://github.com/enkore/gloriousctl/commit/e71fc07afc00f9f4e591cfa52e60a0b1e21da0a7 by @staticssleever668. Can it be ported to libratbag?

**Comment by staticssleever668** [comment]
Hi, there is #1168 for that.
Basically the reason it's not here yet is that it's HIGHLY specific to Glorious mice in the sense that no other mice have this feature exposed. Since libratbag is meant as a cross-vendor configuration utility, it's not too fun implementing this (remember this is a non-commercial passion-driven project).
