### ISSUE TITLE
Allow using ratbag-command without root

### ISSUE THREAD

**Issue by Wolf480pl** [libratbag/libratbag#136]
libratbag just needs access to an appropriate hidraw device, right?

If so, one could make an udev rule that adds the `uaccess` tag to the right hidraw device, which would make systemd-logind give access to the device to whatever user is currently logged in locally (like it does with soundcard, etc.).

I wrote a little quick rule to do this with my G300S, but I'm matching the USB ID directly:
```
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c246", TAG+="uaccess"
```
ratbag-command seems to work without root with this rule.

I think it'd be better if it used the hwdb somehow, instead of matching one particular mouse, but I have no idea how to use hwdb.

**Comment by whot** [comment]
good point, that makes sense. The only comment I'd have here is that libratbag as a library probably shouldn't mess with access rules but that's something we can fix in the future when we have ratbagd/piper set up properly.

 @dvdhrm: any reason you can think of why not to use uaccess here?

We can't use the hwdb directly because we match on input nodes here, not hidraw nodes. But so far we don't really care about anything but bus/vid/pid. So we could lift the data from the current hwdb file into an intermediate file with a lookup table and process that into a .hwdb file and a udev rules file with the uaccess tag.

**Comment by bentiss** [comment]
I am not entirely familiar with the uaccess tag, but there is at least one issue I can think of. Sound cards are not much a security threat for stealing passwords, while input devices are.

And gaming mice are providing both a keyboard node and a mouse node. Though the mouse node is less critical in term of spying the raw data stream, the keyboard node is. And if you allow the current user to open the node without privileges, then something unwanted could spy on the keyboard node.
Also, even if it's just injections of events, this poses a security threat too (see [Mousejack](http://www.mousejack.com/)).

Anyway, ratbag-command is really just a debug tool (OK, that's the only one that works properly). For regular users, they are supposed to use ratbagd, which has the benefit of being a central daemon, and so it doesn't probe the mouse for each command you send. ratbagctl/piper should probably be enhanced, but that's the tools we want users to use.

**Comment by Wolf480pl** [comment]
whot:
>The only comment I'd have here is that libratbag as a library probably shouldn't mess with access rules

You could always put it in some kind of contrib directory, so that people copy it manually to `/etc/udev/rules.d` when they want it.

bentiss:
>I am not entirely familiar with the uaccess tag

Neither am I, but from what I've observed, it gives an rw ACL entry on the node for the user who owns the active session on the current tty. When switching ttys, or logging in/out, the ACL entry is updated.

>Anyway, ratbag-command is really just a debug tool
>[...]
>For regular users, they are supposed to use ratbagd

Well, I personally only need to configure my mouse once, and I think ratbag-command is good for this purpose. Haven't tried ratbagd yet, and I don't see any reason why I'd want it.

But I guess if I only need to do this once, I may as well manually `chmod` the right hidraw device, for the time of configuration.

>And if you allow the current user to open the node without privileges, then something unwanted could spy on the keyboard node.

Will the hidraw node of the mouse send any keyboard events other than macros assigned to keys?

>Also, even if it's just injections of events, this poses a security threat too

Can you inject events through hidraw, other than by defining rogue macros?

**Comment by whot** [comment]
> You could always put it in some kind of contrib directory, so that people copy it manually to /etc/udev/rules.d when they want it.

in that case we could just put it in the README to copy into the local system. One extra step for people to realise it's not something to use as a default thing.

> bentiss:
> 
>     I am not entirely familiar with the uaccess tag
> 
> Neither am I, but from what I've observed, it gives an rw ACL entry on the node for the user who owns the active session on the current tty. When switching ttys, or logging in/out, the ACL entry is updated.

the code is quite simple:
https://github.com/systemd/systemd/blob/master/src/udev/udev-builtin-uaccess.c
triggered by 71-seat-late.rules

> 
>     And if you allow the current user to open the node without privileges, then something unwanted could spy on the keyboard node.
> 
> Will the hidraw node of the mouse send any keyboard events other than macros assigned to keys?

no, but I'm not sure we can guarantee to only hit the mouse-related keyboard node. A rule may apply to the normal keyboard node and whoops, your keyboard input is world-readable (to anything from the current user, anyway).

**Comment by whot** [comment]
Ok, closing this for now. Right now we have ratbag-command that requires root and this won't change. We have ratbagctl as part of ratbagd which doesn't require root though it requires ratbagd. With a couple of larger changes likely to happen to libratbag/ratbagd, we'll probably have a command that won't require root as part of the standard distribution but it won't be ratbagd-command.
