### ISSUE TITLE
Logitech G303 Shroud Edition support

### ISSUE THREAD

**Issue by lennie420** [libratbag/libratbag#1374]
**Information**

- `ratbagd` version (`ratbagd --version`):0.16
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): Linux 6.0.9-zen1-1-zen x86_64 GNU/Linux

Device info (if applicable):
```
$ ratbagctl <device> info
No devices available.
```

**Describe the bug**
Device not detected

Wired:
Bus 003 Device 006: ID 046d:c097 Logitech, Inc. G303 SHROUD EDITION GAMING MOUSE
Receiver:
Bus 003 Device 012: ID 046d:c547 Logitech, Inc. USB Receiver

**Comment by staticssleever668** [comment]
Hello, have you tried making a device file?
```dosini
[Device]
Name=Logitech G303 Shroud Edition
DeviceMatch=usb:046d:c097
Driver=hidpp20
```
Create a file names `logitech-g303-shroud.device` and put it in `/usr/share/libratbag` or `/usr/local/share/libratbag` depending on where other `.device` files reside.

**Comment by lennie420** [comment]
I have created a .device file and confirmed  the mouse is being detected in Piper. I am able to successfully change the DPI and apply the settings. I have created a .device file in Github but not sure if I've done it correctly.

**Comment by lennie420** [comment]
Pull request successfully committed, marking as closed: https://github.com/libratbag/libratbag/commit/919cde2b15c1afd740f11f7c2b06101fb6e68999
