### ISSUE TITLE
Failed to enable unit: Unit file ratbagd.service does not exist.

### ISSUE THREAD

**Issue by gregorypiro** [libratbag/libratbag#1379]
Guys, just quick easy probably question and im removing it.

[root@localhost gpiro]# systemctl enable ratbagd
Failed to enable unit: Unit file ratbagd.service does not exist.

 It is a last command, hehe, to complete installation in order to launch piper.

Im running RHEL 9.1, perhaps someone can quickly offer help?

Addition:

Also,

[root@localhost ~]# ratbagd 
ratbagd error: Failed to start ratbagd: Permission denied
Why so?

Thanks

**Comment by staticssleever668** [comment]
Did you build from source? How did you do it, and what were meson and ninja's outputs?

**Comment by gregorypiro** [comment]
Hi @staticssleever668 ,

All installation went completally fine, every single command.

**Comment by gregorypiro** [comment]
Solved by re-installing.

**Comment by gregorypiro** [comment]
Solved by re-installing.
