### ISSUE TITLE
Errors loading Logitech G502 in Arch Linux

### ISSUE THREAD

**Issue by T10a** [libratbag/libratbag#138]
Hello. I'm trying to load my Logitech G502 mouse into ratbag, however I am running across issues loading the device.

 For starters, Piper doesn't recognise the mouse, and when I check the device with
`sudo ratbag-command list`, my shell returns:
`“sudo ratbag-command list” terminated by signal SIGSEGV (Address boundary error)`.

systemctl-status of ratbagd.service returns the following:
`● ratbagd.service - Daemon to introspect and modify configurable mice`
 `  Loaded: loaded (/usr/lib/systemd/system/ratbagd.service; enabled; vendor preset: disabled)`
`   Active: failed (Result: core-dump) since Fri 2017-03-24 16:38:22 AEDT; 20min ago`
` Main PID: 1881 (code=dumped, signal=SEGV)`
`Mar 24 16:38:22 arch-desktop-26 systemd[1]: ratbagd.service: Unit entered failed state.`
`Mar 24 16:38:22 arch-desktop-26 systemd[1]: ratbagd.service: Failed with result 'core-dump'.`
`Mar 24 16:38:22 arch-desktop-26 systemd[1]: ratbagd.service: Service hold-off time over, scheduling restart.`
`Mar 24 16:38:22 arch-desktop-26 systemd[1]: Stopped Daemon to introspect and modify configurable mice.`
`Mar 24 16:38:22 arch-desktop-26 systemd[1]: ratbagd.service: Start request repeated too quickly.`
`Mar 24 16:38:22 arch-desktop-26 systemd[1]: Failed to start Daemon to introspect and modify configurable mice.`
`Mar 24 16:38:22 arch-desktop-26 systemd[1]: ratbagd.service: Unit entered failed state.`
`Mar 24 16:38:22 arch-desktop-26 systemd[1]: ratbagd.service: Failed with result 'core-dump'.`

`sudo udevadm info /sys/class/input/eventX | grep RATBAG_DRIVER` returns
`Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.`

Keep in mind, I installed via the AUR. I'm still not sure why the daemon is resulting in a core dump and a segmentation fault.

**Comment by bentiss** [comment]
That's a packaging issue. Libratbag 0.6 broke the ABI, so I bumped the .so version. ratbagd simply needs to be recompiled against the new libratbag for it to find the new symbols and not core dump.

@r3pek can you please rebuild ratbagd in AUR?

**Comment by r3pek** [comment]
@bentiss done ;)
