### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [libratbag/libratbag#14]
Would you like to add more error handling for return values from functions like the following?
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [ratbag_cmd_list_supported_devices](https://github.com/libratbag/libratbag/blob/a3aacd3a99904cf87ac270055c1dd7061499e584/tools/ratbag-command.c#L688)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [ratbag_device_new](https://github.com/libratbag/libratbag/blob/a3aacd3a99904cf87ac270055c1dd7061499e584/src/libratbag.c#L222)

**Comment by whot** [comment]
sprintf - yes please, printf doesn't need to
strdup - I think we should just make a wrapper that aborts if strdup fails, similar to zalloc. there is not much value in handling OOM

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/libratbag/libratbag/blob/31dc1f47726fbca483f3bed8d7881434bdc22845/tools/shared.c#L278 "More update candidates") left over?

How do you think about to annotate any functions with "[`__attribute__((warn_unused_result))`](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Function-Attributes.html#index-g_t_0040code_007bwarn_005funused_005fresult_007d-function-attribute-3299 "Special function attributes?")"?

**Comment by whot** [comment]
do we have functions where we need to warn about this? That's generally one of the flags I disable from the warning flags, too many false positives.
