### ISSUE TITLE
Option to install it on Steam Deck?

### ISSUE THREAD

**Issue by rafx85** [libratbag/libratbag#1408]
**Is your feature request related to a problem? Please describe.**
I can't install it on Steam Deck, SD is based on Arch Linux, but the command for Arch Linux not working for Steam Deck.

**Describe the solution you'd like**
Would be nice to have some simple way to install on Steam Deck. Piper I can install from Flatpak but without libratbag it does not work.

**Describe alternatives you've considered**
I did not find any alternatives.

**Additional context**
No

**Comment by staticssleever668** [comment]
Hello, I think it's on distro maintainers to make packages, especially on rolling distros.
For now, your only option would be do build from source: https://github.com/libratbag/libratbag/wiki/Building-from-source
If I remember correctly, Steam OS has an immutable base system that gets reset whenever Steam OS updates, which would mean you will have to reinstall libratbag after every system update, but I don't think there is anything we can do about this, sorry.
