### ISSUE TITLE
Inphic PG2 (Sinowealth 258a:0028) support

### ISSUE THREAD

**Issue by nebspacefarer** [libratbag/libratbag#1411]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Distribution: EndeavourOS (Arch)
- Kernel version (ex. `uname -srmo`): `Linux 6.1.7-zen1-1-zen x86_64 GNU/Linux`

**Describe the bug**
Another Sinowealth device that can be supported with a few tricks. I have a Inphic PG2 G-Series recognized as a Sinowealth 258a:0028 by `lsusb` command.
It has 7 buttons (without including clicks) and 2 buttons for DPI.
4 levels of DPI.
LED(s?) under the logo, under the mouse wheel and one going around the bottom of the mouse, and 1 led for each DPI level (so 4).

```
$ lsusb
Bus 001 Device 002: ID 258a:0028 SINOWEALTH Wired Gaming Mouse
```

Here is what the in-depth info from `lsusb` tells me
```
$ lsusb -d 258a:0028 --verbose
Bus 001 Device 002: ID 258a:0028 SINOWEALTH Wired Gaming Mouse
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x258a 
  idProduct          0x0028 
  bcdDevice            1.00
  iManufacturer           1 SINOWEALTH
  iProduct                2 Wired Gaming Mouse
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x003b
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              480mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      71
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     213
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

```
**Steps done**

Command `ratbagctl list` was outputting `no device found` so I've followed the wiki and created a simple `sinowealth-0028.device` with this content:
```
[Device]
Name=Sinowealth Generic Mouse (0028)
DeviceMatch=usb:258a:0028
Driver=sinowealth
```

Killing and restarting `ratbagd` with verbose gives me these logs:
```
$ sudo ratbagd --verbose
Initializing libratbag
ratbag debug: New device: SINOWEALTH Wired Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver sinowealth
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x28
ratbag debug: SINOWEALTH Wired Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x28
ratbag debug: SINOWEALTH Wired Gaming Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 05
ratbag raw: feature set:   05 01 00 00 00 00
ratbag raw: feature get:   05 01 47 32 30 30
ratbag debug: firmware version: G200
ratbag raw: feature set:   05 11 00 00 00 00
ratbag raw: feature get:   04 11 00 00 00 00 06 00 64 4b 03 36 c0 03 07 0f 17 1f 31 81 82 00 00 00 00 00 00 00 00 ff 00 00 00 ff 00 00 00 ff ff ff 00 ff 00 ff ff 46 00 ff ff ff 00 00 00 01 02 00 40 ff 00 ff 02 07 ff 00 00 00 ff 00 00 00 ff 00 ff ff ff ff 00 ff 00 ff ff ff ff 02 02 00 ff 00 00 00 ff 00 00 00 ff ff ff 00 00 ff ff ff ff ff fa 00 ff ff 00 00 ff 00 00 ff 00 00 02 00 ff 00 fa 03 6a 02 02 00 00 00 00 00 00
ratbag debug: driver match found: Sinowealth
hidraw0: "SINOWEALTH Wired Gaming Mouse", 1 profiles
ratbag debug: New device: SINOWEALTH Wired Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver sinowealth
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x28
ratbag debug: SINOWEALTH Wired Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
DBus server ready
```

And the device now gets recognized when using `ratbagctl list` :
```
$ ratbagctl list
warbling-mara:       SINOWEALTH Wired Gaming Mouse
```

When launching Piper many settings are lacking, showing only the Resolutions and LED tabs (both having no effect on the mice).

ratbagctl info gives me this:
```
$ ratbagctl warbling-mara info
warbling-mara - SINOWEALTH Wired Gaming Mouse
             Model: usb:258a:0028:0
 Number of Buttons: 0
    Number of Leds: 1
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 400x400dpi
    1: 800x800dpi
    2: 1600x1600dpi (active) (default)
    3: 2400x2400dpi
    4: 3200x3200dpi
    5: 5000x5000dpi
  LED: 0, depth: rgb, mode: cycle, duration: 1000, brightness: 0
```

I would definitely appreciate some help to figure out what to change in the .device file or the source code in order to help supporting this gaming mice.

**Comment by staticssleever668** [comment]
Hi! First of all, thank you for such a detailed report.
Could you retry this using libratbag v0.17? There have a been a lot of changes to the Sinowealth driver since v0.16.

You will need adjust the device file for the new version:

```
[Device]
DeviceMatch=usb:258a:0028
Driver=sinowealth
Name=Sinowealth Generic Mouse (0028)

# Configuration length: 131 bytes.
# Sensor: PMW3360.
[Driver/sinowealth/devices/InphicPG2]
ButtonCount=12
DeviceName=Inphic PG2
FwVersion=G200
# You may have to replace this with "RGB" if LED colors are incorrect.
LedType=RBG
```

**Comment by staticssleever668** [comment]
By the way, does this mouse even have an official configuration utility? I couldn't find it, and I actually couldn't find the product page either.

**Comment by nebspacefarer** [comment]
Thank you for looking into it.
Amazon product page: [https://www.amazon.co.uk/Programmable-Ergonomic-Lighting-Adjustable-Computer/dp/B08XXNNXHT/](https://www.amazon.co.uk/Programmable-Ergonomic-Lighting-Adjustable-Computer/dp/B08XXNNXHT/)

The mouse officially support these DPI levels: 400/800/1600/2400/3200/5000.
There is 4 DPI presets, with two buttons to cycle them on the mouse.

I've built libratbag and piper from source to have the latest versions and your config file from above was working way better already.
I had to switch the LedType indeed:
```LedType=RGB```
Every LED mode works well and the settings seem to be respected.

For the buttons, I'm struggling to know what each one correspond to on the mouse, is there a way to test this in order to maybe PR a mouse illustration?
Also it displays only 8 buttons and not 12 as the `.device` file defines.

Another problem, after messing with the resolutions and DPIs my mouse clicks are now way too fast and it always trigger multiple clicks everytime, making it hardly usable right now.

Currently on libratbag 0.17 git, here is what we got with the config file:
```
[Device]
DeviceMatch=usb:258a:0028
Driver=sinowealth
Name=Sinowealth Generic Mouse (0028)

# Configuration length: 131 bytes.
# Sensor: PMW3360.
[Driver/sinowealth/devices/InphicPG2]
ButtonCount=12
DeviceName=Inphic PG2
FwVersion=G200
# You may have to replace this with "RGB" if LED colors are incorrect.
LedType=RBG
```

**Comment by staticssleever668** [comment]
> For the buttons, I'm struggling to know what each one correspond to on the mouse, is there a way to test this in order to maybe PR a mouse illustration?

You would have to play around to figure this out.
Usually the first six go as the following:
Left, Middle, Right (middle and right are swapped in Piper), Backward, Forward (these two are often swapped on different mice physically), DPI.


> Also it displays only 8 buttons and not 12 as the `.device` file defines.

I think Piper only shows 8 until there is an illustration for the device.
For now you can set the rest with `ratbagctl`



> ~Another problem, after messing with the resolutions and DPIs my mouse clicks are now way too fast and it always trigger multiple clicks everytime, making it hardly usable right now.~
> **EDIT** Two buttons were bind on the Left Mouse Click, probably conflicting and making the clicks being sent multiple times, it's fixed by replacing the second Left Mouse click entry with anything else.

Sorry, I don't really understand what was wrong here. Was there a macro set for the left mouse button? This should be impossible through Piper as it doesn't allow reassigning left and right mouse buttons to anything else.

**Comment by staticssleever668** [comment]
Let's close this until @nebspacefarer or someone else can clarify further.
