### ISSUE TITLE
Add support for Corsair Ironclaw RGB

### ISSUE THREAD

**Issue by metov** [libratbag/libratbag#1416]
I have a Corsair Ironclaw RGB mouse. The model number is `‎‎CH-9307011-EU`.

It doesn't seem to be supported by libratbag because Piper says "no devices are connected" even though the mouse is connected and working.

Can you please add support for this mouse?

I also have a Logitech G502 Hero and the Corsair mouse seems very similar. It has a button for changing DPI, a button for changing config profiles, two configurable LEDs, a few extra buttons on the side... If anything it's a bit simpler, since there's no wheel paddle. So maybe this would make things easier.

**Comment by metov** [comment]
This is similar to https://github.com/libratbag/libratbag/issues/444 but it's a different model of mouse. However probably #444 could be closed also if this issue was solved.

**Comment by metov** [comment]
Since I have the mouse, I am interested in giving it a try and seeing if I can compose a PR. If it's successful, I would be interested in owning this particular device's support for the future.

However, I'm not familiar with libratbag code. From reading https://github.com/libratbag/libratbag#adding-devices-to-libratbag and skimming https://github.com/libratbag/libratbag/blob/master/data/devices/device.example it seems like creating a device file is not too complicated. But in #444 people are talking about writing C code. Is this a situation where the libratbag code needs to be extended as well, and just a device file won't be enough?

**Comment by staticssleever668** [comment]
> Is this a situation where the libratbag code needs to be extended as well, and just a device file won't be enough?

Yes. We don't have a driver for corsair devices, so this will require making one.

**Comment by metov** [comment]
Thanks for the response @staticssleever668 ! Making a driver sounds complicated and hard - would that be a big task?

Also, I saw #174 which sounds like the driver exists already. But that was 5 years ago. What's the deal with that - can libratbag use https://github.com/ckb-next/ckb-next or not?

**Comment by metov** [comment]
Also, for later readers - it looks like ckb-next IS able to customize various functions of this mouse, like remapping buttons and lights.

**Comment by staticssleever668** [comment]
> would that be a big task

I think it's quite fun, but it *does* take a lot of time and effort, so it is pretty hard.
Generally it comes down to using official software and looking at what USB packets it produces.
Since there is already an existing open source tool, you can try figuring out how it works instead, or, as the mentioned issue suggests, try to hook it up to libratbag.

> can libratbag use https://github.com/ckb-next/ckb-next or not?

No. As it looks by the thread, there doesn't seem to have been any progress - it was just an idea.

> I got confused also because that issue is talking about keyboards - but I thought libratbag was only for mice.

Although libratbag is designed for mice first, there isn't actually anything blocking from using it with other devices.
I think right now there are only device files for several Logitech keyboards.

**Comment by metov** [comment]
Thanks again for the reply!

I'm afraid it's best if I do not attempt to add this driver right now. Sounds like it would be quite a big project for it, and I have an alternative option. I'm not confident enough in my C knowledge to port the code from ckb-next to libratbag.
