### ISSUE TITLE
support motospeed v30 mouse or how to modify code of piper to support it? 

### ISSUE THREAD

**Issue by estatistics** [libratbag/libratbag#1417]
I have motospeed v30 gamemouse
I know that is not supported (yet), but i though if i give the mouse usb address, it may work, this was not the case. 
Please tell me how to play with settings or the program in order to make it work. I dont work the led lights on the mouse and i want to turn them off. 

lsusb reports
`Bus 003 Device 009: ID 04d9:a09f Holtek Semiconductor, Inc. E-Signal LUOM G10 Mechanical Gaming Mouse`

device file 
```
Name=Holtek Semiconductor, Inc. E-Signal LUOM G10 Mechanical Gaming Mouse

# DeviceMatch is a triplet of bus:vid:pid, where bus is 'usb' or bluetooth'
# and pid/vid are lowercase 4-digit hexadecimal numbers with preceding
# zeroes.
DeviceMatch=usb:04d9:a09f

# The libratbag driver backend
Driver=asus

# The types of the LEDs, in the indexed order they appear in, separated by a
# semicolon.
# Allowed values: logo, side, battery, dpi
LedTypes=logo;side;dpi
[Driver/asus]
Profiles=3
Buttons=10
Leds=4
Dpis=3
DpiRange=100:8200@100
```

**Comment by staticssleever668** [comment]
Duplicate: #1417.

We don't currently have a driver for Holtek devices.
