### ISSUE TITLE
Switch to meson as build system

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#142]
The meson build system [1] is gaining a fair bit of traction, parts of GNOME are being switched over and we are currently discussing it for X.Org and Wayland. It'd remove automake, the big benefit is a great speedup in configure + build time (quick tests here are 20s vs 4s for a build from a fresh repo).

What's better though is that it's a lot more understandable, your average meson config makes a lot more sense than your average autotools setup.

I have a test branch that adds meson, if we're happy with this I think we should go ahead here. 

[1] https://github.com/mesonbuild/meson/

**Comment by whot** [comment]
Disclaimer: the only thing missing from 5e8d91b is the symbols-leak-test and some testing

**Comment by whot** [comment]
Another comment: the 'auto' handling of configure-time options feels dirtier in meson than in autotools. So I'm tempted to just switch the options we have to yes/no, default to yes and require anyone who wants to build without documentations/tests to explicitly say so.

**Comment by bentiss** [comment]
TBH, I don't care much about autotools or meson. The meson speedup is nice and the syntax seems indeed clearer. But I don't think it'll change the whole project :)

If other projects are moving to meson, I am fine installing it on my machine and switch over to it.

So +1 for this (and for ratbagd, piper and others)

**Comment by amfern** [comment]
+1
I love the idea of moving away from auto tools

**Comment by whot** [comment]
just as an update, if we switch libratbag we should switch ratbagd too. The python installation for ratbagd's ratbagctl isn't supported until meson 0.40 which is currently unreleased. We can hack around this, it just won't be as pretty. Alternative would be to move ratbactl into a different repo or implementing it in C.

CC @dvdhrm, just so he's aware

**Comment by tpruzina** [comment]
@whot Good catch, 0.40 haven't even made it to testing repositories of any distro that I'm aware of. 

On a completely related note, every time a project moves away from autotools, a puppy gets saved from being ran over by a stranger in a car (somewhere). Also possibly saves lives of gentoo users because waiting 30 seconds for autotools to configure something that takes 2 seconds to compile wants them to end it all (even though libratbag ain't in official portage tree as of yet).

**Comment by whot** [comment]
fwiw, the libratbag bits are done, so if anyone wants to try them be my guest. I won't be sending a PR until after easter, maybe by then we have a new meson too :)

**Comment by whot** [comment]
libratbag branch is ready, please give it a test and let me know if anything's missing.

**Comment by amfern** [comment]
It works, there is a warning in the documentation.

```~/s/libratbag$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.39.1
Source dir: /home/iliya/src/libratbag
Build dir: /home/iliya/src/libratbag/builddir
Build type: native build
Project name: libratbag
Native c compiler: cc (gcc 6.3.0)
Native cpp compiler: c++ (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency libudev found: YES 232
Native dependency libevdev found: YES 1.5.6
Library m found: YES
Configuring libratbag-version.h using configuration
Configuring ratbag-command.1 using configuration
Native dependency check found: YES 0.10.0
Program test/symbols-leak-test found: YES (/home/iliya/src/libratbag/test/symbols-leak-test)
Program doxygen found: YES (/usr/bin/doxygen)
Program dot found: YES (/usr/bin/dot)
Configuring libratbag.doxygen using configuration
Configuring config.h using configuration
Build targets in project: 17
~/s/libratbag$ ninja -C builddir
ninja: Entering directory `builddir'
[35/46] 'Generating doxygen with a custom command.'
/home/iliya/src/libratbag/README.md:135: warning: Unexpected html tag <img> found within <a href=...> context
[46/46] Linking target lur-command
~/s/libratbag$ ls -l builddir/ratbag-command
-rwxr-xr-x 1 ilya ilya 83496 Apr 19 12:18 builddir/ratbag-command```

**Comment by whot** [comment]
thanks for testing, were the documentation bits enough?
fwiw, that warning is unrelated, it's a doxygen complaint about the Readme.md.

**Comment by amfern** [comment]
yes, very easy, i am on debian sid, and i was able to install meson from repositories, but i am not sure how non sid or ubuntu distributions, maybe they would need some kind of how to for mason.

i haven't had the chance to look over the code through, but it compiles just fine.

**Comment by whot** [comment]
For the ratbagd part: https://github.com/libratbag/ratbagd/pull/16
