### ISSUE TITLE
SteelSeries ApS SteelSeries Rival 3

### ISSUE THREAD

**Issue by msmafra** [libratbag/libratbag#1421]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Distribution: 
- Kernel version (ex. `uname -srmo`): `Linux 6.1.9-200.fc37.x86_64 x86_64 GNU/Linux`

Device info (if applicable): ratbagctl shows it 4 times
```
warbling-mara - SteelSeries SteelSeries Rival 3
             Model: usb:1038:1824:0
 Number of Buttons: 6
    Number of Leds: 3
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800dpi (active) (default)
    1: 1600dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-cycle-up'
  LED: 0, depth: rgb, mode: on, color: 0000ff
  LED: 1, depth: rgb, mode: on, color: 0000ff
  LED: 2, depth: rgb, mode: on, color: 0000ff
singing-gundi - SteelSeries SteelSeries Rival 3
             Model: usb:1038:1824:0
 Number of Buttons: 6
    Number of Leds: 3
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800dpi (active) (default)
    1: 1600dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-cycle-up'
  LED: 0, depth: rgb, mode: on, color: 0000ff
  LED: 1, depth: rgb, mode: on, color: 0000ff
  LED: 2, depth: rgb, mode: on, color: 0000ff
hooting-chinchilla - SteelSeries SteelSeries Rival 3
             Model: usb:1038:1824:0
 Number of Buttons: 6
    Number of Leds: 3
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800dpi (active) (default)
    1: 1600dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-cycle-up'
  LED: 0, depth: rgb, mode: on, color: 0000ff
  LED: 1, depth: rgb, mode: on, color: 0000ff
  LED: 2, depth: rgb, mode: on, color: 0000ff
chanting-squirrel - SteelSeries SteelSeries Rival 3
             Model: usb:1038:1824:0
 Number of Buttons: 6
    Number of Leds: 3
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800dpi (active) (default)
    1: 1600dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-cycle-up'
  LED: 0, depth: rgb, mode: on, color: 0000ff
  LED: 1, depth: rgb, mode: on, color: 0000ff
  LED: 2, depth: rgb, mode: on, color: 0000ff
```

**Describe the bug**
My mouse is a USB Steelseries Rival 3 with a different USB ID (1038:1024) than the ones in the steelseries-rival.device file,  ratbagctl shows it 4 times and the file has some configs diffent from what is said in the box. NOt sure if creating a new one could cause problems or if would even work.
```
ratbagctl
warbling-mara:       SteelSeries SteelSeries Rival 3 
singing-gundi:       SteelSeries SteelSeries Rival 3 
hooting-chinchilla:  SteelSeries SteelSeries Rival 3 
chanting-squirrel:   SteelSeries SteelSeries Rival 3

ratbagctl 
```
I'm not sure if it's a new mode, reginal model (Brazil), different model rebranded as it is identified as SteelSeries ApS SteelSeries Rival 3.
On the box relevant info:
Sensor system: TrueMove Core
Sensitivity: 8,500 CPI
Maximum speed: 300 IPS
Maximum Acceleration 35 G
Switch Rating 60 Million Clicks
On-board Memory: Yes
Buttons 6: Prorammable
Lighting: 3-zone RGB
**To Reproduce**

**Logs**
Initializing libratbag
ratbag debug: New device: SteelSeries SteelSeries Rival 3
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1824
ratbag debug: SteelSeries SteelSeries Rival 3 is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1824
ratbag debug: SteelSeries SteelSeries Rival 3 is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw0: "SteelSeries SteelSeries Rival 3", 1 profiles
ratbag debug: New device: SteelSeries SteelSeries Rival 3
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1824
ratbag debug: SteelSeries SteelSeries Rival 3 is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1824
ratbag debug: SteelSeries SteelSeries Rival 3 is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: driver match found: SteelSeries
hidraw1: "SteelSeries SteelSeries Rival 3", 1 profiles
ratbag debug: New device: SteelSeries SteelSeries Rival 3
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1824
ratbag debug: SteelSeries SteelSeries Rival 3 is device '/dev/hidraw5'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1824
ratbag debug: SteelSeries SteelSeries Rival 3 is device '/dev/hidraw5'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw5: "SteelSeries SteelSeries Rival 3", 1 profiles
ratbag debug: New device: SteelSeries SteelSeries Rival 3
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1824
ratbag debug: SteelSeries SteelSeries Rival 3 is device '/dev/hidraw6'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1824
ratbag debug: SteelSeries SteelSeries Rival 3 is device '/dev/hidraw6'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw6: "SteelSeries SteelSeries Rival 3", 1 profiles
ratbag debug: New device: Gaming KB  Gaming KB 
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 258a:1006
ratbag debug: New device: Gaming KB  Gaming KB 
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 258a:1006
ratbag debug: New device: Burr-Brown from TI               USB Audio CODEC 
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 08bb:2902
DBus server ready

First make sure it isn't running already.
```
$ ratbagd --verbose=raw

```

**Additional context**

**Comment by staticssleever668** [comment]
You are running an outdated version of libratbag, this has been fixed in #1211 (present in the v0.17 release).
