### ISSUE TITLE
Piper installed, Ratbagd installed, G600 undetected.

### ISSUE THREAD

**Issue by Aonner** [libratbag/libratbag#1422]
- `ratbagd` version (0.15):
- Distribution: Debian 11
- Kernel version: `Linux 5.10.147-20159-g06a9a2b12b31 x86_64 GNU/Linux`

Device info (if applicable):
```
$ ratbagctl <device> info
```

Unable to find device G600

**Describe the bug**

I don't think it is a bug, but I recently bought a wired Logitech G600 MMO mouse. 
I thought I could use the software for the mouse via Lutris but quickly found out I couldn't. 
After a fair short google search, I found Piper and Ratbagd. 
I installed Ratbagd first using the debian option from the Libratbag wiki 
(Debian (10 and later) and Ubuntu (18.04 and later) apt install ratbagd) 
then installed the flatpak version of Piper.

I started Ratbagd then fired up Piper.  Mouse trap.

The mouse itself works with its pre installed shortcuts.

**To Reproduce**

Download required software and plug the mouse in the usb port. Start software. See mouse trap.

**Logs**
```
$ sudo ratbagd --verbose=raw

Initializing libratbag
DBus server ready
```

At this point, my terminal will display the blue text box below and nothing will work.

lsusb provides
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Additional context**

If you need any other information from Linux, please include the command on how I can do it. I am new to Linux

**Comment by staticssleever668** [comment]
From the output of lsusb and ratbagd it looks like you don't have not just any USB-HID devices, but anything at all connected through USB. Is this true?

**Comment by Aonner** [comment]
the G600 mouse is connected to the usb port. I stated that the mouse itself works with its pre installed shortcuts. So the laptop is getting signal from it,

**Comment by staticssleever668** [comment]
This doesn't seem to be anything libratbag-related, so I'm closing this.
I have no idea how can it even be that no devices at all are shown in lsusb.
