### ISSUE TITLE
Can't set binding back to BTN_LEFT (g600)

### ISSUE THREAD

**Issue by code32123** [libratbag/libratbag#1428]
**Information**

- ratbagd version: 0.17
- Distribution: Kali Linux
- Kernel version: `Linux 6.0.0-kali3-amd64 x86_64 GNU/Linux`

**Device info:**
 + "Logitech Gaming Mouse G600"
 + Crashes after `ratbagctl "Logitech Gaming Mouse G600" profile 1 button 0 action set macro BTN_LEFT` is run, otherwise irrelevant

**Describe the bug**
After attempting to set my main click to KEY_0 and back, I couldn't reset it to BTN_LEFT. `set button BTN_LEFT` fails, while `set macro BTN_LEFT` immediately crashes piper and makes the mouse unusable. I can save it by resetting the macro to KEY_0 and then re-applying right handed mode in piper.

**To Reproduce**
1. Run `ratbagctl "Logitech Gaming Mouse G600" profile 1 button 0 action set macro BTN_LEFT`
2. Observe that left click no longer works, and piper has crashed. `info` command also crashes with `KeyError: 272`

**Additional context**
I have rebuilt both piper and libratbag today, and setting other macros works (`set macro +KEY_LEFTSHIFT KEY_B -KEY_LEFTSHIFT`), I just can't map to the mouse buttons. My end goal is just to write a super simple python tool to write to the G-Shift keys of my mouse.

This seems like a simple question that should have a simple answer, but I cannot find a solution anywhere. Let me know if additional information is required, thank you for any help or ideas!

Afterthought, I don't understand how this all ties together but `sudo evtest` puts the BTN events on a separate event ID altogether

**Comment by staticssleever668** [comment]
> `set button BTN_LEFT` fails,

Use `ratbagctl "Logitech Gaming Mouse G600" profile 1 button 0 action set button 1` instead. :)

**Comment by code32123** [comment]
This solves it! Looking back through my trial and error, I had attempted `set button 0`, but given up on it without trying button 1. :)
Thank you so much!
