### ISSUE TITLE
Start script/executable

### ISSUE THREAD

**Issue by skjerns** [libratbag/libratbag#1431]
On G-Hub it was possible to set certain mouse buttons to start a program/script. 

It would be great to have this functionality as well. Currently it seems only possible to add other key buttons or macros, but not to start an executable.

Is something like this even possible with libratbag? Or would it need an external DBUS listener?

**Comment by skjerns** [comment]
(I do have a workaround by assigning a random hotkey and listening for this hotkey via system shortcuts)

**Comment by staticssleever668** [comment]
> I do have a workaround by assigning a random hotkey to the button and listening for this hotkey via system shortcuts

This is the way.
It would work basically the same way if we implemented it, and I don't think this is in scope of libratbag.

Although it's a bit annoying that you *do* need to assign *something* to the button, which outside of the target system would type some key combination. I wonder how G-Hub does it, maybe it assigns the button to just send a custom HID interrupt, which is not handled by the system, but rather the program itself listens to it? Still, I don't think it fits libratbag.
