### ISSUE TITLE
Cannot find the GPG key used in latest release

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#1436]
I cannot find @staticssleever668's GPG key (`CCF75EB2BBF8F69C`), which was used for the latest release, on any keyserver. I also search to see if Github has a way to fetch GPG keys from users, and it doesn't seem so :confused:

@staticssleever668 could you upload it somewhere? Thanks!

Btw, here's the script I usually use to upload my keys, to make sure it's easy to find.
https://github.com/FFY00/dotfiles/blob/main/scripts/send_key.sh

**Comment by staticssleever668** [comment]
Hi, I've used the script you linked, could you check if the key uploaded correctly? I've never actually uploaded it to any key server before.

**Comment by staticssleever668** [comment]
Great, thank you!
