### ISSUE TITLE
I use a model o but only the wired version is supported.

### ISSUE THREAD

**Issue by Santa0101** [libratbag/libratbag#1448]
[message (1).txt](https://github.com/libratbag/libratbag/files/10902200/message.1.txt)
Here's the details, hope you can do something. I attempted to add a .device file but that didn't work, I probably did something wrong.

**Comment by staticssleever668** [comment]
Model O and Model O Wireless are two completely different mice under the hood.
libratbag doesn't support the latter (yet), but you can use another tool in the mean time: [mow](https://github.com/korkje/mow) (or it's fork [mxw](https://github.com/dxbednarczyk/mxw)).

Closing as duplicate: #1172.
