### ISSUE TITLE
Make readme pretty and kill doxygen warning

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#145]
As noted on issue #142:
`/home/iliya/src/libratbag/README.md:135: warning: Unexpected html tag <img> found within <a href=...> context`

The problem is that `README.md` is used for both the github front page, and for the docs.

I wonder if we couldn't have a simpler `README.md` without the doxygen tags (`/*@mainpage`, `*/`), and have doxygen ignore for the semaphoreCI tag, and have a doxygen front page that just includes the content of `README.md` with proper doxygen marks.

This could easily be achieved by a script, but a proper doxygen include (if any) would be better.

**Comment by whot** [comment]
Note: the commit only addresses the mainpage bit, not the warning. Removing that warning requires adding doxygen markers to the readme again, I couldn't find a good way for doxygen to include the readme from a separate file (short of a script).
