### ISSUE TITLE
[Support] libratbag and piper successfully compiled on Void Linux, now I need to get ratbagd running.

### ISSUE THREAD

**Issue by jaamivstheworld** [libratbag/libratbag#1461]
The binary package of libratbag on Void Linux provides a runit service file. I am unable to find out how I can make my own clone of this file (since I do not have it because I compiled libratbag) and enable the service to finally get piper working.

Any help? This is the binary package source but I couldn't find the runit service here either: https://github.com/void-linux/void-packages/tree/master/srcpkgs/libratbag

**Comment by staticssleever668** [comment]
I don't have any experience with runit, but I think the `ratbagd` folder under `files` contains/is the service unit file.
https://github.com/void-linux/void-packages/tree/master/srcpkgs/libratbag/files/ratbagd
I'm just guessing that this directory is supposed to go under `/etc/sv`, then you can do `sv up /etc/sv/ratbagd`, but you will known it better.
By the way, it probably won't make sense to "enable" ratbagd as a service (by putting it to `/var/service`), as ratbagd automatically shuts down after some time of inactivity. On systemd ratbagd is started on demand by D-Bus. Now I wonder if it would make sense to add a way to disable the shut down timeout :thinking:.
