### ISSUE TITLE
Add modifiers to single key bindings

### ISSUE THREAD

**Issue by staticssleever668** [libratbag/libratbag#1470]
We need a way to add to modifiers to single key bindings (`RATBAG_BUTTON_ACTION_TYPE_KEY`, not `RATBAG_BUTTON_ACTION_TYPE_MACRO`).
There is a few FIXMEs in the code for this:
https://github.com/libratbag/libratbag/blob/70f2e96a66ab4b5822ebb17c7eabeb8857b20446/src/libratbag-private.h#L351
https://github.com/libratbag/libratbag/blob/70f2e96a66ab4b5822ebb17c7eabeb8857b20446/src/libratbag.c#L1389
https://github.com/libratbag/libratbag/blob/70f2e96a66ab4b5822ebb17c7eabeb8857b20446/src/libratbag.c#L1409
These functions take in/out modifiers like this:
Pointer to an array of modifiers, and pointer to a variable with size of the array. Currently it ignores whatever is in the array, and just resets the variable with size to zero.

However, some other functions, like ratbag_button_macro_new_from_keycode(), use a mask for modifiers.
https://github.com/libratbag/libratbag/blob/70f2e96a66ab4b5822ebb17c7eabeb8857b20446/src/libratbag.c#L1907-L1910

Here's what I plan on doing:
1) Add array of modifiers and it's size to ratbag_button_action.action.key
1) Use it in ratbag_button_set_key and ratbag_button_get_key.
It should check that there is only key (e.g. `KEY_A KEY_B` not allowed), and that there are no duplicate modifiers.
1) Add tests for it.
1) Not well thought off: modify the interface in ratbagctl to use it like this:
`ratbagctl Glorious button 5 action set key KEY_LEFTSHIFT KEY_LEFTMETA KEY_A`
1) Check if there was a proper reason for this, if not, change ratbag_button_macro_new_from_keycode() to use an array instead of a mask. There should be only one API for this (maintenance burden), and I think an array is more straightforward.

Continuation of #1251, I think the only blocker for #1388.

**Comment by staticssleever668** [comment]
Looking at the way single key bindings are implemented in the ASUS driver right now, it looks like ASUS devices don't support modifiers in such bindings. 
https://github.com/libratbag/libratbag/blob/a4eb09ea6ddf4c2c670c32d27a1ecb465fa7ed53/src/asus.h#L70
To verify, @kyokenn, is that true?

Because of this, "macro" bindings really do seem more flexible. In the end-game instead of "key" bindings we should really have "macro" bindings with some constraints. For now this will work though.

**Comment by kyokenn** [comment]
>Looking at the way single key bindings are implemented in the ASUS driver right now, it looks like ASUS devices don't support modifiers in such bindings.

ASUS devices supports modifiers, it just does not implemented in the driver yet.

**Comment by staticssleever668** [comment]
I decided not to add such API, instead, this can be accomplished with macros.
d0c34bdbe97 in #1523 shows how simple enough macros can be interpreted as key actions by the driver.
