### ISSUE TITLE
Update G102 USB ID (046d:c09d)

### ISSUE THREAD

**Issue by stefan-steinegger** [libratbag/libratbag#1472]
I just bought a brand new Logitec G102. Piper didn't recognize it, because it has another USB ID that what is know by Piper.

lsusb gave me this line:
Bus 001 Device 008: ID **046d:c09d** Logitech, Inc. G102 LIGHTSYNC Gaming Mouse

Adding this ID to the device-file seemed to fix the issue:

logitech-g102-g203.device:

> [Device]
> Name=Logitech Gaming Mouse G102/G103/G203
> DeviceMatch=usb:046d:c084;usb:046d:c092;**usb:046d:c09d**
> Driver=hidpp20
> LedTypes=logo;side;

I found the information how to do this here: #1014, but there they found yet another USB ID.

**Comment by staticssleever668** [comment]
Duplicate: #1406 (fixed by #1389). 
It will work out of the box in the next libratbag release. :)

**Comment by stefan-steinegger** [comment]
Thanks! Sorry that I didn't see the duplicate.
