### ISSUE TITLE
SINOWEALTH Game Mouse (marvo G930)

### ISSUE THREAD

**Issue by germanTom** [libratbag/libratbag#1479]
No devices available.
Initializing libratbag
ratbag debug: New device: SINOWEALTH Game Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver sinowealth
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x1007
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x1007
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 05
ratbag raw: feature set:   05 01 00 00 00 00
ratbag error: Error while sending read firmware version command: -110
ratbag debug: New device: SINOWEALTH Game Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver sinowealth
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x1007
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x258a product 0x1007
ratbag debug: SINOWEALTH Game Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 05
ratbag raw: feature set:   05 01 00 00 00 00
ratbag error: Error while sending read firmware version command: -110
DBus server ready
Exiting after idle

marvo G930; SINOWEALTH in Linux Fedora 37
Is this wirded mouse not supported?

**Comment by staticssleever668** [comment]
Hi, this mouse seems to be the different kind of sinowealth devices from what we currently support.
#1359 doesn't mention Marvo G930, but they are most likely the same thing.
