### ISSUE TITLE
Logitech G502 X Lightspeed only shows up when wired

### ISSUE THREAD

**Issue by wereii** [libratbag/libratbag#1488]
**Information**

- `ratbagd` version: `0.17`
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `Linux 6.3.3-arch1-1 x86_64 GNU/Linux`

**The bug**

My new G502 X Lightspeed (not the Plus version) is not detected by ratbagd when connected over dongle, `ratbagctl list` is empty.
Though, according to this PR https://github.com/libratbag/libratbag/pull/1343 it should be.

This is probably because the wireless dongle has different usb pid:  
`Bus 001 Device 014: ID 046d:c547 Logitech, Inc. USB Receiver`. 
The device definitions for G502 X have `046d:c098`.

```
$ sudo ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: AsusTek Computer Inc. AURA LED Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0b05:19af
ratbag debug: New device: Keychron K6 Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0260
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c547 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c547 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c547 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech PRO X
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:0aaa
DBus server ready
```

**Additional context**
Connecting the mouse thru cable detects the mouse correctly as `hooting-chinchilla:  Logitech G502 X LIGHTSPEED`.

**Comment by wereii** [comment]
I have tried creating another device in `/usr/share/libratbag/logitech-g502-x-wireless2.device` with: 

```
[Device]
Name=Logitech G502 X Wireless
DeviceMatch=usb:046d:c547
DeviceType=mouse
Driver=hidpp20
```
which does seem to detect it but fails, seems like the communication over dongle is logitech's hid++

```
> sudo ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: AsusTek Computer Inc. AURA LED Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0b05:19af
ratbag debug: New device: Keychron K6 Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0260
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: Logitech PRO X
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:0aaa
DBus server ready
```

**Comment by staticssleever668** [comment]
Hi! Sorry, but adding the VID:PID of the receiver in libratbag won't accomplish anything. What we really need, is for the Linux kernel to re-export the devices behind the receiver as separate entities. It doesn't work right now because Linux doesn't support it completely, yet. I'm pretty sure I've seen a patch for this in a custom kernel not that long ago, so there *is* some progress on the issue.
A similar patch or an older iteration of it was mentioned in another thread (https://github.com/libratbag/libratbag/issues/1178#issuecomment-1048065181). For the new patch I can not find the link right now.

Related: #1333 (needs the same patch).
I'm not sure if we have an issue for dedicated specifically for G502 X, but I'll anyway close this in favor of #1333.

**Comment by staticssleever668** [comment]
Actually, it looks like it's going to be in Linux 6.4 already. :)

**Comment by wereii** [comment]
Getting my hopes like this :D 
Nevermind, I can't realistically help with the kernel stuff so I guess it's a wait time, I can still configure stuff over cable so it's good.

**Comment by mzryz** [comment]
Just an update: Using Linux kernel 6.6 which was recently released, the mouse is now showing up when wireless. Even in the Piper GUI.

But: The performance when wireless is not good. Sometimes tracking stops/starts randomly causing hitches/lags in mouse movement when in game. Before kernel 6.1 I thought this was due to a lack of driver, now we have 6.1 which seems to report the mouse properly, but unfortunately has not fixed the performance issues on my end.

**Comment by wereii** [comment]
I rarely have to change stuff on my mouse so I didn't try it with the newer kernels but I just found out I am in the same boat as @adrfantini but on `Linux 6.8.9-arch1-2 x86_64 GNU/Linux`.


```
sudo ratbagd --verbose=raw
Starting ratbagd version 0.17 (API version 2)
Initializing libratbag
ratbag debug: New device: Keychron Keychron K6 Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0260
ratbag debug: New device: Keychron Keychron K6 Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0260
ratbag debug: New device: Keychron Keychron K6 Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0260
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw6'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw7'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw6'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw7'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw6'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw7'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: MSI MYSTIC LIGHT
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1462:7e07
ratbag debug: New device: Generic USB Audio
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0db0:d1d7
ratbag debug: New device: Logitech PRO X
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:0aaa
DBus server ready
```

**Comment by Herschdorfer** [comment]
See this PR for reference: https://github.com/libratbag/libratbag/issues/1488

**Comment by Herschdorfer** [comment]
Note: I only add this here for others googeling the issue.

**Comment by Kallestofeles** [comment]
> See this PR for reference: #1488

This is the exact same PR we are on right now. Did you mis-link it?

**Comment by Kallestofeles** [comment]
Ok, so this was a year ago and there has been no progress on it. Probably not a priority for the kernel... so, why don't we just add the receivers as DeviceMatch entries so that people could actually use their devices in the meantime? I mean, is there a downside to this that I cannot see? Dongles for all the mice and kb's seem to be unique (identifiers), so there should not be a device conflict?

**Comment by Herschdorfer** [comment]
I'm not sure if this will be enough. As I said in my other post, I still did not see a device in `ratbagctl list`.


But maybe I missed some other configuration.

**Comment by Kallestofeles** [comment]
Compiled from GIT with my patch for G502X Lightspeed and it shows up nicely:
[kst@shoemaster ~]$ ratbagctl list
warbling-mara:       Logitech USB Receiver           

Kind of a bummer if people need to start maintaining their own patches for libratbag in order to keep their devices supported.😞

**Comment by Kallestofeles** [comment]
Please someone explain why this is closed? There is still a problem about to which we have a solution but is not accepted for whatever reason... but the issue remains.

**Comment by tl-photography** [comment]
Even with the comment this should still not be closed. 

One issue is the missing enumeration from the kernel, the other is the code changes needed. This issue already has some code examples of what is required and some further debugging going on.

So once the kernel issue is resolved, this issue will still remain and there is already knowledge collected on this issue. 

I would therefore propose to not close it.

**Comment by Kallestofeles** [comment]
> [#1488 (comment)](https://github.com/libratbag/libratbag/issues/1488#issuecomment-1567401560)

Ok, so there is a "hope" that kernel somehow fixes the way that the device is seen beyond the receiver device... does anyone know whether this will be fixed at any point in the future? Or at all?
I mean, I am not trying to be a dick here, but my PRs fix all that mess for G502X Lightspeed as I am happily running it right now... no issues, all working. I simply wish to know why we cannot have a simple fix for an issue that people are having instead of waiting something which might not ever come to fruition... :\
I'm totally OK with forking/patching my own version of libratbag and piper, but a lot of people would benefit from having a working solution out of the box.

**Comment by Kallestofeles** [comment]
Ok, understood. Thank you for the explanation. 🍻

**Comment by Gamma195** [comment]
> Compiled from GIT with my patch for G502X Lightspeed and it shows up nicely

How would one achieve this? I currently have the Logitech G502 Lightspeed...and heard that Logitech had support on Linux. Then, I ran into the issue being discussed here. If there's a fix, please let me know :)

**Comment by ShayBox** [comment]
@Kallestofeles a fork of (lib)ratbag(ctl) to fix this would be nice, this is never going to be fixed by Linux, and workarounds aren't going to be accepted by this project. Maybe just a diff patch and a PKGBUILD on the AUR would suffice.

**Comment by fridtjof** [comment]
Support in the kernel is now merged since 6.19: https://lore.kernel.org/linux-input/9q9po5no-op7n-o07o-rn1n-rr36oqs9p9sp@xreary.bet/

While my G502 X Plus's battery status now shows up in upower (indicating the mouse is being picked up properly now), ratbagctl unfortunately still does not detect it :(

**Comment by Kitt3120** [comment]
oh, so that's why my scrolling has been completely broken for weeks. I blamed it on KDE Plasma. Time to blacklist this driver, it really is unusable at the moment. I am able to see my G 502 X Plus' battery status using Solaar anyway, so I don't need the new driver. It's worth checking from time to time if it improved, though!

**Comment by albertorm95** [comment]
@ShayBox @Kitt3120 
```
flatpak run io.github.pwr_solaar.solaar config 1 hires-smooth-resolution false
```

This command disables the hi-res scroll wheel

**Comment by Kitt3120** [comment]
> @ShayBox @Kitt3120 
> ```
> flatpak run io.github.pwr_solaar.solaar config 1 hires-smooth-resolution false
> ```
> 
> This command disables the hi-res scroll wheel

Thanks for the recommendation. It's probably the same as doing it through Solaar's UI, right? Fron my experience, doing this while the kernel driver is still active results in the mouse wheel behaving really weird. Sometimes it triggers 2 scrolls, sometimes it completely misses a scroll. My way to go is to blacklist the new kernel driver + disabling smooth scroll. This has been working great since I posted my comment.

**Comment by albertorm95** [comment]
> > [@ShayBox](https://github.com/ShayBox) [@Kitt3120](https://github.com/Kitt3120)
> > ```
> > flatpak run io.github.pwr_solaar.solaar config 1 hires-smooth-resolution false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This command disables the hi-res scroll wheel
> 
> Thanks for the recommendation. It's probably the same as doing it through Solaar's UI, right? Fron my experience, doing this while the kernel driver is still active results in the mouse wheel behaving really weird. Sometimes it triggers 2 scrolls, sometimes it completely misses a scroll. My way to go is to blacklist the new kernel driver + disabling smooth scroll. This has been working great since I posted my comment.

How do you do that? 👀

**Comment by Kitt3120** [comment]
> > > [@ShayBox](https://github.com/ShayBox) [@Kitt3120](https://github.com/Kitt3120)
> > > ```
> > > flatpak run io.github.pwr_solaar.solaar config 1 hires-smooth-resolution false
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This command disables the hi-res scroll wheel
> > 
> > 
> > Thanks for the recommendation. It's probably the same as doing it through Solaar's UI, right? Fron my experience, doing this while the kernel driver is still active results in the mouse wheel behaving really weird. Sometimes it triggers 2 scrolls, sometimes it completely misses a scroll. My way to go is to blacklist the new kernel driver + disabling smooth scroll. This has been working great since I posted my comment.
> 
> How do you do that? 👀

Sorry for late reply, I simply blacklisted the "hid_logitech_dj" kernel module. In NixOS, it's `boot.blacklistedKernelModules = [ "hid_logitech_dj" ];`. On other distros, you will have to create a config file in /etc/modprobe.d.
