### ISSUE TITLE
Trust Verto Ergonomic Wireless mouse support (145f:0263); no official configuratin utility available

### ISSUE THREAD

**Issue by iozudono** [libratbag/libratbag#1489]
I have no idea of how to include new devices but got this mouse with 6 buttons, and thought if it'd be possible to configure them, in place of the back/forward/dpi/central button standard use.

Thank you for answering

**Comment by iozudono** [comment]
Thanks for the answer! I'm afraid there's no conf utility or drivers. The
output is:

lsusb -v -d 145f:0263

Bus 001 Device 026: ID 145f:0263 Trust Trust Wireless Mouse
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x145f Trust
  idProduct          0x0263
  bcdDevice            1.00
  iManufacturer           1 MOSART Semi.
  iProduct                2 Trust Wireless Mouse
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     118
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0007  1x 7 bytes
        bInterval               4

Thanks again! I'll see the devices list of libratbag the next time I'm
gonna get a mouse lol

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.
That is, if the mouse supports configuring it at all, considering "there's no conf utility or drivers"..
