### ISSUE TITLE
Can you please add support for White Shark Marcus 2 GM-5005 Gaming mouse and A4Tech X7 Oscar Gaming Mouse (X-710BK)?

### ISSUE THREAD

**Issue by Draguljche** [libratbag/libratbag#1492]
It would be nice if you add White Shark Marcus 2 GM-5005 Gaming mouse and Oscar Gaming Mouse (X-710BK). My primary mouse is White Shark. I would be very very grateful. 

This is lsusb output for GM-5005:
`Bus 003 Device 003: ID 1bcf:08a0 Sunplus Innovation Technology Inc. Gaming mouse [Philips SPK9304]`

And Thx for answering!  :D

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, I'll close this until someone volunteers to write one.
