### ISSUE TITLE
Incorporate mouse buttons into macros

### ISSUE THREAD

**Issue by jensenr30** [libratbag/libratbag#1497]
**Is your feature request related to a problem? Please describe.**
When I'm browsing source code and need to jump to the definition of a function, it is necessary to click a mouse button, then execute a sequence of keystrokes.  Currently I click my left mouse button to select the function, then click mouse button 7 to execute a macro that is the keyboard shortcut to jump to function definition.

**Describe the solution you'd like**
It would be fantastic if macros could include button presses.  That way, I could use button 7 to move my cursor and execute the keystrokes all in one fell swoop!

**Describe alternatives you've considered**
At present I'm clicking two mouse buttons.  But it would be pretty cool to only click one.

**Additional context**
I tried looking for mouse button definitions in linux/input-event-codes.h and found `BTN_1` and `BTN_LEFT`, but `ratbagctl` threw an error when I tried to use those in a macro and they didn't work.

**Comment by staticssleever668** [comment]
This depends on the device and whether driver for it in libratbag supports such actions.
For examples, this works fine on Glorious mice with our sinowealth driver.
`ratbagctl Glorious button 5 action set macro KEY_A BTN_LEFT`.
