### ISSUE TITLE
Add support for Rampage SMX R85

### ISSUE THREAD

**Issue by erkinalp** [libratbag/libratbag#1499]
**Is your feature request related to a problem? Please describe.**
Rampage SMX R85 has very annoying LED setups in default settings.

**Describe the solution you'd like**
I would like to disable the LEDs using ratbag.

**Describe alternatives you've considered**
*None*

**Additional context**
The default LED cycle in that mouse may induce phototriggered epilepsy in some people.

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, I'll close this until someone volunteers to write one.
