### ISSUE TITLE
Logitech G203 LIGHTSYNC support

### ISSUE THREAD

**Issue by lwindolf** [libratbag/libratbag#1502]
**Is your feature request related to a problem? Please describe.**
I've bought a new Logitech G203 mouse which has a different USB device ids than the G103-203 profile that is in the sources. My model shows as

     $ lsusb
     [...]
     Bus 003 Device 011: ID 046d:c09d Logitech, Inc. G203 LIGHTSYNC Gaming Mouse
     [...]

Button-wise the mouse looks like the previous G203 so it should als work with the existing G103-G203 profile of libratbag.

**Describe the solution you'd like**

If possible allow this USB id too.

**Comment by staticssleever668** [comment]
Duplicate: #1406 (fixed by #1389, but not in a release yet).

See `Additional context` at the bottom of #1406 to see how to apply the change until new libratbag version is released.

**Comment by lwindolf** [comment]
@staticssleever668 Thank you very much!
