### ISSUE TITLE
Support for the Glorious Model I

### ISSUE THREAD

**Issue by inglettronald** [libratbag/libratbag#1505]
**Is your feature request related to a problem? Please describe.**
Currently, my profile is saved properly from my previous windows install with the exception of the 2 extra mouse buttons not being registered. I'm unsure if this is addressable inside the context of libratbag, but I'm open to be as cooperative as possible in developing a solution.

**Describe the solution you'd like**
I would like the extra buttons on this mouse to be properly programmable. RGB does not concern me particularly, but I'm guessing that would be on the agenda as well.

**Describe alternatives you've considered**
I tried checking the raw input of the mouse with the intention of simply writing an AHK script or similar, but it looks like my linux distro doesn't even register the buttons being pressed, indicating there might be firmware issues? I'm not super savvy with this.

I was able to find the information from `lsusb` as expected.

**Additional context**
OS: EndeavourOS

**Comment by staticssleever668** [comment]
Hello! There is #1327 already for Model I.
It's protocol is completely different from other Glorious mice, and we would need to write a completely new driver for it.

> I tried checking the raw input of the mouse with the intention of simply writing an AHK script or similar, but it looks like my linux distro doesn't even register the buttons being pressed, indicating there might be firmware issues?

Things could have changed, but I remember AHK being Windows-only, if you are running AHK through Wine, especially if it's on Wayland, I won't be surprised it doesn't work.
Not sure if there are any alternatives for desktop Linux, as I have never needed such functionality.
