### ISSUE TITLE
Marvo M726W not supported

### ISSUE THREAD

**Issue by krustophenia** [libratbag/libratbag#1507]
**Information**

- `ratbagd` version (`ratbagd --version`):
0.16

- Distribution: 
Fedora 37

- Kernel version (ex. `uname -srmo`): 
Linux 6.4.4-100.fc37.x86_64 x86_64 GNU/Linux

Device info (if applicable):
https://www.scorpion-marvo.es/producto/raton-inalambrico-gaming-rgb-scorpion-ma-m726w/#

```
$ ratbagctl <device> info
sudo ratbagctl list      
No devices available.

```

**Describe the bug**
My device is not being recognized even following this instructions:
https://github.com/libratbag/libratbag/issues/1091

**To Reproduce**
sudo ratbagctl list      
No devices available.

**Logs**
sudo ratbagd --verbose
Initializing libratbag
...
ratbag debug: New device: 2.4G Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1ea7:0066
ratbag debug: New device: 2.4G Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1ea7:0066
...
DBus server ready

```
$ ratbagd --verbose=raw
sudo ratbagd  --verbose=raw
Initializing libratbag
...
ratbag debug: New device: 2.4G Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1ea7:0066
ratbag debug: New device: 2.4G Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1ea7:0066
...
DBus server ready

```

**Additional context**
Tried to add a device like 

```
[Device]
DeviceMatch=usb:258a:1007
Driver=sinowealth
Name=Sinowealth Generic Mouse (1007)
```

without luck. I don't know what else to try to get this working.

**Comment by staticssleever668** [comment]
Hi! This looks like a completely different device from the one linked in #1091. As such, it would require writing a new driver from scratch.
Someone needs to volunteer to do this, so I'll close the issue until then, because they create noise while no one is working on them.
