### ISSUE TITLE
add dependecies list to installation readme

### ISSUE THREAD

**Issue by perevertysh** [libratbag/libratbag#1511]
there is a bunch of dependencies, which affect installation from source. error message below:
```Message: Embedding libratbag source will not work because an older version of meson is used
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libudev found: YES 245
Run-time dependency libevdev found: YES 1.9.0
Run-time dependency glib-2.0 found: YES 2.64.6
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency json-glib-1.0 found: NO (tried pkgconfig and cmake)

meson.build:85:0: ERROR: Dependency "json-glib-1.0" not found, tried pkgconfig and cmake
```
much better to install that bunch of libs before main installation process.

library names in variables may not be equivalent to real one

**Comment by staticssleever668** [comment]
Hello!
We have the dependency list on the wiki: https://github.com/libratbag/libratbag/wiki/Building-from-source
(it is reachable from the README, but not in an obvious way; this could be improved upon).
It only lists the dependencies themselves, not how to install them on a specific distro, but packages for them are trivially findable on Arch, for example - putting the dependency name in the package search you can immediately recognize them.

You can also share the packages you've installed to compile :)

**Comment by staticssleever668** [comment]
Since the dependencies are easily searchable by their names, I'll close the issue.
Feel free to list the packages you've installed for compiling, I could add that to wiki.
