### ISSUE TITLE
Please add support for Ant Esport GM 320

### ISSUE THREAD

**Issue by ShreshthTiwari** [libratbag/libratbag#1512]
**Is your feature request related to a problem? Please describe.**
The software is not able to detect any of the Ant esport gaming mice.

**Describe the solution you'd like**
Support for Ant esport gaming mice specially gm 320 as their official one is only for windows.

**Describe alternatives you've considered**
Tried play on linux to run its driver software but it was not able to detect the device.

**Additional context**
N/A

**Comment by staticssleever668** [comment]
Hello! This could be a SinoWealth mouse, like ANT Esports GM500 (#1296).
What is the output of `lsusb -v -d 258a:`? Also, what version of libratbag do you have installed? 

Noting this immediately: if we get libratbag to recognize it, completely make sure that all shown values indeed match up with how the mouse is working. In #1296 it looked like the memory layout of device settings was different.
