### ISSUE TITLE
Piper issue. Cannot Find Device

### ISSUE THREAD

**Issue by jdcdanguk** [libratbag/libratbag#1513]
So, I have a Logitech G203 LightSync, but everytime I run Piper on Ubuntu 22.04 it does not work.  My G203 is plugged in and I do not know what is happening please help. By the way I am not sure about the logs. It just says Cannot Find Device

**Comment by staticssleever668** [comment]
Hello!
Please, try the steps in the bottom of this issue's description: https://github.com/libratbag/libratbag/issues/1406.
