### ISSUE TITLE
LED debugging seems buggy

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#152]
in hidpp10.c, coverity complains that the 0x2 has no effect on the operation and always results in false. 
Looks like we're mixing datatypes here, led is a boolean array but the hidpp10 backend wants 0x1 and 0x2 for off/on (iirc). @bentiss, most of the git blame is on you, so maybe you remember how this was supposed to work.

1526                hidpp_log_raw(&dev->base,
1527                        "LED status: 1:%s 2:%s 3:%s 4:%s\n",
1528                        (profile->dpi_modes[i].led[0] & 0x2) ? "on" : "off",
1529                        (profile->dpi_modes[i].led[1] & 0x2) ? "on" : "off",
1530                        (profile->dpi_modes[i].led[2] & 0x2) ? "on" : "off",
1531                        (profile->dpi_modes[i].led[3] & 0x2) ? "on" : "off");

**Comment by bentiss** [comment]
I am not able to test right now, but it seems coverity is right. The functions that fill in dpi_modes[i].led[] are already doing the test against 0x2, so I suspect we should remove them and just test on the booleans.

I can't test this right now, this will have to wait next week.
