### ISSUE TITLE
Add Support for Fantech THOR X9 Macro RGB Gaming Mouse

### ISSUE THREAD

**Issue by WanderRainID** [libratbag/libratbag#1521]
**Is your feature request related to a problem? Please describe.**
I just bought a new cheap macro gaming mouse from Fantech called Fantech THOR X9 Macro RGB Gaming Mouse (this is the first time I try a macro mouse). I wanna use the macro feature on linux but luckily there is someone who already made the driver

**Describe the solution you'd like**
I found this [repo](https://github.com/muharamdani/FantechX9ThorDriver) for this type of mouse. maybe you guys can try merger it into this repo?

Thanks :3

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.
For now the application mentioned in the top message can be used instead.
