### ISSUE TITLE
Zelotes C-18 support (12c9:2003)

### ISSUE THREAD

**Issue by yhosoxeyu89ye** [libratbag/libratbag#1526]
Is it possible to support zelotes c-18?

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.

**Comment by PadreAdamo** [comment]
Good evening,
I'm working on this. I have all the LED functions properly mapped. I'm working on Key remapping.

**Comment by nnnuulll** [comment]
@PadreAdamo 
What about custom DPI?
Is it possible?

**Comment by PadreAdamo** [comment]
> [@PadreAdamo](https://github.com/PadreAdamo) What about custom DPI? Is it possible? @nnnuulll 

I will need to check the windows software. If the windows software supports I should be able to. LED functions are all finished and I'm about 20% through keymapping.

**Comment by JohnnyBob1970** [comment]
> Good evening, I'm working on this. I have all the LED functions properly mapped. I'm working on Key remapping.

do you have a specific package built for install or is this already incorp. to all distros like nobara and more

**Comment by PadreAdamo** [comment]
No package yet.

*The future is not set. There is no fate but what we make for ourselves.*

**Comment by tian2992** [comment]
I have the same device, sold under Steren brand in the latam market. Also including the keyboard emu. Let me know if i can contribute.

**Comment by PadreAdamo** [comment]
Almost done everyone! Taking a little longer than expected.

**Comment by PadreAdamo** [comment]
Another update, I have more features complete... getting there! You can follow my work here:

https://github.com/PadreAdamo/c18_reverseengineer

**Comment by PadreAdamo** [comment]
> [@PadreAdamo](https://github.com/PadreAdamo) What about custom DPI? Is it possible?

I will check. My current goal is everything from the software and custom DPI is not in the software. There are 5 levels with a DPI slider. The DPI slider moves in 100 intervals starting at 200 to 10000.

**Comment by PadreAdamo** [comment]
I did a PR just now.

https://github.com/libratbag/libratbag/pull/1877

**Comment by PadreAdamo** [comment]
> [@PadreAdamo](https://github.com/PadreAdamo) What about custom DPI? Is it possible?

Per-axis DPI isn't something the hardware supports at all; tested this tonight.
