### ISSUE TITLE
Corsair SABRE RGB PRO mouse support (1b1c:1b79, packet dumps available)

### ISSUE THREAD

**Issue by look-at-the-sky** [libratbag/libratbag#1537]
I have this mouse and the Corsair software is horrible, bloated and buggy.
I've already extracted all the relevant packets the Corsair software sends to the mouse, and documented everything to the best of my abilities.
I have 0 programming skills unfortunately so I can't really write the driver.
This should be fairly simple for someone who's familiar with the codebase.
Here's all I have.
[tbhs1j.zip](https://github.com/libratbag/libratbag/files/12778288/tbhs1j.zip)

**Comment by staticssleever668** [comment]
Hello! You did really good job on gathering data! However, someone still needs to volunteer and write a driver. Writing a new driver from scratch for a device you don't own is not as fun, and we are lacking on maintainership power. As such, I'll close the issue until that someone appears, but contributions are always welcome. :)

**Comment by look-at-the-sky** [comment]
I get it.
Is there a simple way I can send some packets to the mouse, like just for fun?

**Comment by staticssleever668** [comment]
You should be able to write bytes directly to HID driver, e.g. like "echo -en "\x05\x00\xFF\x00\x00" > /dev/hidraw6" in this blog post: https://blog.flozz.fr/2016/03/27/steelseries-rival-100-reverse-engineering-dun-peripherique-usb/ (I suggest you reading it before trying anything).
You seem to have some packets dumped as binaries - I think it should be possible to read them directly into hidraw handles, then, like `cat "angle snapping OFF.bin" > /dev/hidrawX`.

I did *not* do any of these, I started off with coding from start, but I did have programming experience. Double check everything and be careful!

**Comment by look-at-the-sky** [comment]
Thank you, I haven't tried that method yet but if I do I will report back.
Does piper/libratbag work on Windows using WSL2?

**Comment by staticssleever668** [comment]
I think libratbag doesn't work under WSL https://github.com/libratbag/piper/issues/808
