### ISSUE TITLE
Piper cannot find my steelseries rival 600

### ISSUE THREAD

**Issue by esanscoopsers** [libratbag/libratbag#1542]
**Information**

- `ratbagd` version (`ratbagd --version`):
- Distribution: Garuda
- Kernel version (ex. `uname -srmo`): `Kernel: 6.5.6-zen2-1-zen`

Device info (if applicable):
```
$ ratbagctl <device> info
OUTPUT HERE
```

**Describe the bug**
Piper does not recognize mt steelseries rival 600 which is supposed to be supported by libratbag
**To Reproduce**
1. Open Piper
2. says cannot find any devices

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
OUTPUT HERE
```

**Additional context**

**Comment by staticssleever668** [comment]
Duplicate: #1438.
This will be fixed in the next release. Until then, you can rollback libratbag or build it from source (e.g. AUR).
