### ISSUE TITLE
ASUS ROG Chakram Core support (0b05:1958)

### ISSUE THREAD

**Issue by pipes80-collab** [libratbag/libratbag#1551]
Could the ROG Chakram core model be supported in the future?
0b05:1958 ASUSTek Computer, Inc. ROG CHAKRAM CORE

Thanks for work

**Comment by staticssleever668** [comment]
cc @kyokenn

**Comment by pipes80-collab** [comment]
if I reopen I ask sorry, but not work

**Comment by pipes80-collab** [comment]
there is no folder there in that path

**Comment by staticssleever668** [comment]
Maybe /usr/local/share/libratbag then?

**Comment by pipes80-collab** [comment]
yes, there is in that path

**Comment by pipes80-collab** [comment]
i have not installing ratbagd.service, there is no in the folder

**Comment by pipes80-collab** [comment]
work but i can't use piper
