### ISSUE TITLE
G502 X Wireless (Non-plus version) macros only work when wired.

### ISSUE THREAD

**Issue by Y2K350** [libratbag/libratbag#1555]
Cannot get Logitech G502 X WIreless (Non-plus version) to work correctly without being wired.

Distro: Arch Linux
Kernal: Linux 6.6.1-arch1-1
Compositor: X11
DE: Gnome 45.1
Piper Version:  0.7
Ratbagctl version: 0.17

When connected by wire I am able to configure the mouse in Piper as well as see it in ratbagctl as Logitech G502 X LIGHTSPEED,

However, when connected wirelessly ratbagctl list returns no devices available. same as ratbagctl -vvv list.

Oddly enough some macros work, but input the wrong keys when wireless. When wired they input the correct keys.

Any idea what the issue might be, recently started using Arch again after a stint with Debian 12, this issue did not occur on Debian 12 for me.

**Comment by PollastreGH** [comment]
The same issue is present with me, where any macros on the mouse (Logitech G502 Lightspeed) only work when in wired mode.

Distro: EndeavourOS (Arch-based)
Kernel: 6.7.4.arch1-1
Compositor: X11
DE: KDE Plasma 5.27.10-1
Piper Version: 0.7-2
Libratbag version: 0.17-1

I also experience the same pattern of ratbagctl only showing the device in wired, not wireless mode. Any help would be appreciated, if anyone needs more info, please let me know

**Comment by staticssleever668** [comment]
Hi!

> Oddly enough some macros work, but input the wrong keys when wireless. When wired they input the correct keys.

That's weird. Do you happen to know if this also happens in Windows or if you set the macro with official Logitech software?

> However, when connected wirelessly ratbagctl list returns no devices available.

Pretty sure that's a receiver not yet properly supported by Linux. When connected wirelessly, we expect Linux to reexport connected USB devices in addition to the receiver.

**Comment by PollastreGH** [comment]
Going to answer for me even though I'm not the OP since the issue might be the same or similar.

> That's weird. Do you happen to know if this also happens in Windows or if you set the macro with official Logitech software?

The macro was set with the official "Logitech G Hub" software, and in Windows the issue is not present, the macro working fine in both wired and wireless mode.

> Pretty sure that's a receiver not yet properly supported by Linux. When connected wirelessly, we expect Linux to reexport connected USB devices in addition to the receiver.

Interesting, I will note that when plugged in, the following is output from ratbagctl:
`
hollering-marmot:    Logitech G502 LIGHTSPEED Wireless Gaming Mouse
singing-hare:        Logitech G502
`
Though when connected wirelessly, only the "singing-hare" entry displays.

I'll also note that the receiver is listed as the following under lsusb:

`Bus 001 Device 006: ID 046d:c539 Logitech, Inc. Lightspeed Receiver`

Hope this helps!

**Comment by Y2K350** [comment]
Sorry for delayed response. Issue had seemed to be resolved with a certain update to the Arch Linux Kernal, this was months (around December maybe?) ago, but I believe it was 6.6.0-arch-1-1 or something around then. Leaving case open for others visibility.

**Comment by PollastreGH** [comment]
Strange, for me the issue is still very present.

**Comment by staticssleever668** [comment]
> The macro was set with the official "Logitech G Hub" software, and in Windows the issue is not present, the macro working fine in both wired and wireless mode.

Looks like an issue with Linux.

https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.7
`Revert "HID: logitech-dj: Add support for a new lightspeed receiver iteration"` could be the fix.
