### ISSUE TITLE
Bug after install - " ratbagd error: Failed to start ratbagd: Permission denied "

### ISSUE THREAD

**Issue by ping-88** [libratbag/libratbag#1575]
I follow the exact steps on the README:

git clone https://github.com/libratbag/libratbag.git
cd libratbag
meson builddir
ninja -C builddir
sudo ninja -C builddir install

Now when I try to start libratbagd, it gives me this error:

sudo ratbagd
ratbagd error: Failed to start ratbagd: Permission denied

The output of the verbose is:
 
sudo ratbagd --verbose
Starting ratbagd version 0.17 (API version 2)
Initializing libratbag
ratbagd error: Failed to start ratbagd: Permission denied

I belive this to, most likely to be a me problem, so do you have any ideia how I fix it?

**Comment by staticssleever668** [comment]
Hi! It's likely a problem with D-Bus policies.
Try rebooting first, or if that doesn't help install to /usr (instead of default /usr/local) like described here on the wiki: https://github.com/libratbag/libratbag/wiki/Building-from-source#overwriting-the-system-installation.

**Comment by ping-88** [comment]
Thank you so much for the help! 
You were correct, after change the install folder it worked perfectly!

**Comment by nils-skowasch** [comment]
As someone, who is completely new to the used tools, it took me several hours to get **ratbagd** and **piper** running on **LinuxMint 21.3**. Here are my notes, just in case, someone else has issues setting up the systemd service and piper using the default installation guides:

```
## install fresh build from source:
- compile ratbagd
-- install cmake and meson:         
                                    sudo apt-get install cmake meson
-- install build dependencies:      
                                    sudo apt-get install libudev-dev libevdev-dev libglib2.0-dev libjson-glib-dev libunistring-dev libsystemd-dev swig check valgrind
-- clone repository and change directory:
                                    git clone https://github.com/libratbag/libratbag.git; cd libratbag
-- compile ratbadg:
                                    meson builddir --prefix=/usr
                                    meson configure builddir -Dsystemd-unit-dir=/usr/lib/systemd/system
                                    ninja -C builddir
- install ratbagd:
                                    sudo ninja -C builddir install
-- (to uninstall)                   (sudo ninja -C builddir uninstall)

- create systemd service (systemd files have been added by ninja install)
-- reload systemctl:
                                    sudo systemctl daemon-reload
                                    sudo systemctl reload dbus.service
-- enable service:
                                    sudo systemctl enable ratbagd.service

- install piper
-- clone piper repository:          
                                    cd ..; git clone https://github.com/libratbag/piper.git; cd piper
-- install build dependencies:      
                                    sudo apt-get install python-gi-dev python3-lxml python3-evdev
-- compile piper:
                                    meson builddir --prefix=/usr/
                                    ninja -C builddir
-- install piper:
                                    sudo ninja -C builddir install
-- install runtime dependencies:
                                    sudo apt-get install librsvg2-dev
-- start piper
                                    piper
```

Nevertheless, thank you for your work!
