### ISSUE TITLE
Logitech G Pro keyboard support? 

### ISSUE THREAD

**Issue by tsoernes** [libratbag/libratbag#1578]
Piper does not detect my keyboard even though there's a device file?

**Comment by staticssleever668** [comment]
Hi! The device file in libratbag is only in the master branch and not in a release yet.
Make sure you have it on your system (e.g. as `/usr/share/libratbag/logitech-g-pro-keyboard.device`).
If that doesn't help, please, post the output of ratbagd in verbose mode (e.g. run `sudo systemctl stop ratbagd && sudo ratbagd --verbose=raw`).

**Comment by tsoernes** [comment]
Thank you.

It worked.
