### ISSUE TITLE
Ant Esports GM 320 support?

### ISSUE THREAD

**Issue by ShadeZerox** [libratbag/libratbag#1579]
**Problem**
Ant esports mouses seem to be labeled as SINOWEALTH mouses, (referring to GM500), so i presume my GM 320 should be Sinowealth too, though after trying ratbagctl list and ratbagctl -vvv list there is no response. 
There is barely any info on this online and the only thread about this seems to be dead.

**Info**
Ratbagctl version -> 0.17 (installed it with piper)
Ratbagctl list output -> No devices available.
Distro -> Garuda

**Question**
So mainly put, is there any support for this mouse, if yes how do I make it work.

**Comment by staticssleever668** [comment]
Hi! What's the output of `lsusb` for you? This command lists connected USB devices.

(Also, somebody asked about this device in #1512, but they never replied back.)

**Comment by ShadeZerox** [comment]
Bruh, yeah i checked on that post in which the guy just didnt respond, 

Either way it seems the lsusb calls my mouse as-
`Bus 001 Device 002: ID 30fa:1440 INSTANT USB GAMING MOUSE`
(other than that there is just my webcam and other usb devices, this is the only mention of a mouse)

**Comment by ShadeZerox** [comment]
Oh, and JIC I tried out the command given in #1512, `lsusb -v -d 258a:` and got no result.
![image](https://github.com/libratbag/libratbag/assets/155251572/15b12f68-6ca7-4ad5-bb95-dad339a4c778)
