### ISSUE TITLE
No usb id for Logitech G102

### ISSUE THREAD

**Issue by Shchepan** [libratbag/libratbag#1585]
- ratbagd version 0.17
- Distribution: Gentoo

There was missing usb id for Logitech G102.

Fixed by adding **usb:046d:c09d** at the end of DeviceMatch
in /usr/share/libratbag/logitech-g102-g203.device
so now it's
DeviceMatch=usb:046d:c084;usb:046d:c092;usb:046d:c09d

and works.

**Comment by staticssleever668** [comment]
Hi! This will work out of the box with the next release with #1389.
