### ISSUE TITLE
Is it possible to update firmware on any device using Libratbag

### ISSUE THREAD

**Issue by Frambooisier** [libratbag/libratbag#1596]
as in title, additionally is there any other way to flash firmware using other tools on Linux? I thinking about devices like Glorious, Logitech, razor mices

**Comment by staticssleever668** [comment]
libratbag does not support updating device firmware. fwupd might support some devices.

(I'll mention https://github.com/carlossless/sinowealth-kb-tool for 'sinowealth' devices, but I certainly do not recommend trying to do anything with it yourself).
