### ISSUE TITLE
hwdb: G900 wireless usb dongle is the same for the G403

### ISSUE THREAD

**Issue by gicmo** [libratbag/libratbag#160]
Which in theory is good, because it just works, but in the hwdb file the svg image is also specified  RATBAG_SVG=logitech-g900.svg which would be wrong for the G403.

**Comment by bentiss** [comment]
As said on the PR, give me a couple of days to get to it.

First idea is to upgrade the kernel to a local branch I have which provides a different name for the 2 devices. But it's probably not the best given we might not want to force users to upgrade their kernel just to have a nice SVG :)

**Comment by FFY00** [comment]
This should now work properly with the latest libratbag release and Linux 5.2.
