### ISSUE TITLE
Does this use the HID API of the kernel or what?

### ISSUE THREAD

**Issue by korpe1** [libratbag/libratbag#1603]
The topic, do the drives use [HID API](https://docs.kernel.org/hid/index.html) of the kernel or what? The drives of libratbag implement these non-standard protocols on top of the HID API?

**Comment by enkore** [comment]
It (directly) uses hidraw, specifically

https://github.com/libratbag/libratbag/blob/master/src/libratbag-hidraw.c

**Comment by korpe1** [comment]
> It (directly) uses hidraw, specifically
> 
> https://github.com/libratbag/libratbag/blob/master/src/libratbag-hidraw.c

Okay, since uses RAW API, are all logic implemented in the libratbag/userland?
