### ISSUE TITLE
LED "rate" parameter shouldn't be expressed in Hz

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#167]
ratbag_led_get_effect_rate() says: `The LED rate in Hz, can be 100 - 20000`.

100Hz is something the eye doesn't distinguish, so 20000 is insanely more insane :)

I think the intend was to express the period in ms of the effect, not in Hz.

(opening an issue given it's public API).

Reported by @cvuchener

**Comment by phomes** [comment]
This was fixed in #423
