### ISSUE TITLE
[hidpp10] Memory offset size

### ISSUE THREAD

**Issue by cvuchener** [libratbag/libratbag#17]
In CMD_READ_MEMORY, you use a 16 bits offset. I am not sure what the real size offset but I don't think it makes sense. Since pages are 512 byte long, the maximum offset is 0xFF. And if you look at the parameters for the memory op command (0xA0), there is no room to have the two offsets be 16 bits with the same endianness.

Here is a test with offset 0x100 on my G500:
```
$ xxd -r -p <<< "10 00 83 A2 02 00 00" | src/send-raw-request /dev/hidraw1 | xxd -g 1
00000000: 11 00 83 a2 ff 00 00 80 00 11 00 11 22 11 00 22  ............".."
00000010: 00 22 22 12                                      ."".
$ xxd -r -p <<< "10 00 83 A2 02 00 01" | src/send-raw-request /dev/hidraw1 | xxd -g 1
00000000: 11 00 83 a2 ff 00 00 80 00 11 00 11 22 11 00 22  ............".."
00000010: 00 22 22 12                                      ."".
$ xxd -r -p <<< "10 00 83 A2 03 00 00" | src/send-raw-request /dev/hidraw1 | xxd -g 1
00000000: 11 00 83 a2 00 ff 00 80 00 09 00 09 22 11 00 22  ............".."
00000010: 00 22 22 1
```
It looks like the third byte is ignored.

**Comment by bentiss** [comment]
I confirm, the documentation says that byte 3 in the parameters of CMD_READ_MEMORY is always set to 0.

**Comment by bentiss** [comment]
commit  c26ce20 fixes this
