### ISSUE TITLE
man pages use the wrong hyphens

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#170]
Triggered by a47f50629357595ddb9064d304c2a0f5c2293374 which replaced the - in the man page with \-
I think it's the wrong thing to do tbh. Can't see a difference in the man page but when converting to PDF, it puts a minus sign in, instead of a hyphen. Looks wrong tbh and http://man7.org/linux/man-pages/man7/groff_char.7.html says

>  the ISO latin1 ‘Hyphen, Minus Sign’ (code 45) prints as a  hyphen; a minus sign can be obtained with ‘\-’.

Given the double meaning of "-" on the terminal, "minus minus help" or "dash dash help", we shouldn't be using the explicit minus sign. Definitely not on concatenated words like ratbag-command which is now rendered as "ratbag minus command"

cc @skitt, any comments?

**Comment by whot** [comment]
From http://liw.fi/manpages/

> An unfortunate bit of arcane syntax is that dashes in options should be prefixed by backslashes. Thus, write \-\-bits, not just --bits. The Debian and Ubuntu implementation of man treats them the same, for terminal output, but this is not portable. Technically a naked - means a hyphen, whereas \- means a minus sign. Typographically these are distinct, and they are also distinct in Unicode. The typesetter is free to break a line at a hyphen, but not at a minus. For dashes in options, you should thus use minuses, but in normal text, for normal words, the hyphen.

Ok, I guess we just need to be more fine-grained than the current approach which replaced all dashes.

**Comment by skitt** [comment]
The general rule covers a bit more than Lars’ description copied above — basically, anything that could be copied and pasted to a terminal command line needs to escape dashes. So in a47f506, the only incorrect escape that I can see is the one before KEY_A (possibly).

See Branden’s presentation (linked from Lars’ web page above) for much more on this, and recent discussions on the `groff` mailing list (starting [here](http://lists.gnu.org/archive/html/groff/2017-04/msg00007.html)).

**Comment by skitt** [comment]
In particular see Branden’s suggested [clarification patch](http://lists.gnu.org/archive/html/groff/2017-04/txtPmXjNornRZ.txt): in manpages, backslash-hyphen encodes hyphen-minus, not minus.

**Comment by whot** [comment]
the one in front of -KEY_A is an explicit minus (meaning "release"), so that's the one that's definitely correct. After reading through the presentation I reluctantly agree, the escaping is necessary, thanks.
