### ISSUE TITLE
LEDs should be named in SVG

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#171]
As pointed out in the Piper redesign wiki here: https://github.com/libratbag/piper/wiki/Piper-Redesign/

The LEDs should be named in the SVG file, just as the buttons are, ideally on their own SVG layer

**Comment by raghukamath** [comment]
Some models have indicator Led like the logitech g9 and g500, should these be labled as well or just the light (Fancy) LED like the ones in roccat cone xtd, should be labled

**Comment by whot** [comment]
Related to #178

**Comment by Hjdskes** [comment]
This will be automatically resolved in #182.

**Comment by Hjdskes** [comment]
After #209, naming LEDs is a reguirement for the GNOME theme only. Since we'll import those on a "when we get them" basis, I suppose this can be closed. Free to reopen if this also applies to the default theme.
