### ISSUE TITLE
LED set brightness for "on" mode

### ISSUE THREAD

**Issue by amfern** [libratbag/libratbag#173]
it is possible to change brightness for cycle and breathing mode but not for "on", it should be possible to set brightness for "on" mode

**Comment by amfern** [comment]
although Logitech drivers doesn't support brightness settings for "on" mode

**Comment by bentiss** [comment]
Yeah, problem is we can't fix the hardware :)

The protocol specification of the Logitech feature explicitly says that brightness can't be fixed for a fixed color. We _could_ trick the system by using some other effect (like color wave between two identical colors), but that would be a little bit pushing too far I think :)

Closing as "Naah"
