### ISSUE TITLE
Tune down the SVGs

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#178]
@Hjdskes is working on the Piper redesign:
https://github.com/libratbag/piper/wiki/Piper-Redesign

He already talked to @jimmac, so most of the below is from their discussion.

Basically, our SVGs don't look particularly great, have a look at the button mapping picture on that wiki page. They look (imo) good enough as icon in the device list and @raghukamath's font size fixes should've helped with the general looks but I think the drawings we have atm are in the uncanny valley.

So we need to either get a lot better with the graphics or just abstract them a lot more, similar to the gnome tablet design here: https://wiki.gnome.org/Design/SystemSettings/Tablet
It's unlikely we're going to get the almost photo-realism because ETIME and possibly ETALENT, so we should go the other direction and provide them in a more abstract manner.

This makes highlighting buttons and LEDs a bit easier too. And re-usability of the SVGs.

Any comments?

**Comment by raghukamath** [comment]
I like how the pen in the gnome tablet settings panel are shown. Here one color scheme with only the outer silhouette and recognizable shape is used for the product. That way the most important parts for us like buttons and LEDs can be highlighted with a bit contrasting colors. If we can achieve something like that with our drawing of mice, then it would be awesome. 

Also when creating the logitech g9 artwork,  I was not sure if we could trace the designs of the products as it is still copying someones product shot illustrations and might attract copyright problems. 

So yes I like what you are suggesting, remove the product specific branding, colors etc, keep only the recognizable shapes and features. This will make our designs consistent. If possible i'll do a quick mock of how it will look.

So +1 from me.

**Comment by Hjdskes** [comment]
Currently in progress in #182.

**Comment by Hjdskes** [comment]
After #209, it's decided that the toned down SVGs fall under the GNOME theme and is in progress in #182 still.

Feel free to reopen if this also applies to the default theme.
