### ISSUE TITLE
merge ratabgd into libratbag

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#179]
Currently, the only user of libratbag is ratbagd (minus ratbag-command).
Given libratbag requires root access to the hidraw nodes, and given that the devices that do not store their config in the device itself (some mice with CAP_QUERY_CONFIGURATION and the G910 keyboard for instance), we might as well force anybody else to use ratbagd as this is the cleaner way to access devices.

This should also ensures ratbag-ctl gets promoted to be the actual CLI interface for libratbag (or ratbag-command can be converted to use dbus).

**Comment by whot** [comment]
Let me expand on that:
* libratbag was originally *intended* to be a generic device access library
* it requires root, so it needs a wrapper to be useful on a normal setup
* at that point the wrapper becomes the generic library applications use, not libratbag itself
* the interface the wrapper uses (dbus, in the case of ratbagd) becomes the real API, so having separate APIs in libratbag becomes cumbersome for little gain
* and if we expect to always ship a wrapper process, we might as well accept that and start using it to our advantage (software profiles, etc.)

Everybody wins, except people with a terminal allergy to dbus :)

**Comment by whot** [comment]
Ok, given the fairly low outrage here I'll probably go ahead with this very soon

**Comment by whot** [comment]
Closed va #184
