### ISSUE TITLE
Meson encountered an error in file meson.build, line 298, column 1

### ISSUE THREAD

**Issue by Chronigan** [libratbag/libratbag#181]
I am on linux mint 8.1

I also want to say thanks for making a program like this. Not having a setpoint like program is the one thing that is keeping me from moving full time to linux.

'check' with pkg-config executable '/usr/bin/pkg-config'

Meson encountered an error in file meson.build, line 298, column 1:
Native dependency 'check' not found

**Comment by whot** [comment]
you need to install check-devel or whatever it's called on mint. See this post here, it's still configure but the same principle applies:
http://who-t.blogspot.com.au/2014/05/configure-fails-with-no-package-foo.html

**Comment by Chronigan** [comment]
Thanks for the help! Check just didn't sound like a package to me. Once
again thanks for making this software.

**Comment by lrenaud** [comment]
Can you indicate what on earth "check" actually is? I'm having a hell of a time finding anything about the library/project to say nothing of actually finding a package with the headers for it.

**Comment by Hjdskes** [comment]
https://libcheck.github.io/check/
