### ISSUE TITLE
systemd unit file is installed in /usr/lib64/

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#188]
Fedora uses /usr/lib64 as libdir and we use libdir as default for the systemd-unit-dir. Our systemd service files end up in /usr/lib64/systemd/system where there are happily ignored.

We could get the full path from the systemd.pc file ('systemdsystemunitdir') but that would break the expected behaviour of installing into a custom prefix. It's probably best to just hack around this particular behaviour and move on.

**Comment by Hjdskes** [comment]
Fixed in https://github.com/libratbag/libratbag/pull/189.
