### ISSUE TITLE
[hidpp10] G5: no event node for the configuration interface

### ISSUE THREAD

**Issue by cvuchener** [libratbag/libratbag#19]
The second interface of G5 that provide the vendor specific reports for HID++, does not have any input reports. Thus, the kernel does not create any input/event device and libratbag does not find the device.

Event devices:
```
$ ll /dev/input/by-id/
total 0
lrwxrwxrwx. 1 root root  9 17 sept. 09:47 usb-Chicony_Electronics_Co._Ltd_Chicony_USB_2.0_Camera-event-if00 -> ../event9
lrwxrwxrwx. 1 root root 10 17 sept. 12:07 usb-Logitech_G500_05554A4FA20018-event-mouse -> ../event13
lrwxrwxrwx. 1 root root 10 17 sept. 12:07 usb-Logitech_G500_05554A4FA20018-if01-event-kbd -> ../event14
lrwxrwxrwx. 1 root root  9 17 sept. 12:07 usb-Logitech_G500_05554A4FA20018-mouse -> ../mouse1
lrwxrwxrwx. 1 root root 10 17 sept. 12:07 usb-Logitech_USB_Gaming_Mouse-event-mouse -> ../event15
lrwxrwxrwx. 1 root root  9 17 sept. 12:07 usb-Logitech_USB_Gaming_Mouse-mouse -> ../mouse2
```

Logitech_USB_Gaming_Mouse is the G5, there is no event device for if01.

The report descriptor for the second interface:
```
06 00 FF       	Usage Page (FF00 - Vendor)
09 01          	Usage (0001 - Vendor)
A1 01          	Collection (Application)
85 10          	  Report ID (16)
75 08          	  Report Size (8)
95 06          	  Report Count (6)
15 00          	  Logical Minimum (0)
26 FF 00       	  Logical Maximum (255)
09 01          	  Usage (0001 - Vendor)
81 00          	  Input ()
09 01          	  Usage (0001 - Vendor)
91 00          	  Output ()
C0             	End Collection
06 00 FF       	Usage Page (FF00 - Vendor)
09 02          	Usage (0002 - Vendor)
A1 01          	Collection (Application)
85 11          	  Report ID (17)
75 08          	  Report Size (8)
95 13          	  Report Count (19)
15 00          	  Logical Minimum (0)
26 FF 00       	  Logical Maximum (255)
09 02          	  Usage (0002 - Vendor)
81 00          	  Input ()
09 02          	  Usage (0002 - Vendor)
91 00          	  Output ()
C0             	End Collection
```

**Comment by bentiss** [comment]
We are aware of the situation for the G5. @phomes has one, and already reported the problem. We currently have a hack in place fr this device. You should be able to directly open the second hidraw node created by the kernel for this interface (/dev/hidrawX).

We are not sure whether or not this situation is common so currently this workaround is used. I think we will end up having a quirk for the G5 in the drv-hidpp10 in which we will open the other hidraw node instead of the one attached to the actual input node.

Keeping the issue open until this is properly fixed.

**Comment by cvuchener** [comment]
I think the Corsair M65 RGB will have the same issue.

**Comment by bentiss** [comment]
Actually, @whot just told me that this feature (open a hidraw node directly) branch was only available in his wip/open-hidraw-directly (or something close to it) branch on his repo.

Thanks for the tip on the Corsair mouse.

**Comment by cvuchener** [comment]
I don't own the M65, I have read some code from [ckb](https://github.com/ccMSC/ckb) for my work on Corsair keyboards.

I understand it has 4 interfaces. ckb polls the first three and use set_feature/get_feature or bulk transfer on the fourth for configuration.

Here are the report descriptors extracted from the firmware. I think they match ckb code:
```
05 01          	Usage Page (0001 - Generic Desktop)
09 02          	Usage (0002 - Mouse)
A1 01          	Collection (Application)
09 01          	  Usage (0001 - Pointer)
A1 00          	  Collection (Physical)
05 09          	    Usage Page (0009 - Button)
19 01          	    Usage Minimum (0001 - Button 1)
29 05          	    Usage Maximum (0005 - Button 5)
15 00          	    Logical Minimum (0)
25 01          	    Logical Maximum (1)
95 05          	    Report Count (5)
75 01          	    Report Size (1)
81 02          	    Input (Variable)
95 01          	    Report Count (1)
75 03          	    Report Size (3)
81 01          	    Input (Constant)
05 01          	    Usage Page (0001 - Generic Desktop)
09 30          	    Usage (0030 - X)
09 31          	    Usage (0031 - Y)
09 38          	    Usage (0038 - Wheel)
15 81          	    Logical Minimum (-127)
25 7F          	    Logical Maximum (127)
75 08          	    Report Size (8)
95 03          	    Report Count (3)
81 06          	    Input (Variable, Relative)
95 03          	    Report Count (3)
75 08          	    Report Size (8)
81 01          	    Input (Constant)
C0             	  End Collection
C0             	End Collection
```

```
05 01          	Usage Page (0001 - Generic Desktop)
09 02          	Usage (0002 - Mouse)
A1 01          	Collection (Application)
85 01          	  Report ID (1)
09 01          	  Usage (0001 - Pointer)
A1 00          	  Collection (Physical)
05 09          	    Usage Page (0009 - Button)
19 01          	    Usage Minimum (0001 - Button 1)
29 20          	    Usage Maximum (0020 - Button 32)
15 00          	    Logical Minimum (0)
25 01          	    Logical Maximum (1)
95 20          	    Report Count (32)
75 01          	    Report Size (1)
81 02          	    Input (Variable)
05 01          	    Usage Page (0001 - Generic Desktop)
09 30          	    Usage (0030 - X)
09 31          	    Usage (0031 - Y)
16 01 80       	    Logical Minimum (-32767)
26 FF 7F       	    Logical Maximum (32767)
75 10          	    Report Size (16)
95 02          	    Report Count (2)
81 06          	    Input (Variable, Relative)
09 38          	    Usage (0038 - Wheel)
15 81          	    Logical Minimum (-127)
25 7F          	    Logical Maximum (127)
75 08          	    Report Size (8)
95 01          	    Report Count (1)
81 06          	    Input (Variable, Relative)
C0             	  End Collection
C0             	End Collection
05 0C          	Usage Page (000C - Consumer)
09 01          	Usage (0001 - Consumer Control)
A1 01          	Collection (Application)
85 02          	  Report ID (2)
15 00          	  Logical Minimum (0)
25 01          	  Logical Maximum (1)
75 01          	  Report Size (1)
95 04          	  Report Count (4)
09 E2          	  Usage (00E2 - Mute)
09 CD          	  Usage (00CD - Reserved)
09 B5          	  Usage (00B5 - Scan Next Track)
09 B6          	  Usage (00B6 - Scan Previous Track)
81 62          	  Input (Variable, No Preferred, Null State)
75 01          	  Report Size (1)
95 04          	  Report Count (4)
81 01          	  Input (Constant)
75 08          	  Report Size (8)
95 06          	  Report Count (6)
81 01          	  Input (Constant)
C0             	End Collection
```

```
06 C1 FF       	Usage Page (FFC1 - Vendor)
09 01          	Usage (0001 - Vendor)
A1 01          	Collection (Application)
15 00          	  Logical Minimum (0)
26 FF 00       	  Logical Maximum (255)
09 11          	  Usage (0011 - Vendor)
95 40          	  Report Count (64)
75 08          	  Report Size (8)
81 02          	  Input (Variable)
C0             	End Collection
```

```
06 C2 FF       	Usage Page (FFC2 - Vendor)
09 02          	Usage (0002 - Vendor)
A1 01          	Collection (Application)
15 00          	  Logical Minimum (0)
26 FF 00       	  Logical Maximum (255)
95 40          	  Report Count (64)
75 08          	  Report Size (8)
09 02          	  Usage (0002 - Vendor)
B1 02          	  Feature (Variable)
C0             	End Collection
```

**Comment by whot** [comment]
i think we'll need to put a quirk in for the devices affected in libratbag. Hard to test without a device, but I think it should be enough to change udev_find_hidraw() to look for the parent devtype "usb_device" instead of "hid". The enumeration should work from there. If that works, we put a quirk in for the devices affected and do it whenever that flag is set.

@phomes  - let us know if that works for your devices, I'm looking at your udevadm output here.

**Comment by cvuchener** [comment]
Can this happen with bluetooth devices too?

**Comment by whot** [comment]
I'm gonna say "probably" but let's figure that out when we have access to one of those devices and we can figure out the exact device tree.

**Comment by Susurrus** [comment]
I see this same problem on my g5. Went down a rabbit hole in GDB trying to figure it out, and turns out this was exactly the issue. I've built the code that should allow this to work,  whot/libratbag@2a8691bad3b5b0c598f1cc4ee24a1723d84e129b, but it didn't.

How can I help with this issue, as I have both a g5 and I can compile and test libratbag?

**Comment by Susurrus** [comment]
If you checkout libratbag/master and then cherry-pick the commit I linked to above, it merges in cleanly. And then you can see the following output:
```
ratbag debug: Logitech USB Gaming Mouse is device '/dev/hidraw1'.
ratbag debug: trying driver 'Roccat Kone XTD'
ratbag debug: trying driver 'Logitech HID++1.0'
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: driver match found
Device 'Logitech USB Gaming Mouse'
Capabilities:
Number of buttons: 3
Profiles supported: 1
  Profile 0 (active) (default)
    Resolutions:
      0: <disabled>
    Button: 0 type left is mapped to 'none'
    Button: 1 type middle is mapped to 'none'
    Button: 2 type right is mapped to 'none'
```

**Comment by bentiss** [comment]
Just a FYI to everybody involved here. I checked a steelseries rival, and it also behaves like the G5 and the corsair: no input node created for the hidraw node that can be used to configure it.

We currently do not use the event node for anything, and I am more and more tempted to just drop it and rely on /dev/hidraw only.

The only problem I have with using hidraw is when the device is not using HID at all (and uses bulk USB transfers, or any other communication channel). Relying on the input event node allows us to say that we want the device, no matter its communication channel...

Any ideas?

**Comment by cvuchener** [comment]
Why not use the USB or bluetooth devices, and then let the driver find the child devices and nodes it needs?

My Corsair K90 keyboard use only USB control transfers for configuration, some mice may work this way too.

I think event nodes are too loosely tied to configuration:
- the G5 has one event device not used for configuration
- the G500 has two event devices, only one used for configuration
- the K90 (not mouse but it could happen) has three devices, none used for configuration but all direct children of the USB device used for configuration

I think I am getting out of the scope of libratbag but in order to implement software LED dynamic animation on Corsair RGB devices, you need to read events on one HID interface and write configuration to another.

Nevertheless, event nodes could be kept for the user interface, but all event nodes should work and identify the same ratbag device.

**Comment by whot** [comment]
very short comment, I'm on holidays and try to avoid emails :)

the reason we use the event nodes atm is because they're the easiest API for clients to handle - loop through event nodes and create a udev device, then pass that to libratbag. The same wouldn't work quite as nicely for usb/bt devices directly, though if you can find a good template to handle that we can reconsider. or some other alternative that works well for the API.

I suspect that long-term the dbus api will become more important to clients than the C API, so optimising here may not be useful anyway. But I'd like to see that happen first, @dvdhrm has been volunteered for the dbus daemon :)

**Comment by bentiss** [comment]
Hopefully commit 975c91ae54 fixes this. Please close it if so.

**Comment by phomes** [comment]
Works for me with the G5
