### ISSUE TITLE
Does every resolution has its own report rate?

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/libratbag#197]
From https://github.com/libratbag/piper/blob/master/piper/ratbagd.py#L344 it appears that every resolution has its own report rate, but the mockups (ironically made by me) indicate there is one per profile report rate that applies to all that profile's resolutions.

@bentiss says that for Logitech hidpp2/0, there is only one report rate per profile but he isn't sure about the rest. @whot and others, what do you say?

**Comment by whot** [comment]
IIRC it depends on the device, pretty sure my G500s only has one report rate across all.

However - you're making a GUI app that is supposed to be usable by most, so it's perfectly acceptable to provide a subset of features only. I think this is one case where it's just fine to do so, so I'd say don't worry about it

**Comment by Hjdskes** [comment]
One global report rate it is then.
