### ISSUE TITLE
Move the report rate into the profile

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#202]
The report rate is currently part of the resolution but that's unrealistic, no device seems to do that. Refresh rate per profile is what the devices  support, so let's do that.

This will be an API/ABI break, `RATBAG_RESOLUTION_CAP_INDIVIDUAL_REPORT_RATE` will have to go, `ratbag_resolution_set_report_rate` and `ratbag_resolution_get_report_rate` as well. That affects the DBus bindings too, so it'll break the world.

Note that at least Piper already ignored the per-resolution report rate and only had one toggle per profile anyway.

**Comment by whot** [comment]
I was about to get started on this, but I'm wondering if it's worth the effort and API break. We have a flag that tells us whether the report rate applies to all and that flag isn't set on any device. Moving this to the profile is a break for relatively little benefit with the potential of locking us out of individual report rates in the future.

**Comment by Hjdskes** [comment]
> We have a flag that tells us whether the report rate applies to all and that flag isn't set on any device.

This is definitely something I can check for in Piper to do the correct thing, i.e. make it appear per-profile if it's not set and per-resolution if it is. I think that would solve this, so we don't have to break the API and possibly locking ourselves out as you said.

**Comment by whot** [comment]
tbh, not worth the effort given no devices supports it, stick with what you have and we're good

**Comment by staticssleever668** [comment]
Fixed by #648
