### ISSUE TITLE
Make ratbagctl take the same arguments as ratbag-command

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#203]
In the medium-term plan to replace/remove ratbag-command, ratbagctl needs to do the exact same thing, albeit by going through ratbagd. This means the commandline interface should be the same.

**Comment by Hjdskes** [comment]
Ratbagctl's bindings are not up to date, just FYI.

**Comment by whot** [comment]
Benjamin has the ratbagd.py sync patch for that in https://github.com/libratbag/libratbag/pull/207

**Comment by bentiss** [comment]
This has been almost done in PR #218.

We are missing a few commands and proper keycode mappings but we should be close to be able to close this one.

**Comment by bentiss** [comment]
Feature complete:
https://226-41394739-gh.circle-artifacts.com/0/root/libratbag/build/meson-logs/testlog.txt
https://circleci.com/gh/libratbag/libratbag/226#artifacts/containers/0

\o/
