### ISSUE TITLE
Add support for theming to ratbagd

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#204]
This is required for #182, especially to merge the new SVGs while they're still WIP without breaking everything else.

Proposal is to add three new APIs to ratbagd:
- `GetSvgBaseDir()` -> /usr/share/libratbag
- `GetThemes()` -> [ 'default', 'gnome' ]
- `GetSvg()` -> 'logitech-g500s.svg'

And the caller then assembles the path to the right file. Alternatively, an option could be to supply the theme as argument to `GetSvg('gnome')` and get the full path.

**Comment by bentiss** [comment]
> Alternatively, an option could be to supply the theme as argument to `GetSvg('gnome')` and get the full path.

I think I like this one better.

**Comment by Hjdskes** [comment]
^ Me too

**Comment by Hjdskes** [comment]
Done through https://github.com/libratbag/libratbag/pull/209, but note https://github.com/libratbag/libratbag/pull/212 as a followup.
