### ISSUE TITLE
ActiveResolutionChanged should only emit when the active resolution changed.

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/libratbag#205]
Right now, it's emitted for every change: https://github.com/libratbag/libratbag/blob/master/ratbagd/ratbagd-resolution.c#L98

**Comment by whot** [comment]
yep, definitely a bug. We don't have a call to change the active resolution in ratbagd, so this signal is a bit superfluous.

**Comment by Hjdskes** [comment]
Fixed in #208.
