### ISSUE TITLE
Have ratbagctl from git master start and talk to ratbagd master

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#206]
When developing with rabtagd/ratbagctl, we should make sure we are not talking to the system ratbagd but the current in-tree ratbagd.

I am thinking at adding a wrapper in ratbagctl (that might be removed when installed). This wrapper would start ratbagd with an environment variable that will launch ratbagd and bind it to a different bus than the system installed ratbagd.

I am also thinking at adding a tag on the ratbagd version by using the git sha of the last change in ratbagd folder (kind of `echo $(git log  --format=format:%h -1 -- ./ratbagd)`).

**Comment by whot** [comment]
Discussed in PR https://github.com/libratbag/libratbag/pull/207
