### ISSUE TITLE
Devices missing for the GNOME theme

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/libratbag#213]
Devices converted:

- [ ] etekcity
- [x] logitech-g300
- [x] logitech-g303
- [x] logitech-g403
- [x] logitech-g500
- [x] logitech-g500s
- [x] logitech-g502
- [x] logitech-g700
- [x] logitech-g9
- [x] logitech-g900
- [x] logitech-mx_master
- [x] roccat-kone-xtd

**Comment by Hjdskes** [comment]
@jimmac Feel free to do more, requirements are in [the GNOME guidelines](https://github.com/libratbag/libratbag/blob/master/data/gnome/README.md).

**Comment by whot** [comment]
https://github.com/libratbag/libratbag/pull/228 has the g303

**Comment by Hjdskes** [comment]
Roccat Kone in #294.

**Comment by phomes** [comment]
I am working on G300 in https://github.com/phomes/libratbag/tree/WIP-G300-svg

**Comment by phomes** [comment]
G9 is completed

**Comment by whot** [comment]
I think we can just remove the default theme and symlink it to the gnome theme. We only promise the "default" theme exists, not how it looks like.

And this is git, we can git rm the svgs and resurrect them if we ever need them again. tbh, I have no idea if anyone is using the default theme anyway.

**Comment by whot** [comment]
Closing this. SVGs have moved to Piper anyway so any missing SVGs should be handled there.
