### ISSUE TITLE
capabilities need renaming for better namespacing

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#224]
`LIBRATBAG_CAP_SWITCHABLE_RESOLUTION` to `LIBRATBAG_CAP_RESOLUTION_SWITCHABLE`, and so on.

API break again, but we haven't released since the last one (iirc)

**Comment by bentiss** [comment]
Will this really be an API break knowing that libratbag.so will not be exposed anymore?

**Comment by whot** [comment]
nope, if we remove the .so anyway we don't care about the changes in the API.
