### ISSUE TITLE
ratbagd: SvgPath property does not take themes into account

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#235]
Still returns a theme-less string

**Comment by bentiss** [comment]
Wouldn't it be easier to remove the property altogether?
We already have the method GetSvg...

**Comment by whot** [comment]
yeah, it's not super urgent to fix (I assigned it to myself for that reason). There's a bunch of other things 'wrong' with the dbus API, I'm currently trying to collect that. Feel free to ignore this bug for now

**Comment by Hjdskes** [comment]
Just as an FYI -- these properties have already been removed from Piper's bindings

**Comment by whot** [comment]
This is addressed in #242 by removing SvgPath
