### ISSUE TITLE
Calling SetDefault on resolution through dbus fails

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#246]
While trying to implement SetActive on resolution, I realized that the SetDefault code currently fails with:
```
GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Unknown method 'SetDefault' or interface 'org.freedesktop.ratbag_devel1_8a49721.Resolution'. (19)
```

Also, it would be good to have coverage of SetDefault in the test suite.

**Comment by Hjdskes** [comment]
Closed through #247.
