### ISSUE TITLE
SetSpecialMapping in ratbagd should accept an enum instead of a string

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/libratbag#252]
I suppose this one was simply glanced over, but this function too should take an `enum ratbag_button_action_special` instead of a string. Right now Piper will crash over this (in https://github.com/libratbag/piper/pull/47), because it already assumes the enum while the bindings and ratbagd still want the string.

**Comment by bentiss** [comment]
Yeah, this simply has not been implemented yet. See https://213-41709447-gh.circle-artifacts.com/0/root/libratbag/build/meson-logs/testlog.txt -> the last skipped test is related to set action special :)

**Comment by Hjdskes** [comment]
I'll fix this
