### ISSUE TITLE
G500s no profile set as active profile

### ISSUE THREAD

**Issue by adrien-martin** [libratbag/libratbag#261]
Hello,

I'm facing a strange problem, ratbag-command seems to detect my mouse (a G500s) but can not print information or configure anything.

```
# ratbag-command --verbose=debug list
ratbag debug: Logitech G500s Laser Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Logitech G500s Laser Gaming Mouse is device '/dev/hidraw5'.
ratbag debug: report ID 01
ratbag debug: report ID 03
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag error: unknown tag: 0x12
ratbag error: unknown tag: 0x08
ratbag error: unknown tag: 0x12
ratbag error: unknown tag: 0x08
ratbag error: libratbag bug: Logitech G500s Laser Gaming Mouse: no profile set as active profile
No supported devices found
```

```
# udevadm info /sys/class/input/event0 | grep RATBAG_DRIVER
E: RATBAG_DRIVER=hidpp10
```

The libratbag version is 0.9.0 provided by debian (sid), but the only patch I found was for the doc files.

According to the error message, setting a profile could fix the problem but I don't know how to change it without ratbag.

**Comment by cvuchener** [comment]
I can reproduce the bug with my current installed version of ratbag-command, but it is not a debug build. I made a debug build from the latest revision, and it looks like it has already been fixed. Could you try with the current development version?

------------

When looking at this, I also discovered that there may be some problem with the way we get the current active profile for HID++1.0 devices.

Using a G500s with three profiles, I always get "3" as the current profile after plugging in the mouse and changing the profile using the buttons. If I change the profile by sending a command to the device, the current profile is then read properly, even if I later change the profile using the mouse buttons.

libratbag test if the value is out of bound and replace it with 0, so it should work but it may be lying about the current profile (if there are more than one profile). I don't know any way to improve the current behavior.

**Comment by adrien-martin** [comment]
I built from master and it works too, sorry I should have tried before.

For the profiles I don't know, mine seems to have only one profile (says "Profiles supported: 1", and verbose=raw don't find more).

**Comment by cvuchener** [comment]
Officially, the G500 and G500s don't support multiple profiles. It is actually possible to have more than one profile but it does not work perfectly. It is best to use those mice with only one profile, anyway. It is just that I thought it was the cause of the bug at some point.

**Comment by adrien-martin** [comment]
Ah interesting, could be useful some day.

Anyway, tanks for your help.
