### ISSUE TITLE
Ditch ratbag-command C in favor of a python version

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#274]
Playing with ratbagctl is so much more fun than ratbag-command that I suspect ratbag-command will slowly depress alone in its corner while ratbagctl become the preferred child.

During breakfast (no kidding, no beers were involved), we realize we could autogenerate a Python to C wrapper for libratbag, and have a thin ratbagd_c.py library we could use to directly talk from ratbagctl to libratbag. Bonus point if we actually rename the merge of ratbagctl.in and ratbagd_c.py to ratbag-command.

**Comment by whot** [comment]
@bentiss i think you said we're ready to finish this off?

**Comment by bentiss** [comment]
Not really. The goal would be to have a common ratbagctl.in that directly calls libratbag, bypassing ratbagd.
