### ISSUE TITLE
Meson failure: Meson encountered an error in file meson.build, line 33, column 0

### ISSUE THREAD

**Issue by Brainiarc7** [libratbag/libratbag#276]
Hello there,

I ran into the following issue with building the project, as you can see in the log below:

```
meson scratch --prefix=/usr
The Meson build system
Version: 0.29.0
Source dir: /home/lin/source.build/libratbag
Build dir: /home/lin/source.build/libratbag/scratch
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: libratbag
Native c compiler: cc (gcc 5.4.0-6ubuntu1)
Native cpp compiler: c++ (gcc 5.4.0-6ubuntu1)
Program git found: YES (/usr/bin/git)

```
```
Meson encountered an error in file meson.build, line 33, column 0:
Unknown function "add_project_arguments".
```

This is encountered after cloning the repository, creating the build directory scratch and calling up meson.

FYI, I'm running the current version of Meson available from pip3.

```
meson --version
0.29.0


```

Kindly assist.

**Comment by Brainiarc7** [comment]
Oh, my bad, was missing some dependencies on my end, such as libeventd.

Fixed by installing them one by one.

Closing the issue.

**Comment by whot** [comment]
meson 0.29 is likely too old, `add_project_arguments` was added in 0.36 afacit from a quick git search. we should have a version check in meson.build

I can't imagine that pip gives you 0.29 either, meson is at 0.41.x
