### ISSUE TITLE
systemd needs to be optional

### ISSUE THREAD

**Issue by dsalt** [libratbag/libratbag#278]
I'm still using sysvinit and I don't plan on switching from that; I've not dug into the dbus side of things; but a SysV init script for this would still be useful for various reasons including compatibility.

Also, if this gets ported to any of the BSDs, it'll need to work without systemd anyway.

(I may post patches. If I'm beaten to it, that's fine.)

**Comment by cvuchener** [comment]
I think the only systemd part is the ratbagd service file. The systemd dependency could be made optional, so that the service file is not installed on systems not using systemd.

**Comment by tpruzina** [comment]
@cvuchener It uses udev hence unless an user is using non-systemd fork of udev it's systemd.

**Comment by whot** [comment]
realistically: not going to happen, sorry. See issue #239 for an explanation.
