### ISSUE TITLE
HWDB not automatically updating

### ISSUE THREAD

**Issue by PlasmaPower** [libratbag/libratbag#279]
Previously: libratbag/piper#109

`ratbagctl info event4` outputs:

```
event4 - Logitech Gaming Mouse G502
               SVG: 
      Capabilities: query-configuration, resolution, switchable-resolution, profile, switchable-profile, disable-profile, button, button-keys, led
 Number of Buttons: 11
    Number of Leds: 2
Number of Profiles: 3
Profile 0: (disabled)
Profile 1: (disabled) (active)
Profile 2: (disabled)
```

Notice that the SVG line is missing, despite being clearly installed: https://gist.github.com/PlasmaPower/e8ed4680689726b89f20e53d64dece75

`/usr/share/libratbag/gnome/logitech-g502.svg: SVG Scalable Vector Graphics image`

This causes piper to crash.

**Comment by PlasmaPower** [comment]
Also, in `journalctl`: `ratbagd error: Unable to fetch SVG for event4`

**Comment by PlasmaPower** [comment]
Fixed it!

```sh
sudo systemctl-hwdb update
sudo udevadm control -R
sudo udevadm trigger
sudo systemctl restart ratbagd
```

Not sure if all of that was necessary. I'll keep the issue open for now, because I think this should be documented somewhere.

**Comment by PlasmaPower** [comment]
I had rebooted before this. I think that should've updated the hwdb, but maybe it didn't.

**Comment by whot** [comment]
nope, rebooting doesn't update the hwdb, that's a manual command. once you run `systemctl-hwdb update`, a reboot should then work fine after that.

This should get better with #268 but mean you could submit a PR for a `meson.add_install_script` that toggles the hwdb on install (if root, and warns otherwise), I think that would make sense.

**Comment by PlasmaPower** [comment]
I'll close this issue, and instead comment on the AUR package.
