### ISSUE TITLE
Add a `dirty` property to RatbagdDevice

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/libratbag#283]
This way Piper doesn't have to resort to the hack in its bindings introduced by https://github.com/libratbag/piper/commit/f69ccde09ee8e82f874cb97a6e6698f2845bd258. This initially was https://github.com/libratbag/piper/issues/105 but I don't have the time currently to do this myself, hence I'm opening it here as it's related to ratbagd anyway.

If no one gets around to doing it I can probably do it after GSoC has ended; right now my focus is on making Piper more robust.

**Comment by whot** [comment]
trying to page this back into my head to remember what this was about in detail. But I think we can just close this. It'd be nice to have but it's not required, we've managed for 18m without it now. And there's only one place where the workaround is needed, in the call to `Commit`.

Given that virtually everything else is tied to the profile anyway, having callers monitor dirty signals on the profile instead seems to make sense.

So, shrugh, it wasn't important enough for the last year and a bit, so let's close this and implement it when someone has a specific need for it.
