### ISSUE TITLE
`ratbagctl -h` gives incorrect usage

### ISSUE THREAD

**Issue by mxmgh** [libratbag/libratbag#288]
```
$ ratbagctl -h
usage: ratbagctl [-h] [-V] [--verbose]

Inspect and modify configurable mice

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  show program's version number and exit
  --verbose, -v
```

This should state that ratbagctl takes a command argument, and ideally list which command arguments are available.

The message when running `ratbagctl asdf` is better in this respect, but it would be nice to have the "command" on the same line as the rest of the command-line for clarity:
```
usage: ratbagctl [-h] [-V] [--verbose]
                 {list,info,profile,resolution,dpi,rate,button,led} ...
ratbagctl: error: invalid choice: 'h' (choose from 'list', 'info', 'profile', 'resolution', 'dpi', 'rate', 'button', 'led')
```

In addition, error handling on incomplete invocations seems really rough, throwing exceptions in logic rather than validating and giving feedback at parse-time.

**Comment by whot** [comment]
>  it would be nice to have the "command" on the same line

that's controlled by python's argparse module, we have some control but given our crazy parser this is going to be a fair bit of work
