### ISSUE TITLE
Logitech G5(2007) detects only 3 buttons instead of 9

### ISSUE THREAD

**Issue by sl1pkn07** [libratbag/libratbag#299]
the Logitech Laser G5 (2007) has 9 buttons

![](http://images.anandtech.com/reviews/peripherals/logitech-g5-2007/setp5.png)

but libratbag only detect 3 as `Logitech USB Gaming Mouse`

```
└───╼  sudo ratbagctl info event2
event2 - Logitech USB Gaming Mouse
               SVG: 
      Capabilities: query-configuration
 Number of Buttons: 3
    Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
  Resolutions:
    0: <disabled>
  Button: 0 type left is mapped to none
  Button: 1 type middle is mapped to none
  Button: 2 type right is mapped to none
```

is not fully supported, right?

greetings

**Comment by cvuchener** [comment]
The G5 doesn't support hardware profiles. There is a few settings that can be changed (changing resolutions buttons and wheel tilt to generic buttons, changing the report rate), but I don't think they stay after rebooting.

**Comment by whot** [comment]
Yeah, sorry, we don't do software profiles yet. Closing based on @cvuchener's comment above
