### ISSUE TITLE
drop the signed-off-by "requirement"

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#30]
we've already merged a bunch of patches without it and many projects don't bother with it anyway. How about we drop this too? any comments?

**Comment by bentiss** [comment]
I am fine with that. The problem I see is that github is not that convenient to add the sign-off-by after the pull request has been sent unless we re-write the patches.
So if we want to keep external contributors, it should not be a hard requirement.

However, I still like the signed-off-by, it help keeping tracks of who wrote which code, so I will definitively encourage people to use it and I will personally use it.

**Comment by whot** [comment]
well, the 'easy' way would be to pull it locally, then rebase/rewrite the commits and push to master. which is what we're doing wherever we don't use github's pull clickyness.

if we keep it, we should document what it means though :) even if it is just a link to the kernel doc

**Comment by phomes** [comment]
I keep forgetting s-o-b - sorry. The other projects I work on typically do not use it so I forget.

**Comment by whot** [comment]
closing because there isn't much more to discuss. We encourage the s-o-b and may require it for some things (e.g. device drivers where the legal situation could be hairy) but we'll be lenient where we can be.
