### ISSUE TITLE
No image for device

### ISSUE THREAD

**Issue by kudlatyamroth** [libratbag/libratbag#300]
as suggested by @Hjdskes in https://github.com/libratbag/piper/issues/161
i opened this bug.

When i launch piper i get error with message that i don't have image for my device
"Device has no image or its path is invalid"

My device is Logitech G903 (same as G900)
My system is Arch Linux

piper version: 0.2.900-3
libratbag version: 0.9.900-2

udevadm output:

> [root@arch kudlaty]# udevadm info /sys/class/input/event2
> P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.5/2-1.5.2/2-1.5.2:1.1/0003:046D:C539.0004/input/input19/event2
> N: input/event2
> S: input/by-id/usb-Logitech_USB_Receiver-if01-event-mouse
> S: input/by-path/pci-0000:00:1d.0-usb-0:1.5.2:1.1-event-mouse
> E: DEVLINKS=/dev/input/by-path/pci-0000:00:1d.0-usb-0:1.5.2:1.1-event-mouse /dev/input/by-id/usb-Logitech_USB_Receiver-if01-event-mouse
> E: DEVNAME=/dev/input/event2
> E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.5/2-1.5.2/2-1.5.2:1.1/0003:046D:C539.0004/input/input19/event2
> E: ID_BUS=usb
> E: ID_INPUT=1
> E: ID_INPUT_KEY=1
> E: ID_INPUT_MOUSE=1
> E: ID_MODEL=USB_Receiver
> E: ID_MODEL_ENC=USB\x20Receiver
> E: ID_MODEL_ID=c539
> E: ID_PATH=pci-0000:00:1d.0-usb-0:1.5.2:1.1
> E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_5_2_1_1
> E: ID_REVISION=3904
> E: ID_SERIAL=Logitech_USB_Receiver
> E: ID_TYPE=hid
> E: ID_USB_DRIVER=usbhid
> E: ID_USB_INTERFACES=:030101:030102:030000:
> E: ID_USB_INTERFACE_NUM=01
> E: ID_VENDOR=Logitech
> E: ID_VENDOR_ENC=Logitech
> E: ID_VENDOR_ID=046d
> E: LIBINPUT_DEVICE_GROUP=3/46d/c539/111:usb-0000:00:1d.0-1.5
> E: MAJOR=13
> E: MINOR=66
> E: RATBAG_DRIVER=hidpp20
> E: RATBAG_HIDPP20_INDEX=1
> E: RATBAG_SVG=logitech-g900.svg
> E: SUBSYSTEM=input
> E: TAGS=:power-switch:
> E: USEC_INITIALIZED=753497472

**Comment by kaymio** [comment]
Same here: Arch, piper, libratbag all the same. Arch is always up to date! 

> 
udevadm info /sys/class/input/event2
P: /devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.1/1-1.1:1.0/0003:046D:C539.0006/input/input13/event2
N: input/event2
S: input/by-id/usb-Logitech_USB_Receiver-event-kbd
S: input/by-path/pci-0000:00:12.2-usb-0:1.1:1.0-event-kbd
E: DEVLINKS=/dev/input/by-path/pci-0000:00:12.2-usb-0:1.1:1.0-event-kbd /dev/input/by-id/usb-Logitech_USB_Receiver-event-kbd
E: DEVNAME=/dev/input/event2
E: DEVPATH=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.1/1-1.1:1.0/0003:046D:C539.0006/input/input13/event2
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c539
E: ID_PATH=pci-0000:00:12.2-usb-0:1.1:1.0
E: ID_PATH_TAG=pci-0000_00_12_2-usb-0_1_1_1_0
E: ID_REVISION=3901
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: LIBINPUT_DEVICE_GROUP=3/46d/c539/111:usb-0000:00:12.2-1
E: MAJOR=13
E: MINOR=66
E: RATBAG_DRIVER=hidpp20
E: RATBAG_HIDPP20_INDEX=1
E: RATBAG_SVG=logitech-g900.svg
E: SUBSYSTEM=input
E: TAGS=:power-switch:
E: USEC_INITIALIZED=30793454780

It seems that there should be a 900 image already. 

`Installing /home/X/.cache/pacaur/libratbag/src/libratbag-0.9.900/data/default/logitech-g900.svg to /home/X/.cache/pacaur/libratbag/pkg/libratbag/usr/share/libratbag/default`

**Comment by cvuchener** [comment]
Here is a start: https://github.com/cvuchener/libratbag/blob/g900-svg/data/gnome/logitech-g900.svg

But I will need to know the numbers for every buttons and leds to make a proper svg. Use ratbag-command/ratbagctl/piper to get the info and try to guess what is what.

The g900 image is from the older theme, it is not used by piper. See issue #213 for missing SVG for the gnome theme.

**Comment by Hjdskes** [comment]
> It seems that there should be a 900 image already.

That's for the default theme, there is no G900/903 image for the GNOME theme. That's the issue here, see #213.

**Comment by Hjdskes** [comment]
Whoops, seems I got sniped! Reopened because you guys are making the SVG here.

**Comment by cvuchener** [comment]
The old image has the button labels. I could use that. But Logitech's website says 11 programmable buttons, the old svg has 12. Is the button under the mouse actually programmable? I don't see it on LGS screenshots.

I still need to know the numbers for the LEDs. Are the LEDs under the mouse configurable or do they only show battery status or something?

**Comment by kaymio** [comment]
Go with the 11 buttons, as the button on the underside is a switch for program presets. I couldn't really use piper yet but I don't think it has programmable program presets.

The three indicator LEDs have three functions. Showing the status of the chosen dpi settings (low - medium -high, or even in 5 steps) with a color that can be chosen for these LEDs. The second is for showing the battery status. In my case I've set it that the left button behind the wheel is switching dpi and by pushing the right one I get the battery status. 
The third function is to show in which pre-programmed the mouse is at the moment when the '12th' button on the underside is pressed.

Hope that this is helpful.

**Comment by cvuchener** [comment]
I know for the three led on the top. I was speaking of the mechanical switch with green and red color, that I mistook for a LED. So forget about that.

I will try with 11 buttons first.

@Hjdskes If I need to add the twelfth button, do you have any recommendations for a button under the mouse? Where to place the leader? What should be highlighted?

**Comment by Hjdskes** [comment]
@cvuchener I think @jimmac is better suited to answer that. Maybe just add a loose button in ghf bottom right corner for now with some kind of indication?

Do you know how logitech's software shows it?

**Comment by bentiss** [comment]
Just FYI, IIRC the button below the mouse is a regular button (remappable), but is not advertised as such. So the Windows UI doesn't allow to configure it IIRC. Right now, ratbagd will export it because it is described by the device, but we *might* not want to allow piper to configure it, so we can just leave this one out from the SVG

**Comment by jimmac** [comment]
For an underside I think we'd just do a little window ala LEGO manuals, rather than doing the whole mouse from the other side.

**Comment by cvuchener** [comment]
I updated the image and sent a pull request. @kudlatyamroth or @kaymio could you please test this? It is easy to forget or make mistakes with ids.

**Comment by bentiss** [comment]
I merged @cvuchener's PR now. Please test on the G903 so we can close this bug now :)

Thanks everybody for the quick fix

**Comment by kaymio** [comment]
I've tested piper with my G900, looks good, most things seem to work. There were two hickups:

1: Asigning any resolution change to a key doesn't seem to work. To asign battery status to any key is no problem, cycling through resolutions is.

2: To use the LEDs with pulse or cycle at a minimum of 100Hz seems somewhat fast.

I guess these are problems related to ratbagd and piper, not so much to libratbag. 

Thank you for responding so quickly. Thx all of you.

**Comment by kudlatyamroth** [comment]
same for me, resolution and double click not work, everything else is good
but main problem is fixed :)
there is no more svg error :)

**Comment by kaymio** [comment]
Please let me know when I can start the second round of testing.

**Comment by Hjdskes** [comment]
@kaymio with second round of testing you mean the resolution change special mappings and/or the double click special mapping? Please open separate issues for those.
