### ISSUE TITLE
Supply a default SVG where the image is missing?

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#307]
Next step for #306: it's a lot better to supply a fallback SVG file for devices that don't have one than bail out completely. Adding SVGs is the last thing to do when adding a device because it's just spit and polish, not a requirement for functionality.

So the main question here is: how do we supply the default SVG? Just send across the fallback SVG file and don't tell anyone? Or send an empty SVG and provide some extra query for the fallback file?

I'm tempted to go for the first option, it makes clients a lot easier.

**Comment by Hjdskes** [comment]
If you can transparently handle this in libratbag or ratbagd then that is probably the easiest. It prevents having to do error checking and requesting the default SVG in all clients.

**Comment by whot** [comment]
The main issue is that always supplying a fallback svg means we **prevent** the ability for any error checking in the clients. But I'm willing to defer that need until we do.

**Comment by Hjdskes** [comment]
Fixed in https://github.com/libratbag/libratbag/pull/306.
