### ISSUE TITLE
Issue building on Fedora 25

### ISSUE THREAD

**Issue by Adobe-Android** [libratbag/libratbag#309]
I have dependency issues of things that are already installed.
Native dependency 'libevdev' not found
Package libevdev-1.5.6-1.fc25.x86_64 is already installed.

**Comment by cvuchener** [comment]
You need the libevdev-devel package.

**Comment by Adobe-Android** [comment]
:+1:  Thanks! Might be a good idea to make note of this somewhere for future users.
