### ISSUE TITLE
Fix return values in ratbagd dbus methods

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/libratbag#316]
See https://github.com/libratbag/libratbag/pull/275#discussion_r136026896.

**Comment by Hjdskes** [comment]
I've started working on this one, and replacing the `return r;` at the end of setter methods (i.e., upon success) to `return 0;` is a matter of a search and replace.

However, what values do we return in case of errors? I.e. in the following case, what do we return?

```
r = <some libratbag function>
if (r < 0)
    return r;

<continue in case of success and return 0>
```

Likewise, what do we do with instances of `return sd_bus_message_append` and the like?

**Comment by whot** [comment]
What errors are we expecting here? afaict the only real error we can get are dbus errors - where we're screwed anyway - or programming errors when we try to append the wrong format or something. Those ones we can assert on.

**Comment by bentiss** [comment]
Given that we already need to have a signal from ratbagd telling "you screwed, I can not commit". How about the dbus methods always return the dbus status (as @whot said, either "you screwed in the arguments" or "something went wrong at the dbus level"), and if the libratbag return code is not null, then we emit the "BOO, pointing finger at you, please resync" signal while returning success?

**Comment by bentiss** [comment]
I guess we can close this one now?

**Comment by Hjdskes** [comment]
Well, there's still what I mentioned in https://github.com/libratbag/libratbag/pull/336#issuecomment-328616146:

> Also, this PR currently only changes those functions where we'd return r upon error. It does not, for example, check for errors in ratbagd-led where we didn't do that before either. I can add this if required.
