### ISSUE TITLE
probe does more than advertised

### ISSUE THREAD

**Issue by phomes** [libratbag/libratbag#333]
In src/libratbag-private.h we document the probe callback function as:

> Callback called while trying to open a device by libratbag.
> This function should decide whether or not this driver will
> handle the given device.
> 
> Return -ENODEV to ignore the device and let other drivers
> probe the device. Any other error code will stop the probing.

But that is not really what the function is used for today in most drivers. Instead it is a convenient place to do full initialization of the driver. This may involve several reads from the mouse to get all profile data, currently active profile/resolution, etc. 

Probing unknown devices is only used today for the HID++2.0 (and 1.0 but I think we have .device files for all relevant mice). All other drivers depend on the .device files and for them probing should not be needed. Probing also got less useful now that we require per-device SVGs before we really support the mouse for the users. 

Everything works fine of course. There is no bug to fix. I just find it confusing. Both reading the code and observing read_profile calls for a simple "ratbagctl list".

Do I just mention the description of the probe callback in the description? or should we rethink probing?

**Comment by whot** [comment]
I think changing the documentation to match reality is the best here.

> Probing also got less useful now that we require per-device SVGs before we really support the mouse for the users.

with the fallback.svg file that's not quite as urgent anymore now

**Comment by bentiss** [comment]
Yeah, the documentation is wrong. I chose to use .probe() to match the kernel behaviour. In the kernel .probe() does both the decision and the initialization. In libratbag, we forget to put the intialization bit. So changing the doc is the best thing to do.

**Comment by whot** [comment]
assigning to @phomes, you found it, you get to fix it ;)
