### ISSUE TITLE
hidpp20: reporting only 1 supported DPI resolution for G603

### ISSUE THREAD

**Issue by SonicFrog** [libratbag/libratbag#343]
I'm not sure about this but after some investigation it seems that libratbag incorrectly sets the number of configured resolution in a profile to the number of sensors in the mouse. 

https://github.com/libratbag/libratbag/blob/548a40dba677d1f5c45e86611b4dab3a070e7964/src/driver-hidpp20.c#L498

Removal of this line does not affect mice that were working with it, and fixes the one mouse I've encountered that is affected by this "bug"

**Comment by bentiss** [comment]
I guess we never saw this because feature 0x2201 was enumerated before 0x8100 on all the devices we have seen.

I must say I am quite confused by the feature 0x2201 and the number of sensors (does Logitech ever had a mouse with more than one sensor?). A proper fix, if there is a mouse with 2 sensors would be to check on the value of `num_resolutions` and only overwrite it if it is equal to 1 (or 0, but I _think_ we initialize it to 1).

**Comment by SonicFrog** [comment]
The thing is this value does not even need to be dynamic, it's not advertised at any point by the mouse in any feature. It's a constant value for every HID++2.0 mice that depends on their profile format (which has 5 slots to store resolutions. Which is basically how it's set in the HID++2.0 protocol implementation. 

https://github.com/libratbag/libratbag/blob/8440a36f92b5e28ff3f336c283c82ea4c01ae358/src/hidpp20.c#L1511

The way I see it this should be set to a default of 0, and be overriden to 5 when initializing the 2201 feature since it only makes to show customizable DPI if the mouse supports it.

**Comment by bentiss** [comment]
Problem is, the MX master supports feature 0x2201 but doesn't have hardware profiles. So we can not initialize it to 5 when we see 0x2201.

I am open to any solution, just adding some thoughts to it.

**Comment by SonicFrog** [comment]
Could this be something we can pass to the driver only for the G603 through the .device files?

**Comment by bentiss** [comment]
The less we put in .device, the better. I would prefer we fix 0x2201 once for all.

**Comment by SonicFrog** [comment]
Makes sense. I'll see what can I do this afternoon
