### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [libratbag/libratbag#35]
I would like to point out that identifiers like "[`__ratbag_find_hidraw`](https://github.com/libratbag/libratbag/blob/31dc1f47726fbca483f3bed8d7881434bdc22845/src/libratbag-hidraw.c#L198)" and "[`__test_probe`](https://github.com/libratbag/libratbag/blob/9b18b877a78bb35b381d1f9ac187b5a9ea2db8b6/src/driver-test.c#L115)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by whot** [comment]
heh, yes, we did talk about this today but didn't change the code yet. Please feel free to submit a patch/PR with a fix for this

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/libratbag/libratbag/commit/bf44465ff58e9c8cf6927ae8a473b2d0b6d95614 "Deletion of a few underscores").
