### ISSUE TITLE
100Hz LED as minimum is much to fast

### ISSUE THREAD

**Issue by kaymio** [libratbag/libratbag#350]
Setting the minimum frequency of a 100Hz for 'Breathing' or 'Cycling' is somewhat excessive as it results in a strobe effect.

Also when I apply changes to the LEDs the program crashes with:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 192, in callback_handler
    res = obj.call_finish(result)
GLib.Error: g-io-error-quark: Timeout was reached (24)

**Comment by bentiss** [comment]
Again, this is a piper issue. Please reopen in the piper project. (and I am closing this one here)
