### ISSUE TITLE
"Unknown" (-1) LED type causes ratbagctl crash

### ISSUE THREAD

**Issue by lrenaud** [libratbag/libratbag#364]
I'm just starting some tinkering with the G203 and one of the first things I've tried produces a crash in lratbagctl.

**Steps to reproduce:**
execute: ratbagctl led get event<#>

**Result:**
```
LED: 0 type: side, mode: cycle, rate: 8000, brightness: 255
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 2124, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ratbagctl", line 2121, in main
    f(r, cmd)
  File "/usr/bin/ratbagctl", line 1008, in func_led_get_all
    print_led(d, p, l, 0)
  File "/usr/bin/ratbagctl", line 797, in print_led
    types[l.type],
KeyError: 4294967295
```

**Suspected cause**
l.type on the LED object/structure is incorrectly converting signed int -1 to unsigned 4294967295 (2^32-1) in the _get_dbus_property call. Specifically the call to the DBusProxy object indicates that the expected container type for the "type" property is uint32 rather than int32, explaining the conversion.

**Comment by whot** [comment]
Put a printf into `hidpp20_color_led_effects_get_zone_info` and check what the value of `info->location` is being set to. We may have to add a new mapping here.
