### ISSUE TITLE
[hidpp10] What we need to know about devices

### ISSUE THREAD

**Issue by cvuchener** [libratbag/libratbag#37]
I am trying to make a list of things we cannot guess from the HID++ 1.0 protocol only.

Needed for correctly using the mouse protocol:
- Format/scheme for 0x63: scheme 1 and scheme 2 use the same report type, but we can guess that scheme 3 is to be used if the others fail.
- Format for the resolution (used by 0x63 or the profile) depending on the device it can be a list (G5, G9(?)) or conversion ratio (1/50 for G500s, G700s(?) or 17/400 for G500, G9x(?))
- Profile format: currently I know of three different formats: G9 and G500/G500s/G9x and G700s
- Maximum profile count

Some features are present/tolerated in the protocol but don't do anything. They won't prevent the driver from successfully communicating with the mouse, but the feature will appear broken to the user.
- Supported special functions: mapping a invalid special function to a button won't break the profile but the button won't do anything.
- G500(s) LEDs cannot change color despite the working feature (with both register command and profile)
- The actual number of buttons: profiles may have more buttons than physically present.
- Maybe other features that I don't understand enough to talk about (the "angle" thing in 0x63 and the values in 0x61, ...)

**Comment by phomes** [comment]
The number of buttons. While the profile in my G9 can hold 10 buttons the mouse only has 9. That is also the number of buttons that can be configured from LGS.

**Comment by whot** [comment]
The ability of each button - which ones can we assign to dpi +/-, which ones are just plain buttons, etc.

0x63 request: the actual value of the resolution when it's in the 0x80..0xFF range
0x63 request: I think the conversion ratio isn't one, the doc says it's an "index", so there's likely some hardcoded magic table for the device and for the G500s that just lists every resolution from 50..max. but if you look at the 0x63 scheme 1 resolution list, there are holes in there, so the G500 may do something similar here.

**Comment by cvuchener** [comment]
> The ability of each button - which ones can we assign to dpi +/-, which ones are just plain buttons, etc.

I don't know any button that is different from the other from the same device. But I forgot the special button functions: dpi+, dpi-, dpi cycle, profile cycle, battery status. The last three are from the G700s and do not work with the G500.

> 0x63 request: the actual value of the resolution when it's in the 0x80..0xFF range

That is the list I was talking about for the G5 and G9.

> 0x63 request: I think the conversion ratio isn't one, the doc says it's an "index", so there's likely some hardcoded magic table for the device and for the G500s that just lists every resolution from 50..max. but if you look at the 0x63 scheme 1 resolution list, there are holes in there, so the G500 may do something similar here.

It behaves like there is a conversion ratio, and unlike scheme 1 any value seems to be acceptable. I cannot reasonably make a dpi measurement for each value in order to check that and build the list.

**Comment by whot** [comment]
fwiw, with the update to the .ini style configuration data, we can put stuff like this into the device files and thus eliminate the need for querying it.

**Comment by cvuchener** [comment]
Nice, hidpp10 requires a lot of knowledge about the device. Because of #282, I think we will need to add the default profile page too. Although it could be known from the profile list, if it is correct.

**Comment by whot** [comment]
Feel free to add anything you need, just add it to the `[Driver/hidpp10]` section and go for it. Probably easier to add things and remove them later than to worry too much about what should and shouldn't go in there. It's all internal anyway.
