### ISSUE TITLE
Wrong button mapping in G700 profile

### ISSUE THREAD

**Issue by 11111010000** [libratbag/libratbag#372]
button set (using different software) to `resolution cycle down` gives output:
`Button: 7 type resolution cycle up is mapped to 'resolution cycle up'`
while setting button to `resolution cycle up` gives:
`Button: 7 type resolution cycle up is mapped to 'UNKNOWN'`

edit:
values in [src/hidpp10.c](https://github.com/libratbag/libratbag/blob/master/src/hidpp10.c#L1613,L1618) are correct. Problem is probably just with formatting output

**Comment by whot** [comment]
this bug is coming up to 2 years now - any chance this got fixed in the various other bits that we implemented since?

**Comment by 11111010000** [comment]
Looks like it's fixed.
