### ISSUE TITLE
hid++20-returned LED location is random

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#377]
We cannot rely on the correct `location` value returned in `hidpp20_color_led_effects_get_zone_info`. It currently looks like it's off by one compared to the specs but in reality it is not reliable. We need to add this to the `.device` files to have the LED type correct.

- G303: 1 = under logo, 2 = the one on both sides
- G603: LED under the mouse reports primary (1), DPI LED reports logo  (2)
- G703: Logo LED reports Primary, Wheel LED reports Logo
- G903: Logo LED reports primary, DPI LED reports logo

cc @SonicFrog

**Comment by cvuchener** [comment]
It looks ok for mine:
 - G502 spectrum: dpi/profile led = primary (1), logo led = logo (2)

Does it always report 1 and 2, whatever the mouse?

**Comment by whot** [comment]
seems to be, we'd need a mouse with a real side LED to check if those send 4 or 5 as location

**Comment by SonicFrog** [comment]
> Does it always report 1 and 2, whatever the mouse?

The G302 looks much like the G303, though it reports both its LEDs as primary (1). It seems we'll have to map each LED to a type by hand in the `.device` files
