### ISSUE TITLE
Logitech wireless mice are not identified properly

### ISSUE THREAD

**Issue by SonicFrog** [libratbag/libratbag#380]
All wireless Logitech gaming mice use the same receiver (046d:c539). This receiver is a variant of the unifying receiver except it supports pairing with only one device. 

Currently libratbag names all mice using this receiver as Logitech USB Receiver and uses the G900 svg. In short this means that the G403, G603, G703, G903 use the wrong SVG and are misnamed

![2017-10-06-124057_664x244_scrot](https://user-images.githubusercontent.com/3202531/31274535-9e051bec-aa93-11e7-8619-9d676b0f58fe.png)
 
This is fixable by using the receiver during device discovery to ask the paired device to give its name and product id.

**Comment by qidydl** [comment]
Plugging in the mouse directly in order to use Piper is a fairly easy temporary workaround, maybe that could be noted in documentation or a quick message could be displayed in the UI?
