### ISSUE TITLE
rival 310: Driver is missing name

### ISSUE THREAD

**Issue by soredake** [libratbag/libratbag#407]
oct 18 20:01:13 gentoo-main ratbagd[21336]: ratbag error: libratbag bug: Driver is missing name
oct 18 20:01:13 gentoo-main ratbagd[21336]: ratbag error: SteelSeries SteelSeries Rival 310 eSports Mouse: driver 'steelseries' does not exist

latest from libratbag git

**Comment by phomes** [comment]
does it work if you run it as 
`builddir/ratbagctl.devel list --keepalive`

**Comment by soredake** [comment]
Just this:
```
❯ sudo work/libratbag-9999-build/ratbagctl.devel list --keepalive
ratbag error: libratbag bug: Driver is missing name
ratbag error: libratbag bug: Driver is missing name
ratbag error: libratbag bug: Driver is missing name
ratbag error: libratbag bug: Driver is missing name
ratbag error: libratbag bug: Driver is missing name
ratbag error: libratbag bug: Driver is missing name
ratbag error: libratbag bug: Driver is missing name
```

**Comment by bentiss** [comment]
This is weird. This error log happens when there is an issue with a driver, which should be seen on our boxes too whether or not we own the device.

Could you paste the output of the full compilation (and check that you are actually running master, and have no changes compared to upstream)?

**Comment by whot** [comment]
I also recommend running `sudo valgrind ./build/ratbagd`, if there's a memory corruption somewhere valgrind should show it.

**Comment by soredake** [comment]
@bentiss	
>have no changes compared to upstream

Just this
```
# no python3 module on gentoo, https://github.com/mesonbuild/meson/issues/2504
sed -i "s/dependency('python3'),/dependency('python-3.4'),/g" meson.build
```

Build log:
[build_log.zip](https://github.com/libratbag/libratbag/files/1398704/build_log.zip)

I use https://github.com/InBetweenNames/gentooLTO, just for note.

**Comment by Hjdskes** [comment]
Why did you suddenly close this? Is the issue fixed meanwhile?

**Comment by Hjdskes** [comment]
Thanks, likely that an update fixed it in that case.

**Comment by justinkb** [comment]
Chiming in here a year later to say this was almost certainly caused by use of the gold linker instead of the standard bfd
