### ISSUE TITLE
MX Master 2S support

### ISSUE THREAD

**Issue by mskarbek** [libratbag/libratbag#419]
What do you need to add support for Logitech MX Master 2S?
Currently ratbag reports some info but Piper doesn't recognize that mouse.
I would like to contribute time/testing/code(?) to make this happen, just point me to the right direction. :)
```
$ sudo ratbag-command info /dev/input/event17
Device 'Logitech MX Master 2S'
Capabilities: res btn-key led
Number of buttons: 8
Number of leds: 2
Profiles supported: 1
  Profile 0 (enabled) (active)
    Resolutions:
      0: 1000dpi @ 0Hz (active)
    Button: 0 type left is mapped to 'button 1'
    Button: 1 type right is mapped to 'button 2'
    Button: 2 type middle is mapped to 'button 3'
    Button: 3 type side (backward) is mapped to 'button 4'
    Button: 4 type extra (forward) is mapped to 'button 5'
    Button: 5 type unknown is mapped to 'none'
    Button: 6 type wheel ratchet mode switch is mapped to 'ratchet mode switch'
    Button: 7 type unknown is mapped to 'none'
    LED: 0 type: logo, mode: off
    LED: 1 type: logo, mode: off
```

**Comment by sheepdestroyer** [comment]
same here, 
I created a .device by copying the MX Master' one and changing the usb ID but can not get it to be recognized : 

[sheepdestroyer@sheepora-X230 libratbag]$ ratbagctl list
No devices available.
[sheepdestroyer@sheepora-X230 libratbag]$

**Comment by Lawstorant** [comment]
Well, MX Master 2S uses newer HID++ 4.5 protocol

**Comment by bentiss** [comment]
Actually, HID++ 4.5 is still HID++ 2.0, but Logitech uses the major/minor numbers to convey more information. It should still be supported.

For the MX Master (or later) to be supported in libratbag, you need the master branch of libratbag that contains #415. Not sure how Piper will export it though.

Note that even if libratbag will now shoe the mouse, I am not sure what can be configured, as the mouse doesn't have hardware profiles, so things may be not very well supported.

**Comment by Hjdskes** [comment]
> Not sure how Piper will export it though.

If it isn't any special behavior (which on a quick glance it doesn't seem to be) it should just work. Otherwise, please open an issue for Piper.

**Comment by sheepdestroyer** [comment]
I built / installed last master of both libratbag and piper on Fedora 28

I have the following profile installed (maybe it's and old test profile, dating back from my previous tries? Could that be a source of problem?) : 
````
$ ll /usr/share/libratbag/logitech-MX-Master-2s.device
-rw-r--r--. 1 root root 148 22 nov.   2017 /usr/share/libratbag/logitech-MX-Master-2s.devic

$ cat /usr/share/libratbag/logitech-MX-Master-2s.device
# Logitech MX Master 2s
[Device]
Name=Logitech MX Master 2s
DeviceMatch=usb:046d:c52b;bluetooth:046d:b019
Driver=hidpp20
Svg=logitech-mx_master.svg
````

Running 
````
$ sudo ratbagctl --verbose list
No devices available.
````

I tried both with the Logitec Unifying connector and with Bluetooth
Running ratbagd as a systemd service  is not better : 
````
● ratbagd.service - Daemon to introspect and modify configurable mice
   Loaded: loaded (/usr/lib/systemd/system/ratbagd.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-07-16 22:13:47 JST; 9min ago
 Main PID: 3423 (ratbagd)
    Tasks: 1 (limit: 4915)
   Memory: 1.0M
   CGroup: /system.slice/ratbagd.service
           └─3423 /usr/bin/ratbagd

juil. 16 22:13:47 sheepora-X230 systemd[1]: Starting Daemon to introspect and modify configurable mice...
juil. 16 22:13:47 sheepora-X230 systemd[1]: Started Daemon to introspect and modify configurable mice.

````
Unplugging / re-plugging the connector, or disconnecting / reconnecting Bluetooth is still silent that way too.

Before opening an issue for Piper, I guess I should first get to have ratbag see my device ?

**Comment by whot** [comment]
yeah, piper relies on ratbag for all its data, so if ratbactl doesn't see the device, piper cannot either. Both use the same interface.

Run `ratbagctl -vvv list`, iirc that's the highest level of verbosity we have. And make sure the DeviceMatch line matches the vid/pid of the device (use evtest to double-check)

**Comment by FFY00** [comment]
@whot the command is `./ratbagctl.devel -vvv list` and needs to be run the build directory. If you really want to get the debug information via `ratbagctl` you need to start the deamon with `-vvv` instead. I had this problem when trying to debug my mouse.

**Comment by sheepdestroyer** [comment]
It seems there is a detection problem on ratbag 's side.

evtest returns : 
````
...
/dev/input/event5:	Logitech MX Master 2S
...
Select the device event number [0-18]: 5
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x46d product 0x4069 version 0x111
Input device name: "Logitech MX Master 2S"
...
````

I can confirm values with solaar which returns the following information : 
````
Unifying Receiver
Path         : /dev/hidraw7
USB id       : 046d:c52b
````
````
MX Master 2S
Index        : 1
Wireless PID : 4069
Protocol     : HID++ 4.5
````
So I also tried (whithout success) changing the previously mentioned logitech-MX-Master-2s.device from : 
```` DeviceMatch=usb:046d:c52b ````  : Unifying Receiver
to 
```` DeviceMatch=usb:046d:4069 ````  : MX Master 2S

With ratbagd service running with --verbose, disconnecting reconnecting the receiver, I only get : 
````
   CGroup: /system.slice/ratbagd.service
           └─18300 /usr/bin/ratbagd --verbose

juil. 20 23:41:06 sheepora-X230 systemd[1]: Starting Daemon to introspect and modify configurable mice...
juil. 20 23:41:06 sheepora-X230 systemd[1]: Started Daemon to introspect and modify configurable mice.

````

While ratbagd is running in verbose mode, I tried : 
````
[builddir]$ sudo ./ratbagctl.devel -vvv --verbose list
ratbag debug: driver match found: Test driver
test_device: Test device                     
[builddir]$ 

[builddir]$ sudo ./ratbagctl.devel -vvv --verbose info /dev/input/event5
ratbag debug: driver match found: Test driver
Unable to find device /dev/input/event5
[builddir]$ 
````

**Comment by codedcosmos** [comment]
Sorry to be a nuisance but what is the progress on adding support to the MX Master 2S? What need's to be done? How can I help?
