### ISSUE TITLE
Issues building with meson

### ISSUE THREAD

**Issue by jbladder** [libratbag/libratbag#427]
I must admit I am very green when it comes to linux still. This may completely be my own fault and not an actual issue, but I am having trouble identifying that.

I did have to pull down meson as I did not have it installed and might have missed some vital step or dependency.

I am running on OpenSuse Tumbleweed. I attempted to install from repository with zypper and it shows installed but doesn't start the ratbagd service as far as I can tell and if I do manually says it does not exist.

If I use the instructions here to do manually I get the following error:

(sorry if there is a protocol for posting error messages that I didn't use here)

_sudo meson builddir --prefix=/usr/
The Meson build system
Version: 0.43.0
Source dir: /home/josh/Downloads/libratbag
Build dir: /home/josh/Downloads/libratbag/builddir
Build type: native build
Project name: libratbag
Native C compiler: cc (gcc 7.2.1)

Meson encountered an error in file meson.build, line 1, column 0:
Unknown compiler(s): ['c++', 'g++', 'clang++']
The follow exceptions were encountered:
Running "c++ --version" gave "[Errno 2] No such file or directory: 'c++': 'c++'"
Running "g++ --version" gave "[Errno 2] No such file or directory: 'g++': 'g++'"
Running "clang++ --version" gave "[Errno 2] No such file or directory: 'clang++': 'clang++'"_

Am I just missing a bunch of dependancies that I am just to ignorant still to realize? Any help or tips would be appreciated. I am trying to use a g300s by the way and my reading seems to show that it is supported. Sorry if this is not the place to report this. Thanks for the time.

**Comment by whot** [comment]
fwiw, you should never need to run meson as root, the only thing requiring root is the `ninja install` process when installing into system directories.

Otherwise, the problem appears to be that you're missing `g++`, the C++ compiler. Package `gcc-g++` on Fedora.

**Comment by jbladder** [comment]
thanks your tip here helped me figure it out discover what I needed for
both this and piper. got it going. gotta work with getting the ratbagd
service running at start up right.

thanks.

**Comment by whot** [comment]
we have a wiki but it lacks information, especially the more user-focused things like how to build libratbag etc. We'd be more than happy to give you editing rights if you want to help fill those missing bits in.

**Comment by SebastianPfliegel** [comment]
@whot, I'd love to help with the documentation. Currently only few things are documented and most of it is scattered all over various Github projects (README.md, wiki, API documentation on libratbag.github.io, device-notes). I think it would be nice to have everything in once place. What's your opinion?

**Comment by whot** [comment]
@SebastianPfliegel I agree, one place would be great but it's not always suitable. Or rather - linking between the various items is sufficient. API documentation is for people that want to programmatically access libratbag/ratbagd and should be separate. For anything that relates to installing and basic FAQ a wiki is best. As long as we link from the wiki to the API documentation, we should be fine I think.

The readme is mostly there because it was the fastest way to plonk down a few notes but it's not intended to answer all questions. Much of the stuff in the readme can be moved to the wiki.
