### ISSUE TITLE
G403 configuration changes fail with ERR_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by Budovi** [libratbag/libratbag#428]
Hi,

I've recently got G403 and was trying to make it work with libratbag. From what I've seen this mouse should be supported but I'm unable to commit any changes.

With the library and ratbagctl I'm able to read pretty much whole configuration and it seems to be correct (maybe except "disabled" profile, but not sure what exactly the terminology is):
```
# ratbagctl info event3
event3 - Logitech G403 Prodigy Gaming Mouse
               SVG: /usr/share/libratbag/gnome/logitech-g403.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, disable-profile, led
 Number of Buttons: 6
    Number of Leds: 2
Number of Profiles: 1
Profile 0: (disabled) (active)
```
```
# ratbagctl led get event3
LED: 0 type: logo, depth: rgb, mode: breathing, color: 005a66, duration: 20000, brightness: 255
LED: 1 type: side, depth: rgb, mode: breathing, color: 005a66, duration: 20000, brightness: 255
```
When I try to change anything, I get the invalid argument error:
```
# ./builddir/ratbag-command dpi set 800 /dev/input/event3 -v
ratbag debug: Logitech G403 Prodigy Gaming Mouse is device '/dev/hidraw2'.
ratbag debug: Logitech G403 Prodigy Gaming Mouse is device '/dev/hidraw3'.
ratbag debug: report ID 01
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: 'Logitech G403 Prodigy Gaming Mouse' is using protocol v4.2
ratbag debug: device has adjustable dpi
ratbag debug: device is at 3200 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has 4 report rates
ratbag debug: device has color effects
ratbag debug: device has onboard profiles
ratbag debug: device has configurable mouse button spy
ratbag debug: driver match found: Logitech HID++2.0
ratbag debug: dictionary: 00 01 00 00 ff ff 00 00 ff ff ff ff ff ff ff ff
ratbag error:     HID++ error from the device (255): ERR_INVALID_ARGUMENT (02)
Could not commit changes to the device
```
Some version details:
`git describe` -> `v0.9.900-218-g0f5beb6`
`uname -a` -> `inux manjaro-ntb 4.14.2-1-MANJARO #1 SMP PREEMPT Fri Nov 24 11:15:23 UTC 2017 x86_64 GNU/Linux`
Mouse firmware version: `108.2.13`

Sorry if I overlooked some important information. I'm happy to assist with further debugging.
Thanks for your work!

**Comment by SonicFrog** [comment]
I'll see if I can get my hands on a G403 and have a look.

**Comment by SonicFrog** [comment]
Just confirmed I can reproduce it, I'll fix it this week.

**Comment by SonicFrog** [comment]
Would you be able to upload the log from running ratbagd --verbose=raw and using ratbagctl dpi set 800 ?

**Comment by Budovi** [comment]
Sure, no problem.

Complete output:
https://gist.github.com/Budovi/ea4e1ca38d565dfbef5903786cd130e2

The output related to the command starts at [line 260](https://gist.github.com/Budovi/ea4e1ca38d565dfbef5903786cd130e2#file-ratbagd_log-txt-L260).

**Comment by cvuchener** [comment]
This look like #280. The only profile written is disabled.

**Comment by Budovi** [comment]
Interesting point. I've got that bug in my search results when I was investigating the problem initially but haven't seen the connection back then. As I've mentioned, I had no clue what "disabled" profile means in terms of use.

I should point out there is no profile section in LGS present that would contain checkboxes – the G403 mouse does have a single profile so there is probably no point in including them.

I've managed to enable the profile using `ratbag-command`, I'll create a new issue about that in a minute. **Enabling the profile has solved the problem**, I've managed to change dpi and some led settings successfuly.

Even though I have no idea what caused this weird state (afaik I bought it like this, possibly a firmware update, maybe @SonicFrog  knows better) but it also resolved an issue regarding the illumination I was discussing with logitech support. **I'm leaving this issue open for now, please consider adding a warning when the "active" profile is also "disabled", or when trying to change the settings of a disabled profile.** "Invalid argument" is not really a user-friendly error, especially if it can be easily solved.

**Comment by SonicFrog** [comment]
After some more investigation it seems this happens everytime you disable the last enabled profile or the active profile on at least 4 different Logitech mice.
