### ISSUE TITLE
Dependency "python3" not found

### ISSUE THREAD

**Issue by lackodan** [libratbag/libratbag#431]
I'm trying to install this library on Ubuntu 16.04, but I can't seem to sort out the dependencies. I've managed to locate the correct packages for most of the deps, e.g. libudev-dev for udev (are these documented anywhere?), but now I'm stuck at Python 3. When I clone the project from Github, make a new dir builddir and run `meson builddir --prefix=/usr/` as specified in the README, I get the following error message:

```
Meson encountered an error in file meson.build, line 525, column 0:
Dependency "python3" not found
```

I have installed Python 3 through Anaconda:

```
$ python --version
Python 3.6.3 :: Anaconda, Inc.
```

Can anyone please help me out?

**Comment by SebastianPfliegel** [comment]
I agree it's a bit confusing. Python3 is not dependency, but the development files for it. Try the package python3-dev. This should do the trick!

**Comment by lackodan** [comment]
Oops, I don't know how I missed that after adding "-dev" to almost all other dependencies... That did indeed do the trick! Should I update the README with the names of the dependencies I had to install (and do a PR)?

**Comment by SebastianPfliegel** [comment]
Glad it worked out for you! In the coming days I will try to update the documentation (READMEs and Wiki), especially the parts for developers.

**Comment by lackodan** [comment]
@SebastianPfliegel: Now that we're on the subject, is there any way someone with not much low-level programming experience (i.e. very rudementary C/C++) could contribute to this project? I have two gaming mice I could theoretically add support for: a SteelSeries Rival (original version) and a Roccat Kova. I'd love to get involved, but I have no idea how to reverse-engineer an input communication protocol or generate a device file. 

Also, I realize this is probably not the best place to ask this question. Should this go on the input-tools mailing list instead?

**Comment by SebastianPfliegel** [comment]
I'm a C/C++-noob myself. I try to contribute to this project myself to gain some C-skills and to improve the gaming experience on Linux.

Writing a device file is the easiest part. The device files are listed here: https://github.com/libratbag/libratbag/tree/master/data/devices/

Your file for the Roccat Kova could look like this:

```
[Device]
Name=Roccat Kova
DeviceMatch=usb:MYUSB
Driver=roccat
Svg=roccat-kone-xtd.svg
```

With lsusb you can find the identifier of the mouse. Issue #421 answers my questions regarding debugging and the device files. Hope some of the answers will help you, too. Once you're stuck just open another issue and ask your questions.

**Comment by lackodan** [comment]
Awesome, that is exactly my motivation for wanting to contribute. Thanks for the tips! I'll look into it as soon as I can.

So the issue tracker is the best place for any communication about this project?

**Comment by SebastianPfliegel** [comment]
I'd say so. @whot, @bentiss: correct me if I'm wrong.

**Comment by bentiss** [comment]
> So the issue tracker is the best place for any communication about this project?

Yes, definitively. We can not guarantee a prompt answer (most of the devs are side tracked at the moment), but this is where we can discuss things. Do not hesitate to also send a PR, even in a bad shape. Just add the tag `WIP - do not merge` and this will tell us that you don't want the code to be merged but discussed.

Regarding the README, our main problem is that we tend to forget to update it when dependencies change. However, the `circle.yml` file is a the safe place where all the building dependencies are listed: it's our CI script, and if we forget to update it, the tests will fail :)

Ideally, the README should point to this file so people can have a look themself (or there can be some automatic import from one file to the other)

**Comment by lackodan** [comment]
Sounds great. I'm very impressed with the response time so far, but don't worry, I know how it feels to be side tracked. I'll be very happy if I will have contributed a single line before the end of the year. ;)

**Comment by phomes** [comment]
@lackodan I wrote the driver for the two steelseries mice already supported (rival 310 and kinzu v2). I can work with you to add support for the rival if you wish.
