### ISSUE TITLE
Build error with ninja

### ISSUE THREAD

**Issue by XeVile** [libratbag/libratbag#432]
It built the first 72 files without errors however it choked at the 73rd. I lost that output, but running `ninja -C builddir` again shows the same error output. Can't seem to build. Compiled without any errors, but I can't seem to get through this one.

``ninja: Entering directory `builddir'
[1/1] Linking target _libratbag.so
FAILED: _libratbag.so 
cc  -o _libratbag.so 'libratbag@sha/libratbag@sha_libratbag.c.o' '-L/usr/local/lib' '-Wl,--no-undefined' '-Wl,--as-needed' '-shared' '-fPIC' '-Wl,-soname,_libratbag.so' 'libutil.a' 'libhidpp.a' 'libratbag.a' 'libutil.a' 'libhidpp.a' 'libutil.a' 'libhidpp.a' 'libutil.a' 'libhidpp.a' 'libshared.a' '-ludev' '-levdev' '-lglib-2.0' '-lpython3.6m' '-ludev' '-levdev' '-lglib-2.0' '-ludev' '-lm' '-ludev' '-levdev' '-lglib-2.0' '-ludev' '-lm' '-ludev' '-lm' '-ludev' '-levdev' '-Wl,-rpath,/home/xevile/src/libratbag/builddir/'  
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
``

**Comment by SebastianPfliegel** [comment]
Are you trying to compile the sources of a release or from the current master branch?

**Comment by XeVile** [comment]
The current master branch.

**Comment by bentiss** [comment]
The failure happens at compiling the python to C SWIG wrapper.
The thing that worries me is that it tries to link against `/usr/local/lib/libpython3.6m.a`. Did you install from sources your python-3 development environment?

**Comment by XeVile** [comment]
Yes, it was from the sources. However, so far none of the other applications using python have had a problem so far. Is this issue due to Python 3.6?

**Comment by bentiss** [comment]
The issue is you can not embed the code in a library that uses `-fPIC` if libpython3.6m.a was not compiled with `-fPIC` either. At least that's how I understand the error message.

Any reasons you would not use your distributed provided python development package? Here, if you need to use your own version, the solution is to rebuild the devel package with -fPIC.
Looking at other people having the same issue (https://github.com/pytorch/pytorch/issues/997 for instance), you need to set `--enable-shared` when building python

**Comment by MostHated** [comment]
Sorry to necro an old issue, but I am getting this same error, though I am not quite sure what the resolution is? I don't recall having manually built python anytime in the recent past (or since I have been using this current OS (Pop_OS! 19.04)). Any suggestions on how I might go about resolving this?

A sample of the errors are as follows:

```shell
ninja: Entering directory `builddir'
[1/1] Linking target _libratbag.so.
FAILED: _libratbag.so
cc  -o _libratbag.so 'libratbag@sha/meson-generated_libratbag.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,_libratbag.so libutil.a libhidpp.a libratbag.a libshared.a /lib/x86_64-linux-gnu/libudev.so /usr/lib/x86_64-linux-gnu/libevdev.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so /usr/lib/x86_64-linux-gnu/libgio-2.0.so /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/local/lib/libpython3.6m.a -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/home/mosthated/_dev/github.com/libratbag/builddir/
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_PC32 against symbol `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(boolobject.o): relocation R_X86_64_PC32 against symbol `_Py_FalseStruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(bytearrayobject.o): relocation R_X86_64_PC32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
 ------ A bunch more of these followed by:

/usr/bin/ld: /usr/local/lib/libpython3.6m.a(parser.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

```

**Comment by whot** [comment]
Looks like the same issue as above and this looks like a distribution issue, i.e. the  package that provides `/usr/local/lib/libpython3.6m.a` doesn't build with `-fPIC` so we can't build a shared lib against it. That is ... odd. But I'm claiming that's an issue with the popos package here.

**Comment by MostHated** [comment]
Is there some way I can make it build with another version of python by chance?

**Comment by whot** [comment]
I guess you can download the actual python sources and start from there but I have no experience with that. or, better, disable those things in `meson.build` since you don't need them as normal user, only to debug a device. anything south of `swig = ...` to the `output files` marker should do.
