### ISSUE TITLE
Sensitivity is unusably high and non-configurable on Rival 310

### ISSUE THREAD

**Issue by ahstro** [libratbag/libratbag#436]
I just tried configuring my Rival 310 using libratbag (through Piper). All I changed was trying to set the scroll LED to solid orange and turning the SteelSeries logo off. The result I got was both LEDs turning off and the sensitivity going through the roof. Playing around with sensitivity or resolution in Piper does not change anything, nor does clicking the resolution button on the mouse itself.

**Comment by phomes** [comment]
That is strange. I tested on mine again and I do not see any problems. Setting the LEDs work and it picks up the DPI set in Piper. Note that we cannot get the current resolution already on the mouse, so Piper will always start with some default settings. But that does not explain why the LEDs do not set correctly.

One theory could be different versions of firmware on our mice. I am working on a way to show the current version.

**Comment by phomes** [comment]
I ran into a similar issue when working on support for the Sensei 310. I had to do a firmware update to get it working. An important thing to note is that it was also not working properly with steelseries own software. They pop up a message to install the "critial firmware update".

**Comment by phomes** [comment]
When the mouse is detected and the driver is loaded we normally will query the mouse to get the current onboard settings. This seems to not be possible on steelseries. I have not found a way yet at least. So instead the idea is that the client (ratbagctl, piper, etc) will have the responsibility of storing the last configuration on disk and load that into the driver. This part is not yet implemented, so we always fall back to the default values that I arbitrarily chose. The two resolutions are set to 800 and 1600 DPI.

We also have dirty flags on parts of the ratbag profile. E.g. a LED or button will have a dirty flag to indicate whether it has been changed. We use these to skip setting parts that have not been changed. However, the resolutions do not have a dirty flag to set, so we always have to set them when we make any other change. That is why changing a LED will also happen to reset the resolution.

So we could solve this in three ways. Find a way to query the device. Implement the on disk storage of settings. Or by adding a dirty flag for the resolution so we can skip them.

It would be great if you want to tackle one of them. For the dirty flags you can see the sturcts here:
https://github.com/libratbag/libratbag/blob/master/src/libratbag-private.h#L251
ratbag_resolution does not have a dirty flag, while ratbag_led just below does.

**Comment by FFY00** [comment]
I'll try to add the dirty flag but that's not the disk storage of settings should also be implemented.

**Comment by phomes** [comment]
Yes, the dirty flag will only help for the very first write where we do not have any settings on disk to start from.

**Comment by FFY00** [comment]
@phomes can you explain me what is happening at https://github.com/libratbag/libratbag/blob/d1918a063c149c81243f8b553adff54c675fcfdc/src/libratbag.c#L1227 and https://github.com/libratbag/libratbag/blob/d1918a063c149c81243f8b553adff54c675fcfdc/src/libratbag.c#L1248. Should I set the resolution's dirty flag to true?

**Comment by FFY00** [comment]
@phomes done! Is there anything else that I could help with?

**Comment by danielfpferreira** [comment]
I'm also experiencing this issue but with a slightly different behavior. 
If I change one of the resolutions the other is the one that gets very high and the resolution button still works

**Comment by jdittrich** [comment]
same problem here (libratbag 0.9.905). Glad to help with log output or whatever is needed (I'm no C-dev though)

**Comment by FFY00** [comment]
Something weird is happening with the DPI Step, it holds a wrong value at the time the buffer is sent.

**Comment by FFY00** [comment]
Please confirm this is fixed in https://github.com/libratbag/libratbag/pull/709.
