### ISSUE TITLE
Request: Retain modalias match in device data

### ISSUE THREAD

**Issue by ikeydoherty** [libratbag/libratbag#442]
Currently the device data provided is locked to the vendor/product portions in the DeviceMatch INI key.
In Solus we're now [reconstructing a modalias](https://dev.solus-project.com/source/piper/browse/master/files/mkmodaliases.py) match from this file to enable [automatic installation](https://solus-project.com/2018/01/26/linux-driver-management-1-0-released/) of `piper` for users with supported devices.

In an ideal world it would be better if we had the true modalias lines (`hid` `bluetooth` `usb`) so that we can attest to their accuracy.

As an example our modalias file contains lines like this when extracted from the `*.device` files:

```
alias bluetooth:v046D*B012* piper piper
alias usb:v046D*101B* piper piper
alias usb:v046D*1028* piper piper
```

Obviously these are a bit moody but they do the job. In an ideal world the device files would contain a mostly unused section containing the real modaliases so we can extract them and have correct matches. Cheers for your consideration :)

**Comment by whot** [comment]
honestly, my first answer her is no. simply because the .device files are not stable API and I don't want anyone relying on any specific key in those files. If tomorrow we decided that .ini files aren't good enough and we need xml, then that shouldn't matter to anyone.

This would be better solved by a tool that hides the device files away and spits out the formats you need. That way we could also test it easier and make sure that the output never changes whenever we mess with the device files.

**Comment by ikeydoherty** [comment]
For me I'm not really fussed if you change the format or not, I'm just asking that you expose the modaliases that your software **supports** so we can make it readily available for folks who need it.

> This would be better solved by a tool that hides the device files away and spits out the formats you need.

I'm already doing that, as I said I don't care /where/ it comes from, just that the data is present somewhere :) Root issue here is discoverability, and having to install libratbag to know whether libratbag will support your hardware.

**Comment by bentiss** [comment]
How about you simply sendind a PR with your script, integrated in the `meson.build` file in a way this gets published when doing a build (or even a push on master with the CI, we already generate the doc this way, it should not be that hard to generate one more file).

As @whot said, we do not want external dependencies on our internal files (if it doesn't hurt you, it will to someone else, and then the format starts being ABI, and we can't change it anymore). The other problem I can see is that none of the core developers will use this feature (we just install the tool :-P) so it's rather difficult for us to get it right and make sure it doesn't get deprecated.

**Comment by whot** [comment]
Closing, it's been a year...
