### ISSUE TITLE
G600 support?

### ISSUE THREAD

**Issue by gandalf3** [libratbag/libratbag#445]
I see that the G600 is not present in data/devices, and I assume that means it is not currently supported.
I have a G600 and would be happy to help test, or help with whatever might be needed to add support.

I also saw that according to https://github.com/libratbag/libratbag/pull/104 the G300 driver seems similar to G600. How similar are they? Should creating a profile with the G300 driver Just Work™?

**Comment by phomes** [comment]
The G600 uses a similar protocol, but they are not 100% identical. I will be happy to attempt to add the support in the driver if you will test and verify that it works.

Other than the driver we also need to create a .SVG for the device. It would be a great help if you could work on that. You need to learn a few basic things in inkscape, but it is fairly easy to figure out. There are existing SVGs in data/gnome. You can start by trying to adjust one of them to look like the G600.

**Comment by gandalf3** [comment]
I have some experience with inkscape already; I can definitely handle the SVG :)

**Comment by gandalf3** [comment]
I've opened a PR for the SVG here: https://github.com/libratbag/libratbag/pull/446

**Comment by Faalagorn** [comment]
My wife uses G600 too, while I have G500 lying around for testing that I can confirm it works. I'll gladly help testing this too :). I really like the SVG @gandalf3 did, but if any more help is needed, we can help as well, as my wife have the mouse and decent drawing skills :P.

I originally thought it was being worked on, seeing the [note in here](https://libratbag.github.io/device-notes/G600.html) and @bentiss being checked out [as device owner](https://libratbag.github.io/device-notes/index.html) there and just some showstopper is blocking it, but I'm glad to hear it might be doable.

Let us know if you need any future info!

**Comment by Rikitik** [comment]
I would like to add that i'm looking forward to this mouse being supported too, is there any ETA?

**Comment by phomes** [comment]
I have a driver that is very close to being ready for review/testing. Maybe during the weekend.

**Comment by Rikitik** [comment]
Awsom, i'm willing to test and maybe eventually debug it, i saw your presentation in Fosdem on youtube it was very interesting i may wanne try sniffing out some mouse/keyboard stuff with wireshack, but i'm New to linux so setting stuff up may take a while

**Comment by phomes** [comment]
A driver for the G600 landed in #496. @Rikitik if you want to help with improving the driver then you can run ratbag with full debug info. This will write out debug messages about parts of the profile messages that are still not understood. You can get the debug info by starting it with `-vvv` like:
`ratbagctl.devel list -vvv --keepalive`
