### ISSUE TITLE
installing libratbag

### ISSUE THREAD

**Issue by kpalczewski** [libratbag/libratbag#447]
Hi,

I'm having trouble installing this software.
I managed to get the latest meson version (0.44), install dependencies, install programs that weren't able to execute (swig, valgrind), but still i'm unable to install it.
The error I'm stuck at is this:
Meson encountered an error in file meson.build, line 542, column 0:
Dependency "python3" not found

I have python3:
python3 --version
Python 3.5.2

Can you tell me how can I fix this?

Thanks in advance,
Kamil

**Comment by Hjdskes** [comment]
You probably need the development package. I don't know what distro you have, but it's likely called something along the lines of `python3-dev`

**Comment by kpalczewski** [comment]
it was it. I really wish it was more clear on installing part. There are more dependencies to install than the script checks.

**Comment by SebastianPfliegel** [comment]
You can check [circle.yml](https://github.com/libratbag/libratbag/blob/master/circle.yml) for the dependencies. I might update the [wiki entry](https://github.com/libratbag/libratbag/wiki/Building-from-source) to make it more clear on what to do. Hope *libratbag* works for you :)
