### ISSUE TITLE
List of supported devices

### ISSUE THREAD

**Issue by rugk** [libratbag/libratbag#450]
Do you plan to setup a website (GitHub Pages would be sufficient), where one can see all supported devices and how good they are supported.

I think for Linux user's, who want to buy a new device this may be very useful in order to choose one, where they can expect good support (in the future).

I know one can look into the source code and  find some names, but this does not show how good the support is, i.e. if all features are supported, what is not supported, etc.

**Comment by SebastianPfliegel** [comment]
@rugk, had exactly the same idea.

**Comment by rugk** [comment]
So just saw https://libratbag.github.io/device-notes/, which is a start, but it does only list those devices. It does not state how "good" their support is. (i.e. a column "support status" or so is missing)

**Comment by Faalagorn** [comment]
I would also like to see a table, in a similar fashion to https://mesamatrix.net/ – with checkboxes for each features and comments if e.g. something doesn't work yet but some work has been started.

I think it would also be nice to list devices that doesn't have anything working, but belong to the scope of the software, and if they are served by another Linux utility (Roccat) or are being prevented from tinkering (Razer). The device owners from https://libratbag.github.io/device-notes/ could be included too, but as the project grows the list becomes outdated, unless the page is open sourced in GitHub and people can create pull request (which I believe https://libratbag.github.io/ isn't? Correct me if I'm wrong).

**Comment by Hjdskes** [comment]
libratbag.github.io is maintained here: https://github.com/libratbag/libratbag.github.io

**Comment by Faalagorn** [comment]
It came to my light that there's also "Devices" section placeholder in [libratbag Wiki](https://github.com/libratbag/libratbag/wiki), that might be good place to host it.

**Comment by whot** [comment]
If anyone is keen to add this to the wiki, let me know if you need write access

**Comment by rugk** [comment]
But in any case we should not duplicate information. Either write it in the wiki, or on the GitHub.io page.

**Comment by whot** [comment]
the github.io page hasn't really been updated much, so moving everything to a wiki is easy enough. The problem with any sort of this documentation is that it needs someone to spend time on it - that's where it usually falls apart.

**Comment by Faalagorn** [comment]
It'd be nice to move the https://libratbag.github.io/device-notes/ to wiki IMO, as it'd be easier to maintain and device owner links would work. Can't promise I'd be taking good care of it forever, but I can help with the initial layout of the wiki and keep an eye on it from time to time at least for a while.

I also found that https://github.com/libratbag/libratbag.github.io seems to only hold the generated documentation found in the main https://libratbag.github.io/ page, not the device info static page itself.

The question is, do you want to copy the entire page to the wiki first, or should it be a new Devices wiki page written from scratch based on the info there @whot ?

Also, should just the supported devices be included there, or the ones that fall in scope of the project too? What about connection to existing protocols: Roccat's libgaminggear #12, Razer's razercfg/openrazer #103 and Corsair's ckb-next #174 – should they be mentioned as well? There's also #172 about possible keyboard support, but that's probably for later time.

Finally, there are more devices that were requested, some of which were put some work into but are not yet in the project, such as Roccat Kone EMP #421, Func MS #25, Saitek R.A.T mice #51 and various mices labeled Holtek Semiconductor at #460 with the question of listing them with a list of owners.

**Comment by whot** [comment]
Go for it! The device-notes are all in .md format anyway, moving it to a wiki should be trivial enough.

Generally, the more information there is, the better, so devices that are part of the scope but not handled for various reasons can be listed, it'll save people asking the same questions. Same with links to other projects, if they're listed at least we know they exist and potential users may start building bridging projects. But there's a limit, e.g. devices that were requested but aren't supported yet are better off in an issue, IMO, otherwise the wiki will become a graveyard of unsupported devices.

**Comment by Faalagorn** [comment]
@whot Could you then move the current device-notes to [Devices](https://github.com/libratbag/libratbag/wiki/Devices) section on wiki, please? For some reason I can't find the original code, as it's not in https://github.com/libratbag/libratbag.github.io and I don't want to just copy the HTML/text without the formatting. Then I'll start from editing the page there and hopefully add something meaningful :)

**Comment by bentiss** [comment]
the sources of device-notes are at: https://github.com/libratbag/device-notes :)

**Comment by FFY00** [comment]
I just updated the list.

**Comment by whot** [comment]
Turns out that the github wiki is a git repo (with md files). So I think it would make sense folding the device notes into the libratbag wiki, even if it means we're losing the pretty formatting. Opinions?

**Comment by bentiss** [comment]
works for me

**Comment by Hjdskes** [comment]
> even if it means we're losing the pretty formatting

GitHub flavored markdown supports tables, so at least we should be able to keep that. I don't care about fancy fonts or anything like that, so that is fine with me.

**Comment by FFY00** [comment]
Fine for me.

**Comment by whot** [comment]
This is done now, see [the wiki](https://github.com/libratbag/libratbag/wiki/Devices). Only took me about 8 tries to figure out how links work... hint: it just seems to search for a page with that name, even when it's in a subfolder. And you can't have folders the same name as a .md file.

**Comment by Faalagorn** [comment]
Thank you a lot @whot ! Now that the page's up and is easier to edit, should this issue be closed as resolved and the original page removed to avoid confusion in future?

**Comment by whot** [comment]
yeah, let's close this issue. I've filed a PR for the other repo to shutter it and remove all content from there, once @bentiss is happy with that, we're good on that side.
