### ISSUE TITLE
Battery level indicator for Logitech mice?

### ISSUE THREAD

**Issue by nick-s-b** [libratbag/libratbag#456]
All,
I have a G900 and the only thing that Piper/libratbag seems to have missing is the battery level indicator. Is there a way to expose that information somehow? I'd really like to use (or write myself) a notifier that would let me know what the battery level is.

Thanks.

**Comment by flak3** [comment]
I also need this feature a lot. There is currently no way to check the battery status from Linux.

**Comment by qidydl** [comment]
There's a [Piper issue](https://github.com/libratbag/piper/issues/222) discussing this, but the underlying work of examining battery levels might be better left to less-specialized systems like [upower](https://gitlab.freedesktop.org/upower/upower) to hopefully integrate it into existing tools and monitoring. That would be a lot more convenient than having to open Piper periodically/repeatedly to check battery levels.

**Comment by whot** [comment]
Right, let's close this issue here in favour of the piper one.
