### ISSUE TITLE
Holtek Semiconductor mice support

### ISSUE THREAD

**Issue by Faalagorn** [libratbag/libratbag#460]
I recently got a new mouse, after the problems with my previous MSI Interceptor DS100 and it turned out to be another Holtek Semiconductor mouse – Lioncast LM20. Again, the mouse is configurable with internal memory, but the included software is Windows-only.

I don't know much about the code, but I assume these mice share some similarities, so maybe some shared code for those mice could be utilized? For this reason, I'm closing my previous #430 issue about MSI Interceptor support making a new issue with the list of those mice and related info – if a separate issue is needed for each of those, then let me know so I'll reopen the MSI Interceptor issue and create new one for Lioncast LM20, as these are the two mice I own.

It might benefit more from a table made in a page similar to https://libratbag.github.io/device-notes/ or #450 but for now, I'll try to keep it updated in here.

Mouse | Manual | Software (Windows) | ID | Owner
--- | --- | --- | --- | ---
Etekcity Scroll T-140 | | | 04d9:a0c2 | [Link](https://github.com/torvalds/linux/commit/5df4eb054fe056ecb15875e812fdadbc47568d7d)
*G-SPY USB Gaming Mouse?* |  ? | ? | 04d9:a078 | [Link](https://forums.opensuse.org/showthread.php/473200-USB-Gaming-Mouse-04d9-a078-not-working-in-linux-plus-workaround)
[HAVIT HV-MS735](https://www.prohavit.com/products/hv-ms735-mmo-gaming-mouse/) | [HV-MS735 User Manual](https://drive.google.com/file/d/0B-UvXwX9IIwiVlN3Y3BieW5pOUE/view?usp=sharing) | [1.2 Beta (20160726)](https://drive.google.com/open?id=0B-UvXwX9IIwiVF9ncGtDMnVUMGM), [1.1 (20160301)](https://drive.google.com/open?id=0B-UvXwX9IIwiUHF1QTZfUVF2aWc), [1.0 (Russian)](https://drive.google.com/open?id=0B-UvXwX9IIwiNFFWOTYxOFczd1U) | 04d9:a09f | [Link](https://usb-ids.gowdy.us/read/UD/04d9), [Link](http://www.linux-usb.org/usb.ids)
[Leetgion Hellion](http://web.archive.org/web/20140730081235/http://www.leetgion.com/products.php) | [Hellion User Guide v1.0](http://web.archive.org/web/*/http://www.leetgion.com/hellion/Hellion_User_Guide_v1.0.rar) (missing) | [Hellion Configurator v1.01](http://web.archive.org/web/*/http://www.leetgion.com/hellion/Leetgion%20Hellion%20Configurator%20v1.01.rar) (missing) | 04d9:a072 | [Link](https://github.com/torvalds/linux/commit/f1a4914bd04911fbeaee23445112adae8977144a)
[Lioncast LM20](https://www.lioncast.com/en/product/lm20-gaming-mouse/)| [Manual](https://support.lioncast.com/hc/de/article_attachments/115000216529/Lioncast_LM20_Gaming_Mouse_Manual.pdf) | [1.3.1](https://support.lioncast.com/hc/de/article_attachments/115000242345/Lioncast_LM20_Gaming_Mouse_Software_1_3_1.zip)  | 04d9:fc12 | @Faalagorn
[LUOM G10](http://szluomo.com/En/ProductView.asp?ID=25)| | [2017.6.6_18.17.8_5198](http://szluomo.com/Upload/PicFiles/2017.6.6_18.17.8_5198.rar)  | 04d9:a09f | [Link](https://usb-ids.gowdy.us/read/UD/04d9), [Link](http://www.linux-usb.org/usb.ids)
[MSI Interceptor DS100](https://www.msi.com/Gaming-gear/Interceptor-DS100-GAMING-Mouse.html) | [Manual](http://download.msi.com/archive/mnu_exe/gm_ds100.zip) | [Link](http://download.msi.com/uti_exe/ds100_sw.zip) | 04d9:fa52 | @Faalagorn
NOVA Gaming Slider X200 | | | 04d9:a04a | [Link](https://github.com/torvalds/linux/commit/d4f5189052c68f5bae3aac62b357577ecb862fee)
Perixx MX-2000 | [Manual](http://perixx.eu/en/service/Perixx_Manual/GAMING/MX-2000_manual.pdf) | [Link](http://perixx.eu/en/service/MX-2000.zip) | 04d9:a067 | [Link](https://github.com/torvalds/linux/commit/41de326eafa6eff71c6ca00ae27c6be235c65a6d)
[Sharkoon DarkGlider](http://en.sharkoon.com/product/12510#desc) | [Manual](http://en.sharkoon.com/Download/Gaming/Mouse/DarkGlider/manual_darkglider_en.pdf), [Datasheet](http://en.sharkoon.com/Download/Gaming/Mouse/DarkGlider/datasheet_darkglider_en.pdf) | [061212_48224](http://en.sharkoon.com/Download/Gaming/Mouse/DarkGlider/sw_config_darkglider_061212_48224.zip) | 04d9:a081 | [Link](https://github.com/torvalds/linux/commit/7da7cbbbeb60e0939fecdf9723b388136c175e5c)
[Sharkoon Drakonia](https://en.sharkoon.com/product/1692/12527#desc) | [Manual](https://en.sharkoon.com/Download/Gaming/Mouse/Drakonia/manual_drakonia_en.pdf), [Datasheet](https://en.sharkoon.com/Download/Gaming/Mouse/Drakonia/datasheet_drakonia_en.pdf)| [34916](https://en.sharkoon.com/Download/Gaming/Mouse/Drakonia/sw_config_drakonia_34916.zip) | 04d9:a067 | [Link](https://github.com/torvalds/linux/commit/41de326eafa6eff71c6ca00ae27c6be235c65a6d)
*Sharkoon Draconia?* | | | 04d9:a071 | [Link](https://forum.peppermintos.com/index.php?topic=2653.0)
[Ritmix ROM-316](http://www.ritmixrussia.ru/products/rom-316) | [Manual (RU)](http://www.ritmixrussia.ru/static/downloads/Manual/PC/ROM_manual.pdf) | No software needed? | 04d9:a070 | [Link](https://github.com/torvalds/linux/commit/274be3eb653c421d68514684024c6d915c94b728)
[Tracer Sniper TRM-503](https://en.tracer.eu/mouse-tracer-gamezone-sniper-avago-9500-6000dpi) | | [42418](https://en.tracer.eu/gfx-base/files/_DRIVERS/ster_42418.rar) | 04d9:a04a | [Link](https://github.com/torvalds/linux/commit/d4f5189052c68f5bae3aac62b357577ecb862fee)
[Zalman ZM-GM1](http://www.zalman.com/contents/products/view.html?no=314) | | [20140306](http://www.zalman.com/board/board_download.php?idx=237&board_uid=6&index=1&path=/DataFile/Contact/Download) | 04d9:a04a | [Link](https://github.com/torvalds/linux/commit/d4f5189052c68f5bae3aac62b357577ecb862fee)

[Elekcity website](https://www.etekcity.com) doesn't cover T-140 mouse anymore, but it's blog [does mention T-142](http://blog.etekcity.com/wp-content/uploads/2014/07/Scroll-T-142-Software.pdf) instead. [One Amazon review](https://www.amazon.com/gp/customer-reviews/RWDBN4JF3GCWK) suggests the driver stopped working on Windows 10, and was removed by manufacturer.
[Leetgion website](http://web.archive.org/web/20140729101105/http://www.leetgion.com/) (archived copy from Wayback Machine) found e.g. [on their Facebook page](https://www.facebook.com/Leetgion/), seems to redirect to another page now.
Finally, NOVA Gaming Slider X200 (also known as SX200) is a French company that I couldn't find website of, they also made X600 gaming mouse.
The manual and drivers for these may be found reuploaded somewhere online, plus the videos, info and store pages with specs. The people behind patchworks for Linux kernel, may still have the devices and associated manuals/drivers somewhere around, too.

Beyond the scope of Libratbag, there's also Holtek Semiconductor keyboards, listed in https://github.com/torvalds/linux/blob/master/drivers/hid/hid-holtek-kbd.c

**Comment by whot** [comment]
If it doesn't have hardware memory, it's out-of-scope for libratbag as it is now. Though with the 'new' design of always having ratbagd, we could in theory implement software profiles. No work has been done on that yet though.

**Comment by FFY00** [comment]
@whot I could try to work on that if you or other developer guide me.

**Comment by whot** [comment]
@FFY00 see #475, we need a config storage backend first

**Comment by tengwar** [comment]
There is another Holtek mouse: [Hiro Octagon](https://hiro.com.pl/produkty/hiro-octagon) with ID 04d9:a070. Drivers download page is [here](https://hiro.com.pl/akcesoria-hiro) and the direct link to the drivers zip is https://hiro.com.pl/upload/files/2017/09/hiro-octagon-gaming-mouse-setup.zip

**Comment by rombert** [comment]
@whot - reverse engineering is not necessarily a problem. But I'm confused about the relation to #475, what does that mean in practical terms? WIll libratbag simply not work or would it need to apply the settings each time after plugging in the mouse?

**Comment by FFY00** [comment]
@rombert first of all we need to know if the mouse actually allows us to configure the hardware, which I don't think it does. If it does then you have check if the settings survive a poweroff, if they do then it is rather easy to add support, you just need to reverse engineer the protocol. If it can't save the settings on the onboard memory then we need #475, I mean, we could still implement the protocol without #475 but it will be super annoying as the settings will be lost on a device poweroff.

**Comment by FFY00** [comment]
I am gonna close this, if anyone wants to reverse engineer the protocol (if there's any) and submit a pull request then feel free, but right now this seems to be going nowhere.
