### ISSUE TITLE
Doesn't detect argument on profile/led/set/mode

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#465]
Compiled from master branch https://github.com/libratbag/libratbag/commit/770dd62b1d95f99215f0c88f5253be308b10c4c0

```
anubis@genesis: ~/g/l/build [master]× ▶︎︎ ratbagctl profile 0 led 0 set mode off
usage: /usr/bin/ratbagctl set mode [-h] mode
/usr/bin/ratbagctl set mode: error: the following arguments are required: mode
```

I tried other different arguments. I also tried without the `profile 0` as I believe changing the LED effects per profile is not supported (at least in the official driver).

**Comment by phomes** [comment]
I am assuming that this is for the steelseries rival 310. I saw an issue from you on rivalcfg.

Is it only this one command that does not work, or does it also fail for "ratbagctl list"?

**Comment by FFY00** [comment]
@phomes yes, sorry. I have a Rival 310 and the firmware was updated last night.

`ratbagclt list` is working as expected
```
anubis@genesis: ~ ▶︎︎ ratbagctl list                                                                                                                                                                     event4:    SteelSeries SteelSeries Rival 310 eSports Mouse
```

**Comment by bentiss** [comment]
> ```
> anubis@genesis: ~/g/l/build [master]× ▶︎︎ ratbagctl profile 0 led 0 set mode off
> usage: /usr/bin/ratbagctl set mode [-h] mode
> /usr/bin/ratbagctl set mode: error: the following arguments are required: mode
> ```

IIRC you need to provide the name of the device as the last argument, right?

So in this case it should be something like:
```ratbagctl profile 0 led 0 set mode off eventX```

**Comment by FFY00** [comment]
I'm sorry, I forgot. This should be removed if we only have one device connected. I'll try again later.
