### ISSUE TITLE
Accessing debug logs

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#469]
I noticed that you have methods to log the buffer but I don't know how to access the output. I am specifically interested in the buffer log. I tried to use verbose mode, I checked the service logs and I tried to set `DEBUG=1` in the environment but none of that worked.

Sorry to bother.

**Comment by phomes** [comment]
you can get the verbose log messages with -vvv. E.g.:
`ratbagctl list -vvv `

**Comment by FFY00** [comment]
That doesn't seem to have any effect. I made a clean build with the last master branch, still the same.

**Comment by FFY00** [comment]
Okay, `ratbagctl.devel` shows the debug logs but `ratbagctl` doesn't. I don't know if this is a bug. Waiting for input to close the issue.

**Comment by bentiss** [comment]
Yes, that's expected. The logs are part of `ratbagd`, and `ratbagctl.devel` starts `ratbagd` in the background with the proper arguments to show the logs.

If you are developing a driver backend, you can also use `ratbag-command` from the git tree, it will bypass dbus and will do plain libc calls, meaning it's easier to attach gdb on it.
