### ISSUE TITLE
Unable to install on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by mihaibuba** [libratbag/libratbag#477]
Hello,

I tried installing librabag on Ubuntu 18.04 LTS, but I ran into so many issues, the last one I could not solve that eventually I had to write this bug report. So, here it goes:

**Installation Take 2**
I am putting Take 2 first because this should have been the way it should work anyway. 

- Given I want to install _libratbag_ and _piper_
- When I run as root `apt-get install libratbag piper`
- Then the the installer should pull all required dependencies
- And it install the required services 
- And start the libratbag service
- And after starting piper
- Then the mouse configuration interface should be displayed

Well, that did not work there are no packages named libratbag piper
OK, so I tried to search for the libraries, so I ran as root:
`apt-get install libratbag-common libratbag-dev libratbag-doc libratbag-tools libratbag4`
so basically throw everything at it, even the kitchen sink.
Well, now I have installed something... at least I can start the services manually right?
Turns out no, after running:
```
sudo systemctl daemon-reload
sudo systemctl reload dbus.service
sudo systemctl enable ratbagd.service
sudo systemctl start ratbagd.service
```
I get the following error when starting service, or running manually either as sudo or su:
`ratbagd error: Failed to start ratbagd: Permission denied`
I checked permission for all three files they are 755

```
-rwxr-xr-x 1 root root       43224 Jan 10 13:56 ratbag-command
-rwxr-xr-x 1 root root       89952 May 10 23:56 ratbagctl
-rwxr-xr-x 1 root root      597912 May 10 23:56 ratbagd

```

now, running 
`/usr/bin# ./ratbag-command list`
returns:
`/dev/input/event8:	Logitech G300s Optical Gaming Mouse`
and running:
`./ratbag-command info /dev/input/event8`
returns:

```
/dev/input/event8:	Logitech G300s Optical Gaming Mouse
root@SuperCoolPC:/usr/bin# ./ratbag-command info /dev/input/event8
Device 'Logitech G300s Optical Gaming Mouse'
Capabilities: res profile btn-key
Number of buttons: 9
Number of leds: 0
Profiles supported: 3
  Profile 0 (enabled) (active)
    Resolutions:
      0: 500dpi @ 500Hz
      1: 1000dpi @ 500Hz (default)
      2: 1500dpi @ 500Hz
      3: 2500dpi @ 500Hz
    Button: 0 type left is mapped to 'button 1'
    Button: 1 type right is mapped to 'button 2'
    Button: 2 type middle is mapped to 'button 3'
    Button: 3 type thumb is mapped to 'KEY_DOWN'
    Button: 4 type thumb2 is mapped to 'KEY_LEFT'
    Button: 5 type pinkie is mapped to 'KEY_RIGHT'
    Button: 6 type pinkie2 is mapped to 'KEY_UP'
    Button: 7 type profile cycle up is mapped to 'KEY_V'
    Button: 8 type resolution cycle up is mapped to 'KEY_C'
  Profile 1 (enabled)
    Resolutions:
      0: 500dpi @ 1000Hz
      1: 1000dpi @ 1000Hz (default)
      2: 1500dpi @ 1000Hz
      3: 2500dpi @ 1000Hz
    Button: 0 type left is mapped to 'button 1'
    Button: 1 type right is mapped to 'button 2'
    Button: 2 type middle is mapped to 'button 3'
    Button: 3 type thumb is mapped to 'button 4'
    Button: 4 type thumb2 is mapped to 'button 5'
    Button: 5 type pinkie is mapped to 'resolution down'
    Button: 6 type pinkie2 is mapped to 'resolution up'
    Button: 7 type profile cycle up is mapped to 'profile cycle up'
    Button: 8 type resolution cycle up is mapped to 'resolution alternate'
  Profile 2 (enabled)
    Resolutions:
      0: 1000dpi @ 500Hz (default)
      1: 1000dpi @ 500Hz
      2: 1000dpi @ 500Hz
      3: 1000dpi @ 500Hz
    Button: 0 type left is mapped to 'button 1'
    Button: 1 type right is mapped to 'button 2'
    Button: 2 type middle is mapped to 'button 3'
    Button: 3 type thumb is mapped to 'button 4'
    Button: 4 type thumb2 is mapped to 'button 5'
    Button: 5 type pinkie is mapped to 'KEY_C'
    Button: 6 type pinkie2 is mapped to 'KEY_V'
    Button: 7 type profile cycle up is mapped to 'profile cycle up'
    Button: 8 type resolution cycle up is mapped to 'KEY_X'
```

Starting piper now doesn't work. I try to start it, but nothing happens, so at this point I am stuck.

**Installation Take 1**
This was the first thing I tried, since this was actually the way described in the readme. But this should be the back-up, if installing the packages doesn't work.
For this I actually had to hack at it slowly to get something, I would not pull all the required libraries. Basically I had to run the build, see what error I had, then find and download each package. That is why there are separate installs:
```
apt-get install -y pkg-config
apt-get install ninja-build
apt-get install libudev-dev
apt-get install libevdev-dev
apt-get install libevdev-dev
apt-get install libsystemd-dev
apt-get install libglib2.0-dev
apt-get install check-devel
apt-get install python3-pip
apt-get install python-dev python-pip gcc
apt-get install linux-headers-$(uname -r)
apt-get install valgrind swig python-gi-dev
sudo pip3 install evdev
pip3 install --user evdev
pip3 install --user meson
```

Then I run the build process:
```
git clone https://github.com/libratbag/libratbag.git
cd libratbag
meson builddir --prefix=/usr/
ninja -C builddir
sudo ninja -C builddir install
```

Tried to start it, it failed, and running ratbag-command shows the following:
`libratbag/builddir# ./ratbag-command info /dev/input/event8`
result:
```
/dev/input/event8 - Logitech G300s Optical Gaming Mouse
               SVG: gnome/logitech-g300.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, switchable-profile, button, button-keys, button-macros, led
 Number of Buttons: 9
    Number of Leds: 1
Number of Profiles: 3
Profile 0: (active)
  Name : 'Profile 1'
  Resolutions:
    0: 500dpi @ 500Hz
    1: 1000dpi @ 500Hz (active) (default)
    2: 1500dpi @ 500Hz
    3: 2500dpi @ 500Hz
  Button: 0 type left is mapped to 'button 1'
  Button: 1 type right is mapped to 'button 2'
  Button: 2 type middle is mapped to 'button 3'
Traceback (most recent call last):
  File "./ratbag-command", line 2359, in <module>
    main(sys.argv[1:])
  File "./ratbag-command", line 2356, in main
    f(r, cmd)
  File "./ratbag-command", line 1094, in show_device
    print_device(d, 0)
  File "./ratbag-command", line 1089, in print_device
    print_profile(d, p, level + 2)
  File "./ratbag-command", line 1061, in print_profile
    print_button(d, p, b, level)
  File "./ratbag-command", line 1027, in print_button
    print("{}macro '{}'".format(header, str(b.macro)))
  File "./ratbag-command", line 601, in macro
    return RatbagdMacro.from_ratbag(libratbag.ratbag_button_get_macro(self._button))
  File "./ratbag-command", line 721, in from_ratbag
    ratbagd_macro.append(type, value)
  File "./ratbag-command", line 740, in append
    self.notify("keys")
AttributeError: 'RatbagdMacro' object has no attribute 'notify'
```

Now, after completing both, after everything is mixed (I assume that the packages installed are good, but they were missing some files created by the build process) I can actually start the service, but piper still doesn't work.

**Comment by FFY00** [comment]
Try running `ratbagctl` instead of `ratbag-command`.

**Comment by mihaibuba** [comment]
I have tried, running from both the /usr/bin and /libratbag/builddir . I get the same result as follows:
`/usr/bin# ratbagctl` 
returns:
`event8:    Logitech G300s Optical Gaming Mouse`

and running:
`/usr/bin# ratbagctl info event8` 
returns:
[note: the changes in the macros associated are because I used the Logitech Windows utility to reprogram the mouse keys, but I would prefer to use libratbag to do it from now on]
```
event8 - Logitech G300s Optical Gaming Mouse
               SVG: /usr/share/libratbag/gnome/logitech-g300.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, switchable-profile, button, button-keys, button-macros, led
 Number of Buttons: 9
    Number of Leds: 1
Number of Profiles: 3
Profile 0: (active)
  Name : 'Profile 1'
  Resolutions:
    0: 500dpi @ 500Hz
    1: 1000dpi @ 500Hz (active) (default)
    2: 1500dpi @ 500Hz
    3: 2500dpi @ 500Hz
  Button: 0 type left is mapped to 'button 1'
  Button: 1 type right is mapped to 'button 2'
  Button: 2 type middle is mapped to 'button 3'
  Button: 3 type thumb is mapped to macro '↓LEFTMETA ↕H ↑LEFTMETA'
  Button: 4 type thumb2 is mapped to macro '↓LEFTMETA ↕LEFT ↑LEFTMETA'
  Button: 5 type pinkie is mapped to macro '↓LEFTMETA ↕RIGHT ↑LEFTMETA'
  Button: 6 type pinkie2 is mapped to macro '↓LEFTMETA ↕UP ↑LEFTMETA'
  Button: 7 type profile-cycle-up is mapped to macro '↓LEFTMETA ↕DOWN ↑LEFTMETA'
  Button: 8 type resolution-cycle-up is mapped to macro '↓LEFTMETA ↕DOWN ↑LEFTMETA'
  LED: 0 type: side, depth: rgb111, mode: on, color: 00ffff
Profile 1:
  Name : 'Profile 2'
  Resolutions:
    0: 500dpi @ 1000Hz
    1: 1000dpi @ 1000Hz (active) (default)
    2: 1500dpi @ 1000Hz
    3: 2500dpi @ 1000Hz
  Button: 0 type left is mapped to 'button 1'
  Button: 1 type right is mapped to 'button 2'
  Button: 2 type middle is mapped to 'button 3'
  Button: 3 type thumb is mapped to 'button 4'
  Button: 4 type thumb2 is mapped to 'button 5'
  Button: 5 type pinkie is mapped to 'resolution-down'
  Button: 6 type pinkie2 is mapped to 'resolution-up'
  Button: 7 type profile-cycle-up is mapped to 'profile-cycle-up'
  Button: 8 type resolution-cycle-up is mapped to 'resolution-alternate'
  LED: 0 type: side, depth: rgb111, mode: on, color: 00ff00
Profile 2:
  Name : 'Profile 3'
  Resolutions:
    0: 1000dpi @ 500Hz (active) (default)
    1: 1000dpi @ 500Hz
    2: 1000dpi @ 500Hz
    3: 1000dpi @ 500Hz
  Button: 0 type left is mapped to 'button 1'
  Button: 1 type right is mapped to 'button 2'
  Button: 2 type middle is mapped to 'button 3'
  Button: 3 type thumb is mapped to 'button 4'
  Button: 4 type thumb2 is mapped to 'button 5'
  Button: 5 type pinkie is mapped to macro '↓LEFTCTRL ↕C ↑LEFTCTRL'
  Button: 6 type pinkie2 is mapped to macro '↓LEFTCTRL ↕V ↑LEFTCTRL'
  Button: 7 type profile-cycle-up is mapped to 'profile-cycle-up'
  Button: 8 type resolution-cycle-up is mapped to macro '↓LEFTCTRL ↕X ↑LEFTCTRL'
  LED: 0 type: side, depth: rgb111, mode: on, color: 0000ff
```

**Comment by mihaibuba** [comment]
Oh, I forgot to mention that after both installing the packages, and running the build, now the libratbag service does actually start, but piper does not.
I _assume_ the build process created the files the services were missing in /usr/share/libratbag
```
   Loaded: loaded (/lib/systemd/system/ratbagd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-05-12 17:29:20 EDT; 20min ago
 Main PID: 2892 (ratbagd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/ratbagd.service
           └─2892 /usr/bin/ratbagd
```

**Comment by FFY00** [comment]
What's wrong with the output above? `ratbagctl` seems to be working fine.
Piper doesn't have it's own service, it is only a GUI version of `ratbagctl`.

**Comment by Hjdskes** [comment]
This is probably the issue you're running into: https://github.com/libratbag/piper/issues/209

**Comment by mihaibuba** [comment]
@Hjdskes Thank you, after reading that it turns out that the linking was missing:
`sudo ln -s /usr/lib/python3.6/site-packages/piper /usr/lib/python3/dist-packages`
Now everything is working, however I still think that it would be useful to have an easier installation process.
Either when pulling the packages, they should somehow also install the required files in `/usr/share/libratbag` if that is indeed what was missing;
Or have better installation instructions on the page and/or wiki, such as installing all the required dependencies, some of which I have listed in the first post. Since this was not really a clean install I cannot say that these are all.
That will save somebody the few hours, which I had to spend trying to install it.

**Comment by Hjdskes** [comment]
Good that it's working now. Regarding the installation process; packaging libratbag and piper isn't up to us but the distributions themselves. You should contact them about this. We don't list dependencies on purpose because such a list is bound to go stale at some point. You may find an up to date list in our CircleCI file though: https://github.com/libratbag/libratbag/blob/master/circle.yml

I'm closing this issue now because everythibg is working. If there are further problems, please open a new issue.
