### ISSUE TITLE
Trouble compiling libratbag on Debian Stretch 9.4

### ISSUE THREAD

**Issue by WingXBlade** [libratbag/libratbag#478]
Hi, 

When I was trying to compile libratbag with
`meson builddir --prefix=/usr/`

I get
```The Meson build system
Version: 0.37.1
Source dir: /home/henry/libratbag
Build dir: /home/henry/libratbag/builddir
Build type: native build
Project name: libratbag
Native c compiler: cc (gcc 6.3.0)
Native cpp compiler: c++ (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency libudev found: YES 232
Native dependency libevdev found: YES 1.5.6
Native dependency libsystemd found: YES 232
Native dependency systemd found: YES 232
Native dependency glib-2.0 found: YES 2.50.3
Library m found: YES
Program /home/henry/libratbag/data/devices/data-parse-test.py found: YES (/home/henry/libratbag/data/devices/data-parse-test.py)
Program data/gnome/check-svg.py found: YES (/home/henry/libratbag/data/gnome/check-svg.py)
Native dependency check found: YES 0.10.0
Program valgrind found: YES (/usr/bin/valgrind)

Meson encountered an error in file meson.build, line 349, column 1:
Unknown function "add_test_setup".
```
I've done some searching and found out that there are cases that some functions from meson might not be available for old versions, is this some what similar to those cases? 

Thanks in advance.
Henry

**Comment by SebastianPfliegel** [comment]
That's right. Your meson is out of date. I assume you obtained it from your distro's repos? If so and you don't rely on this version try fetching it from the official sources: http://mesonbuild.com/Getting-meson.html

**Comment by whot** [comment]
Was our bug, we only checked for meson 0.36 in the meson.build file. I bumped this to 0.38 now so the error message will be a better one. Same workaround applies though, please get meson from git, your version is too old.

**Comment by WingXBlade** [comment]
Hi. Sorry for the late reply. I did try installing the latest meson version and it fixed the problem. Debian seems to have these problems as the stable release only features old versions. Anyway, thank you so much for the support!
