### ISSUE TITLE
Move to GitLab?

### ISSUE THREAD

**Issue by p4block** [libratbag/libratbag#483]

**Comment by bentiss** [comment]
Just to prevent squatting, I just reserved the group gitlab.com/libratbag

**Comment by SebastianPfliegel** [comment]
This is not about Microsoft acquiring GitHub, is it?

**Comment by bentiss** [comment]
> This is not about Microsoft acquiring GitHub, is it?

The time makes it hard not to think about it :)

**Comment by whot** [comment]
What's the real motivation here though? It's some or a lot of work for very little benefit. Is there any feature we would immediately require or even make use of? Or is this just about the supposed MS buyout?

**Comment by whot** [comment]
Somewhat related: there's a gitlab instance on freedesktop.org so we could also move there. But the same arguments apply.

I'm closing this one, we have a clear "nah" here.
