### ISSUE TITLE
Trouble compiling libratbag on Ubuntu 18.04

### ISSUE THREAD

**Issue by BradleyDS2** [libratbag/libratbag#495]
Hey, sorry about this, I'm sure it's something I'm doing wrong.

When I run `meson builddir --prefix=/usr/` it says the following:

```
bradley@bradley-Ubuntu:~/libratbag$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.45.1
Source dir: /home/bradley/libratbag
Build dir: /home/bradley/libratbag/builddir
Build type: native build
Project name: libratbag
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Found pkg-config: /usr/bin/pkg-config (0.29.1)

meson.build:50:0: ERROR: Native dependency 'libudev' not found

A full log can be found at /home/bradley/libratbag/builddir/meson-logs/meson-log.txt
```

Based on the error, I thought In obviously must need to install libudev, so I entered `sudo apt install libudev1` in a terminal but it states:

```
bradley@bradley-Ubuntu:~/libratbag$ sudo apt install libudev1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libudev1 is already the newest version (237-3ubuntu10).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

I tried following the instructions from [here](https://github.com/libratbag/libratbag/issues/477) instead, but `sudo systemctl enable ratbagd.service` states `Failed to enable unit: Unit file ratbagd.service does not exist.
`

Do you know what I'm doing wrong?

**Comment by FFY00** [comment]
You need the development files. In debian based systems they are installed via the `-dev` package. Installing `libudev1-dev` should fix the this.

**Comment by muzena** [comment]
@BradleyDS2 
Try install it from this repository:
https://launchpad.net/%7Etrebelnik-stefina/+archive/ubuntu/ratbag-piper

**Comment by BradleyDS2** [comment]
I tried installing `libudev1-dev` but got the following:
```
bradley@bradley-Ubuntu:~/tmp$ sudo apt install libudev1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libudev1-dev
```

I added the repository muzena linked, but attempting to install `libratbag` ends with the following result:
```
bradley@bradley-Ubuntu:~/tmp$ sudo apt install libratbag
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libratbag
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 705 kB of archives.
After this operation, 1,666 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/trebelnik-stefina/ratbag-piper/ubuntu bionic/main amd64 libratbag amd64 0.9.902.5~bionic [705 kB]
Fetched 705 kB in 1min 9s (10.3 kB/s)                                          
Selecting previously unselected package libratbag.
(Reading database ... 189501 files and directories currently installed.)
Preparing to unpack .../libratbag_0.9.902.5~bionic_amd64.deb ...
Unpacking libratbag (0.9.902.5~bionic) ...
dpkg: error processing archive /var/cache/apt/archives/libratbag_0.9.902.5~bionic_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/lur-command', which is also in package libratbag-tools 0.9-4
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libratbag_0.9.902.5~bionic_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by muzena** [comment]
@BradleyDS2 
I tested this repository in ubuntu 18.04 and Linux Mint 19 and it works.
I think, there is some package conflict:
trying to overwrite '/usr/bin/lur-command', which is also in package libratbag-tools 0.9-4Remove this package "libratbag-tools" and all "libratbag" packages and try then install.

**Comment by BradleyDS2** [comment]
Sorry for the silly question, but how should I go about doing that?
I tried purging "libratbag-tools" and "libratbag" but it didn't work.

```
bradley@bradley-Ubuntu:~$ sudo apt purge libratbag-tools
[sudo] password for bradley: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 piper : Depends: libratbag but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
bradley@bradley-Ubuntu:~$ sudo apt purge libratbag
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libratbag' is not installed, so not removed
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 piper : Depends: libratbag but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
bradley@bradley-Ubuntu:~$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libratbag
The following NEW packages will be installed:
  libratbag
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
6 not fully installed or removed.
Need to get 0 B/705 kB of archives.
After this operation, 1,666 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 189723 files and directories currently installed.)
Preparing to unpack .../libratbag_0.9.902.5~bionic_amd64.deb ...
Unpacking libratbag (0.9.902.5~bionic) ...
dpkg: error processing archive /var/cache/apt/archives/libratbag_0.9.902.5~bionic_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/lur-command', which is also in package libratbag-tools 0.9-4
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libratbag_0.9.902.5~bionic_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```



Sorry, I know I'm doing something wrong, but unsure what it is.

**Comment by BradleyDS2** [comment]
I removed the ` https://launchpad.net/%7Etrebelnik-stefina/+archive/ubuntu/ratbag-piper` repository and was then able to `sudo apt --fix-broken install` which removed the `piper` package then I ran `sudo apt purge libratbag-common libratbag-dev libratbag-doc libratbag-tools libratbag4` added the  ` https://launchpad.net/%7Etrebelnik-stefina/+archive/ubuntu/ratbag-piper` repository again, ran `sudo apt update` and `sudo apt install libratbag` but it gave the following output

```
bradley@bradley-Ubuntu:~$ sudo apt install libratbag
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  fonts-mathjax javascript-common libjs-bootstrap libjs-jquery libjs-mathjax
  liblur3 python3-bs4 python3-evdev python3-html5lib python3-lxml
  python3-webencodings
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libratbag
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/705 kB of archives.
After this operation, 1,666 kB of additional disk space will be used.
(Reading database ... 189521 files and directories currently installed.)
Preparing to unpack .../libratbag_0.9.902.5~bionic_amd64.deb ...
Unpacking libratbag (0.9.902.5~bionic) ...
dpkg: error processing archive /var/cache/apt/archives/libratbag_0.9.902.5~bionic_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/liblur.so.3.0.3', which is also in package liblur3:amd64 0.9-4
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libratbag_0.9.902.5~bionic_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```


How should I remove `liblur3:amd64 0.9-4`?

**Comment by BradleyDS2** [comment]
I tried building and running piper but the result is the following:

```
bradley@bradley-Ubuntu:~/piper$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.45.1
Source dir: /home/bradley/piper
Build dir: /home/bradley/piper/builddir
Build type: native build
WARNING: Newline character in a string detected, use ''' (three single quotes) for multiline strings instead.
This will become a hard error in a future Meson release. config_piper_devel.set('devel', ' 43 32
Project name: piper
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency python3 found: YES 3.6
Native dependency pygobject-3.0 found: YES 3.26.1
Configuring AboutDialog.ui using configuration
Native dependency glib-2.0 found: YES 2.56.1
Message: Getting Python3 install dir
Configuring piper using configuration
Configuring piper.devel using configuration
Program meson_install.sh found: YES (/usr/bin/env sh /home/bradley/piper/meson_install.sh)
Build targets in project: 4
Found ninja-1.8.2 at /usr/bin/ninja
bradley@bradley-Ubuntu:~/piper$ $ ninja -C builddir
$: command not found
bradley@bradley-Ubuntu:~/piper$ ninja -C builddir
ninja: Entering directory `builddir'
[1/1] Generating piper_gresource with a custom command.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
bradley@bradley-Ubuntu:~/piper$ sudo ninja -C builddir install
ninja: Entering directory `builddir'
[0/1] Installing files.
Installing subdir /home/bradley/piper/piper to /usr/lib/python3.6/site-packages/piper
Installing data/piper.gresource to /usr/share/piper/piper.gresource
Installing /home/bradley/piper/data/org.freedesktop.Piper.desktop to /usr/share/applications
Installing /home/bradley/piper/data/org.freedesktop.Piper.svg to /usr/share/icons/hicolor/scalable/apps
Installing /home/bradley/piper/builddir/piper to /usr/bin
Running custom install script '/usr/bin/python3 /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=piper'
Installing /home/bradley/piper/builddir/po/de.gmo to /usr/share/locale/de/LC_MESSAGES/piper.mo
Installing /home/bradley/piper/builddir/po/hr.gmo to /usr/share/locale/hr/LC_MESSAGES/piper.mo
Installing /home/bradley/piper/builddir/po/nl.gmo to /usr/share/locale/nl/LC_MESSAGES/piper.mo
Installing /home/bradley/piper/builddir/po/pl.gmo to /usr/share/locale/pl/LC_MESSAGES/piper.mo
Installing /home/bradley/piper/builddir/po/sv.gmo to /usr/share/locale/sv/LC_MESSAGES/piper.mo
Running custom install script '/usr/bin/env sh /home/bradley/piper/meson_install.sh'
gtk-update-icon-cache: Cache file created successfully.
bradley@bradley-Ubuntu:~/piper$ python '/home/bradley/piper/builddir/piper' 
  File "/home/bradley/piper/builddir/piper", line 12
    print("Version of GTK is too old, 3.22 required", file=sys.stderr)
                                                          ^
SyntaxError: invalid syntax
bradley@bradley-Ubuntu:~/piper$ python3 '/home/bradley/piper/builddir/piper' 
Traceback (most recent call last):
  File "/home/bradley/piper/builddir/piper", line 36, in <module>
    from piper.application import Application
ModuleNotFoundError: No module named 'piper'
```

Trying to run the piper file directly also opens it in gedit even though it's marked to allow as executing as a program.

**Comment by whot** [comment]
`E: Unable to locate package libudev1-dev`

libudev is a special case because it got absorbed by systemd years ago. so try a package `systemd-devel` or something like that.  You should also be able to use `apt-file search --package-only libudev.pc` to find which package the file belongs to (google more for `apt-file` usage, I don't use .deb distros)


`print("Version of GTK is too old, 3.22 required", file=sys.stderr)`: you were trying to run with python 2.x, just execute the file directly as `path/to/piper`. Do not prefix python scripts manually, it usually causes troubles.

If you want to run directly from the builddir, use `piper.devel`, not `piper`, that will set up the module paths correctly  to avoid that issue. Otherwise, run it from the installed location instead

**Comment by adamlaughlin** [comment]
Thanks, Whot.
Your advice resulted in the installation of `libudev-dev`, `libevdev-dev`, `libsystemd-dev`, `libglib-2.0-dev`, `check`, `valgrind`, `swig` as results of following the processes described by this conversation.

After that, I stopped getting errors:
`The Meson build system
Version: 0.45.1
Source dir: /home/smelly/Downloads/libratbag
Build dir: /home/smelly/Downloads/libratbag/builddir
Build type: native build
Project name: libratbag
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libudev found: YES 237
Native dependency libevdev found: YES 1.5.8
Native dependency libsystemd found: YES 237
Native dependency systemd found: YES 237
Native dependency glib-2.0 found: YES 2.56.1
Library m found: YES
Configuring libratbag-version.h using configuration
Configuring lur-command.1 using configuration
Program /home/smelly/Downloads/libratbag/data/devices/data-parse-test.py found: YES (/home/smelly/Downloads/libratbag/data/devices/data-parse-test.py)
Program data/gnome/check-svg.py found: YES (/home/smelly/Downloads/libratbag/data/gnome/check-svg.py)
Native dependency check found: YES 0.10.0
Program valgrind found: YES (/usr/bin/valgrind)
Configuring org.freedesktop.ratbag_devel1.conf using configuration
Message: 
		systemd unitdir libdir mismatch detected, changing unitdir to
			/lib/systemd/system
		or specify with
			mesonconf -Dsystemd-unit-dir=<path>

		See https://github.com/libratbag/libratbag/issues/188
		
Configuring ratbagd.service using configuration
Configuring org.freedesktop.ratbag1.service using configuration
Configuring org.freedesktop.ratbag1.conf using configuration
Configuring ratbagctl.1 using configuration
Configuring ratbagctl.devel using configuration
Configuring ratbagctl.test using configuration
Program /home/smelly/Downloads/libratbag/builddir/ratbagctl.test found: YES (/home/smelly/Downloads/libratbag/builddir/ratbagctl.test)
Configuring toolbox.py using configuration
Configuring config.h using configuration
Program swig found: YES (/usr/bin/swig)
Native dependency python3 found: YES 3.7
Build targets in project: 22
Found ninja-1.8.2 at /usr/bin/ninja`

This is my second day in Linux and I seem not to understand the next step.  I am trying to follow this by running `sudo ratbagd` but am told there is no such command.  Tried the same after cd'ing into the directory which contains `ratbagd.c` but same result.

Are there steps in between I was supposed to know?  I'm assuming the console output I posted was what we wanted to see from the Meson build.

**Comment by FFY00** [comment]
@adamlaughlin, you have built the project, now you need to install it.

```
sudo ninja install
```

After that you may want to activate the daemon service (ratbagd). This way you don't have to manually run `ratbagd` everytime you start the computer.

```
sudo systemctl enable ratbagd
sudo systemctl start ratbagd
```

After that everything should work normally. If you need help with anything else you can reach out to me, my email is in my profile.

**Comment by BradleyDS2** [comment]
Awesome, thanks for all the help.


Just need help with (hopefully) one last thing.

When I try opening Piper from the application list, nothing happens. When I try running it from the terminal, I get the following error:
```
bradley@bradley-Ubuntu:~$ piper
Traceback (most recent call last):
  File "/usr/bin/piper", line 36, in <module>
    from piper.application import Application
ModuleNotFoundError: No module named 'piper'
```


If I CD into the build directory though, I'm able to successfully run piper.devel and set up my mouse there, but ideally I'd like to be able to start it directly, rather than cding into the build directory and running piper.devel every time.

Thank you :)

**Comment by whot** [comment]
This may be https://github.com/libratbag/piper/issues/209#issuecomment-383451686

**Comment by BradleyDS2** [comment]
Ah, okay. Shame it can't be fixed, but I guess that all my issues have been resolved. Thank you :)

**Comment by idantene** [comment]
For future generations who want to compile on Ubuntu 20, I had to install the following packages:
`sudo apt install cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig`

**Comment by sealvessel** [comment]
Is it possible to install this on a darwin(macOS 10.15) based system? There is no homebrew/macos version of the packages you said above. Am I out of luck?

**Comment by FFY00** [comment]
I could maybe be with some work, but right now we depend on some Linux specific APIs.

**Comment by rahmadullah** [comment]
> For future generations who want to compile on Ubuntu 20, I had to install the following packages:
> `sudo apt install cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig`

Thanks, this helped me!

**Comment by Vovchikan** [comment]
> For future generations who want to compile on Ubuntu 20, I had to install the following packages:
> `sudo apt install cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig`

```Using meson's python ['/usr/bin/python3']
Found CMake: /usr/bin/cmake (3.13.4)
Dependency python-3.7 found: NO (tried pkgconfig and cmake)
Dependency python3 found: NO (tried pkgconfig)

meson.build:572:4: ERROR:  Dependency "python3" not found, tried pkgconfig
```

It doesn't help me(

**Comment by idantene** [comment]
@Vovchikan are you on Ubuntu 20.04? It comes with Python 3 built-in, so that's quite unexpected. You could install Python3 I suppose.

**Comment by Vovchikan** [comment]
> @Vovchikan are you on Ubuntu 20.04? It comes with Python 3 built-in, so that's quite unexpected. You could install Python3 I suppose.

I have Python 2.7.16 and Python 3.7.3. Both of them I can run in terminal with commands `python` and `python3`.

**Comment by idantene** [comment]
I'm not sure, seems like a meson issue to me more than `libratbag` related.

**Comment by muzena** [comment]
@Vovchikan 
Try to install from PPA, see wiki.

**Comment by Mortein** [comment]
> For future generations who want to compile on Ubuntu 20, I had to install the following packages:
> `sudo apt install cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig`

Thanks. Install the `python3-dev` package if meson complains about missing the `python3-embed` dependency.

**Comment by erdincay** [comment]
Everything I know about this Library is this: 

sudo apt install cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig

`sudo apt install libjson-glib-dev
sudo apt install libunistring-dev
sudo apt install python-gi-dev
sudo apt install libsystemd-dev
sudo apt install python3.8-dev
sudo apt install python3.8-full
sudo apt install swig
sudo apt install check`

sudo cp dbus/org.freedesktop.ratbag1.conf /etc/dbus-1/system.d/org.freedesktop.ratbag1.conf
sudo cp builddir/org.freedesktop.ratbag1.service /etc/dbus-1/system-services/org.freedesktop.ratbag1.conf
sudo cp builddir/ratbagd.service /etc/systemd/system/ratbagd.service

**Comment by georgettica** [comment]
as @sealvessel noted, as of now there is no macos solution for this.
please inform me if this is no longer the case (and we are able to build it on macos)
- my specific problem is I don't know what package will give me `libudev`
