### ISSUE TITLE
Add arch to CI tests?

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#513]
@whot are you interested in adding Arch Linux to the CI tests environment? If so, I recommend this being done with a `PKGBUILD` like it's done in [Tribler](https://github.com/Tribler/tribler-arch-pkgbuild).

**Comment by whot** [comment]
We have #515 open now, so let's close this bug and resolve the issues there so it gets resolved in the code now too. One less thing to think about when looking at the open issues :)
