### ISSUE TITLE
No active resolution for M705

### ISSUE THREAD

**Issue by davidovitch** [libratbag/libratbag#526]
I have a Logitech M705 mouse (sharing the same unified receiver with a Logitech MK700 keyboard), but the M705 does not have an `active resolution`.

This is what happens:
```
$ ratbagctl list
event4:    Logitech M705

$ ratbagctl profile active get event4
0

$ ratbagctl resolution active get event4
No active resolution. Please report this bug to the libratbag developers
0

$ ratbagctl dpi get event4
No active resolution. Please report this bug to the libratbag developers
0dpi

$ ratbagctl profile 0 get event4
Profile 0: (active)
Name : 'Profile 1'
Resolutions:
  0: <disabled>
Button: 0 type unknown is mapped to none
Button: 1 type unknown is mapped to none
Button: 2 type unknown is mapped to none

$ ratbagctl resolution 0 get event4
0: 800dpi @ 0Hz
```

UPDATE: For every `no active resolution` return message from librattag I get an `ratbagd[15026]: ratbagd error: event4: failed to fetch SVG` reported in the journal logs (systemd).

I am new to libratbag but wouldn't mind helping out debugging this issue if someone can point me in the right direction.

**Comment by Hjdskes** [comment]
See https://github.com/libratbag/piper/issues/239

Please try with the latest libratbag from git to see if that solves your problem.

**Comment by davidovitch** [comment]
Same outcome with latest git master. Not sure if it is relevant, but I am on Arch Linux and the [`libratbag` ](https://www.archlinux.org/packages/community/x86_64/libratbag/) package comes along with `ratbagd`, on Debian those seem to be two packaged separately (https://tracker.debian.org/pkg/ratbagd https://tracker.debian.org/pkg/libratbag).

**Comment by whot** [comment]
`ratbagd` used to be a separate package until we realised it's not ideal to do that and we merged it into libratbag itself. I expect debian will retire the separate package soon.

Attach the output of `sudo ./build/ratbag-command -vvv info /dev/input/event19` please, with the correct event node of course.

**Comment by davidovitch** [comment]
```
$ sudo ratbagctl -vvv info event4
event4 - Logitech M705
               SVG: /usr/share/libratbag/gnome/fallback.svg
      Capabilities: query-configuration
 Number of Buttons: 3
    Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
  Name : 'Profile 1'
  Resolutions:
    0: <disabled>
  Button: 0 type unknown is mapped to none
  Button: 1 type unknown is mapped to none
  Button: 2 type unknown is mapped to none
```
you refer to `ratbag-command`, I assume that should be `ratbagctl`?

**Comment by phomes** [comment]
This is for the M705 Marathon mouse. It speaks HID++1.0, but can only be
configured with logitechs set point software. This means that only very few
things can be configured and not multiple resolutions.

The device is picked up by fallback function for any logitech device
speaking HID++:
https://github.com/libratbag/libratbag/blob/master/src/libratbag.c#L381

**Comment by whot** [comment]
> you refer to ratbag-command, I assume that should be ratbagctl?

both exist, the former uses libratbag directly, the latter goes through ratbagd. In most cases `ratbagctl` is better, ratbag-command can be useful sometimes to get "closer" to the hardware.

Looks like we should make ratbagctl/ratbag-command provide more useful error messages in case there are no resolutions to configure.

**Comment by davidovitch** [comment]
The reason I couldn't find `ratbag-command` was that I was using the `libratbag-git` package form the Arch Linux User Repository (AUR), and that one does not include `ratbag-command` (only includes stuff that is put there after `ninja -C build install` I guess). It is present in the build directory (as you suggested). So here's the output from `ratbag-command`:
```
$ sudo ./ratbag-command -vvv info /dev/input/event4
[sudo] password for dave: 
ratbag debug: Logitech M705 is device '/dev/hidraw3'.
ratbag debug: report ID 02
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag raw: Fetching individual features
ratbag raw:   expected_header:		?? 00 81 01
ratbag raw:   expected_error_dev:	10 00 8f 81 01 00 00
ratbag raw: hidpp write: 10 00 81 01 00 00 00
ratbag raw: hidpp read:  10 01 81 01 02 00 00
ratbag raw:   received: 10 00 81 01 02 00 00
ratbag raw: Fetching HID++ notifications
ratbag raw:   expected_header:		?? 00 81 00
ratbag raw:   expected_error_dev:	10 00 8f 81 00 00 00
ratbag raw: hidpp write: 10 00 81 00 00 00 00
ratbag raw: hidpp read:  10 01 81 00 10 00 00
ratbag raw:   received: 10 00 81 00 10 00 00
ratbag raw: Fetching current resolution
ratbag raw:   expected_header:		?? 00 83 63
ratbag raw:   expected_error_dev:	10 00 8f 83 63 00 00
ratbag raw: hidpp write: 10 00 83 63 00 00 00
ratbag raw: hidpp read:  10 01 8f 83 63 01 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_SUBID (01)
ratbag raw: Fetching LED status
ratbag raw:   expected_header:		?? 00 81 51
ratbag raw:   expected_error_dev:	10 00 8f 81 51 00 00
ratbag raw: hidpp write: 10 00 81 51 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 51 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching USB refresh rate
ratbag raw:   expected_header:		?? 00 81 64
ratbag raw:   expected_error_dev:	10 00 8f 81 64 00 00
ratbag raw: hidpp write: 10 00 81 64 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 64 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching optical sensor settings
ratbag raw:   expected_header:		?? 00 81 61
ratbag raw:   expected_error_dev:	10 00 8f 81 61 00 00
ratbag raw: hidpp write: 10 00 81 61 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 61 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching current profile
ratbag raw:   expected_header:		?? 00 81 0f
ratbag raw:   expected_error_dev:	10 00 8f 81 0f 00 00
ratbag raw: hidpp write: 10 00 81 0f 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 0f 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag debug: no profile type given
ratbag raw: Fetching profile 0
ratbag debug: driver match found: Logitech HID++1.0
Traceback (most recent call last):
  File "./ratbag-command", line 2384, in <module>
    main(sys.argv[1:])
  File "./ratbag-command", line 2381, in main
    f(r, cmd)
  File "./ratbag-command", line 1119, in show_device
    print_device(d, 0)
  File "./ratbag-command", line 1099, in print_device
    with d.get_svg_fd('gnome') as fd:
  File "./ratbag-command", line 305, in get_svg_fd
    return open(self.get_svg(theme))
  File "./ratbag-command", line 293, in get_svg
    return os.path.join(LIBRATBAG_DATA_DIR, theme, libratbag.ratbag_device_get_svg_name(self._device))
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by FFY00** [comment]
@davidovitch just letting you an official package is available, in case you missed that.

https://www.archlinux.org/packages/community/x86_64/libratbag/
