### ISSUE TITLE
building libratbag, can't find libevdev

### ISSUE THREAD

**Issue by cotangity** [libratbag/libratbag#527]
I'm new so I apologize. 
I am trying to build libratbag so I can get piper working to program my mouse, but I've ran into a wall. At first it was gcc, then libudev, but now I'm stuck on libevdev. On fedora, I have 1.5.9-4.fc28 and the devel 1.5.9-5.fc29 installed but meson still can't find it and I'm not sure what is going wrong. Thanks for your time.

[meson-log.txt](https://github.com/libratbag/libratbag/files/2344155/meson-log.txt)

**Comment by whot** [comment]
`sudo dnf build-dep <packagename>` installs the required bits on fedora, or at least the ones used for the fedora package itself. Then it's just down to using the same config option, usually easiest by looking at the `.spec` file. Alternatively, and more generically, [this post here](https://who-t.blogspot.com/2018/07/meson-fails-with-native-dependency-not-found.html) describes how to fix things one-by-one.In your case, `sudo dnf install libevdev-devel` should do it, would be a bit strange to have a fc28 and f29 mix here.
