### ISSUE TITLE
G502 no active profile, no active resolution

### ISSUE THREAD

**Issue by BenFradella** [libratbag/libratbag#545]
I'm trying to get this software to run on ubuntu 18.04 and any function that makes a call to the current state of the mouse such as "profile active get", "LED get", "rate get", etc return the following errors:

```
ben@blackbox:~/piper$ ratbagctl rate get event4
No active profile. Please report this bug to the libratbag developers
No active resolution. Please report this bug to the libratbag developers
1000
ben@blackbox:~/piper$ ratbagctl profile active get event4
No active profile. Please report this bug to the libratbag developers
0
ben@blackbox:~/piper$ ratbagctl LED get event4
No active profile. Please report this bug to the libratbag developers
ben@blackbox:~/piper$ ratbagctl button count event4
No active profile. Please report this bug to the libratbag developers
11
ben@blackbox:~/piper$ ratbagctl dpi get event4
No active profile. Please report this bug to the libratbag developers
No active resolution. Please report this bug to the libratbag developers
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 2579, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ratbagctl", line 2575, in main
    f(r, cmd)
  File "/usr/bin/ratbagctl", line 1464, in func_dpi_get
    print("{}dpi".format(r.resolution[0]))
TypeError: 'NoneType' object is not subscriptable
ben@blackbox:~/piper$ ratbagctl resolution active get event4
No active profile. Please report this bug to the libratbag developers
No active resolution. Please report this bug to the libratbag developers
0
ben@blackbox:~/piper$ ratbagctl info event4
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 2579, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ratbagctl", line 2575, in main
    f(r, cmd)
  File "/usr/bin/ratbagctl", line 1311, in show_device
    print_device(d, 0)
  File "/usr/bin/ratbagctl", line 1287, in print_device
    capabilities = [caps[c] for c in d.capabilities]
  File "/usr/bin/ratbagctl", line 1287, in <listcomp>
    capabilities = [caps[c] for c in d.capabilities]
KeyError: 2
```

This is occuring with the latest version of libratbag from github.

I should note that I am dual booting linux and windows and that I had the mouse configured in windows previous to this. In the logitech software I configured it to turn off the LED's when the computer shut down so that they wouldn't bug me with the computer off. I dunno, maybe that caused it to load a 'None' profile and that broke libratbag?

**Comment by whot** [comment]
Does #547 help?

**Comment by BenFradella** [comment]
I rebooted into windows and switched the mouse from automatically detecting games to using profiles stored in memory on the mouse and that seemed to fix it? It may just have been the reboot that fixed it.

**Comment by whot** [comment]
Probably what fixed it was switching to the in-device memory. Before everything was software-controlled which is why ratbag got confused. Arguably we should detect that case (it's somewhere in the HID specs iirc) but apparently we don't.

Anyway, closing for now, please re-open if it comes back.
