### ISSUE TITLE
Onboard profile feature missing from Logitech G203

### ISSUE THREAD

**Issue by tdaede** [libratbag/libratbag#549]
In theory this should have it according to Logitech's website. libratbag seems to not pick up the capability - maybe it's just not detecting it properly, or a new way to save profiles was added?

**Comment by FFY00** [comment]
Could you send a log?

**Comment by FFY00** [comment]
I just tested it and it is working. The only thing is that you don't get multiple profiles, and this is because the mouse only has 1 onboard profile. If you change a setting and reconnect the device that setting is saved.

**Comment by tdaede** [comment]
Thanks. Sorry, this particular mouse already died on me, so I no longer have it to test.
