### ISSUE TITLE
Logitech G600 buttons 6 & 7 appear to be swapped

### ISSUE THREAD

**Issue by foresto** [libratbag/libratbag#550]
Piper displays the mappings for my Logitech G600 buttons, but buttons 6 & 7 appear swapped: The assignment for the upper button is shown on the lower one, and vice-versa.

**Comment by whot** [comment]
does it work with the above fix?

**Comment by foresto** [comment]
Yep, that fixes it on my system.

**Comment by whot** [comment]
thanks!
