### ISSUE TITLE
Roccat Kone Aimo support?

### ISSUE THREAD

**Issue by DevYama** [libratbag/libratbag#551]
Any plans for supporting Roccat Kone Aimo?

**Comment by bentiss** [comment]
TL;DR: not that I know of, but contributions are welcome :)

Long version: the Roccat implementation in libratbag was a way for us to see if the API was working also on those mice. We haven't invested much in term of time in Roccat devices, because reverse engineering a mouse takes time and we have a million things to do. One other problem is that we all have other urgent work related tasks that takes precedence over libratabg. Sadly.

Still, we would gladly accept any PR regarding a reverse engineering of this mouse.

**Comment by DevYama** [comment]
Gotcha! I'd definitely contribute if I were a programmer, but sadly I'm not. Thank you for a reply!

**Comment by bentiss** [comment]
OK. THen closing this bug. If anyone wants to contribute, you are welcome :)

**Comment by Metaln00b** [comment]
I sniffed the USB transfer, maybe a simple python script can make the LED's work.

IRP = E2A95010
Type = URB

VID=1E7D
PID=2E27
2 Pipes: 1xMouse, 1x Keyboard (for Macro Buttons)

Numbering the LED's
1 = Scroll-Wheel
Anti-clockwhise starting at the scroll-wheel, right up etc.

0E | 06 | 01 | 01 | 00 | FF |   | 2 times send maybe init command |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   | Brightness 00-FF for each LED |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Address |   | LED1 |   |   |   | LED9 |   |   |   | LED8 |   |   |   | LED7 |   |   |   | LED6 |   |   |   |   | LED2 |   |   |   | LED3 |   |   |   | LED4 |   |   |   | LED5 |   |   |   |   |   |   |   |   |   |  
0D | 2E | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00 | 00
  |   | RED | GRN | BLU |   | RED | GRN | BLU |   | RED | GRN | BLU |   | RED | GRN | BLU |   | RED | GRN | BLU |   | GRN | RED | BLU |   | GRN | RED | BLU |   | GRN | RED | BLU |   | GRN | RED | BLU |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  



Follow this way [https://blog.danman.eu/usb-switch-for-2-pc-under-linux/](url)

**Comment by ninnghazad** [comment]
@Metaln00b  do you still have the trace data?

**Comment by Metaln00b** [comment]
> @Metaln00b do you still have the trace data?

I am going to upload it in the next few days okay, or you just use wireshark with USBPCAP.

**Comment by ninnghazad** [comment]
@Metaln00b that'd be nice - i don't have windows to capture with.

**Comment by Metaln00b** [comment]
[Kone_Aimo.pcapng.gz](https://github.com/libratbag/libratbag/files/4098782/Kone_Aimo.pcapng.gz)

**Comment by Metaln00b** [comment]
I have moved the mouse and pressed all buttons with and without running Roccat SWARM,  so that you have the initializing data, too.

- [Kone_Aimo_Init.pcapng.gz](https://github.com/libratbag/libratbag/files/4104295/Kone_Aimo_Init.pcapng.gz)

**Comment by ninnghazad** [comment]
try https://github.com/ninnghazad/roccat_kone_aimo
the aimo.py can set the color - animating the color doesn't quite work as i thought. apparently pyusb/libusb and the kernel hidraw driver conflict and you can't do both at once. however, this should be enough to set some color once the mouse is plugged in.

**Comment by ninnghazad** [comment]
@Metaln00b I also finished a cpp version which can be used in scripts to do animations with the leds. It just needs the hidraw driver, but on my system that was the default anyhow.

**Comment by Metaln00b** [comment]
@ninnghazad Hey that looks very nice. I will try it out.  Thank you very much.
