### ISSUE TITLE
Broken install of libratbag/piper on Ubuntu 18.04

### ISSUE THREAD

**Issue by PierreCapo** [libratbag/libratbag#553]
Hello ! First, thanks a lot for this library, it's really awesome to have tools like that for Linux gamers.

I tried to install libratbag and piper on Ubuntu, but it didn't go wo well. First I tried to install libratbag from the ppa : https://launchpad.net/%7Etrebelnik-stefina/+archive/ubuntu/ratbag-piper

```
$ sudo apt install libratbag
[...]
Setting up libratbag (0.9.903.0~bionic) ...
Failed to enable unit: Unit file /etc/systemd/system/ratbagd.service is masked.
dpkg: error processing package libratbag (--configure):
 installed libratbag package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 libratbag
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

And this is what I got. Then when I try to install piper it says that libratbag is not configured
```
$ sudo apt install piper
[...]
dpkg: dependency problems prevent configuration of piper:
 piper depends on libratbag; however:
  Package libratbag is not configured yet.

dpkg: error processing package piper (--configure):
 dependency problems - leaving unconfigured
```

Note that running `sudo ratbagd --verbose ` outputs:
```
$ sudo ratbagd --verbose 
ratbag debug: Logitech Gaming Mouse G502 is device '/dev/hidraw0'.
ratbag debug: Logitech Gaming Mouse G502 is device '/dev/hidraw1'.
ratbag debug: report ID 01
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: 'Logitech Gaming Mouse G502' is using protocol v4.2
ratbag debug: device has color effects
ratbag debug: device has non-rgb leds
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1200 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has 4 report rates
ratbag debug: device has onboard profiles
ratbag debug: device is using ROM settings
ratbag debug: ROM settings loaded
ratbag debug: device has configurable mouse button spy
ratbag debug: driver match found: Logitech HID++2.0
event2: "Logitech Gaming Mouse G502", 3 profiles
```

Any idea how to fix it ?

**Comment by FFY00** [comment]
That's an issue with the package itself which isn't provided by us. You should be able to build it from source.

**Comment by whot** [comment]
Indeed, I recommend contacting the PPA maintainer instead, we don't know how that package is built.

**Comment by PierreCapo** [comment]
Alright thanks for your fast answers. It would be super cool that you release a package with libratbagd/piper because I have had hard time building it from source, and I just think I'm going to surrender since I've spent some hours already without succeed. I feel it would be a really good improvement to have a package which is more user friendly than building a software from source, especially because this package is a super nice tool.

**Comment by whot** [comment]
piper has a flatpak available on flathub, but libratbag cannot be packaged as flatpak due to technical restrictions. we don't do distribution packages because there are too many of them to keep track of and we're suffering from lack of time as it is. I recommend you ping your distribution to update the package there, otherwise, building from source is your only option at this point.

**Comment by muzena** [comment]
@PierreCapo 
I will try to fix this tomorrow.
I entered wrong install dependency in debian build file.

**Comment by muzena** [comment]
@PierreCapo 
Try now, I think it should work now.

**Comment by PierreCapo** [comment]
@muzena Good job man, it's working like a charm.
Tested on Ubuntu 18.10 : 
```
sudo add-apt-repository ppa:trebelnik-stefina/ratbag-piper
sudo apt-get update
sudo apt-get install ratbagd
sudo apt-get install piper
```
And it works perfectly !

Those commands should really be in the Readme or somewhere else in the doc, it would be definitely more user friendly for new comers in order to run this awesome library.
Thanks for your fast replies and availability guys

**Comment by muzena** [comment]
@PierreCapo 
[New PPA](https://github.com/libratbag/libratbag/wiki/Installation)

**Comment by erdincay** [comment]
there is following command, that installs most dependencies: 

`sudo apt install cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig`

I for my part, needed following on Pop! 20.04 (Ubuntu 20.04): 

**`sudo apt install libjson-glib-dev
sudo apt install libunistring-dev
sudo apt install python-gi-dev
sudo apt install libsystemd-dev
sudo apt install python3.8-dev
sudo apt install python3.8-full
sudo apt install swig
sudo apt install check`**
