### ISSUE TITLE
Support for Logitech's "G Pro Wireless" Mouse?

### ISSUE THREAD

**Issue by n1ete** [libratbag/libratbag#554]
Any Chance that this Mouse is going to Work?
thanks for some hints and for this awesome missing piece of integration on linux
;)

**Comment by whot** [comment]
The wired configuration just got merged as part of #555, so I suspect the wireless entry may just be another `DeviceMatch` line in that file. Give it a try, you may be lucky :)

**Comment by exlevan** [comment]
Configuration of G Pro Wireless works for me, but only in wireless mode, and it lets configure 2 additional buttons under the wheel, which are not present on the mouse.

**Comment by FFY00** [comment]
@exlevan please try it with the cord instead of the wireless receiver. It is working properly for me. Linux 5.2 will bring proper support for the wireless receiver.

**Comment by FFY00** [comment]
Closing this as the mouse does work.

**Comment by exlevan** [comment]
@FFY00 I've tried configuring the mouse with cord in Piper and the LED settings work. The only problems I see is in button configuration the middle and left buttons are swapped, and the button settings aren't updated until I restart Piper. The latter seems to be a UI-only problem, as the mouse behavior is changed as soon as I press "Apply".

**Comment by FFY00** [comment]
The first issue should be fixed by https://github.com/libratbag/piper/commit/e4d35e4bca6f1506235a4356e8af1d156bf5c31e. The second one is a piper issue,`ratbagctl` works as expected. Please open an issue in piper.

**Comment by exlevan** [comment]
Tried again with git versions of ratbag and piper, everything seems to work fine, including the UI.
