### ISSUE TITLE
Request: Roccat Tyon and Leadr support

### ISSUE THREAD

**Issue by jcfrosty** [libratbag/libratbag#557]
The Roccat Tyon and Leadr have the same layouts so the same image could be used between the two. I'll be honest, I'm not sure what would be required to add support for these devices, but I'd be willing to donate enough money so the dev could purchase one of each of these mice to assist with development. I own one of each (Tyon for work, Leadr for home). I'd even be willing to work with someone who'd be willing to teach me how to reverse engineer and code for this (I already have some very basic coding knowledge).

**Comment by whot** [comment]
just fwiw, money to purchase the devices is usually less of an issue as finding the time. but yeah, we suck at writing documentation in a central place to help new users with reverse-engineering a new mouse. I think the best resource right now is @phomes [fosdem talk](https://archive.fosdem.org/2018/schedule/event/hwenablement_adding_a_mouse_to_libratbag/)

**Comment by jcfrosty** [comment]
Nice Video, I'm considering trying this on my Leadr and Tyon. Right now, we only support the kone according to the devices list which is one of seven available roccat mice.. I'm trying to understand if the driver in src folder is roccat universal or directly geared for the kone? I'm also curious if the kone driver (as it has 4 variations) supports all models or just one kone model? the LED max of Zero confuses me and makes be believe it does not. I guess my best lead currently would be to contact @phomes and learn a little more about the driver? 

I apologize, I'm a total noob when it comes to stuff like this. Its not that I'm not interested, I've just never had a goal to code anything beyond a grade in school over 6 years ago. I'd like to help as I really love my roccat gear, and am disappointed the only tool we had is no longer maintained. I'm not good enough at coding to revive it or do much of it myself, but if I had some guidance and a mentor, I could probably learn and help somewhere.

**Comment by vanillajonathan** [comment]
@jcfrosty Run the command `lsusb` to get the USB device identifier.

**Comment by wisemonkey** [comment]
I wouldn't mind helping with this either. I would like to know however how to decide usbpcap port / device to monitor.
It seems to be as easy as running USBPcapCMD.exe and it should provide the info. However when I run this it seems all my USB devices are on single hub, is that correct (please refer to attachment)? If yes is there way to distinguish / capture only one of all these devices?
![capture](https://user-images.githubusercontent.com/537206/49568599-53fc2480-f8e6-11e8-9d5b-f8b6d35144d1.PNG)

If my understanding is not correct then does that mean USBPcap can't detect the mouse? (Roccat swarm works correctly)

**Comment by jcfrosty** [comment]
I think this can be avoided if running Windows 10 in a VM and passing
through the USB device while using wireshark in Linux to capture. Then
everything input-wise is either VirtIO or emulated PS2 ports (you can
emulate USB, but PS2 is default for qemu/kvm). The only thing on USB should
be what you pass through.

**Comment by wisemonkey** [comment]
Only Windows I've is on the Laptop and Laptop didn't come with install media. If I can't use it in standalone Windows, I'll see if I can buy the Windows10 for VBox.

**Comment by jcfrosty** [comment]
You don't have to buy Windows10 for VBox... You can download the ISO from
Microsoft's website and just not activate it. Catch is you'd have to
install it every few months (I can't recall its somewhere around 30-90 days
without activation), but you're only using it for a specific task so it
shouldn't be an issue.

**Comment by wisemonkey** [comment]
Ok I got Windows installed in VM. Roccat Swarm is installed in Windows. Here are few things:
1. Roccat swarm doesn't detect mouse until I pass it through USB capture, after that Swarm can detect mouse and change settings (which are persistent when capture is stopped)
2. USBPcap in windows still has something similar output as posted before

**Comment by jcfrosty** [comment]
USPPcap in windows isn't what you want to use. You want to use wireshark in
the host operating system (Linux) to sniff the USB bus for the packets
coming across it from the VM (Windows).

**Comment by wisemonkey** [comment]
I guess it would be same packets as seen in VM guest ? I'll try that as well.

**Comment by wisemonkey** [comment]
is there an IRC / discussion forum to figure out protocol?
I started looking at dump but would definitely like to discuss findings with people who went through process

**Comment by whot** [comment]
there's #libratbag on freenode, but it's a very quiet channel

**Comment by jcfrosty** [comment]
Roccat TYON : 1e7d:2e4a
Roccat Leadr : 1e7d:2e4e

The Tyon and Leadr have an identical layout. One is wired, one is wireless. One has a better optical sensor. Other than that, I'm assuming they are identical. 

I now have a windows 10 VM running on my machine, I have wireguard on my linux machine. I'm gonna need some guidance beyond here.Using wireguard to capture packets from USB is a new thing to me.

**Comment by FFY00** [comment]
I think you mean Wireshark :smile:.

**Comment by jcfrosty** [comment]
OK, so I've tried watching some [youtube videos](https://youtu.be/GdvmsWnZkyc) on how to do this. basically I've plugged the mouse into a port that is somewhat "isolated" to its own bus.
jcfrosty@Zero ~ $ lsusb
Bus 009 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 010 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 033: ID 1e7d:3098 ROCCAT 
Bus 007 Device 035: ID 09ea:0131  
Bus 007 Device 034: ID 1e7d:2e4e ROCCAT 
Bus 007 Device 032: ID 09ea:0130  
Bus 007 Device 031: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 007 Device 003: ID 8087:0029 Intel Corp. 
Bus 007 Device 002: ID 1050:0407 Yubico.com Yubikey 4 OTP+U2F+CCID
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 003: ID 1e7d:2e4a ROCCAT   <<<<<<< This is the TYON. <<<<<<
Bus 005 Device 002: ID 1e71:170e NZXT 
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 008: ID 05e3:0612 Genesys Logic, Inc. Hub
Bus 002 Device 005: ID 0451:8240 Texas Instruments, Inc. 
Bus 002 Device 004: ID 05e3:0612 Genesys Logic, Inc. Hub
Bus 002 Device 006: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
Bus 002 Device 003: ID 0bda:0411 Realtek Semiconductor Corp. 
Bus 002 Device 002: ID 0bda:0420 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 014: ID 046d:0841 Logitech, Inc. 
Bus 001 Device 015: ID 1e7d:3750 ROCCAT 
Bus 001 Device 011: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 006: ID 0451:8242 Texas Instruments, Inc. 
Bus 001 Device 004: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 003: ID 0bda:5411 Realtek Semiconductor Corp. 
Bus 001 Device 007: ID 0764:0501 Cyber Power System, Inc. CP1500 AVR UPS
Bus 001 Device 002: ID 0bda:5420 Realtek Semiconductor Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

After that I open up wireshark and I select usbmon5 (because my mouse is on BUS 005).
Then I start watching for data on source and/or destination of 5.3.X because BUS 005 and Device 003 is the TYON mouse. the polling rate is 1000hz so lots of data is flying across at this moment. What exactly am I to be taking from this?? Should I be pressing buttons and reading Line 0020 second half is the request and Line 0040 onward is the reply? Do I need to acquire a list of these requests and responses?

If yes, how does that work once the button is configured to something else? Or should I be using the software to configure the mouse one button at a time and seeing capturing the config push? Where should I start on the capturing?

**Comment by FFY00** [comment]
You should look for `Leftover Capture Data` or `Data Fragment`.

**Comment by madmalkav** [comment]
I'm also considering purchasing a Leadr, and just discovered the good oldl roccat driver is not longer adding new devices since 2017, so Tyon is supported but not Leadr. I just read on 2017 that someone got the old roccat driver to somewhat work with the Leadr, in that case that code can probe to be a useful reference. This is the link to the reddit message I was refering to:

https://www.reddit.com/r/Roccat/comments/ftbtie/linux_support_for_leadr/

And this to the old roccat driver:

http://roccat.sourceforge.net/
https://sourceforge.net/projects/roccat/files/

**Comment by FFY00** [comment]
Hey, can someone confirm that the Roccat Leadr saves the keybinds after they are configured on windows? This means they have support to rebind keys in hardware.

cc @Vild

**Comment by jcfrosty** [comment]
Yes it sticks, I dunno about macros though. I do not believe macros stick.

**Comment by FFY00** [comment]
Okay, so rebinds stick, just not macros.

**Comment by wisemonkey** [comment]
Here is how rebind save works:
Key rebinds stick until you unplug the mouse, so there is no persistent memory.
Also if you passed mouse through USB menu of Virtual Box to Windows, for configuring.
Mouse must be taken out from passthrough USB before turning off Windows, otherwise binds are forgotten

**Comment by jcfrosty** [comment]
Interesting, is this new behavior? Neither my Tyon or Leadr act this way.
Both their bindings stick. Maybe it's specific binding types? My Tyon is
used on the go in my backpack. It was a set and forget scenario.  My Leadr
stays connected to my Desktop which only has a Windows VM for configuring
the mouse, but the mouse is wireless and does have a battery so since it's
never "off" maybe that's why my bindings stuck? The only time I've had
issues with the bindings not sticking after Windows shuts down (needing to
remove from VM before shutdown) is my Roccat Vulcan keyboard.

**Comment by FFY00** [comment]
Hey guys. `usbhid.data` annotations just landed in Wireshark master (https://github.com/wireshark/wireshark/commit/f1bc8ad34b55cba7234536483d42c551fc3b2f17), this should make it much easier for people trying to reverse engineer the protocols. Just use the `usbhid.data` filter. You can also apply the field as a column by right-clicking on it, which should be helpful.

**Comment by cet** [comment]
I thought Roccat themselves were helpful with giving information about how their mice worked before, has that stopped? I remember having a Kova+ for years, and found the Open Source driver linked from their pages..? Has someone tried asking for information from them? I have the Leadr too... Awesome mouse, but unfortunately no Linux driver as of yet... Also, I'm no programmer, but a 3D-geek... xD I would love to customize my setup working with Blender with this mouse.

**Comment by SephGER** [comment]
I am trying to reverse engineer the Leadr with wireshark but some buttons don't even send signals. Has anyone any idea why that could be?

**Comment by JaxxArmstrong** [comment]
Roccat Tyon (Linux Mint v20.2):  ID 1e7d:2e4a ROCCAT ROCCAT Tyon Black
