### ISSUE TITLE
Powerplay Receiver RGB Support

### ISSUE THREAD

**Issue by spyfly** [libratbag/libratbag#575]
It would be a nice addition, if the color of the Powerplay Receiver could be configured through Piper.

**Comment by whot** [comment]
[This one here](https://www.logitechg.com/en-au/products/gaming-mouse-pads/powerplay-wireless-charging.html)?

If so, it's not really a mouse and slightly out of scope. We could probably just expose the LEDs and with the right SVG piper would do the same thing.

Not sure what type of protocol it uses though, could be HID++. Best way to start would be to add a `.device` file and see what comes up when you run `ratbag-command --verbose`

**Comment by spyfly** [comment]
@whot alright, I'll take a look.

**Comment by spyfly** [comment]
> [This one here](https://www.logitechg.com/en-au/products/gaming-mouse-pads/powerplay-wireless-charging.html)?
> 
> If so, it's not really a mouse and slightly out of scope. We could probably just expose the LEDs and with the right SVG piper would do the same thing.
> 
> Not sure what type of protocol it uses though, could be HID++. Best way to start would be to add a `.device` file and see what comes up when you run `ratbag-command --verbose`

Piper has had a device file for it for quite a while now: https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-gpowerplay-wireless.device

Running ratbagd --verbose gives me the following output
```$ sudo ratbagd --verbose
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw4'.
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw5'.
ratbag debug: report ID 02
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw6'.
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: 'Logitech USB Receiver Mouse' is using protocol v4.2
ratbag debug: device has adjustable dpi
ratbag debug: device is at 800 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has 4 report rates
ratbag debug: device has onboard profiles
ratbag debug: device is using ROM settings
ratbag debug: ROM settings loaded
ratbag debug: device has configurable mouse button spy
ratbag debug: device has color effects
ratbag debug: device has non-rgb leds
ratbag debug: driver match found: Logitech HID++2.0
event9: "Logitech USB Receiver Mouse", 5 profiles
```

**Comment by jyp** [comment]
I can't understand the status of this. I the device configurable using `ratbagctl`? If not, what needs to be done so that it works?

**Comment by whot** [comment]
the output from @spyfly suggests that libratbag detects it and can identify bits. beyond that I'm not sure, but we're very seriously ETIME on libratbag atm. I barely get to read all the email I get every day. Maybe @FFY00 has time to have a look.

**Comment by bentiss** [comment]
> Maybe @FFY00 has time to have a look.

Yep, it could be nice is @FFY00 could:
- add the USB ID of the powerplay receiver in the kernel (in hid-logitech-dj.c)
- see how it behaves, if there is a new hidpp device for the LED part
- then look for the support of this new device in libratbag.

However, I am not so sure @FFY00 will be ready until a few days, he is just starting his new internship AFAICT

**Comment by jyp** [comment]
FWIW, ratbag can control the led of the mouse even when connected through the powerplay mat receiver. The only issue appears to be to control the led of the mat itself.

**Comment by FFY00** [comment]
Yes, because the powerplay acts as a receiver. I haven't been able to get my hands on one but I expect it to export another HID++ for the mat itself.

**Comment by mattheweigand** [comment]
I have one of these too, but I don't know what to do to make it work. If anyone wants to give me some suggestions I'd apprecaite it.

**Comment by FFY00** [comment]
What's blocking this is the kernel driver. We need to make it handle receiver read-only HID++ devices properly.

**Comment by jyp** [comment]
@FFY00 If I understand correctly your patch https://patchwork.kernel.org/patch/11335659/ was merged. Does this mean progress? Regardless, thanks a lot for your work on this issue :)

**Comment by FFY00** [comment]
Yes! This was actually resolved in https://github.com/libratbag/libratbag/commit/f0a05bb5229b1a6b0e64b251dd2b64f8f5c76ef2 but never closed. You need a recent enough kernel, for that patch, and libratbag 0.13. Are you having any issues getting your device to work?

**Comment by mattheweigand** [comment]
Even though I have a Powerplay Receiver, I only see the wireless mouse associated with it listed in ratbag, no Powerplay device.

**Comment by stiangrindvoll** [comment]
> Even though I have a Powerplay Receiver, I only see the wireless mouse associated with it listed in ratbag, no Powerplay device.

What kernel are you using?

**Comment by jyp** [comment]
I am also only seeing one device. Here is my info
```
$ ratbagctl list
thundering-gerbil:   Logitech G903        
$ uname -rv
5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
$ ratbagctl --version
0.13
```

**Comment by FFY00** [comment]
I just pushed https://github.com/FFY00/lshid, can run it and show me the output? You should see `ID 046d:405f Logitech Candy` just like the example, this is the HID device the kernel should export for the powerplay itself.

**Comment by stiangrindvoll** [comment]
I had the default ubuntu 5.4.0-xx kernel as well, and can confirm that after testing a newer kernel, i can now control the LED on the Powerplay too.
```
Device /dev/hidraw15: ID 046d:405f Logitech Candy
Device /dev/hidraw14: ID 046d:4079 Logitech G Pro
```

**Comment by FFY00** [comment]
Is anyone still having issues or can I close this?

**Comment by mattheweigand** [comment]
> > Even though I have a Powerplay Receiver, I only see the wireless mouse associated with it listed in ratbag, no Powerplay device.
> 
> What kernel are you using?

$ uname -rv
5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC

I guess that kernel is too mainstream for this. How high up to I have to go to get it to work? I tried 5.6 for an unrelated issue and it doesn't work with my nvidia card.

**Comment by stiangrindvoll** [comment]
I haven't checked what the minimum required kernel is, but i went with the 5.8.8, for nvidia, i already have updated the drivers through the graphics-drivers ppa: https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

Do so at your own risk though :)
If you wanna wait, ubuntu 20.10 is not that far away. I would imagine their kernel and drivers are more up to date.

**Comment by FFY00** [comment]
You need https://github.com/torvalds/linux/commit/8c9d734cdffc6e41344653ae9884feece33b4f92, so Linux 5.7.

**Comment by FFY00** [comment]
Can this be closed? Is anyone still having issues?

**Comment by stiangrindvoll** [comment]
I think this can be closed! Any new issues arising from this I'm sure will be asked for!
