### ISSUE TITLE
G900 used instead of G Pro Wireless due to same DeviceMatch id

### ISSUE THREAD

**Issue by akstrfn** [libratbag/libratbag#579]
G900 and G Pro have the same DeviceMatch=usb:046d:c539 and even though the repo now has G Pro Wireless support, svg file of G900 is used instead of G Pro Wireless. When the mouse is connected with a wire, it is properly recognized due to different DeviceMatch.

Some details of the problem can be found in PR #571 but since that PR is closed I opened this issue to further track the problem.

**Comment by whot** [comment]
Just found #380 which explains the issue and what is required to fix it.

**Comment by akstrfn** [comment]
I guess the best is to wait for the kernel to implement it. You would not accept some workarounds like #381?

**Comment by whot** [comment]
I'd prefer the energy to be spent on fixing it in the correct place :)

**Comment by akstrfn** [comment]
Makes sense :smile:

**Comment by davidovitch** [comment]
For the record, should be fixed in combination with Linux 5.2: a04f2d1c24ab390213c313ace0e274a3db9922ef. See also https://www.phoronix.com/scan.php?page=news_item&px=Better-Logitech-Linux-5.2

**Comment by akstrfn** [comment]
In the next weeks when 5.2 lands in my distro I'll do the tests.

**Comment by FFY00** [comment]
The wireless PID (WPID) still needs to be added to the device file.

**Comment by aTosser** [comment]
The WPID for G Pro Wireless is 4079 I have already made this change on my fork of both piper and libratbag and will submit PR when linux 5.2 is released.

**Comment by FFY00** [comment]
@aTosser feel free to submit right now if you want :grin:.

**Comment by aTosser** [comment]
I would prefer to wait until the WPID of the G900 is known. The USB receiver still shows up on Kernel 5.2. After updating all of the files for the G Pro W, I was getting duplicate entries because of the receive PID being in the G900 files. I don't want to remove the USB receiver from the G900 files but I also do not want duplicate devices showing up for anyone using G Pro W. When someone can tell me the WPID fro G900 We can just hit it all in one swoop.

**Comment by bentiss** [comment]
AFAICT: https://github.com/libratbag/libratbag/commit/a04f2d1c24ab390213c313ace0e274a3db9922ef#diff-7bac8358e9b0ad1f5a1fea627b59d0d4 already added the WPID of my G900 and G403 :)

**Comment by aTosser** [comment]
The WPID for the G903 and G603 still need to be corrected as the logitech-lightspeed.device will have to be removed. There will still be duplicate devices detected otherwise. These are the only 2 remaining lightspeed devices. Once that is the case there will be no devices using 046d:c539.

**Comment by FFY00** [comment]
@aTosser you are getting duplicated entries because the `c539` is incorrectly present in the G Pro Wireless .device file.

**Comment by FFY00** [comment]
Fixed in the last release. Make sure you have Linux 5.2.

**Comment by akstrfn** [comment]
Seems that everything works fine. Cheers!
