### ISSUE TITLE
No way to identify device in hidpp20

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#611]
There's a way to identify the mouse (get mouse name, id or something like that) in the hidpp20 protocol since the official driver does this. That should be implemented so that piper/ratbagctl can correctly identify devices that use the same usb receiver.

Devices that would benefit from this:
  - G900, G903, G603 and G403

**Comment by bentiss** [comment]
See #380 #579 

And for the record, I am currently working on that particular feature in the kernel, a WIP can be found there: https://github.com/bentiss/linux/tree/misc-v5.0-rc2+

**Comment by FFY00** [comment]
Sorry about that. Do you also plan to add it to libratbag? I can give it a try when my exams finish.

**Comment by bentiss** [comment]
> Do you also plan to add it to libratbag?

No, not really. When the kernel job is in place, we will just have to add the new PID in libratbag and done. The wireless mice will be indistinguishable from wired ones.

(and no worries for opening a new bug)

**Comment by FFY00** [comment]
Anything else, I could help with in the development of the HID++ 2.0 driver? I'll probably be tackling https://github.com/libratbag/libratbag/issues/574 so that might be a good way to extend my knowledge about HID++ 2.0.

**Comment by bentiss** [comment]
I think the biggest missing point for hidpp20 right now is the general macro write support.
However, I am not sure this would be the smartest choice to dive into the code if you don't have the specs. And unfortunately, I can not share those specs, they were released to us under NDA.

Writing a macro should be the opposite of reading one, but I don't know how easy it would be to implement if you are not familiar with the driver.
BTW, the problem with writing macro is not so much the conversion from libratbag to the internal Logitech language, but more the internal memory management. A simple solution would be to rewrite the whole memory when you write a new macro, but I think we should be smarter, and this leads to fragmentation issues, reallocation, etc...

**Comment by FFY00** [comment]
Okay, thank. I might play with it if I have time. If there's any other thing I could help with, please let me know.

**Comment by cvuchener** [comment]
How do you handle macros that are too complex for libratbag interface? You cannot simply ignore them. You still need to be able to relocate them, or, at least, know the space they occupy (but I think managing fragmented memory is harder than relocating everything). Or do you think libratbag should delete them?

**Comment by bentiss** [comment]
> How do you handle macros that are too complex for libratbag interface?

We are in the driver. The driver knows about all macros, and should be able to deal with currently stored macros, not just the ones the libratbag API is capable of expressing.

> You cannot simply ignore them.

nope, see above.

> You still need to be able to relocate them, or, at least, know the space they occupy (but I think managing fragmented memory is harder than relocating everything).

Both should be doable. The existing parser should already be capable of counting the space of those special macros. If not, then it should be a bug (maybe not fully implemented, but this is something that needs to be fixed).

So from the driver point of view, we should be able to know all of the existing macros, and their space. So reallocating them or not overriding them is something doable.

> Or do you think libratbag should delete them?

Nope. We should not mess up with existing configuration, unless expressively asked by the user. If we were to remove them, what would be the new assignment? We can't decide.

**Comment by cvuchener** [comment]
> Both should be doable. The existing parser should already be capable of counting the space of those special macros. If not, then it should be a bug (maybe not fully implemented, but this is something that needs to be fixed).

Right, I was mixing things up with hidpp10. I was thinking about branching macros. As far as I know hidpp20 does not have conditional jumps (are you able to confirm that?), so macro are linear. Adding the missing opcodes or guessing the size (0x0? = 1 byte, 0x2? = 2 bytes, 0x4? = 3 bytes, 0x6? = 5 bytes) should be enough.

**Comment by bentiss** [comment]
> I was thinking about branching macros. As far as I know hidpp20 does not have conditional jumps (are you able to confirm that?), so macro are linear

A quick look at the doc shows that there is no conditional besides `WaitForRelease`, `RepeatWhilePressed` and `RepeatUntilCancel`. The `jump` command is here too. So I *think* there is no conditional jumps.

But even if there were, the **driver** should be able to read and parse entirely the macro, and get the full allocated data used by the macro. So conditional jumps should not be an issue either.

**Comment by cvuchener** [comment]
> RepeatUntilCancel

I always thought it should be called that, but I never found how to cancel macros.

> the driver should be able to read and parse entirely the macro

I think the current hidpp10 code will miss a part of a macro if there is a conditional jump whose target is after an end marker (it is a weird case but it is possible).

Conditional jumps are also harder to relocate because you need to compute the new destination address.

**Comment by bentiss** [comment]
```
RepeatUntilCancel: The Macro is replayed as long as a dedicated Cancel button is not pressed
```

So I guess there must be a `cancel` action we can assign. And this probably must be the `0x1X | Sect Lo | Addr Hi | Addr Lo: Stop the macro @(Sector : Address)` definition
