### ISSUE TITLE
Keep a change log

### ISSUE THREAD

**Issue by theMarix** [libratbag/libratbag#612]
It would be neat if a change log was kept in the repository or the documentation so that I, as a user or distribution package maintainer, can get an overview of new capabilities and changed behaviour in new versions without having to read through all commits.

The problem with reading through commit logs is that they are noisy and written from the perspective of how the code changes. A change log could focus on what changes for a user. E.g, the entry for version 0.9.904 could look like this:

  * Added Devices:
    + Logitech G PowerPlay
    + Logitech G Pro
    + Logitech G402
    + Logitech G502 HERO
    + Logitech MX Anywhere 2
    + Logitech MX Anywhere 2S
    + Logitech MX Master 2S
    + Steelseries Rival 600
  * Improved Devices:
    + All supported Roccat Devices
    + Logitech G102/203
    + Logitech G502
    + Logitech G600
    + Logitech G603
    + Logitech G903
    + Logitech MX Master
  * Improved error messages provided by the command line tools.

**Comment by bentiss** [comment]
That's exactly what we are already doing:
https://lists.freedesktop.org/archives/input-tools/2019-January/001495.html

Every new libratbag (or piper FWIW) release gets announced on this list, and we (maintainers) parse the commit history and provide a release log.

**Comment by theMarix** [comment]
Thanks, I was not aware of this.

**Comment by bentiss** [comment]
Well, we *could* improve the process by adding those release notes to the release page of github, but that would be more work from us :)

Not sure if the non committer can add data in the release notes github page

**Comment by whot** [comment]
@theMarix: congratulations, you now have write access to the wiki! :)
