### ISSUE TITLE
Rename logitech-g900-wireless.device to logitech-lightspeed.device?

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#614]
There are a lot of mice using this Lightspeed connector, I think it would make more sense to rename the device file `logitech-lightspeed.device`.

**Comment by whot** [comment]
yeah, we should change the svg to something more generic and add a wiki page explaining what's going on here. Once the kernel patches are in place, we should even be able to leave this one in, presumably the new files will then just work.

**Comment by FFY00** [comment]
Yeah, I though the same about the svg file but then I remembered it won't really matter when the kernel patches get upstreamed.

Perhaps we could still make the new svg file for users that don't meet the kernel version requirements or have the driver disabled.

**Comment by whot** [comment]
@FFY00 want to send us a MR for this? Fame and fortune guaranteed*


\* this is not a guarantee.
