### ISSUE TITLE
Maxxter mouse support 

### ISSUE THREAD

**Issue by Macribit** [libratbag/libratbag#615]
HI I'm trying to make this mouse work, I think is branded different in several countries but the driver is Maxxter

`Bus 001 Device 003: ID 18f8:0f97 [Maxxter] `

now if I do this , it says, 4 profiles detected which is good, because the only thing I'm interested is changing the DPI.
```
sudo ./ratbagctl.devel --verbose info event2
test_device: "Test device", 4 profiles
Unable to find device event2
```

now I don't know how to continue from here.

I added the device id into /usr/share/libratbag/devices but I doesn't seem to work
```

[Device]
Name=Maxxter
DeviceMatch=usb:18f8:0f97
Driver=hidpp10
```

**Comment by FFY00** [comment]
I don't think it is supported by any of the protocols implemented.

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.
