### ISSUE TITLE
Move the SVGs from libratbag to piper

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#628]
Right now, ratbagd provides the SVGs to client. The SVGs are themed, with the theory that different clients can load differently-looking SVGs. Realistically we only have one theme: "gnome", used by piper. No-one has shown interest in other themes, including the original few SVGs we had before piper.

I'm proposing removing the themes from libratbag and pushing them into piper.
- there is nothing about the API that specifies what the SVG does, beyond "it's an SVG". This is problematic, because:
- the theme is a "piper" theme more so than a GNOME theme. piper has requirements on how the theme must behave which only exist because of piper's implementation. Button label names, leader lines, etc.
- if we are to make this a stable API, this behaviour of the SVGs becomes ABI too - we could never change the theme without potentially breaking other users
  - hypothetical issue: if piper's svg library changes/goes away and the new one renders slightly differently, we cannot update the svgs because they are part of the ABI. So we're doubly screwed.
- the only reason we have the fd passing is because we expect piper to run in a container and not have access to the host. Shipping it in piper makes that problem go away.

There are some notable downsides:
- adding a new device requires the user updates libratbag and piper
- other tools that rely on these SVGs (if they exist? ratbagctl doesn't count) will stop working. But see my ABI comment above.
- it is harder to enforce SVGs being added for new device if they're across two different repositories. That's a social problem, nothing technical stop us from saying "no .device file in libratbag until an SVG is in piper".

I think the benefit of not having to care about SVGs and magic ABI issues is greater than those drawbacks, so let's drop the SVGs and live merrily ever after

cc @bentiss, @Hjdskes, @FFY00, @phomes, @cvuchener

**Comment by Hjdskes** [comment]
I'm in favor of this change and had been thinking along the same lines of it really being a "Piper" theme more than a "GNOME" theme when @bentiss brought it up in #626.

> * it is harder to enforce SVGs being added for new device if they're across two different repositories. That's a social problem, nothing technical stop us from saying "no .device file in libratbag until an SVG is in piper".

I don't think this is a new problem. We already have .device files without there being an SVG for Piper, for example the etekcity.
