### ISSUE TITLE
Asus rog gladius II and Cooler master masterkeys pro L support ?

### ISSUE THREAD

**Issue by startas** [libratbag/libratbag#632]
Does this have support for mentioned mouse and keyboard ?

**Comment by bentiss** [comment]
If the USB ids are not in https://github.com/libratbag/libratbag/tree/master/data/devices then I guess not.
We need someone to reverse engineer the protocol, but we are all struggling with the currently supported devices.

Closing this now, but feel free to reopen if you know someone interested in adding the support for those devices.
