### ISSUE TITLE
Piper Cant find Mouse 

### ISSUE THREAD

**Issue by ThanosPlanetSmasher** [libratbag/libratbag#665]
Hey All, I'm a new user to Linux (Mint) and I am at my wits end trying to get Libratbag and Piper to work. So far I have installed both from the PPA, Ratbag is rooted and running, but Piper just will not see it. I have enabled the ratbagd.service in the terminal and my mouse is definitely supported (G602)

**Comment by whot** [comment]
Cross-posted bug, see https://github.com/libratbag/piper/issues/313
