### ISSUE TITLE
Request: add support for Logitech G100s

### ISSUE THREAD

**Issue by tethragon** [libratbag/libratbag#666]
Will it be possible to add support for Logitech G100s?

```
sudo lsinput
.
.
.

/dev/input/event11
   bustype : BUS_USB
   vendor  : 0x46d
   product : 0xc247
   version : 272
   name    : "Logitech G100s Optical Gaming Mo"
   phys    : "usb-0000:00:1d.0-1.2/input0"
   uniq    : ""
   bits ev : (null) (null) (null) (null)
```

and 

```
sudo ratbagctl info event11
Unable to find device event11

```

**Comment by FFY00** [comment]
You need to create a new device file.

Create `/usr/local/share/libratbag/devices/logitech-g100s.device`

```ini
[Device]
Name=Logitech G100s
DeviceMatch=usb:046d:c247
Driver=hidpp10
```

**Comment by FFY00** [comment]
Let us know if it works so that we add it to the repo.

**Comment by tethragon** [comment]
> Let us know if it works so that we add it to the repo.

No it doesn't work.

**Comment by Hjdskes** [comment]
Did you restart ratbagd after adding the file? Is libratbag even installed in /usr/local/ or in plain /usr?

**Comment by tethragon** [comment]
> Did you restart ratbagd after adding the file? Is libratbag even installed in /usr/local/ or in plain /usr?

I rebooted computer after adding the file and still didn't work. libratbag is in /usr/local/

**Comment by FFY00** [comment]
@Hjdskes if the libratbag properly implements the freedesktop spec it shouldn't matter where libratbag is installed, it should be able to pick up the device file either way. `/usr` shouldn't be touched by anything other than your distro's package manager, `/usr/local` is the place to manually add files.

**Comment by FFY00** [comment]
Just checked and this isn't working as I expected.

@tethragon install the file to `/usr/local/share/libratbag/devices/logitech-g100s.device` instead.

**Comment by tethragon** [comment]
> Just checked and this isn't working as I expected.
> 
> @tethragon install the file to `/usr/local/share/libratbag/devices/logitech-g100s.device` instead.

But my path is /usr/share/libratbag/devices.

**Comment by FFY00** [comment]
Ugh! Sorry, I forgot to remove the `/local`.

Install to `/usr/share/libratbag/devices/logitech-g100s.device`.

Sorry again :grimacing:

**Comment by whot** [comment]
fwiw, we **only** parse `$prefix` because we don't want a hand-placed `.device` file to be anything but a temporary measure. These are files libratbag needs to trust and their content is not stable API so we just check the location where we install those and done. In distribution-installed system that is `/usr/share/libratbag/devices/`, otherwise it's `$prefix/share/libratbag/devices/` where meson was involved.

@tethragon: your best choice right now is:
```
$ sudo killall ratbagd
$ sudo ratbagd --verbose=raw
```
and attach the output. This may show up any errors that prevent the device from working. medium-term you should get the git repo and work with with either `sudo ./builddir/ratbagctl.devel` or `sudo ./builddir/ratbag-command` to get the issues sorted.

**Comment by tethragon** [comment]
It is working now, I guess:

`sudo ratbagd --verbose=raw
ratbag debug: Logitech G100s Optical Gaming Mouse is device '/dev/hidraw0'.
`
So now it is up to piper developers to implement support for the mouse? Because piper still not finding the device. Is there a command line option to manipulate mouse settings using only libratbagd?

**Comment by Hjdskes** [comment]
Piper will need an SVG drawing of the mouse, then it can work. You can check Piper's repository to see the guidelines and some tips to maybe do it yourself.

As for the commandline, there's `ratbagctl`.

**Comment by tethragon** [comment]
Thank for the info. I'll check the guidelines and I'll try make the svg myself. I hope I'll succeed and give something back to the community.

**Comment by FFY00** [comment]
In the meantime we can add the device file to libratbagm. @tethragon do you want to open a pull reqquest :grin:?

**Comment by tethragon** [comment]
I am not familiar to github's functions, so please @FFY00 you do it. Thank you.

**Comment by FFY00** [comment]
No problem.
