### ISSUE TITLE
Logitech G Pro wrong device ID

### ISSUE THREAD

**Issue by chent7** [libratbag/libratbag#684]
It's not a big deal, but I do have to change it manually in the .device file to `046d:c08c`.
After that everything works as normal, expect the mouse image is the 404 mouse. I did double-check with my G502 and everything works fine with that mouse.

**Comment by whot** [comment]
Is it an actually wrong device ID or does the device just have multiple IDs that match this device?

If you get the 404 and you use libratbag 0.905 and most recent piper, you'll also need to update the `svg-lookup.ini` in piper.

**Comment by chent7** [comment]
So the default for ID for `logitech-g-pro.device` is `046d:c085`.
My G Pro mouse has `046d:c08c`
I don't know if the ID is wrong or that Logitech makes the G Pro with different IDs, since I don't have a second G Pro to test this. (I bought mine in Australia)
When I update `svg-lookup.ini` from
`[Logitech G Pro]`
`DeviceMatch=usb:046d:c085`
`Svg=logitech-g-pro.svg` 
to
`[Logitech G Pro]`
`DeviceMatch=usb:046d:c08c`
`Svg=logitech-g-pro.svg`
and build from source, everything works and displays just fine.

So I guess my issue is will there be updates to support multiple device IDs for the same mouse?

**Comment by bentiss** [comment]
Multiple devices id for the same mouse is not so uncommon. We should have support for that in libratbag. See https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-MX-Master.device for an example.

Looking around on google showed that both PID are referring to the same mouse (G Pro), so it should be safe to add a PR adding this PID to the G Pro file

**Comment by chent7** [comment]
> Multiple devices id for the same mouse is not so uncommon. We should have support for that in libratbag. See https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-MX-Master.device for an example.
> 
> Looking around on google showed that both PID are referring to the same mouse (G Pro), so it should be safe to add a PR adding this PID to the G Pro file
Changing `logitech-g-pro.device` to this `DeviceMatch=usb:046d:c085;usb:046d:c08c` does work.
Anyway I can change `svg-lookup.ini` without building from source again?
Otherwise, I think we can close the issue :)

**Comment by bentiss** [comment]
> Anyway I can change svg-lookup.ini without building from source again?

Not sure, @whot would know

> Otherwise, I think we can close the issue :)

I think it would be best if we close the issue through a pull request merging your changes :)

**Comment by chent7** [comment]
I'm not sure how to do that as I am fairly new to github and Linux, so someone will have to walk me though it.
However, I am more than happy to send just the two files I've modified if someone can merge them for me. I've only changed the device ID so it shouldn't be anything too difficult.

**Comment by Katana-Steel** [comment]
@chent7 created a PR with the needed updates, I think
#686

**Comment by chent7** [comment]
@Katana-Steel @bentiss 
I also created a PR [https://github.com/libratbag/piper/pull/332](url)
I'm pretty sure that's all it needs.
Thanks.
