### ISSUE TITLE
Request: add an option to disable acceleration for Logitech g203

### ISSUE THREAD

**Issue by itsnoteasy** [libratbag/libratbag#689]
this is the first thing most competitive gamers do after buying a mouse. aside from setting the dpi, this is the only feature I use. it would be helpful to do other mice also, like the g502.

**Comment by FFY00** [comment]
I don't think Logitech mice have hardware acceleration. @whot and @bentiss might be able to confirm this.

**Comment by whot** [comment]
same here, never heard of acceleration in hardware and nothing comes to mind that would fit that bill in the specs we have available. This is just a case of disabling it in the desktop environment, I know gnome-tweaks allows you to set the acceleration profile to "flat" on the most recent few releases.

**Comment by bentiss** [comment]
Just to confirm what has been said above, yes, there is no hardware acceleration in the devices. It is all done in the desktop environment.
