### ISSUE TITLE
Wrong button mapping for Logitech G500s

### ISSUE THREAD

**Issue by kleinph** [libratbag/libratbag#69]
I played around with piper and noticed that some button mappings are wrong.

As you can see in the picture Button 6 and 7 are mapped as Wheel Left and Right and Button 8 and 9 for the Resolution Control. But these mappings are actually the other way round. Also shouldn't the arrows of Button 8 and 9 point left and right?

![bildschirmfoto von 2016-03-10 18-38-24](https://cloud.githubusercontent.com/assets/566413/13679263/2a4e09e4-e6f3-11e5-9440-4114b7be6819.png)

**Comment by cvuchener** [comment]
You are right, and buttons 3 and 4 are inverted too.

**Comment by whot** [comment]
fwiw, that's the old graphic, I applied a bit of polish since. But I didn't change the button mappings (and clearly didn't doublecheck them either). They're just inscape SVGs, can you send us a PR with the labels fixed?

**Comment by cvuchener** [comment]
I sent PR #71, with fixed labels and rotated arrows. I hope I did not break anything.

**Comment by bentiss** [comment]
closing this as fixed as of PR #71.

Please re-open if things are still not correct
