### ISSUE TITLE
I accidentally edited the Devices wiki

### ISSUE THREAD

**Issue by mjarkk** [libratbag/libratbag#691]
First of all sorry for this issue this was not supposed to happen.  

I wanted to add link to all owners here:  https://github.com/libratbag/libratbag/wiki/Devices#device-owners  
And thought i was editing in a fork but that is not the case with wiki's  
The problem was that i noticed this after i was dune editing.  

I don't want to mess up more things by a force rollback. So i created this issue to notice you about this change.

**Comment by FFY00** [comment]
No, problem. Your changes are fine.

@whot should we only allow maintainers to edit the wiki?

**Comment by bentiss** [comment]
> No, problem. Your changes are fine.

Yep. The wiki is just a git tree, so we can always revert the changes if we think so. And here, I do not think there is an issue with your changes as @FFY00 said.

> @whot should we only allow maintainers to edit the wiki?

The point is to allow non maintainers to edit the wiki as we are definitively overloaded with other tasks. So I do not mind revert a change from time to time and let contributors contribute.
