### ISSUE TITLE
Low poll/refresh-rates not avaliable

### ISSUE THREAD

**Issue by Riesi** [libratbag/libratbag#692]
I know this sounds like a silly issue. I mean who wants to use a lower poll-rate? But here is the point. Wine has [a problem with high mouse poll-rates](https://bugs.winehq.org/show_bug.cgi?id=33643) in multiple titles and the only fix for now is to set the poll-rate to 125Hz. Which is not possible with libratbag at least on the mice a friend of mine and I own.

Logitech G203 Prodigy
Logitech G700
Both mice support poll-rates of 125, 250, 500 and 1000Hz on Windows, but the lower two (125 & 250) are not available in libratbag+piper.

I am not sure if its possible to enable the low poll-rates for every mouse. But it would be great to maybe support setting the supported refresh-rates in the device config?

thanks in advance,
Riesi

**Comment by mpipo** [comment]
I just got a G203 today and while ratbagctl seems to be letting me "change" the rate, ```evhz``` still reports 1000Hz and ```/sys/kernel/debug/usb/devices``` ```Ivl=1ms```

I can't even get it down to 500Hz. It's a shame Wine has this problem in 2019.

**Comment by soredake** [comment]
@FFY00 can you please add 125 and 250 poll-rate to rival 310?

**Comment by FFY00** [comment]
They are there:
```
$ ratbagctl hollering-marmot rate get-all
125 250 500 1000
```

We are, however, not printing the correct values when using the `get` command.
```
$ ratbagctl hollering-marmot rate set 125
$ ratbagctl hollering-marmot rate get
100
$ ratbagctl hollering-marmot rate set 250
$ ratbagctl hollering-marmot rate get
200
$ ratbagctl hollering-marmot rate set 500
$ ratbagctl hollering-marmot rate get
500
$ ratbagctl hollering-marmot rate set 1000
$ ratbagctl hollering-marmot rate get
1000
```

Can you reproduce this? Which version of libratbag are you using?

If you can't reproduce and you are not using an outdated version please open a new issue.

**Comment by soredake** [comment]
I see, but from piper i see only 500/1000 rates, maybe report to the piper repo?

**Comment by whot** [comment]
piper is hardcoded to only show the 500/1000 rate, that was a conscious decision on the basis that was a combination of "meh, do we need more?" and "it looks nicer this way" :)

**Comment by FFY00** [comment]
But with wireless mice being more widespread it might make sense to change this behavior as lower polling rates have lower power consumption.

**Comment by whot** [comment]
would be interesting to expose this only on wireless devices then, but either way, that bit is a question for piper, not libratbag.

**Comment by Riesi** [comment]
It would also be a good idea to expose the lower polling rates on wired mice, due to the wine bug mentioned in my first comment.
