### ISSUE TITLE
Gentoo ebuild using elogind

### ISSUE THREAD

**Issue by mpipo** [libratbag/libratbag#696]
Hello,

Not sure where to put this, but I've written an ebuild for Gentoo that doesn't need systemd to compile or operate. It seems to be working *so far.* Hopefully resolves #239

I've only tested it on an OpenRC + elogind system and *I'm almost clueless about writing ebuilds* so comments are welcome. You'll have to write your own init.d script though.

[Gist link](https://gist.github.com/mpipo/34370f3f31e3c0d65c4aa69612a3e03e)

**Comment by whot** [comment]
This has been addressed in 9b409822c309152644d8de7664b2f152a7cee895, the ebuild should be submitted to the Gentoo repos I guess. We don't really need a bug open for this here.
