### ISSUE TITLE
Logitech M705 gives invalid dpi list error

### ISSUE THREAD

**Issue by ikelos** [libratbag/libratbag#699]
Using ratbagd-0.9.905 and a Logitech M705 I get the following log line:

```
Apr 29 00:47:12 ikelos ratbagd[10462]: ratbag error: libratbag bug: Logitech M705: invalid dpi list
```

Solaar reports the device with the following information:
```
Index        : 1
Wireless PID : 101B
Protocol     : HID++ 1.0
Polling rate : 8 ms (125Hz)
Serial       : XXX
  Firmware   : 17.01.B0017
  Bootloader : 02.06
  Other      : 00.04
Notifications: battery status
```

ratbagctl lists no devices found.

Is this something I can resolve by changing the `.device` file, or will I need to build a debug version and bring back protocol responses?  Happy to provide any further information if it'll help me map my side key to my middle key under wayland...  5:)

**Comment by kaadmy** [comment]
Can confirm this, on Arch Linux running latest Git version of libratbag (6f27053ab0791e7e5db0a16eb8ce37b77ecee629)

**Comment by chadbaum** [comment]
Same issue with G602:

`May 06 19:18:53 Valoria systemd[1]: Starting Daemon to introspect and modify configurable mice...
May 06 19:18:53 Valoria systemd[1]: Started Daemon to introspect and modify configurable mice.
May 06 19:18:53 Valoria ratbagd[30514]: ratbag error:     HID++ error from the device (1): ERR_INVALID_ARGUMENT (02)
May 06 19:18:53 Valoria ratbagd[30514]: ratbag error: Error while requesting resolution: Protocol error (-71)
May 06 19:18:53 Valoria ratbagd[30514]: ratbag error:     HID++ error from the device (1): ERR_INVALID_ARGUMENT (02)
May 06 19:18:53 Valoria ratbagd[30514]: ratbag error: libratbag bug: Logitech USB Receiver: invalid dpi list
May 06 19:18:54 Valoria ratbagd[30514]: ratbag error:     HID++ error from the device (1): ERR_INVALID_ARGUMENT (02)
May 06 19:18:54 Valoria ratbagd[30514]: ratbag error: Error while requesting resolution: Protocol error (-71)
May 06 19:18:54 Valoria ratbagd[30514]: ratbag error:     HID++ error from the device (1): ERR_INVALID_ARGUMENT (02)
May 06 19:18:54 Valoria ratbagd[30514]: ratbag error: libratbag bug: Logitech USB Receiver: invalid dpi list`

**Comment by ikelos** [comment]
I haven't seen any further information regarding how to debug this further?  The best I could find (since ratbagctl -vvv didn't seem to do a lot) was to run `ratbagd --verbose=raw` which gave the following output:
```
ratbag debug: New device: Logitech M705
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp10
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x101b
ratbag debug: Logitech M705 is device '/dev/hidraw5'.
ratbag debug: HID report ID 02
ratbag debug: HID report ID 10
ratbag debug: HID report ID 11
ratbag debug: HID report ID 20
ratbag debug: HID report ID 21
ratbag raw: Fetching individual features
ratbag raw:   expected_header:		?? 00 81 01
ratbag raw:   expected_error_dev:	10 00 8f 81 01 00 00
ratbag raw: hidpp write: 10 00 81 01 00 00 00
ratbag raw: hidpp read:  10 01 81 01 40 00 00
ratbag raw:   received: 10 00 81 01 40 00 00
ratbag raw: Fetching HID++ notifications
ratbag raw:   expected_header:		?? 00 81 00
ratbag raw:   expected_error_dev:	10 00 8f 81 00 00 00
ratbag raw: hidpp write: 10 00 81 00 00 00 00
ratbag raw: hidpp read:  02 00 00 06 f0 ff 00 00
ratbag raw: hidpp read:  10 01 81 00 10 00 00
ratbag raw:   received: 10 00 81 00 10 00 00
ratbag raw: Fetching current resolution
ratbag raw:   expected_header:		?? 00 83 63
ratbag raw:   expected_error_dev:	10 00 8f 83 63 00 00
ratbag raw: hidpp write: 10 00 83 63 00 00 00
ratbag raw: hidpp read:  02 00 00 03 00 00 00 00
ratbag raw: hidpp read:  10 01 8f 83 63 01 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_SUBID (01)
ratbag raw: Fetching LED status
ratbag raw:   expected_header:		?? 00 81 51
ratbag raw:   expected_error_dev:	10 00 8f 81 51 00 00
ratbag raw: hidpp write: 10 00 81 51 00 00 00
ratbag raw: hidpp read:  02 00 00 05 00 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 51 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching USB refresh rate
ratbag raw:   expected_header:		?? 00 81 64
ratbag raw:   expected_error_dev:	10 00 8f 81 64 00 00
ratbag raw: hidpp write: 10 00 81 64 00 00 00
ratbag raw: hidpp read:  02 00 00 0a c0 ff 00 00
ratbag raw: hidpp read:  10 01 8f 81 64 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching optical sensor settings
ratbag raw:   expected_header:		?? 00 81 61
ratbag raw:   expected_error_dev:	10 00 8f 81 61 00 00
ratbag raw: hidpp write: 10 00 81 61 00 00 00
ratbag raw: hidpp read:  02 00 00 09 c0 ff 00 00
ratbag raw: hidpp read:  10 01 8f 81 61 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching current profile
ratbag raw:   expected_header:		?? 00 81 0f
ratbag raw:   expected_error_dev:	10 00 8f 81 0f 00 00
ratbag raw: hidpp write: 10 00 81 0f 00 00 00
ratbag raw: hidpp read:  02 00 00 0e c0 ff 00 00
ratbag raw: hidpp read:  10 01 8f 81 0f 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag debug: no profile type given
ratbag raw: Fetching profile 0
ratbag error: libratbag bug: Logitech M705: invalid dpi list
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c52b
```

Any thoughts on what's going on or how to fix it, please?  It's very frustrating not to be able to remap my additional buttons without having to tinker with udev's hwdb.  I'd really like to see ratbag working as expected with a device that is supposedly supported?

**Comment by ikelos** [comment]
As far as I can tell from the hidpp10 document, the device id has to be from 0x01 to 0x06 (or be 0xFF).  Libratbag seems to always send 0x00 (and even though I tried to change the message templates to return `idx + 1`, or getting liblur to loop from 0x01 to 0x06).  I haven't been able to get it to send `10 01 81 0f 00 00 00`, but I suspect that would return more accurate information and allow it to continue successfully.  It's as though it thinks the device is wired?

**Comment by FFY00** [comment]
The device ID `0x00` corresponds to wired mice. Can you send me Wireshark dumps of you connecting the device and trying to use libratbag?

Run `lsusb` to get the Bus and Device IDs, load the `usbmom` kernel module (`sudo modprobe usbmon`) to be able to sniff USB with Wireshark and then run Wireshark on the `usmon(Bus ID)` interface and apply following filter `usb.device_address == (Device ID)`. After that just save the file (`File > Export Specified Packets`).

**Comment by ikelos** [comment]
Hmmm, the packet capture doesn't match the raw verbose logs?  It seems it is using the right device identifier when it sends the packets?
capture: [libratbag-packetcapture.zip](https://github.com/libratbag/libratbag/files/3244039/libratbag-packetcapture.zip)
verbose=raw:
```
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x101b
ratbag debug: Logitech M705 is device '/dev/hidraw5'.
ratbag debug: HID report ID 02
ratbag debug: HID report ID 10
ratbag debug: HID report ID 11
ratbag debug: HID report ID 20
ratbag debug: HID report ID 21
ratbag raw: Fetching individual features
ratbag raw:   expected_header:		?? 00 81 01
ratbag raw:   expected_error_dev:	10 00 8f 81 01 00 00
ratbag raw: hidpp write: 10 00 81 01 00 00 00
ratbag raw: hidpp read:  10 01 81 01 40 00 00
ratbag raw:   received: 10 00 81 01 40 00 00
ratbag raw: Fetching HID++ notifications
ratbag raw:   expected_header:		?? 00 81 00
ratbag raw:   expected_error_dev:	10 00 8f 81 00 00 00
ratbag raw: hidpp write: 10 00 81 00 00 00 00
ratbag raw: hidpp read:  10 01 81 00 10 00 00
ratbag raw:   received: 10 00 81 00 10 00 00
ratbag raw: Fetching current resolution
ratbag raw:   expected_header:		?? 00 83 63
ratbag raw:   expected_error_dev:	10 00 8f 83 63 00 00
ratbag raw: hidpp write: 10 00 83 63 00 00 00
ratbag raw: hidpp read:  10 01 8f 83 63 01 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_SUBID (01)
ratbag raw: Fetching LED status
ratbag raw:   expected_header:		?? 00 81 51
ratbag raw:   expected_error_dev:	10 00 8f 81 51 00 00
ratbag raw: hidpp write: 10 00 81 51 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 51 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching USB refresh rate
ratbag raw:   expected_header:		?? 00 81 64
ratbag raw:   expected_error_dev:	10 00 8f 81 64 00 00
ratbag raw: hidpp write: 10 00 81 64 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 64 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching optical sensor settings
ratbag raw:   expected_header:		?? 00 81 61
ratbag raw:   expected_error_dev:	10 00 8f 81 61 00 00
ratbag raw: hidpp write: 10 00 81 61 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 61 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: Fetching current profile
ratbag raw:   expected_header:		?? 00 81 0f
ratbag raw:   expected_error_dev:	10 00 8f 81 0f 00 00
ratbag raw: hidpp write: 10 00 81 0f 00 00 00
ratbag raw: hidpp read:  10 01 8f 81 0f 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag debug: no profile type given
ratbag raw: Fetching profile 0
ratbag error: libratbag bug: Logitech M705: invalid dpi list
```

**Comment by FFY00** [comment]
Yes, this is definitely weird but it isn't the actual issue. @whot @bentiss could you please look at this? Although there's a .device file, libratbag isn't prepared to deal with the M705. I don't have the documentation to fix this right now so unless someone comes forward you will have to wait 1.5~3 months.

**Comment by whot** [comment]
Based on #726 being merged, I'm assuming that this is fixed now? Esp. given that the above uses `hidpp10` but the file merged uses `hidpp20`.

**Comment by FFY00** [comment]
@whot they are different mice.

**Comment by FFY00** [comment]
This mouse does not export DPI value, it uses a "pointer speed" setting.

**Comment by whot** [comment]
Can we internally wrap this to dpis? doesn't need to be for every setting, doesn't need to be 100% accurate, if it's close enough it should do.

**Comment by FFY00** [comment]
I already looked into this, we will need to have native DPI value for each mouse. The HID++ feature in question just implements a multiplier.

**Comment by whot** [comment]
Do they have different sensors? Or do they all just have the 1000dpi default sensor anyway which would make life a bit easier.

**Comment by FFY00** [comment]
They can have different sensors.

**Comment by FFY00** [comment]
I am gonna close this now. I think this feature is slightly out of scope.

**Comment by mpol** [comment]
This is an old, closed bug, but may I have a question? I thought, based on the existence of the `logitech-M705.device` file, that my mouse is supported, then I hit the same issue that is reported here.
Are there different `DeviceMatch=usb:046d:101b` Logitech M705 mice, some of which work with libratbag and some don't (I wouldn't be surprised), or should the device file maybe be removed?

**Comment by FFY00** [comment]
You *might* be able to configure any of the features. The device does speak the protocol we implemented in the driver, it just might not actually have any usable features.
I think we could reconsider this issue and add support for changing the sensibility, though I am not sure how useful that'd be since it gets reset on device poweroff.
