### ISSUE TITLE
rival 310 can't set dpi

### ISSUE THREAD

**Issue by CKWarner** [libratbag/libratbag#702]
I mentioned this in the comments to #683, that the failure to set the LEDs in that release also set both DPI settings to 100, and couldn't change them to something worthwhile.

The new release can now set the LEDs, but it's still incapable of changing the DPI settings away from 100.

**Comment by CKWarner** [comment]
If you need more information to be able to fix this, let me know.

**Comment by FFY00** [comment]
Please confirm this is fixed in https://github.com/libratbag/libratbag/pull/709.

**Comment by CKWarner** [comment]
Yes, seems to have been fixed by 709. Thanks.
