### ISSUE TITLE
Logitech G403 (Wireless) mouse wheel LED

### ISSUE THREAD

**Issue by NoxNebula** [libratbag/libratbag#704]
I'm using the **G403 Wireless** mouse. In piper I can configure the Logitech logo LED *(bottom)* but I have no option to control the mouse wheel LED.

![Piper screenshot](https://i.imgur.com/Lq7e9aQ.png)

PS: I hope I'm here at the right place, because I think its an issue with the device definition in libratbag and not a front end thing with piper.

**Comment by FFY00** [comment]
Can you confirm this also doesn't work in `ratbagctl`?

**Comment by NoxNebula** [comment]
Ok I get 2 LEDs, it doesn't seem to be ratbag then :sweat_smile: 
```
$ ratbagctl 'Logitech USB Receiver' led get
LED: 0, depth: rgb, mode: off
LED: 1, depth: rgb, mode: off
```

**Comment by FFY00** [comment]
This should be fixed in the latest release, could you check? Make sure you are running linux 5.2.
