### ISSUE TITLE
Logitech M720 Triathlon

### ISSUE THREAD

**Issue by Sudrien** [libratbag/libratbag#705]
> #https://support.logitech.com/en_us/product/m720-triathlon/specs
> [Device]
> Name=Logitech M720 Triathlon
> DeviceMatch=bluetooth:046d:b015
> Driver=hidpp20

Detects 8 buttons. 
Stuck at 1000dpi.

This mouse supports switching between three devices, that works fine, all three devices can be the same computer.

Unfortunately the 8th button, right under my thumb, seems to be set to switch windows by default. Opposite of what I want in games.

Piper Can't set the buttons, I assume that goes elsewhere.

Not sure if it means anything but

[ 5007.332796] input: M720 Triathlon Keyboard as /devices/virtual/misc/uhid/0005:046D:B015.000E/input/input39
[ 5007.332851] input: M720 Triathlon Mouse as /devices/virtual/misc/uhid/0005:046D:B015.000E/input/input40

**Comment by FFY00** [comment]
Pressing the button sends a key code (you can see this with `evemu-record`), you should remap that key code to another action.

**Comment by Sudrien** [comment]
It is Ctrl+Alt+Tab. Which degrades into into Alt+Tab... sometimes? That's at least something I can try and work around, thank you @FFY00.

**Comment by Cediddi** [comment]
> Pressing the button sends a key code (you can see this with `evemu-record`), you should remap that key code to another action.

I tried that and got this output. Just for reference.

```
E: 10.555856 0004 0004 458795   # EV_MSC / MSC_SCAN             458795
E: 10.555856 0001 000f 0000     # EV_KEY / KEY_TAB              0
E: 10.555856 0000 0000 0000     # ------------ SYN_REPORT (0) ---------- +8ms
E: 10.563928 0004 0004 458978   # EV_MSC / MSC_SCAN             458978
E: 10.563928 0001 0038 0000     # EV_KEY / KEY_LEFTALT          0
E: 10.563928 0000 0000 0000     # ------------ SYN_REPORT (0) ---------- +8ms
E: 10.571941 0004 0004 458976   # EV_MSC / MSC_SCAN             458976
E: 10.571941 0001 001d 0000     # EV_KEY / KEY_LEFTCTRL         0
E: 10.571941 0000 0000 0000     # ------------ SYN_REPORT (0) ---------- +8ms
E: 11.155840 0004 0004 458976   # EV_MSC / MSC_SCAN             458976
E: 11.155840 0001 001d 0001     # EV_KEY / KEY_LEFTCTRL         1
E: 11.155840 0000 0000 0000     # ------------ SYN_REPORT (0) ---------- +584ms
E: 11.163838 0004 0004 458978   # EV_MSC / MSC_SCAN             458978
E: 11.163838 0001 0038 0001     # EV_KEY / KEY_LEFTALT          1
E: 11.163838 0000 0000 0000     # ------------ SYN_REPORT (0) ---------- +8ms
E: 11.171840 0004 0004 458795   # EV_MSC / MSC_SCAN             458795
E: 11.171840 0001 000f 0001     # EV_KEY / KEY_TAB              1
E: 11.171840 0000 0000 0000     # ------------ SYN_REPORT (0) ---------- +8ms
```

**Comment by FFY00** [comment]
That is correct, you seem to be getting the ctrl, the alt and the tab. @Sudrien are you sure this isn't something in your software? If you change desktop environments does it keep happening?

**Comment by Sudrien** [comment]
It definitely seems to be a Cinnamon keyboard polling bug. I've had keystrokes dropping in other programs - and I can't reproduce the issue in XFCE4.

That said, the issue was mentioned as an unfortunate behavior, as libratbag still doesn't support the M720.

**Comment by FFY00** [comment]
Ok, I'll close this now. We hope to had support for Logitech's sensitivity feature, which will enable the M720 to work properly.
