### ISSUE TITLE
MX Master settings not applying.

### ISSUE THREAD

**Issue by PixlOne** [libratbag/libratbag#716]
Nothing happens when I change on of the libratbag settings on my MX Master.

ratbagctl returns no errors when I set an option but the new changes do not take effect.

When I try changing it in Piper, it says 'Something went wrong. The device has been reset to a previous state.'

**Comment by whot** [comment]
start with `ratbagd --verbose` and try it then, do you see any error messages?

**Comment by PixlOne** [comment]
Here's what I get with `ratbagd --verbose`:
`ratbag debug: New device: Sony PLAYSTATION(R)3 Controller
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 054c:0268
ratbag debug: New device: HID 04b4:1007
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 04b4:1007
ratbag debug: New device: HID 04b4:1007
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 04b4:1007
ratbag debug: New device: Logitech MX Master
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x4069
ratbag debug: Logitech MX Master is device '/dev/hidraw4'.
ratbag debug: HID report ID 01
ratbag debug: HID report ID 0e
ratbag debug: HID report ID 02
ratbag debug: HID report ID 03
ratbag debug: HID report ID 04
ratbag debug: HID report ID 10
ratbag debug: HID report ID 11
ratbag debug: HID report ID 20
ratbag debug: HID report ID 21
ratbag debug: 'Logitech MX Master' is using protocol v4.5
ratbag debug: device battery level is 90% (next 50%), status 0 
ratbag debug: device has programmable keys/buttons
ratbag debug: device has 8 buttons
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1000 dpi (variable between 400 and 1600).
ratbag debug: device is at 1000 dpi (variable between 400 and 1600).
ratbag debug: device has 8 buttons
ratbag debug: driver match found: Logitech HID++2.0
hidraw4: "Logitech MX Master", 1 profiles
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c52b
`

**Comment by PixlOne** [comment]
I've also noticed that it says `hidraw info: bus 0x03 vendor 0x46d product 0x4069`

The MX Master's IDs are 4041, 4060, b012 while the MX Master 2S's IDs are 4069, b019. Also, Solaar recognises my mouse as an MX Master 2S and says `Wireless PID : 4069`.

I just got this mouse a few days ago, is it possible that Logitech is basing their newer MX Masters on the MX Master 2S?

**Comment by 02souitch** [comment]
I have the same problem but I see no error with ratbagd --verbose : 

`ratbag debug: Logitech MX Master is device '/dev/hidraw3'.ratbag debug: Logitech MX Master is device 
'/dev/hidraw3'.`
`ratbag debug: report ID 01`
`ratbag debug: report ID 0e`
`ratbag debug: report ID 02`
`ratbag debug: report ID 03`
`ratbag debug: report ID 04`
`ratbag debug: report ID 10`
`ratbag debug: report ID 11`
`ratbag debug: report ID 20`
`ratbag debug: report ID 21`
`ratbag debug: 'Logitech MX Master' is using protocol v4.5`
`ratbag debug: device battery level is 90% (next 50%), status 0`
`ratbag debug: device has programmable keys/buttons`
`ratbag debug: device has 8 buttons`
`ratbag debug: device has adjustable dpi`
`ratbag debug: device is at 1000 dpi (variable between 400 and 1600).`
`ratbag debug: device is at 1000 dpi (variable between 400 and 1600).`
`ratbag debug: device has 8 buttons`
`ratbag debug: driver match found: Logitech HID++2.0`
`hidraw3: "Logitech MX Master", 1 profiles`

I don't know if I did something wrong, I just install piper with the Arch repository.

**Comment by PixlOne** [comment]
@02souitch I'm working on something over here: https://github.com/PixlOne/masterOptions

It's in an early stage of development but you may be able to modify it a bit to get it kinda working.

**Comment by 02souitch** [comment]
Thank's for your reponse but I am very busy at the moment and I was looking for something that's work. If I get time, I will look at it more seriously. Anyway good luck for your project

**Comment by rockerbacon** [comment]
I'm having the exact same problem, here's the output for ratbagd --verbose:
```
ratbag debug: New device: Logitech MX Master 2S
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x4069
ratbag debug: Logitech MX Master 2S is device '/dev/hidraw3'.
ratbag debug: HID report ID 01
ratbag debug: HID report ID 0e
ratbag debug: HID report ID 02
ratbag debug: HID report ID 03
ratbag debug: HID report ID 04
ratbag debug: HID report ID 10
ratbag debug: HID report ID 11
ratbag debug: HID report ID 20
ratbag debug: HID report ID 21
ratbag debug: 'Logitech MX Master 2S' is using protocol v4.5
ratbag debug: device battery level is 50% (next 20%), status 0 
ratbag debug: device has programmable keys/buttons
ratbag debug: device has 8 buttons
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1000 dpi (variable between 200 and 4000).
ratbag debug: device is at 1000 dpi (variable between 200 and 4000).
ratbag debug: device has 8 buttons
ratbag debug: driver match found: Logitech HID++2.0
hidraw3: "Logitech MX Master 2S", 1 profiles
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c52b
ratbag debug: New device: HOLTEK USB-HID Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04d9:a1cc
ratbag debug: New device: HOLTEK USB-HID Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04d9:a1cc
ratbag debug: New device: HOLTEK USB-HID Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04d9:a1cc
ratbag debug: New device: HOLTEK USB-HID Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04d9:a1cc
```
There's no other output when trying to edit the mouse's configuration with ratbagctl. Ratbagctl will also not display anything even with the --verbose option.
For the DPI settings ratbagctl will act as if the DPI was changed (using dpi get returns the previously set DPI), but there's no perceivable different from 200dpi to 4000dpi, so it's safe to say nothing is being changed.
The buttons will not change and ratbagctl will always return the same value for "ratbagctl <device> button N action get"

**Comment by rockerbacon** [comment]
I just downloaded and built version 0.9.904 and that version seems to be working just fine

**Comment by tcmug** [comment]
MX Master 2S user here, settings don't seem to apply, even though the return code claims success, e.g.:
```
~ $ sudo ratbagctl singing-gundi button 5 action set button 1; echo $?
0
~ $ sudo ratbagctl singing-gundi button 5 action get; echo $?
Button: 5 is mapped to 'button 1'
0
```
Button 5 works just the same as before. Piper fails also.

Verbosed dump:
```
$ ratbagd --verbose
ratbag debug: New device: Wacom Co.,Ltd. Pen and multitouch sensor
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 056a:5146
ratbag debug: New device: Wacom Co.,Ltd. Pen and multitouch sensor
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 056a:5146
ratbag debug: New device: Logitech MX Master 2S
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x4069
ratbag debug: Logitech MX Master 2S is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 0e
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID 20
ratbag debug: - HID report ID 21
ratbag debug: 'Logitech MX Master 2S' is using protocol v4.5
ratbag debug: device battery level is 50% (next 20%), status 0 
ratbag debug: device has programmable keys/buttons
ratbag debug: device has 8 buttons
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1000 dpi (variable between 200 and 4000).
ratbag debug: device is at 1000 dpi (variable between 200 and 4000).
ratbag debug: device has 8 buttons
ratbag debug: driver match found: Logitech HID++2.0
hidraw1: "Logitech MX Master 2S", 1 profiles
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c52b
```

**Comment by PixlOne** [comment]
@tcmug I'm working on an alternative for Logitech devices over here: https://github.com/PixlOne/logiops

It isn't necessarily perfect but it works fairly well with my MX Master in my experience. You could try out that program and if you're having any issues just file a bug report there.

**Comment by capoei** [comment]
MX Master 2S user here.
still doesn't work

**Comment by andrefcorreia** [comment]
yes, for me either
not for  applying mx master 2s

**Comment by capoei** [comment]
acording to Arch wiki it should detect 10 buttons, not 8
https://wiki.archlinux.org/index.php/Logitech_MX_Master

**Comment by Vincevrp** [comment]
I also experience this issue. I'm using the original MX Master.

**Comment by darekpro** [comment]
Me too :/ wtf is with this mouse solaar also not working...

**Comment by BjoernDaase** [comment]
Did anyone found a workaround for the MX Master 2S in the meantime?

**Comment by capoei** [comment]
I'm using Solaar for DPI and scroll wheel setting and Xbindkeys+Xdotool for key mapping

**Comment by BjoernDaase** [comment]
> I'm using Solaar for DPI and scroll wheel setting and Xbindkeys+Xdotool for key mapping
> […](#)
> On Dez 25 2019, at 8:34 pm, Björn Daase ***@***.***> wrote: Did anyone found a workaround for the MX Master 2S in the meantime? — You are receiving this because you commented. Reply to this email directly, view it on GitHub ***@***.***/0?redirect=https%3A%2F%2Fgithub.com%2Flibratbag%2Flibratbag%2Fissues%2F716%3Femail_source%3Dnotifications%26email_token%3DAFLJROCUURBK75URHLI3AYDQ2PUZ5A5CNFSM4HYOMFDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHUU4WI%23issuecomment-568938073&recipient=cmVwbHkrQUZMSlJPSFRYU0NQQjRKNVRaUjNNNTU0Q0VTSjVFVkJOSEhCV05OMlJVQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFLJRODK5V4KZ3SOSJGQ6B3Q2PUZ5ANCNFSM4HYOMFDA&recipient=cmVwbHkrQUZMSlJPSFRYU0NQQjRKNVRaUjNNNTU0Q0VTSjVFVkJOSEhCV05OMlJVQHJlcGx5LmdpdGh1Yi5jb20%3D).

But that atr both Xorg only solutions, right? 
I unfortunately have to use Wayland (due to other reasons)...

**Comment by capoei** [comment]
try this https://github.com/mathportillo/wayland-mouse-mapper (https://link.getmailspring.com/link/17F7EBDF-8745-412A-903B-4869C123D273@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fmathportillo%2Fwayland-mouse-mapper&recipient=cmVwbHkrQUZMSlJPSE1MWEk0V09FWUFMVDJXUDU0Q0hCTjNFVkJOSEhCV05OMlJVQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by FFY00** [comment]
Can you try #890?

**Comment by PixlOne** [comment]
That seemed to have fixed the issue, thanks.
