### ISSUE TITLE
[G Pro Wireless] read DPI values and profiles are wrong

### ISSUE THREAD

**Issue by deathtrip** [libratbag/libratbag#717]
Using both ratbagctl and piper the DPI values shown are always the default ones, even though i changed them in LGS on Windows, and in LGS they are seen correctly. 

Also only the current profile is seen, and i have 3 in total.

Happens both in wired and in wireless mode.

**Comment by FFY00** [comment]
Does this still happen. I didn't try Windows but it does work when I edit the DPI values via libratbag.

**Comment by aTosser** [comment]
If I run ratbagd manually with --verbose=raw I get:

`ratbag raw: sensor 0: current dpi: 550 (default: 800) min: 100 max: 25600 steps: 50`
`ratbag debug: device is at 550 dpi (variable between 100 and 25600).`

This value is absolutely correct but if I follow up with:

`$ ratbagctl Pro dpi get`
`800dpi`

Which is the same behavior described in #681.

**Comment by FFY00** [comment]
Fixed by #732
