### ISSUE TITLE
(logitech) Bad CRC when reading onboard memory profiles (8100)

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#729]
I haven't been able to check this on older devices but at least in the newer ones (tested on G Pro Wireless, G603, MX518) we get an invalid CRC when reading the onboard memory profiles (feature 8100). Maybe the memory map changed and we are reading in the wrong place. I need some confirmation on how libratbag behaves with older devices.

**Comment by aTosser** [comment]
This is definatly the case for G Pro Wireless, spend many hours in windows with wireshark and LGS. 
Beginning few lines for ratbagd trying to read profiles:
`ratbag raw: hidpp write: 10 01 09 08 00 00 00`
`ratbag raw: hidpp read:  11 01 09 08 01 03 01 05 01 08 10 00 ff 0a 04 00 00 00 00 00`
`ratbag raw: hidpp write: 10 01 09 28 00 00 00`
`ratbag raw: hidpp read:  11 01 09 28 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

Same lines of LGS reading the profiles:
`Leftover Capture Data: 1001094e000000`
`Leftover Capture Data: 1101094e00010000000000000000000000000000`
`Leftover Capture Data: 1101095e00010000000000000000000000000000`
`Leftover Capture Data: 1101095e01000064009600c800fa002c01ffffff`

LGS is reading my DPI correctly from the profile.. Therefore we are reading the wrong place. At least for newer devices.

ratbagd full init:
http://dpaste.com/2K1NR5W
LGS-profile full read:
http://dpaste.com/27YFJZM

Full capture of device being plugged in and LGS querying it:
[Initial Start.pcapng.gz](https://github.com/libratbag/libratbag/files/3364234/Initial.Start.pcapng.gz)

Please let me know if there is anything I can do to help. My C is very rusty but I can take a whack at it if someone would be willing to review some of the codebase with me.

**Comment by FFY00** [comment]
I just confirmed this doesn't happen due to different memory mappings. The memory mapping is the same between all devices. What did however changed is the profile structure but it was done in such way that newer versions just extend the older ones, so that wouldn't cause this issue either.

Bypassing the CRC check fixes everything, so we have a faulty CRC check routine.

**Comment by FFY00** [comment]
Finally found the issue :dizzy_face:. The last byte of the CRC isn't being properly read.

**Comment by FFY00** [comment]
So, the newer devices report a 255 sector size, but we need to read 256 bytes.

**Comment by FFY00** [comment]
Fixed by #732
