### ISSUE TITLE
ratbagctl.devel is broken on Fedora 30 (dbus-broker)

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#753]
Causes a  "permission denied" on every run. Could be caused by the dbus-broker switch or some other updates. Adding a 200ms delay after the `shutil.copy` call in `start_ratbagd()` fixes is *most* of the time. This indicates that dbus-broker is simply not fast enough reloading the file from disk when we install it.

**Comment by whot** [comment]
Filed as https://github.com/bus1/dbus-broker/issues/206

**Comment by FFY00** [comment]
I think that might be related to what's happening on the arch ci.

**Comment by whot** [comment]
Have you looked at dbe98ed5b9fd56761adc36722803bfb5e80cab6b and c4257802206186b891bea8d055c14b03772a64bf for the arch CI? Possibly related?
