### ISSUE TITLE
Rename Profile.Enabled to Profile.Disabled

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#756]
Fallout from #646 - if we make the current `Enabled` property optional, the three states are
`True`, `False`, `None`. Unfortunately, `None` means "enabled and cannot be disabled" but evaluates as false in boolean checks - like disabled does. This means it's likely to cause issues in clients that use it.

Renaming to `Disabled` makes both boolean-false cases mean "enabled".

Generally it's bad form to have a negative state in an API (too much confusion with double-negatives) but in this case I think we need to make an exception.

This is of course an API break and will affect Piper (cc @Hjdskes)

**Comment by stephanlachnit** [comment]
Does the same apply for #870?

**Comment by whot** [comment]
yes, but I'd rather all the properties switch to disabled in one go. So we don't have some of then "enabled" some of them "disabled" - makes the API worse than it currently is.

**Comment by stephanlachnit** [comment]
Sounds reasonable. But since I really don't want to rewrite everything just to get reverted in the future, I rather tackle this problem first.
