### ISSUE TITLE
[Logitech G Pro Wireless] Change default resolution has no effect.

### ISSUE THREAD

**Issue by aTosser** [libratbag/libratbag#769]
If i do something alon the lines of:
`$ ratbagctl Pro resolution default set 0`
or 
`$ ratbagctl Pro profile 1 resolution default set 0`
then change the profile (i have a mouse button dedicated to this)
the default resolution resets to 1
if I issue:
`$ ratbagctl Pro resolution default get`
`0`
Which is strange because the led indicator on the mouse shows DPI setting 1. (the bottom 2 of the 3 led indicators are lit)

I can confirm this if I stop ratbagd and issue:
`$ ratbagctl Pro resolution default get`
`1`

Bug?

**Comment by FFY00** [comment]
Yes, I think the default property is not working properly. Everything else should be working though. TBH it is not on my high priority list but I'll have a look when I can.
