### ISSUE TITLE
error message when dealing with devices with multiple event nodes

### ISSUE THREAD

**Issue by whot** [libratbag/libratbag#78]
reproducer here is the G500s, symptom is that this device has two event nodes and I'm getting a "no hidraw device found" on each ratbagd start. ratbag-command list lists both event nodes as supported and both show the same info. but: ratbag_open_hidraw_node() has a check so we don't open the same hidraw node twice for two devices. It returns -ENODEV which triggers the error message.

ratbag-command list papers over this because we close the first device before we look at the second one, thus never triggering that code path.

**Comment by bentiss** [comment]
Not being picky, but this was introduce by 855a6bd83.

Just pointing finger at someone to assign the bug to him :)
