### ISSUE TITLE
ratbagd: permission denied AND ratbagctl: No one currently owns org.freedesktop.ratbag1

### ISSUE THREAD

**Issue by adrianocr** [libratbag/libratbag#781]
I had the libratbag package installed from the fedora servers. It was like 2-3 versions behind so I pulled the source, compiled, and installed. 

I used `--prefix=/usr` to overwrite the system installation. Piper was acting weird though so I decided to `sudo dnf remove libratbag-ratbagd piper` and then `sudo ninja -C builddir uninstall` to remove all instances of libratbag and piper so I can start fresh. Verified that everything was purged from my system, logged out, logged back in, and then proceeded to pull the latest sources and re-compile and install. 

However, now I'm getting the following: 

```
➜  sudo ratbagd                
ratbagd error: Failed to start ratbagd: Permission denied
```
and
```
➜  ratbagctl
Unable to connect to ratbagd: No one currently owns org.freedesktop.ratbag1
```

I tried pulling and compiling an older source, and the issue remains. I once again purged my system of libratbag and re-installed the fedora package. The issue remains...

**Comment by whot** [comment]
please run with `--verbose` or `--verbose=raw` to see the actual error messages. But most likely: the dbus policy file (`org.freedesktop.ratbag1.conf`) isn't in the right place. Should be in `/usr/share/dbus-1/system.d` or `/etc/dbus-1/system.d`.

**Comment by adrianocr** [comment]
@whot I don't currently have a use for the library anyway so I'm just going to deal with this in the future if the issue arises again once I purchase a new mouse. I'll reopen in the future if necessary.

**Comment by preppie22** [comment]
For anyone else dealing with this issue. Reloading the dbus service fixed this issue for me.

1. Compile from source with the `/usr` prefix.
2. Reload dbus service: `sudo systemctl reload dbus.service`.
3. Continue as normal.
