### ISSUE TITLE
Incompatible ratbagd API version (required 1, provied -1)

### ISSUE THREAD

**Issue by CesarioFV** [libratbag/libratbag#793]
Hello, 
first of all. Thanks for the amazing work on this issue. 
Both ratgabd and piper are updated (by PPA). 
But when I try to run, I get a mousetrap with this message:
Incompatible ratbagd API version (required 1, provided -1), and a small one asking for an update. I already update many times, using PPA or Flatpak for piper and official ubuntu repositories. 
I tried... 
myuser@myputer:~/piper$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.45.1
Source dir: /home/cesario/piper
Build dir: /home/cesario/piper/builddir
Build type: native build
Project name: piper
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency python3 found: YES 3.6
meson.build:16:0: ERROR: Native dependency 'pygobject-3.0' not found

myuser@myputer:~/piper$ ninja -C builddir
ninja: Entering directory `builddir'
ninja: error: loading 'build.ninja': No such file or directory

Then.. I try.. 

myuser@myputer:~$ sudo ratbagd
ratbagd error: Bus name is taken, another instance of ratbagd is already running.

I also tried...
sudo apt-get install python3-evdev
sudo apt install python3-lxml
Both installed and newest ... 

Any suggestions???
Thanks in advance...

**Comment by whot** [comment]
> meson.build:16:0: ERROR: Native dependency 'pygobject-3.0' not found

You need to install the pygobject3 **develoment** package,  whatever it's called on ubuntu. Fedora calls it pygobject3-devel.

See the [Piper FAQ](https://github.com/libratbag/piper/wiki/FAQ#piper-complains-about-incompatible-ratbagd-api-version-error) for the actual warning, a similar issue is in  https://github.com/libratbag/piper/issues/379.

And yes, the Ubuntu PPA is currently broken, we're waiting on that to be updated.

**Comment by muzena** [comment]
@whot 
I have this problem when I connect G700s at the same time via USB and Nano reciver and then start Piper, when I disconnect USB and again start Piper works normally.

Is python-gi-dev package in Ubuntu, pygobject3-devel package in Fedora?

**Comment by FFY00** [comment]
Is ratbagd running before you start piper for the first time?

**Comment by whot** [comment]
>Is python-gi-dev package in Ubuntu, pygobject3-devel package in Fedora?

see [the piper CI](https://github.com/libratbag/piper/blob/master/.circleci/config.yml#L69) for a list of packages needed to build

**Comment by erdincay** [comment]
This is all that I found on the Internet: 

sudo apt install cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig

sudo cp dbus/org.freedesktop.ratbag1.conf /etc/dbus-1/system.d/org.freedesktop.ratbag1.conf
sudo cp builddir/org.freedesktop.ratbag1.service /etc/dbus-1/system-services/org.freedesktop.ratbag1.conf
sudo cp builddir/ratbagd.service /etc/systemd/system/ratbagd.service

This is what I did myself: 

`sudo apt install libjson-glib-dev
sudo apt install libunistring-dev
sudo apt install python-gi-dev
sudo apt install libsystemd-dev
sudo apt install python3.8-dev
sudo apt install python3.8-full
sudo apt install swig
sudo apt install check`

and:

sudo cp builddir/ratbagd.service /etc/systemd/system/ratbagd.service
