### ISSUE TITLE
Logitech G703 Hero

### ISSUE THREAD

**Issue by nicklaskh** [libratbag/libratbag#794]
Hello. According to the devices list, Logitech G703 Hero are supporter. But Piper doesnt find it. Can I contribute somehow? I have No idea how, so if you need any information, tell me what information you need.

**Comment by whot** [comment]
the G703 Hero is definitely listed in the `svg-lookup.ini`, so it *should* work provided libratbag provides the right strings. What's the output of `ratbagctl info G703`?

**Comment by FFY00** [comment]
I tested it and it was working. Which versions of piper and libratbag are you running? Is your kernel at least 5.2?

**Comment by nicklaskh** [comment]
I'm om openSUSE tumbleweed, so kernel is up to date. Piper is 0.2.904, and libratbag-tools is 0.9.905. Regular libratbag package can't be installed, don't find it in package manager. Tried downloading the installer from openSUSE software page, but it didnt want to install it. Piper installs libratbag-tools automatically.

**Comment by nicklaskh** [comment]
Will check those commands later, omw out with the family.

**Comment by nicklaskh** [comment]
This is the output:

nicklas@linux-1353:~> ratbagctl info g
usage: /usr/bin/ratbagctl <device>
                                   {info,name,profile,resolution,dpi,rate,button,led}
                                   ...
/usr/bin/ratbagctl <device>: error: invalid choice: 'g' (choose from 'info', 'name', 'profile', 'resolution', 'dpi', 'rate', 'button', 'led')
nicklas@linux-1353:~> ratbagctl info G703
usage: /usr/bin/ratbagctl <device>
                                   {info,name,profile,resolution,dpi,rate,button,led}
                                   ...
/usr/bin/ratbagctl <device>: error: invalid choice: 'G703' (choose from 'info', 'name', 'profile', 'resolution', 'dpi', 'rate', 'button', 'led')
nicklas@linux-1353:~>

**Comment by nicklaskh** [comment]
Did this, gives this output:

nicklas@linux-1353:~> ratbagctl G703 info
Unable to find device G703
nicklas@linux-1353:~>

**Comment by nicklaskh** [comment]
nicklas@linux-1353:~> ratbagctl logitech-g703-hero info
Unable to find device logitech-g703-hero
nicklas@linux-1353:~>

**Comment by nicklaskh** [comment]
Any ideas?

**Comment by whot** [comment]
`ratbagctl list`? Looks like the device isn't found, the `ratbagctl G703 info` should've shown it.

**Comment by nicklaskh** [comment]
nicklas@linux-1353:~> ratbagctl list
No devices available.
nicklas@linux-1353:~>

**Comment by nicklaskh** [comment]
I know why it wont work. I have the powerplay mousepad. How can we add it? What do you need?

**Comment by FFY00** [comment]
My kernel patch adding the powerplay receiver was already accepted. You just need to wait for a new release.

**Comment by nicklaskh** [comment]
Oh, I see. Thanks for the info. 😀 Is this solved then? How do I mark it as solved?

**Comment by FFY00** [comment]
Solved!

**Comment by nicklaskh** [comment]
Thanks!

**Comment by nYrXvcpk2l47ciid** [comment]
What kernel version was this patch merged into?
