### ISSUE TITLE
Compiling libratbag Error

### ISSUE THREAD

**Issue by Strowser** [libratbag/libratbag#796]
While trying to compile libratbag to get the latest version (since the Piper+libratbag repo for ubuntu is partially outdated) got this error

`meson.build:77:0: ERROR:  C library 'unistring' not found`

Any ideas?

**Comment by whot** [comment]
https://who-t.blogspot.com/2018/07/meson-fails-with-native-dependency-not-found.html

it's `libunistring-devel` on Fedora, presumably ubuntu has a similarly-named package (`libunistring-dev` or somesuch).

**Comment by Strowser** [comment]
That solved it, thanks :)
