### ISSUE TITLE
Don't ship filenames with `[]` characters, please

### ISSUE THREAD

**Issue by ahkok** [libratbag/libratbag#800]
Some characters are very difficult for packaging tools. You're shipping 2 files with `[]` characters and we have to manually rename them for including them in `clearlinux`. This will affect all RPM based distributions as far as I can see. I'd appreciate if these files can omit those characters so we don't need special handling.

**Comment by whot** [comment]
sounds reasonable, can you send us a PR with the renames please? And ideally a test script so we don't forget about this in the future :)

**Comment by FFY00** [comment]
We can totally do that, but that could also be patched in the packaging tools themselves.

**Comment by whot** [comment]
> this will affect all RPM based distribution

just a note on this:
```
$ rpm -ql libratbag-ratbagd | grep g9x
/usr/share/libratbag/logitech-g9x-[Call-of-Duty-MW3-Edition].device
/usr/share/libratbag/logitech-g9x-[Original].device
```
Fedora is happy with those file names, for reasons I'm too lazy to dig into :)
