### ISSUE TITLE
Update to 0.10 on all supported ubuntu versions

### ISSUE THREAD

**Issue by TannerYoung** [libratbag/libratbag#801]
Currently the released version 0.9.905 at https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git is broken with the released version of piper, resulting in "Incompatible ratbagd API version (required: 1, provided: -1)"

I'm guessing 0.10 fixes this since it was a recent change, but it hasn't been released.

**Comment by muzena** [comment]
Updated new version!
