### ISSUE TITLE
ratbagd API version is -1

### ISSUE THREAD

**Issue by Pshemas** [libratbag/libratbag#802]
I've cleaned the meson build of ratbag and piper as there are up to date version in Opensuse repos.
But I'm having an issue that makes me scratch my head - when I run as root everything works, but when I try to run as regular user I get:

Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 2468, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ratbagctl", line 2452, in main
    _r = open_ratbagd(verbose=cmd.verbose)
  File "/usr/bin/ratbagctl", line 2418, in open_ratbagd
    r = Ratbagd(1)
  File "/usr/bin/ratbagctl", line 266, in __init__
    raise RatbagdIncompatible(self.api_version or -1, api_version)
__main__.RatbagdIncompatible: ratbagd API version is -1 but we require 1

What have I messed up?

**Comment by FFY00** [comment]
No, this is a version mismatch between piper and ratbagd.

**Comment by Pshemas** [comment]
but why it works when I launch it as root?
Checked on a laptop (clean Opensuse Leap 15.1 install) and I get the same problem.

ratbagctl --version
0.10

sudo ratbagd --version
0.10

Piper at 0.3

**Comment by whot** [comment]
I suspect that somehow the ratbagd that's running (possibly started by dbus activation) is an older version that's left over from somewhere. and there's some `PATH` setting that messes things up.

try running everything with the full path, i.e. `sudo /usr/bin/ratbagctl` and check if the error occurs - if so, then we have the culprit.

**Comment by Pshemas** [comment]
as mentioned I've tried on a clean system (Opensuse too) and got the same.
Using full path doesn't help - if I run as regular user ( /usr/bin/ratbagctl) I get API error, but when I do (sudo /usr/bin/ratbagctl) it starts (and shows connected device).

**Comment by whot** [comment]
run `d-feet` (a gnome dbus debugging GUI) and search for the `org.freedesktop.ratbagd1` bus, then go into the `/org/freedesktop/ratbagd1/` path and click on the `org.freedesktop.ratbagd1.Manager` interface. That should have a `APIVersion` property, what does it report when you double-click it?

**Comment by lavadrop** [comment]
I have the same problem.
I have ratbag installed from the Ubuntu 19.04 repositories and Piper installed from Flathub.
This is what d-feet shows me:

⏷/org/freedesktop/ratbagd1/
    ∟⏷**Interfaces**
        ∟⏵org.freedesktop.DBus.Introspectable
        ∟⏵org.freedesktop.DBus.Peer
        ∟⏵org.freedesktop.DBus.Properties
        ∟⏵org.freedesktop.ratbagd1.Manager
            ∟⏷**Properties**
               ∟⏷Array of [Object Path] Devices (read)
               ∟⏷Array of [Strings] Themes (read)

**Comment by FFY00** [comment]
How are you installing libratbag and piper?

**Comment by Pshemas** [comment]
@FFY00 - through zypper (OpenSUSE's package manager - official hardware repos). It seems the issue is distro related - I've noticed another mention of the problem on OpenSUSE's Discord channel.

**Comment by SBado** [comment]
@Pshemas - I'm also using Tumbleweed, you have to add your user to the _games_ group in order to make piper work.
If you take a look at the file _/usr/share/dbus-1/system.d/org.freedesktop.ratbag1.conf_ you will find:
```
<?xml version="1.0"?> <!--*-nxml-*-->
<!DOCTYPE busconfig PUBLIC
        "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
        "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">

<busconfig>

        <policy user="root">
                <allow own="org.freedesktop.ratbag1"/>
                <allow send_destination="org.freedesktop.ratbag1"/>
                <allow receive_sender="org.freedesktop.ratbag1"/>
        </policy>

        <policy group="games">                
                <allow send_destination="org.freedesktop.ratbag1"/>
                <allow receive_sender="org.freedesktop.ratbag1"/>
        </policy>

</busconfig>
```

Piper uses D-Bus to ask ratbagd the version of its API, and as you can see, only _root_ and users in _games_ group can send to or receive from the org.freedesktop.ratbag1 bus.

**Comment by theMarix** [comment]
I am the maintainer of the package in openSUSE. Yes, this error is quite misleading as it is actually a permission problem. I have already been looking into the source whether it wouldn't be possible to give a more specific error message as it is known at compile time what group is required. Sadly, it's not to obvious to me how to detect the situation. Thus, if anybody has a hint, that would be highly appreciated.

**Comment by whot** [comment]
The code bits that matter here are:
- the actual exception being thrown: https://github.com/libratbag/libratbag/blob/master/tools/ratbagd.py#L65
- where it is thrown from: https://github.com/libratbag/libratbag/blob/master/tools/ratbagd.py#L258
- where the data is sourced: https://github.com/libratbag/libratbag/blob/master/tools/ratbagd.py#L278

The last bit is where you'd need to hook in. Right now we abstract dbus properties through a common call to make the code easier, you'd have to adjust [`_get_dbus_property`](https://github.com/libratbag/libratbag/blob/master/tools/ratbagd.py#L182) to handle the permission error (or whatever we're getting on dbus here). Then you can go from there and adjust the rest.

`ratbagd.py` is internal API so we can change it at-will. Piper has a copy of `ratbagd.py`, and we usually sync any changes back and forth, so it roughly follows the same requirements.

**Comment by theMarix** [comment]
As this is now merged I am wondering, should I also make a PR to Piper or will the `ratbagd.py` be copied over before the next Piper release anyhow?

**Comment by FFY00** [comment]
Sure submit a PR.

**Comment by perigoso** [comment]
looks solved to me.
