### ISSUE TITLE
Rival 300 isn't supported

### ISSUE THREAD

**Issue by warriormaster12** [libratbag/libratbag#804]
It's really odd that you don't have rival 300 in supported devices list since there is another non gui program called rivalcfg that does support. I'm just suggesting that you should add support for this mouse as well because I would like to see it working with Piper so that I or future users of this mice won't have to use non-gui alternatives.

**Comment by whot** [comment]
we are seriously struggling for time. If there's an existing implementation for this mouse, I strongly encourage you to look at the protocol and implement the libratbag driver for it - shouldn't be too hard and we're happy to help where needed. Piper support will come for free once libratbag supports it.

**Comment by FFY00** [comment]
This .device file should work.

```
[Device]
Name=SteelSeries Rival 300
DeviceMatch=usb:1038:1710
Driver=steelseries

[Driver/steelseries]
DeviceVersion=1
Buttons=6
Leds=2
DpiRange=50:6500@50
MacroLength=1
```

**Comment by FFY00** [comment]
@warriormaster12 can you confirm this worked? If so we can add it to the repo.

**Comment by warriormaster12** [comment]
@FFY00 can you guide me through the setup?

**Comment by whot** [comment]
@warriormaster12 drop the above as a `somename.device` into `/usr/share/libratbag/ and restart `ratbagd`. That should do the trick.

**Comment by warriormaster12** [comment]
I added the file. Piper detects my mouse but changing and applying any setting won't change a thing.

**Comment by FFY00** [comment]
Please run `ratbagd` with verbosity and paste the output.

```
ratbagd --verbose=raw
```

**Comment by FFY00** [comment]
@warriormaster12 do you need any further help getting the log I requested?

**Comment by warriormaster12** [comment]
@FFY00 I got it working, sorry for the late response. I had an issue where it wouldn't allow me to debug even in sudo mode but now it seems that updates resolved the problem 

`ratbag debug: New device: SteelSeries SteelSeries Rival 300 Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw0: "SteelSeries SteelSeries Rival 300 Gaming Mouse", 1 profiles
ratbag debug: New device: SteelSeries SteelSeries Rival 300 Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw1: "SteelSeries SteelSeries Rival 300 Gaming Mouse", 1 profiles
ratbag debug: New device: SteelSeries SteelSeries Rival 300 Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: driver match found: SteelSeries
hidraw2: "SteelSeries SteelSeries Rival 300 Gaming Mouse", 1 profiles
ratbag debug: New device: SEMICO USB Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1a2c:4ee8
ratbag debug: New device: SEMICO USB Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1a2c:4ee8
ratbag debug: Profile 0 changed, rewriting
ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 07 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 08 01 ef 29 29 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: Profile 0 changed, rewriting
ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 07 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 08 01 ef 29 29 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 07 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 08 02 34 65 a4 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

**Comment by warriormaster12** [comment]
@FFY00 did it help? Do I have to do something else?

**Comment by jakestevens96** [comment]
Hi,

I followed everything that was said here and mine isn't working either. Even after restarting ratbagd. When I start piper I get 3 profiles to pick from for some reason too.

**Comment by FFY00** [comment]
It is weird it isn't working. @jakestevens96, so I guess you get the same output as @warriormaster12, right? If you have a bit of time please try to run wireshark in a windows machine (vm or otherwise) while configuring the mouse and post the packet dumps. Try to make a packet dump for each thing (starting the driver, changing dpi, changing leds, etc.).

**Comment by gimbas** [comment]
Just wanted to leave here my logs,
i have a Rival 300.

this is without a .device file:
```
ratbag debug: New device: SteelSeries Rival Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1384
ratbag debug: SteelSeries Rival Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1384
ratbag debug: SteelSeries Rival Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw0: "SteelSeries Rival Gaming Mouse", 1 profiles
ratbag debug: New device: SteelSeries Rival Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1384
ratbag debug: SteelSeries Rival Gaming Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1384
ratbag debug: SteelSeries Rival Gaming Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw1: "SteelSeries Rival Gaming Mouse", 1 profiles
ratbag debug: New device: SteelSeries Rival Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1384
ratbag debug: SteelSeries Rival Gaming Mouse is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1384
ratbag debug: SteelSeries Rival Gaming Mouse is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw2: "SteelSeries Rival Gaming Mouse", 1 profiles
ratbag debug: New device: SteelSeries Rival Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1384
ratbag debug: SteelSeries Rival Gaming Mouse is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1384
ratbag debug: SteelSeries Rival Gaming Mouse is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: driver match found: SteelSeries
hidraw3: "SteelSeries Rival Gaming Mouse", 1 profiles
ratbag debug: Profile 0 changed, rewriting
ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 03 01 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: Profile 0 changed, rewriting
ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 03 02 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: Profile 0 changed, rewriting
ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 07 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 08 02 00 00 ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: Profile 0 changed, rewriting
ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 07 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 08 02 ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: output report: 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```
it shows up as 4 devices in piper, the first one lets us attempt to write some settings, the other three report `Something went wrong. The device has been reset to a previous state`, the dpi settings do nothing, the led settings do some weird things, but kind of work, if you squint real hard

**Comment by gimbas** [comment]
I just notice my device's PID (0x1384 vs 0x1710) is different, and doesn't seem to align with other rival models, maybe an older version?

**Comment by klausenbusk** [comment]
In my case, most of the logic seems to work (sensitivity, button and leds) (tested with Piper):
```
[Device]
Name=SteelSeries Rival 300
DeviceMatch=usb:1038:1710
Driver=steelseries

[Driver/steelseries]
DeviceVersion=1
Buttons=6
#DeviceIndex=1
Leds=2
DpiRange=50:6500@50
MacroLength=1
```

The protocol is documented here: https://github.com/flozz/rivalcfg/blob/2ba56151bfde4e5cadbb9ea7cb2768b5a9a3509c/doc/rival300-spec.md

**Comment by amfern** [comment]
@klausenbusk Thank you for validating, we appreciate your effort.
I was wondering does it still works for you, can you confirm?

**Comment by klausenbusk** [comment]
Plugging in the mouse, running `ratbagctl singing-gundi led 0 set mode cycle` twice and `ratbagctl singing-gundi dpi set 65000` twice:
```
okt 08 23:03:39 foo ratbagd[1041129]: ce: SteelSeries SteelSeries Rival 300 Gaming Mouse
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Using data directory '/usr/share/libratbag'
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: device assigned driver steelseries
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw2'.
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw2'.
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: driver match found: SteelSeries
okt 08 23:03:39 foo ratbagd[1041129]: hidraw2: "SteelSeries SteelSeries Rival 300 Gaming Mouse", 1 profiles
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: New device: SteelSeries SteelSeries Rival 300 Gaming Mouse
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Using data directory '/usr/share/libratbag'
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: device assigned driver steelseries
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw3'.
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: - HID report ID 01
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: - HID report ID 02
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw3'.
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: - HID report ID 01
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: - HID report ID 02
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: - HID report ID 01
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: - HID report ID 02
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: driver match found: SteelSeries
okt 08 23:03:39 foo ratbagd[1041129]: hidraw3: "SteelSeries SteelSeries Rival 300 Gaming Mouse", 1 profiles
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Profile 0 changed, rewriting
okt 08 23:03:39 foo ratbagd[1041129]: ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
okt 08 23:03:39 foo ratbagd[1041129]: ratbag raw: output report: 03 01 1f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
okt 08 23:03:39 foo ratbagd[1041129]: ratbag raw: output report: 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Profile 0 changed, rewriting
okt 08 23:03:39 foo ratbagd[1041129]: ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Profile 0 changed, rewriting
okt 08 23:03:39 foo ratbagd[1041129]: ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Profile 0 changed, rewriting
okt 08 23:03:39 foo ratbagd[1041129]: ratbag raw: output report: 04 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: New device: SteelSeries SteelSeries Rival 300 Gaming Mouse
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Using data directory '/usr/share/libratbag'
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: device assigned driver steelseries
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw1'.
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw1'.
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: driver match found: SteelSeries
okt 08 23:03:39 foo ratbagd[1041129]: hidraw3: "SteelSeries SteelSeries Rival 300 Gaming Mouse", 1 profiles
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: New device: SteelSeries SteelSeries Rival 300 Gaming Mouse
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Using data directory '/usr/share/libratbag'
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: device assigned driver steelseries
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw2'.
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1710
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: SteelSeries SteelSeries Rival 300 Gaming Mouse is device '/dev/hidraw2'.
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:39 foo ratbagd[1041129]: ratbag debug: Parsing HID report descriptor
okt 08 23:03:41 foo ratbagd[1041129]: ratbag debug: driver mratbagd error: error committing device (-1000)
okt 08 23:03:44 foo ratbagd[1041129]: ratbagd error: error committing device (-1000)
okt 08 23:03:47 foo ratbagd[1041129]: ratbagd error: error committing device (-1000)
okt 08 23:03:49 foo ratbagd[1041129]: ratbagd error: error committing device (-1000)
```

**Comment by perigoso** [comment]
rival and rival 300 use the same protocol so I tested mine again, it seems to be mostly working, i was able to set the dpi, and map the buttons, the leds do some configuration but not what would be expected, for instance setting them to off sets blue color, this might be an hardware issue on my end, seems like the blue led is always on.

so in short the driver is apparently working and this should be true for the rival 300

**Comment by amfern** [comment]
@klausenbusk 65000 is actually above the maximum value defined in the .device file. Could you test again with it 6500 dpi value?

**Comment by klausenbusk** [comment]
> Could you test again with it 6500 dpi value?

Sure, it makes no difference.

**Comment by FFY00** [comment]
Looks like a previous iteration of the protocol in the Rival 310, which tracks. Perhaps looking at the Rival 310 protocol will help reverse engineering those commands, as they should probably be similar, https://github.com/FFY00/rival310-re.

**Comment by amfern** [comment]
After going over the code of libratbag and rivalcfg i found some difference:

It seems there was a firmware update somewhere in the middle of  2017 for rival 300 devices. The protocol changed abit and the fix was to prefix with 0x00 (https://github.com/flozz/rivalcfg/commit/5cdfa43f5e29f7641cbddbd6372a8f4ab82598ca) before every packet for every steel series mouse
OpenRGB also do the same prefix 0x00 https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Controllers/SteelSeriesController/SteelSeriesRivalController.cpp#L19

also, rivalcfg has a larger sleep interval of 50 ms instead of 10ms, but looking at the commit message it doesn't seem effecting the riva 300 devices.

@klausenbusk can you confirm the 0x00 difference in the packet?

**Comment by klausenbusk** [comment]
The only difference I'm seeing is ratbag always sending 32 byte and using a different wValue (`0x0203`) where rivalcfg is always using `0x0200`.

**Comment by klausenbusk** [comment]
Reading a bit into how USB/HID works. We are always sending a `SET_REPORT` (bRequest = `0x09`) and in that case `wValue` represents `Report Type and Report ID`.

Page 61:
> The wValue field specifies the Report Type in the high byte and the Report 
> ID in the low byte. Set Report ID to 0 (zero) if Report IDs are not used.  
> Report Type is specified as follows: 
>
> | Value | Report Type |
> | - | - |
> | 01 | Input |
> | 02 | Output |
> | 03 | Feature |
> | 04-FF | Reserved |

So in both cases the report type is "output". Report ID is explained as (page 27):
> **Report ID** items are used to indicate which data fields are represented in each report structure. A **Report ID** item tag assigns a 1-byte identification prefix to each report transfer. If no **Report ID** item tags are present in the Report descriptor, it can be assumed that only one Input, Output, and Feature report structure exists and together they represent all of the device’s data.

The kernel [HIDRAW documentation](https://www.kernel.org/doc/html/v5.14/hid/hidraw.html) states:
> **write()**
> [...]
> The first byte of the buffer passed to write() should be set to the **report number**. If the device does not use numbered reports, the first byte should be set to 0. The report data itself should begin at the second byte.

So the mouse has:
> only one Input, Output, and Feature report structure exists and together they represent all of the device’s data

is the conclusion.

Spec here: https://www.usb.org/sites/default/files/documents/hid1_11.pdf

**Comment by amfern** [comment]
> The first byte of the buffer passed to write() should be set to the report number. If the device does not use numbered reports, the first byte should be set to 0. The report data itself should begin at the second byte.

So steel series aren't using numbered reports, so that's why we need to set 0x00 as the first bytes and then send the raw data starting from the second byte, i wonder what sets the 0x02 in the wValue, the hidraw driver because we called write() on it?

**Comment by klausenbusk** [comment]
> i wonder what sets the 0x02 in the wValue, the hidraw driver because we called write() on it?

Yes, https://github.com/torvalds/linux/blob/717478d89fe22df61a4ecf73b1adb31b5f8d1bba/drivers/hid/hidraw.c#L151-L152

**Comment by amfern** [comment]
Ok, so the next step for me is to create a patch for that, I am wondering if I should go ahead and create a quirk for supporting older firmware of this device?

**Comment by amfern** [comment]
I guess sticking to the hardware manufacturer of 32 bytes would be the safest choice.
Regarding the quirk, it's possible to retrieve the firmware version by sending 0x10 and reading back 2 bytes like in [here](https://github.com/flozz/rivalcfg/blob/7b80115a90ae18d20024bebe6fe121b2c4206c36/rivalcfg/mouse.py#L108)
But i don't know at what version it changed, so i can start with implementing a quirk and changing it once we have more information

**Comment by FFY00** [comment]
Can anyone run `lshid -v -d 1038:1710`? https://github.com/FFY00/lshid
If you have Wireshark captures for the original driver, and libratbag, it would also be helpful.

**Comment by flozz** [comment]
> how if we add 0x00 as report message, does it affect the devices before the firmeware update in any way? based on your experience with rivalcfg.

I think it should not affect old models. I have a Rival 300 at home, I can try to check its firmware version to confirm maybe?

> And also what do you think about consolidating our efforts and maintaining libratbag, rivalcfg and libratbag pretty much aim to do the same thing

I am not good enough in C to dev on libratbag (and I have too much work currently to improve my skills).

Also you cannot make a single "steelseries driver" with some parameters / protocol version (as i saw [here](https://github.com/libratbag/libratbag/blob/master/src/driver-steelseries.c)) to support all devices (there are more than 80 mice, and some are very different from each others ¬_¬'...).

As Rivalcfg is specific to SteelSeries products and is in Python, it is easier for me to support all devices and their strange behavior. But I can help you if you need info about a specific mouse that is already supported by Rivalcfg.

**Comment by amfern** [comment]
It's true that steel series are odd, unlike Logitech where the protocol is a bit more stable and unified across their devices. But we can adapt the driver to handle such oddities. Maybe in the same way as you did in rivalcfg.

I think if you are able to reverse engineer binary protocol and write rivalcfg, you are more then capable to handle the C part :)

**Comment by flozz** [comment]
> I think if you are able to reverse engineer binary protocol and write rivalcfg, you are more than capable to handle the C part :)

Yeah I can probably handle this on the technical side. But I am working on too many projects and I am already not able to handle all the work required by them...
