### ISSUE TITLE
Logitech G502 Lightspeed not detected

### ISSUE THREAD

**Issue by MohanVashist1** [libratbag/libratbag#805]
Hello all,

I tried to configure my Logitech G502 Lightspeed using Piper, except for the fact that no devices show up.

![Screenshot from 2019-08-31 17-02-25](https://user-images.githubusercontent.com/34726032/64069115-2e9c0d00-cc11-11e9-91b3-6edee7fa28d7.png)

![Screenshot from 2019-08-31 17-03-14](https://user-images.githubusercontent.com/34726032/64069118-3bb8fc00-cc11-11e9-9302-e4e5fbfbb7b1.png)

Does anyone know a fix??? Any help is appreciated.

**Comment by FFY00** [comment]
The .device file has only added a few days ago (https://github.com/libratbag/libratbag/commit/75bcf39114933dba60aee3f47fa449b5000ee39e) and hasn't been included in any release. For now you can just add it yourself.

**Comment by MohanVashist1** [comment]
@FFY00 do you know when it's going to be released or how I can include it myself????

**Comment by FFY00** [comment]
We haven't had enough relevent changes to make a new release.

You can get your device to work just by adding this file in `/usr/share/libratbag/logitech-g502-hero-wireless.device`.
```yaml
[Device]
Name=Logitech G502 Hero Wireless
DeviceMatch=usb:046d:407f
Driver=hidpp20
```

**Comment by MohanVashist1** [comment]
Strange, file already exists but the mouse still is not detected
![Screenshot from 2019-08-31 17-17-45](https://user-images.githubusercontent.com/34726032/64069222-57250680-cc13-11e9-8deb-616724a819fe.png)

**Comment by FFY00** [comment]
Stop the daemon and run it manually with verbosity.

```
ratbagd --verbose=raw
```

**Comment by MohanVashist1** [comment]
Still nothing :( 

![Screenshot from 2019-08-31 17-26-58](https://user-images.githubusercontent.com/34726032/64069282-956ef580-cc14-11e9-9f43-4d93c251634f.png)

![Screenshot from 2019-08-31 17-27-00](https://user-images.githubusercontent.com/34726032/64069283-9869e600-cc14-11e9-9411-ff2f3ab01713.png)

**Comment by FFY00** [comment]
I said to stop the deamon.

```
systemctl stop ratbagd
```

Then run the daemon with verbosity and post the log so I can see what's going on.

**Comment by FFY00** [comment]
You need Linux 5.2 for Logitech wireless devices to work properly. Alternatively you can change the usb PID in the .device file to `c539` to bypass the kernel driver and talk to the receiver directly, but you won't get proper device identification.

**Comment by MohanVashist1** [comment]
Sorry I'm a bit of a linux novice.

But I updated the .device file
![Screenshot from 2019-08-31 17-37-31](https://user-images.githubusercontent.com/34726032/64069358-1bd80700-cc16-11e9-9d45-0c0683849879.png)

Then ran the same steps above and got this
![Screenshot from 2019-08-31 17-37-35](https://user-images.githubusercontent.com/34726032/64069363-2abeb980-cc16-11e9-8e6d-f160d6cd002d.png)
![Screenshot from 2019-08-31 17-37-37](https://user-images.githubusercontent.com/34726032/64069365-2e524080-cc16-11e9-9cdb-3af3b9ddc94d.png)

**Comment by FFY00** [comment]
You changed the driver, not the usb PID.

This is the correct content.
```yaml
[Device]
Name=Logitech G502 Hero Wireless
DeviceMatch=usb:046d:c539
Driver=hidpp20
```

**Comment by FFY00** [comment]
Were you able to get it to work? Do you need any further help?

**Comment by MohanVashist1** [comment]
I wasn't able to try out what you recommended yet. I will let you know once I try.

**Comment by MohanVashist1** [comment]
Upgrading to kernel version 5.2 did the trick! Everything works now thank you so much :)
![Screenshot from 2019-09-01 13-04-56](https://user-images.githubusercontent.com/34726032/64079748-344d2d80-ccb9-11e9-97c0-a057e3598e37.png)
![Screenshot from 2019-09-01 13-04-54](https://user-images.githubusercontent.com/34726032/64079749-37481e00-ccb9-11e9-87e4-592a4b412c97.png)
