### ISSUE TITLE
Logitech G703 Hero is not supported

### ISSUE THREAD

**Issue by hsa1280** [libratbag/libratbag#807]
New purchased G703 Hero, `lsusb` shows:
Bus 001 Device 007: ID 046d:c539 Logitech, Inc.

`ratbagctl` can't recognize it, and Piper can't recognize it either. But the mouse is working fine. I checked the `/usr/share/libratbag/`, it has `logitech-g703-hero.device` file. `ratbagd` is running in the background.

OS: 4.19.66-1-MANJARO
Piper:  0.3
Libratbag: 0.10-1

**Comment by FFY00** [comment]
You need Linux 5.2. I believe Manjaro has packages that provide newer kernels.

**Comment by FFY00** [comment]
Yup, `pacman -S linux52` or `pacman -S linux53` should do the trick.

**Comment by hsa1280** [comment]
@FFY00 Thanks, I will give it a try.

**Comment by FFY00** [comment]
I updated the wiki to document this.

https://github.com/libratbag/libratbag/wiki/Building-from-source#dependencies

**Comment by hsa1280** [comment]
It is working now, I will close this issue, thank you for your help!
