### ISSUE TITLE
Add a LED API

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#81]
We also need an API to control the LED (because we need it).

From what I can gather from the various devices I encountered, some have very tunable LED (like the G303), others have basic functionalities (like the Etekcity). I think the common denominator is:
- export, per profile, one LED object per LED on the device (Roccat Konw XTD has 4, G303 has 2 and pretty much the rest 1)
- allow to change the LED color if possible (we need a capability for that)
- allow to apply an effect on the color (or not -> only seen in the Roccat, maybe in the G303)
- allow to turn to set the light effect:
  - on
  - off
  - hearbit
  - breathing
  - pulsing

We might not expose that many effects (breathing, heartbit, etc). The most important ones are IMO ON/OFF and the set_color so we can assign a color per profile.

**Comment by amfern** [comment]
I added LED support for g502 and g900 devices  #113 
can you please review it

**Comment by bentiss** [comment]
Apologies for the delay in the review process.

Before starting the review (and asking for changes if need be), I wanted to coordinate with @whot given that your pull request contains both internal changes in the hidpp20 driver and public API changes. I have done that just now, and so we can move on to the next part of the process, doing the actual review.

However, as you must know, the public API changes are the most difficult ones because we need to be spot on. We can't change the API/ABI at each commit, so we need to be careful when we amend the public API. Don't be afraid if we ask for changes. Just keep pushing :)

Anyway, thanks a lot for your pull request. I really appreciate the work done, especially for caring about tests. Expect a review of the pull request in the coming days, and if it doesn't come up, don't hesitate to send (again) a gentle ping :)

**Comment by amfern** [comment]
Thanks for taking the time and reviewing my PR, i will gladly modify the PR to suite your standards.

**Comment by amfern** [comment]
I pushed changes the PR #113 
its still big change, and i am not sure how to break it further, open for suggestions.

**Comment by amfern** [comment]
#129 resolves this issue

**Comment by amfern** [comment]
#129
