### ISSUE TITLE
DPI configuration different on Linux vs Windows?

### ISSUE THREAD

**Issue by diogovk** [libratbag/libratbag#821]
If I set the DPI to 800, which is what I use on Windows, the pointer is way too slow. If I set to 1600 DPI in piper, it seems to get similar to 800 DPI on Windows on but not precisely. (I measure by counting "in game" revolutions on my mousepad, while using the same game settings).

Do you have documentation or resources which can help me match my DPI configuration on both Linux and Windows?

My mouse is a `Logitech, Inc. G502 Proteus Spectrum Optical Mouse`

**Comment by FFY00** [comment]
Both Windows and Linux have speed multipliers for the cursor, so that you can change the speed of mice without configurable DPI. Can you check your settings?

**Comment by diogovk** [comment]
I think I found my problem:
https://bugs.winehq.org/show_bug.cgi?id=45882
