### ISSUE TITLE
not opening/running

### ISSUE THREAD

**Issue by tarbear123** [libratbag/libratbag#822]
when i type:
sudo apt-get install libratbag

i get this error:
E: Unable to locate package libratbag

plz help me fix this

**Comment by whot** [comment]
you distribution doesn't package libratbag or it's not available under that name. Please look up the `apt-get` documentation to learn how to search for packages.

Ubuntu has a PPA here: https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git
