### ISSUE TITLE
Logitech G604 Lightspeed

### ISSUE THREAD

**Issue by jboxberger** [libratbag/libratbag#827]
Hello libratbag Team, 

thanks a lot for the great work. Is there already any approaches for the new Logitech G604 Lightspeed? I own this mice and would like to use it in full on linux. So is there a way i can help you out?

Kind Regards

**Comment by FFY00** [comment]
I'll see if I can do it today.

**Comment by FFY00** [comment]
Okay, I tested it and it works fine with the current codebase. The only issue is that you won't be able to configure it when connected over bluetooth until #829 gets merged.
