### ISSUE TITLE
G304 not supported? even though it is exactly the same as G305 which is supported

### ISSUE THREAD

**Issue by yashvone** [libratbag/libratbag#833]

**Comment by FFY00** [comment]
Probably just needs the a .device file for the device ID to be identified.

**Comment by yashvone** [comment]
so after adding .device file would i need to build it and piper from source?

**Comment by yashvone** [comment]
> Probably just needs the a .device file for the device ID to be identified.

so after adding .device file would i need to build it and piper from source?

**Comment by FFY00** [comment]
No, you should be able to just drop the file in your filesystem. However, if you want the correct image to show up in piper you will need to add an entry in the resources file and rebuild it.

**Comment by yashvone** [comment]
I tried getting the device id, but it only shows the usb reciever id. It's basically the same device as g305 but for non US regions. Am i doing something wrong? I tried "lsusb" and "ratbagctl"

**Comment by FFY00** [comment]
Can you post the output of `dmesg | grep logitech`?

**Comment by yashvone** [comment]
~$ dmesg | grep Logitech
[20412.460085] usb 1-6: Manufacturer: Logitech
[20412.466069] input: Logitech USB Receiver as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:046D:C53F.0004/input/input23
[20412.527308] hid-generic 0003:046D:C53F.0004: input,hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:00:14.0-6/input0
[20412.531266] input: Logitech USB Receiver Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/0003:046D:C53F.0005/input/input24
[20412.589238] input: Logitech USB Receiver Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/0003:046D:C53F.0005/input/input25
[20412.589603] input: Logitech USB Receiver System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/0003:046D:C53F.0005/input/input26
[20412.590222] hid-generic 0003:046D:C53F.0005: input,hiddev0,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:00:14.0-6/input1
[20412.594536] hid-generic 0003:046D:C53F.0006: hiddev1,hidraw2: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:14.0-6/input2
[21887.395707] usb 1-6: Manufacturer: Logitech
[21887.401636] input: Logitech USB Receiver as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:046D:C53F.0007/input/input28
[21887.459972] hid-generic 0003:046D:C53F.0007: input,hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:00:14.0-6/input0
[21887.463986] input: Logitech USB Receiver Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/0003:046D:C53F.0008/input/input29
[21887.464808] input: Logitech USB Receiver Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/0003:046D:C53F.0008/input/input30
[21887.523303] input: Logitech USB Receiver System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/0003:046D:C53F.0008/input/input31
[21887.524162] hid-generic 0003:046D:C53F.0008: input,hiddev0,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:00:14.0-6/input1
[21887.528090] hid-generic 0003:046D:C53F.0009: hiddev1,hidraw2: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:14.0-6/input2

**Comment by FFY00** [comment]
Which kernel are you running? You need at least Linux 5.2.

**Comment by yashvone** [comment]
Linux 5.3.0-19-generic x86_64

**Comment by FFY00** [comment]
Ah! Forgot the G305 comes with the new Lightspeed receiver. You need https://github.com/torvalds/linux/commit/5722f3386eb9847131573513190796533e8f4999 which appears to be in Linux 5.4.

**Comment by yashvone** [comment]
Ok, so something messed up while updating the kernel. It can't find the root file system when I boot with 5.4 but still boots with old kernel...although I can't adjust brightness and volume and some other features seem to be missing as well. 
Any idea how I my fix it? Will deleting the new kernel automatically revert it back to old? I might just reinstall the linux

**Comment by crab2313** [comment]
I have not add a .device file. But ratbagd just crash on launch.
```
(gdb) run --verbose
Starting program: /usr/bin/ratbagd --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
ratbag debug: New device: LEOPOLD Mini Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0853:0134
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c53f
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c53f
ratbag debug: New device: Logitech G304
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc53f
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc53f
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x4074
ratbag debug: Logitech G304 is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 0e
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID 20
ratbag debug: - HID report ID 21
ratbag debug: 'Logitech G304' is using protocol v4.2
ratbag debug: 'Logitech G304' is quirked (HIDPP20_QUIRK_G305)
ratbag debug: device battery level is 90% (next 50%), status 0 
ratbag debug: device has color effects
ratbag debug: device has onboard profiles
ratbag debug: Reading sector 0x0000
ratbag error:     HID++ error from the device (1): ERR_INVALID_ARGUMENT (02)
double free or corruption (fasttop)

Program received signal SIGABRT, Aborted.
0x00007ffff7df3f25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7df3f25 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7ddd897 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7e37258 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff7e3e77a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff7e40295 in _int_free () from /usr/lib/libc.so.6
#5  0x0000555555568d75 in hidpp20drv_remove.part.0.lto_priv.0 (device=<optimized out>) at ../src/driver-hidpp20.c:1512
#6  0x000055555556909c in hidpp20drv_remove (device=0x555555592c70) at ../src/driver-hidpp20.c:1608
#7  hidpp20drv_probe (device=<optimized out>) at ../src/driver-hidpp20.c:1608
#8  hidpp20drv_probe (device=<optimized out>) at ../src/driver-hidpp20.c:1550
#9  0x00005555555717dc in ratbag_try_driver (test_device=0x0, dev_id=<optimized out>, driver_name=0x555555593b30 "hidpp20", device=<optimized out>)
    at ../src/libratbag.c:325
#10 ratbag_assign_driver (test_device=0x0, dev_id=<optimized out>, device=<optimized out>) at ../src/libratbag.c:404
#11 ratbag_device_new_from_udev_device (device_out=<synthetic pointer>, udev_device=<optimized out>, ratbag=0x55555558eba0) at ../src/libratbag.c:467
#12 ratbagd_process_device (ctx=0x55555558e870, udevice=<optimized out>) at ../ratbagd/ratbagd.c:218
#13 0x0000555555559500 in ratbagd_run_enumerate (ctx=0x55555558e870) at ../ratbagd/ratbagd.c:451
#14 ratbagd_run (ctx=0x55555558e870) at ../ratbagd/ratbagd.c:495
#15 main (argc=<optimized out>, argv=<optimized out>) at ../ratbagd/ratbagd.c:641

```

**Comment by crab2313** [comment]
```
# dmesg | grep Logitech
[ 2215.748500] usb 2-3: Manufacturer: Logitech
[ 2215.766041] logitech-djreceiver 0003:046D:C53F.000D: hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:05:00.3-3/input0
[ 2215.827524] logitech-djreceiver 0003:046D:C53F.000E: hiddev0,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:05:00.3-3/input1
[ 2215.886108] logitech-djreceiver 0003:046D:C53F.000F: hiddev1,hidraw2: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:05:00.3-3/input2
[ 2215.956508] input: Logitech G304 as /devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb2/2-3/2-3:1.2/0003:046D:C53F.000F/0003:046D:4074.0010/input/input31
[ 2215.957009] logitech-hidpp-device 0003:046D:4074.0010: input,hidraw4: USB HID v1.11 Keyboard [Logitech G304] on usb-0000:05:00.3-3/input2:1
```
kernel version 5.4

**Comment by FFY00** [comment]
@crab2313 thanks! This happens because the G305 has a bug where we can't read any memory from it before we have written to it. I wrote a quirk for that but as it appears I've made a mistake and it's causing your daemon to crash. I do not have any G305 in that state so could you please avoid connecting your mouse to a windows machine with logitech software on it, so that you can test my fix?

**Comment by crab2313** [comment]
@FFY00 No problem. I think it is in the original state since I don't use any software from logitech.

**Comment by gagan0123** [comment]
> Ah! Forgot the G305 comes with the new Lightspeed receiver. You need [torvalds/linux@5722f33](https://github.com/torvalds/linux/commit/5722f3386eb9847131573513190796533e8f4999) which appears to be in Linux 5.4.

Seems we'll have to wait for 5.4 kernel to be able to use piper and ratbag

**Comment by crab2313** [comment]
@FFY00 I can confirm it is somehow work with this patch applied.

```diff
diff --git a/src/hidpp20.c b/src/hidpp20.c
index 0811e4c..7049338 100644
--- a/src/hidpp20.c
+++ b/src/hidpp20.c
@@ -2627,7 +2627,7 @@ hidpp20_onboard_profiles_initialize(struct hidpp20_device *device,
                                                  profiles->sector_size,
                                                  data);
 
-       if (rc && device->quirk != HIDPP20_QUIRK_G305) {
+       if (rc && device->quirk == HIDPP20_QUIRK_G305) {
                /* The G305 has a bug where it throws an ERR_INVALID_ARGUMENT
                   if the sector has not been written to yet. If this happens
                   we will read the ROM profiles.*/
```

**Comment by FFY00** [comment]
Oh my god, I am so stupid :persevere:. Do you want to submit a PR or want me to do it?

**Comment by crab2313** [comment]
@FFY00 I will submit a PR. There is still a segfault when I stop the daemon by ctrl-c. Maybe I can fix that too.

**Comment by FFY00** [comment]
Thanks! If you could do that it would be great, I don't have a lot of time right now.

**Comment by FFY00** [comment]
@whot please wait for @crab2313's patch before making a release.

**Comment by gagan0123** [comment]
What about G304? It's simply a clone of 305 but for Asian market(I'm from India)

**Comment by crab2313** [comment]
@gagan0123 Try my patch above. I am using a G304. Everything is fine except piper shows a 404 mouse picture. G304 has the same internal ID with G305 and is work out of box if G305 is supported.
