### ISSUE TITLE
ratbagd assert failure: double free or corruption (fasttop)

### ISSUE THREAD

**Issue by qidydl** [libratbag/libratbag#850]
Ubuntu just popped up an "internal error" dialog due to a ratbagd crash; I can't seem to get actual text from it, so for now all I have is screenshots. I was not actively using ratbag/piper when the dialog appeared. I had opened piper a few minutes ago, looked through the dialog pages, and closed it without attempting to make any changes.

This is what I could find in journalctl:

```
Dec 01 15:20:48 frequency systemd[1]: Starting Daemon to introspect and modify configurable mice...
Dec 01 15:20:48 frequency systemd[1]: Started Daemon to introspect and modify configurable mice.
Dec 01 15:41:28 frequency ratbagd[6516]: double free or corruption (fasttop)
Dec 01 15:41:28 frequency systemd[1]: ratbagd.service: Main process exited, code=dumped, status=6/ABRT
Dec 01 15:41:28 frequency systemd[1]: ratbagd.service: Failed with result 'core-dump'.
Dec 01 15:41:28 frequency systemd[1]: ratbagd.service: Service RestartSec=100ms expired, scheduling restart.
Dec 01 15:41:28 frequency systemd[1]: ratbagd.service: Scheduled restart job, restart counter is at 1.
Dec 01 15:41:28 frequency systemd[1]: Stopped Daemon to introspect and modify configurable mice.
Dec 01 15:41:28 frequency systemd[1]: Starting Daemon to introspect and modify configurable mice...
Dec 01 15:41:28 frequency systemd[1]: Started Daemon to introspect and modify configurable mice.
```

![ratbagd-basic](https://user-images.githubusercontent.com/5160192/69920225-25f6e500-1453-11ea-979e-b8057b55a62d.png)
![ratbagd-stack](https://user-images.githubusercontent.com/5160192/69920226-2abb9900-1453-11ea-8599-7308060fd632.png)

**Comment by FFY00** [comment]
Which device are you using?

**Comment by qidydl** [comment]
Shoot, that would have been a smart thing to mention. I have a Logitech G703, being accessed via the wireless dongle. Please let me know if there's any log or system data that would be useful.

**Comment by FFY00** [comment]
Which version of the G703? There are two, one with the hero sensor and one with other sensor IIRC.

Can you paste the output of `dmesg | grep logitech`?

**Comment by qidydl** [comment]
dmesg output:

[    1.716674] logitech-djreceiver 0003:046D:C539.0003: hidraw2: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:0b:00.3-1.1/input0
[    1.880746] logitech-djreceiver 0003:046D:C539.0004: hiddev2,hidraw3: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:0b:00.3-1.1/input1
[    1.940729] logitech-djreceiver 0003:046D:C539.0005: hiddev3,hidraw4: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:0b:00.3-1.1/input2
[    2.002776] logitech-djreceiver 0003:046D:C539.0005: device of type eQUAD Lightspeed (0x0c) connected on slot 1
[    2.116896] logitech-hidpp-device 0003:046D:4070.0006: input,hidraw5: USB HID v1.11 Keyboard [Logitech G703] on usb-0000:0b:00.3-1.1/input2:1
[  430.643132] logitech-hidpp-device 0003:046D:4070.0006: HID++ 4.2 device connected.
[21181.516031] logitech-hidpp-device 0003:046D:C087.0007: input,hidraw2: USB HID v1.11 Mouse [Logitech G703 Wired/Wireless Gaming Mouse] on usb-0000:0b:00.3-1.1/input0
[21181.580095] logitech-hidpp-device 0003:046D:C087.0008: HID++ 4.2 device connected.
[21181.702711] logitech-hidpp-device 0003:046D:C087.0008: input,hiddev2,hidraw3: USB HID v1.11 Keyboard [Logitech G703 Wired/Wireless Gaming Mouse] on usb-0000:0b:00.3-1.1/input1
[25767.536974] logitech-djreceiver 0003:046D:C539.0009: hidraw2: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:0b:00.3-1.1/input0
[25767.598642] logitech-djreceiver 0003:046D:C539.000A: hiddev2,hidraw3: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:0b:00.3-1.1/input1
[25767.658138] logitech-djreceiver 0003:046D:C539.000B: hiddev3,hidraw4: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:0b:00.3-1.1/input2
[25767.717182] logitech-djreceiver 0003:046D:C539.000B: device of type eQUAD Lightspeed (0x0c) connected on slot 1
[25767.731819] logitech-hidpp-device 0003:046D:4070.000C: HID++ 4.2 device connected.
[25767.792537] logitech-hidpp-device 0003:046D:4070.000C: input,hidraw5: USB HID v1.11 Keyboard [Logitech G703] on usb-0000:0b:00.3-1.1/input2:1

**Comment by FFY00** [comment]
Are you able to reproduce this?

**Comment by qidydl** [comment]
Not so far. There was a kernel upgrade on December 2 from 5.3.0-23 to 5.3.0-24, not sure if a driver change could have resolved it? If it does reoccur for myself or anyone else at least we have this issue to refer back to, let me know if there's any other information that would help.

**Comment by FFY00** [comment]
I think this was resolved by the latest commit in master, could you try?

**Comment by qidydl** [comment]
I have version 0.12, would that contain the fix? I get it via the Ubuntu/Launchpad PPA.

**Comment by FFY00** [comment]
Yes, can you confirm it works?

**Comment by qidydl** [comment]
I poked it with piper and it hasn't crashed after 20 minutes, so it's tough to prove a negative but it seems to be behaving now. Thanks, much appreciated!
