### ISSUE TITLE
Provide GPG signature for releases

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#853]
I would like if we provided signed tarballs for releases. There are two approaches here, sign the tarballs generated by github or provide our own signed tarballs. Signing github tarballs shouldn't be an issue as they are deterministic and we can reproduce them locally. But I feel like maybe it's best to upload or own tarballs?

cc @bentiss @whot

**Comment by whot** [comment]
what's the specific use-case here? we're pushing signed tags anyway and given the trust we place in github for everything anyway, having the tarballs it generates based on that signed tag doesn't seem that much of an issue.

Having said that, it'd be trivial-ish to upload the bits to have the checksums signed for the tarballs. the [xf86-input-wacom `release.sh`](https://github.com/linuxwacom/xf86-input-wacom/blob/master/release.sh#L114) script does something like that and should be easy to copy/adjust.

**Comment by FFY00** [comment]
Ah, sorry. Github tricked me, in https://github.com/libratbag/libratbag/releases/tag/v0.11 it says "Unverified" but that's because your PGP key isn't in github.

Signed tags are fine by me. Signing the tarballs is always good but this is sufficient for me. If you want to copy the tarball signing routine from that `release.sh` feel free.

**Comment by whot** [comment]
uploaded my gpg key now, so it should show as verified now
