### ISSUE TITLE
Rely on libabigail to check ABI breakages

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#86]
We are currently trying to provide stable ABI in libratbag by bumping the soname when needed and properly exporting the symbols. We are not guarantee to introduce any breakage unless we rely on ABI comparison between versions.

[libaigail](https://www.sourceware.org/libabigail/) allows to run ABI checks between .so.

It would be interesting to add such comparison in the semaphore script.

libabigail provides a tool abidiff which compares 2 .so and returns a non null value in case of an ABI failure. The 2 .so need to be compiled with debug information ([DWARF](http://www.dwarfstd.org/) style, obtained by appending "-g" to the CPPFLAGS).

We should compare the ABI to the last tagged git entry and/or to the last soname bump.

(I propose we try to integrate libabigail in our continuous integration so we can have the same type of check in libinput, libevdev, etc... )

**Comment by bentiss** [comment]
Update after discussion with libabigail guys:

We might as well generate the XML abi file (directly upstream ~300KB) or in a separate repo, and compare to it. This way, we can declare an ABI "current" and avoid having to generate a lot of abi suppression files.

**Comment by whot** [comment]
Update after a discussion between @bentiss and me: this is something we should first integrate in our semaphore build scripts, not just yet into a Makefile hook. Mainly because we need to compare to a previous API and the XML files aren't always stable. This is fairly trivial in semaphore but more complicated in a make dist hook.

**Comment by bentiss** [comment]
Closing given Naaah was already set
