### ISSUE TITLE
Unable to delete DPI profile

### ISSUE THREAD

**Issue by ghost** [libratbag/libratbag#869]
I am able to change DPI and LED options, but not able to set the 5th profile to 0 DPI (as was originally) or delete any profile. Please see the following demonstration:

[https://my.mixtape.moe/mkvwky.mkv](https://my.mixtape.moe/mkvwky.mkv)

**Kernel:**
4.18.11-arch1-1-ARCH

**Mouse:**
Logitech G403

**Versions:**
piper 0.2.902-1
libratbag 0.9.903-1

Packages were installed from the Arch repo. Issue occurs also with piper-git AUR package:
**piper-git-0.2.902.r15.g31085fa-1**

Thanks for any help!

**Comment by bentiss** [comment]
> I'm going to work on this feature in libratbag. @whot can you move the issue to libratbag and assign me?

done :)

(I wasn't aware we can transfer issues between repos)

@stephanlachnit: Should we keep this one open or can we close it?

**Comment by stephanlachnit** [comment]
Please let it open, I don't know how fast I'm able to do it since I have to figure out libratbag's internals first.

**Comment by FFY00** [comment]
Implementation tasks:
	- Add a `enabled` property for resolutions in the DBus API
	- Implement it in `driver-hidpp20.c` (set the dpi to 0)

You might have to adapt the DPI checks to take this into account.

**Comment by stephanlachnit** [comment]
> Implementation tasks:
> - Add a `enabled` property for resolutions in the DBus API
> - Implement it in `driver-hidpp20.c` (set the dpi to 0)
> 
> You might have to adapt the DPI checks to take this into account.

Thanks! Right now I try to figure out how a call from `libratbag.c` actually goes to the driver, meaning when I call `ratbag_resolution_set_dpi`, what will this do in `driver-hidpp20.c`? Been a couple of years since I touched C code...

**Comment by moll** [comment]
It seems since my last workaround (https://github.com/libratbag/libratbag/issues/869#issuecomment-459985256) from Feb 2, 2019, this broke and setting the DPI to 0 via `ratbagctl` doesn't work any mor.e

**Comment by FFY00** [comment]
#870 should solve it.
