### ISSUE TITLE
Steelseries Sensei 310 brightness not supported

### ISSUE THREAD

**Issue by morfcz** [libratbag/libratbag#883]
I believe this mouse should support brightness settings for led as previous versions of this mouse (for example steelseries sensei raw), but it reports it's not supported.

ratbagctl "SteelSeries SteelSeries Sensei 310 eSports Mouse" led 0 capabilities
Modes: breathing, cycle, off, on

It would be nice to have the led on but with lower brightness.

**Comment by FFY00** [comment]
It does support brightness, black is 0 brightness, white is 100% brightness. It's the same implementation as the official software.
