### ISSUE TITLE
Inconsistent Device Identifiers

### ISSUE THREAD

**Issue by ghost** [libratbag/libratbag#902]
**Is your feature request related to a problem? Please describe.**
Device identifiers are not consistent, for example I've seen a single G600 listed as "warbling-mara" and then as "singing-gundi" after rebooting. Unsure if this is actually a bug or just how libratbag works.

**Describe the solution you'd like**
Device identifiers should be deterministic and always unique to that device.

Hopefully there's some identifier you could pull to also uniquely determine the difference between two devices connected from the same model.

**Comment by FFY00** [comment]
This is not a bug. You can use the device name as an identifier if you want, ex. `ratbagctl 'Logitech G600' info`.

**Comment by MicrosoftTakeover** [comment]
> This is not a bug. You can use the device name as an identifier if you want, ex. `ratbagctl 'Logitech G600' info`.
What if there's two Logitech G600s connected?

**Comment by FFY00** [comment]
Then you need to use the normal identifier.

**Comment by MicrosoftTakeover** [comment]
> Then you need to use the normal identifier.

But the normal identifier is inconstant, if I wanted to write scripts to control multiple devices I'm limited here.

**Comment by FFY00** [comment]
You shouldn't write scripts that invoke `ratbagctl`, that is not a use case we support. What you should do instead is talk directly to the daemon using DBus.

Having consistent device IDs would require us to read serial numbers, which not all devices support.

**Comment by MicrosoftTakeover** [comment]
Could you provide an example of how to properly talk to the daemon using DBus in a way I could use in a script?

I was thinking the same thing about device IDs needing serial numbers but I wasn't sure. Would you consider supporting unique identifiers for devices with serial numbers when the device supports it, and less reliable identifier when they don't?

**Comment by whot** [comment]
fwiw, we specifically randomise the assigned pseudo-names to make it impossible to script around ratbagctl for this particular use-case. and we do it simply because we cannot promise that the assigned names are constant - they will be *most of the time* but by luck, not by design. So we simply prohibit that case.

Exporting a serial number property *may* be interesting but I don't know how many of the devices we currently support have one.

**Comment by FFY00** [comment]
Well, all HID++ 2.0 devices should support it. I am not sure about HID++ 1.0 but it's very possible. Even though this is just one vendor, it's still a considerable amount of devices.

**Comment by MicrosoftTakeover** [comment]
I'm also curious why is it unsupported to write scripts around ratbagctl? I don't see the difference between configuring a mouse in a terminal manually vs configuring the mouse using the same command in a bash script or similar.

**Comment by FFY00** [comment]
Because it's impossible to guarantee that you are configuring the right device. A solution, as discussed here, would be to get the serial number from the device, but that will not work for all devices.

**Comment by MicrosoftTakeover** [comment]
Ah sorry, I think there's some confusion here. As mentioned previously, for a single device you can just state the device name, i.e. `ratbagctl 'Logitech Gaming Mouse G600' profile 0 dpi set 400`

The problem is with multiple devices like in the case where you have two mice/keyboards of the same make/model. 

Is it that scripting is unsupported in general or only for the multiple device use case?

**Comment by FFY00** [comment]
Well, considering the nature of the command you can consider it supported in cases where you only have one device.

**Comment by MicrosoftTakeover** [comment]
Thanks, that's how I'm currently using it.

Multiple device support would be nice though, like if I had a second G600 hooked up for use in a Virtual Machine (Like a PCI-Passthrough VM for gaming) and I didn't want my script to interact with the wrong mouse while the VM was shut off.

**Comment by whot** [comment]
ratbagctl is primarily a debugging tool for the developres. where we expect users to use that for scripting, we need to commit to a stable interface - lest we brake everyone's scripts. There is room for a commandline tool to interact with ratbagd but ratbagctl isn't it and at least I don't want to commit to a specific commandline interface forever.
