### ISSUE TITLE
Logitech G815 keyboard support.

### ISSUE THREAD

**Issue by Nouwan** [libratbag/libratbag#903]
Today I bought a new logitech G815 keyboard from the store. Since I've had a lot of luck so far with my linux installation I didn't think anything of it until I tried downloading Logitech G hub to set the colors which of course is only supported on Windows and Mac.
After some googeling I found libratbag which I tried to use but sadly does not seem to support my keyboard.

I would love it if libratbag could support my logitech G815 keyboard. 
Ive tried to use the g810-led package in hopes it would maybe support the 815 as well but could not get it working. 

I of course understand this is a community effort and would love to help with proggraming / debugging / testing for this feature. My C is quite rusty but with some guidance I think it could be fun.

**Comment by FFY00** [comment]
Logitech keyboards are supported in master, but we can't configure colors yet. I did not try test the G815 but my G915 is working. I hope to have colors working before the end of the month in time for FOSDEM :grin:.

**Comment by Lars-bs** [comment]
Thats super cool. I will compile the main branch and see if the G815 detects as well. Are there any logs or information that I can report back that will help?

**Comment by Nouwan** [comment]
I've managed to get the device to show up and I seem to be able to change the profile. However binding buttons doesn't work. Nor do the profile buttons on the keyboard when running ratbag. Of course colors don't work as well but this I assume is normal since you mentioned its not supported yet. The debug log gives ERR_INVALID_ARGUMENT (02) when trying to set button actions. I don't really know how to go from here so if someone could point me in the right direction that would be great.

Device file so far:
https://gist.github.com/Nouwan/762bbda7f9d5c78b0b05db78d955acc9

Debug log from trying to assing a hotkey and switching profiles:
https://gist.github.com/Nouwan/ab8f18109bcd61d39fa699fc8d34d1d0

**Comment by FFY00** [comment]
I have a patch fixing that in my desktop. But I am in a bus with direction to FOSDEM and totally forgot to push it.

I can try re-writing it when I get to my airbnb but I will need someone to test it.

cc @tfylling

**Comment by Nouwan** [comment]
I could compile your fix and test it on my system with the G815 if this is still needed.

**Comment by tfylling** [comment]
Sure, I can probably help test this as well.

@Nouwan: The following will set your profile keys (except going straight from M1 to M3 doesn't work, for whatever reason, as per [issue #909](https://github.com/libratbag/libratbag/issues/909))
First find your assigned device name with
```
ratbagctl list
```
Mine was singing-gundi, so replace that with whatever yours is
```
ratbagctl singing-gundi profile 0 button 5 action set special unknown
ratbagctl singing-gundi profile 0 button 6 action set special profile-up
ratbagctl singing-gundi profile 0 button 7 action set special profile-cycle-down

ratbagctl singing-gundi profile 1 button 5 action set special profile-down
ratbagctl singing-gundi profile 1 button 6 action set special unknown
ratbagctl singing-gundi profile 1 button 7 action set special profile-up

ratbagctl singing-gundi profile 2 button 5 action set special profile-cycle-up
ratbagctl singing-gundi profile 2 button 6 action set special profile-down
ratbagctl singing-gundi profile 2 button 7 action set special unknown
```
I also disabled all the G-buttons, as their default mapping to F keys is just annoying, especially in the case of G5 being that close to Ctrl.
```
ratbagctl singing-gundi profile 0 button 0 action set special unknown
ratbagctl singing-gundi profile 1 button 0 action set special unknown
ratbagctl singing-gundi profile 2 button 0 action set special unknown

ratbagctl singing-gundi profile 0 button 1 action set special unknown
ratbagctl singing-gundi profile 1 button 1 action set special unknown
ratbagctl singing-gundi profile 2 button 1 action set special unknown

ratbagctl singing-gundi profile 0 button 2 action set special unknown
ratbagctl singing-gundi profile 1 button 2 action set special unknown
ratbagctl singing-gundi profile 2 button 2 action set special unknown

ratbagctl singing-gundi profile 0 button 3 action set special unknown
ratbagctl singing-gundi profile 1 button 3 action set special unknown
ratbagctl singing-gundi profile 2 button 3 action set special unknown

ratbagctl singing-gundi profile 0 button 4 action set special unknown
ratbagctl singing-gundi profile 1 button 4 action set special unknown
ratbagctl singing-gundi profile 2 button 4 action set special unknown
```

**Comment by kamushadenes** [comment]
Hello!

Have you managed to assign any key or macro to G1-G5?

I tried

```ratbagctl cheering-viscacha profile 0 button 4 action set macro KEY_SPACE KEY_M KEY_E KEY_B```

```
cheering-viscacha - Logitech G815 RGB MECHANICAL GAMING KEYBOARD
             Model: usb:046d:c33f:0
 Number of Buttons: 8
    Number of Leds: 2
Number of Profiles: 3
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
  Button: 0 is mapped to 'unknown'
  Button: 1 is mapped to 'unknown'
  Button: 2 is mapped to 'unknown'
  Button: 3 is mapped to 'unknown'
  Button: 4 is mapped to macro '↕SPACE ↕M ↕E ↕B'
  Button: 5 is mapped to 'unknown'
  Button: 6 is mapped to 'profile-up'
  Button: 7 is mapped to 'profile-cycle-down'
  LED: 0, depth: rgb, mode: cycle, duration: 2100, brightness: 255
  LED: 1, depth: rgb, mode: off
```

But it does nothing. Setting it to unknown as the comment above stopped it from mapping to the F keys, but nothing else seems to work.

Running ratbagd as raw shows this when trying to write the macro:

```
ratbag error: Error while writing macro for button 4
ratbag error: hidpp20: failed to update button
ratbagd error: error committing device (-1000)
```

Can anyone please point me to how to debug this further?

**Comment by Nouwan** [comment]
I compiled the last version from source and tested it with the G815.
Working in both piper and libratbagctl:
- Changing the color brightness and mode for the keyboard leds
- Changing the color brithtness and mode for the logitech logo leds
- Switching between profiles (Thanks to the commands provided by @tfylling )
- Binding Macro's to all of the G keys (Tested ALT + F4 and CTRL + T)
- Binding specials to all of the G keys and profile keys (Tested cycle)

Remaining issues
- It's not possible to go from profile 0 directly to profile 2 with the m3 key, as per #909 
- Piper doesn't recognizes the device as a mouse (I will open a seperate issue to properly support the G815 on their github after this issue is closed)
- After committing changes to the keyboard on profile 0 I have to activate any other profile and switch back to 0 for changes to become active. (Maybe this is as it should be)

@kamushadenes  I could not reproduce the hidpp20: failed to update button.
A few things you could check (If you didn't already)
- Are all dependencies for libratbag installed?
- Did you compile the latest version of the master branch for your testing?
- Are there any differences between the device file I posted and the one you used?

**Comment by FFY00** [comment]
> Have you managed to assign any key or macro to G1-G5?

We currently don't suppor macros on Logitech devices, you can still remap the buttons, just no write complex macros.

> It's not possible to go from profile 0 directly to profile 2 with the m3 key, as per #909

I don't think there's anything we can do about it, it comes from Logitech.

> After committing changes to the keyboard on profile 0 I have to activate any other profile and switch back to 0 for changes to become active. (Maybe this is as it should be)

I am pretty sure you can just re-enable the same profile, for clicking in M1 when in profile 1 to reload it. I haven't found any way to get past this, I am not even sure there's one.

**Comment by Nouwan** [comment]
> We currently don't suppor macros on Logitech devices, you can still remap the buttons, just no write complex macros.
So it working for me is just luck, this issue would not block a merge request then right?

> I am pretty sure you can just re-enable the same profile, for clicking in M1 when in profile 1 to reload it. I haven't found any way to get past this, I am not even sure there's one.
It doesn't do anything for me (Since bound it to special Unknown) Is there a way to bind it a special reloading the profile?

**Comment by FFY00** [comment]
> So it working for me is just luck, this wouldn't prevent the issue from closing then?

Which command were you issuing?

> It doesn't do anything for me (Since bound it to special Unknown) Is there a way to bind a special reloading the profile?

Not for now, but libratbag should keep the settings if they were already configured there.

**Comment by Nouwan** [comment]
> Which command were you issuing?
I used:
ratbagctl warbling-mara profile 0 button 2 action set macro +KEY_LEFTCTRL  t300 +KEY_W -KEY_W -KEY_LEFTCTRL

**Comment by FFY00** [comment]
Well, if it works, great! But it shouldn't...

**Comment by Nouwan** [comment]
Yeah it really does. Should I provide the log from ratbagd --verbose for future reference?

**Comment by kamushadenes** [comment]
Really doesn't work for me, as expected.

I see https://github.com/libratbag/libratbag/pull/792 but I'm not sure I can help as I'm not familiar with this project's architecture, but I'll give it a try.

Anything I should know?

**Comment by FFY00** [comment]
Well, the G815 is nor supported so I'm closing. Please open a new issue for the other stuff if it persists.

**Comment by kamushadenes** [comment]
Sorry to comment on a closed issue, but just to make sure we are on the same page, macros are still not supported, right?

**Comment by Floppy012** [comment]
> Sorry to comment on a closed issue, but just to make sure we are on the same page, macros are still not supported, right?

Simple macros like CTRL + S do work. However the keyboard doesn't accept anything more than one normal key being pressed.

This works fine on my keyboard:
`ratbagctl <name> profile 0 button 0 action set macro +KEY_LEFTCTRL +KEY_S t150 -KEY_S -KEY_LEFTCTRL`

**Comment by FFY00** [comment]
Basically, everything that is translatable to a single key binding (supports modifiers) should work.
