### ISSUE TITLE
G903 - Missing usb id

### ISSUE THREAD

**Issue by patvdleer** [libratbag/libratbag#905]
The id missing is `046d:c539` which is for a G903 

M/N: M-R0068

**Comment by FFY00** [comment]
That is the ID if the receiver,  not the device itself. Does the device not show up?

**Comment by patvdleer** [comment]
It does when connected via wire.

**Comment by FFY00** [comment]
Which kernel version are you running?

**Comment by FFY00** [comment]
You need at least Linux 5.5.
