### ISSUE TITLE
Cant add repository

### ISSUE THREAD

**Issue by hirax02** [libratbag/libratbag#914]
sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git
[sudo] password for hirax: 
'This PPA does not support xenial'
???

**Comment by FFY00** [comment]
Seems like the repo isn't supported in your Ubuntu version.

**Comment by muzena** [comment]
No, xenial is too old, it has to many build dependencies issue.

**Comment by stephanlachnit** [comment]
You could simply download the libratbag and Piper debs from the Debian archive.
libratbag is included in Ubuntu anyway, but probably outdated in xenial, Piper is included since eoan.

**Comment by hirax02** [comment]
OK good to know :) I will try to download them separately. Btw my OS is not pure ubuntu, it is ubuntu based Linux Mint 18.3 KDE

**Comment by stephanlachnit** [comment]
Closing since this is not really an upstream issue.
