### ISSUE TITLE
Is it possible to configure a mouse while inside a virtual machine?

### ISSUE THREAD

**Issue by rhyek** [libratbag/libratbag#915]
I have a windows 10 host and an Ubuntu 19.10 guest OS where I would like to use Piper to configure a Logitech G903 mouse (specifically the left/right scroll wheel buttons).

Is it possible or would this only work when using Linux as the host system? Currently Piper says it can't find any supported device which I understand since what the OS is seeing is probably an emulated mouse.

I am using VMWare player.

**Comment by stephanlachnit** [comment]
I guess it's only possible when you assign the device to the VM, but then you can't use it in Windows anymore.

**Comment by FFY00** [comment]
Closing as unrelated.
