### ISSUE TITLE
G700s wireless USB not fully functional

### ISSUE THREAD

**Issue by vividnightmare** [libratbag/libratbag#92]
The G700s is reporting expected results when accessing the device over its wired USB connection.

However, when trying to access it over its wireless USB receiver I am not able to retrieve information on buttons beyond left, right, and middle click.  This occurs when using both ratbag-command and ratbagctl.

Sample output:

```
vivid@2500k:~$ sudo ratbag-command list
/dev/input/event2:  Logitech G700s Rechargeable Gaming Mouse
/dev/input/event22: Logitech USB Receiver
/dev/input/event23: Logitech USB Receiver
/dev/input/event3:  Logitech G700s Rechargeable Gaming Mouse
vivid@2500k:~$ sudo ratbag-command button count /dev/input/event3
13
vivid@2500k:~$ sudo ratbag-command button count /dev/input/event23
3
vivid@2500k:~$ ratbagctl list-devices
event23:   Logitech USB Receiver           
event3:    Logitech G700s Rechargeable Gaming Mouse
vivid@2500k:~$ ratbagctl show-button event3 0 3
Button 3 on Profile 0 on event3 (Logitech G700s Rechargeable Gaming Mouse)
           Type: thumb
    Action Type: button
 Button Mapping: 4
vivid@2500k:~$ ratbagctl show-button event23 0 3
Invalid button index 3
```

**Comment by 11111010000** [comment]
I think the firmware ignores the wireless connection while connected by the wire.
You can plug wireless dongle to one computer and wire to the another. You will see that the wired connection breaks the wireless one, so behaviour you experienced should be expected.

**Comment by hoshsadiq** [comment]
This is correct. This is the way it behaves even when using on Windows and Mac using the official drivers.

**Comment by FFY00** [comment]
Yes, this works as expected. The device can only be connected to 1 host, the cable has priority over the dongle.
