### ISSUE TITLE
question: can I change profiles from bash?

### ISSUE THREAD

**Issue by BETLOG** [libratbag/libratbag#921]
How do I switch between profiles from the command line?
I have some game binds that are fairly hazardous on the desktop, so it would be nice if i could script the switching of profiles.

**Comment by BETLOG** [comment]
My bad.. didn't see it until I looked a little deeper.
https://github.com/libratbag/libratbag/wiki/Usage
$ ratbagctl "$(ratbagctl list|sed -E 's/.*:\ *(.*)\ /\1/')" profile active set 1
$ ratbagctl "$(ratbagctl list|sed -E 's/.*:\ *(.*)\ /\1/')" profile active set 0

**Comment by bentiss** [comment]
Couple of notes:

> $ ratbagctl "$(ratbagctl list|sed -E 's/.:\ (.)\ /\1/')" profile active set 1

Better use:
```
$ ratbagctl G9x profile active set 1
```
(replace `G9x` with any part of your device that is unique enough to not be confused with anyone else shown by `ratbagctl list`)

And second, we do not guarantee a stable output/parameters from `ratbagctl`, so do not get angry if we change something in the future (we already did that once)

**Comment by BETLOG** [comment]
Nice!

No problem. Change is to be expected. Bash scripts are how I amuse myself.
For a while there a few months ago I was changing my .evrouterrc between 'Logitech Unifying Device' and'Logitech Performance MX'.
After about the third time I just scripted a permanent auto-select.
