### ISSUE TITLE
Support for ASUS ROG Devices (e.g. Gladius 2, Gladius 2 Wireless,...)

### ISSUE THREAD

**Issue by SuperMeowBro** [libratbag/libratbag#925]
It would be very cool, if support for ASUS ROG Devices like Gladius 2 or Gladius 2 Wireless could be added. There is an driver project on github (https://github.com/kyokenn/rogdrv), that could help to implement.

**Comment by FFY00** [comment]
Yes, sure. @kyokenn what do you think? We can't do it for now as we don't have the hardware.

**Comment by kyokenn** [comment]
I'm just a Python developer. I'm not that good at C/C++ and I'm not familiar with the API. So I would need some help with it, some debug tools for the library and some dummy driver where I could start.

**Comment by stephanlachnit** [comment]
The driver with the most features is the [hidpp20](https://github.com/libratbag/libratbag/blob/master/src/driver-hidpp20.c) driver, but also quite complicated I guess. The easiest one is probably the [etekcity](https://github.com/libratbag/libratbag/blob/master/src/driver-etekcity.c) driver, albeit without LED support.

libratbag has a [`ratbag_device` class](https://github.com/libratbag/libratbag/blob/master/src/libratbag.c#L186), and more important a [`ratbag_profile` class](https://github.com/libratbag/libratbag/blob/master/src/libratbag.c#L694), which should include all informations about dpi, buttons, leds, etc. The driver should be able to read these informations from the device, and should be able to commit the set of these variables on the device if wished by the user. It's not easy, but maybe you can fiddle around with the etekcity driver and we can help if you have a problem.

**Comment by FFY00** [comment]
I wonder if it's not better to get the devices emulated in https://github.com/libratbag/ratbag-emu and then write the driver.

**Comment by evrifaessa** [comment]
I own a ROG Gladius ii Core and can post any needed diagnostic data you need about it.

- Distribution: Pop!_OS 21.10

- `uname -srmo`
Linux 5.13.0-7619-generic x86_64 GNU/Linux

- `ratbagd --version`
0.15

- `sudo ratbagd --verbose=raw`
```
Initializing libratbag
ratbag debug: New device: Razer Razer USB Audio Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:0520
ratbag debug: New device: ASUSTeK ROG GLADIUS II CORE
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0b05:18dd
ratbag debug: New device: ASUSTeK ROG GLADIUS II CORE
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0b05:18dd
ratbag debug: New device: ASUSTeK ROG GLADIUS II CORE
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0b05:18dd
DBus server ready
```

More information:

* Amazon: https://www.amazon.com/ASUS-Lightweight-Ergonomic-ROG-Exclusive-Switch-Socket/dp/B07V6WWGST
* Maximum DPI: 6200

If you need anything else, feel free to ping me. Thanks for your nice work :)
