### ISSUE TITLE
Error compiling on Archlinux

### ISSUE THREAD

**Issue by sigzegv** [libratbag/libratbag#928]
**Describe the bug**
I'm trying to compile libratbag but I get this meson error
```
Run-time dependency check found: NO (tried pkgconfig and cmake)
meson.build:364:1: ERROR: Dependency "check" not found, tried pkgconfig and cmake
```
I'm not sure which package I'm missing, "check" keyword is really too generic for a search...

**Comment by whot** [comment]
it's unfortunately really called [check](https://libcheck.github.io/check/) but you may find it as libcheck, check-code, or some other name in the arch repos. 

https://who-t.blogspot.com/2018/07/meson-fails-with-native-dependency-not-found.html has instructions on how to figure out what to install based on the error message.

**Comment by sigzegv** [comment]
I install `check` package but it installed a `checkmk` binary, so I had to rename it to check and it worked fine ty.

**Comment by FFY00** [comment]
@whot you could have just pinged me :grin:

Archlinux keeps the upstream names so the package is called `check`.

@sigzegv that shouldn't be necessary, actually you should not do that.
