### ISSUE TITLE
[question] Add libratbag to meson users

### ISSUE THREAD

**Issue by stephanlachnit** [libratbag/libratbag#932]
Do we want to set ourselves to the [list of projects that use meson](https://github.com/mesonbuild/meson/edit/master/docs/markdown/Users.md)? Quote:
> All the software on this list is tested for regressions before release, so it's highly recommended that projects add themselves here.

I think it would be nice, what do you think @whot @bentiss @FFY00?

**Comment by whot** [comment]
So I guess they `git clone libratbag` and make sure it builds with the latest version of meson? Sounds useful, but whether it's truly necessary I don't know. I don't think we've every had true issues with meson itself.

**Comment by FFY00** [comment]
Sure, I don't see why not.

**Comment by bentiss** [comment]
nothing against from me. If it ever catches one breakage, that would be already the infinity times more than what we ever had :)

**Comment by stephanlachnit** [comment]
> but whether it's truly necessary I don't know

The list is not just for testing, people can browse various projects and check out different examples. And it's some advertisement for libratbag as well as for meson I guess.
Here's the PR: https://github.com/mesonbuild/meson/pull/6719
