### ISSUE TITLE
ERROR: Dependency "libsystemd" not found

### ISSUE THREAD

**Issue by DestroyFX** [libratbag/libratbag#934]
I have PC with Gentoo and some other older computers with MX Linux

Is is actually possible to actually build that lib without installing systemd? Because none of my system come with it by default.

meson.build:82:1: ERROR: Dependency "libsystemd" not found, tried pkgconfig and cmake

Not going to install that malware (systemd) and mess with my custom script tonight, might just install windows to configure that mouse instead, if it's not possible to build without systemd.

**Comment by bentiss** [comment]
See #239 #278:

we do not require systemd, but libsystemd and udev. libesystemd is the only sane dbus API. So, yes, that's a choice, and that is your choice to not install this project but install windows instead.

**Comment by jaamivstheworld** [comment]
2+ years late but I find it hilarious that this guy won't install SystemD because he considers it malware but will install Windows... the duality of man. LOL
