### ISSUE TITLE
Support for automatic profile switching for different applications

### ISSUE THREAD

**Issue by ElHyperion** [libratbag/libratbag#935]
Probably the most useful feature of my Logitech gaming mouse is the ability to create a profile for various applications, which are automatically switched to once I focus that application.

For example I can create a profile for a web browser where the extra buttons (beyond previous/next which are automatically recognized) work as tab switching buttons (Ctrl + PgDn/Up), or for going one level higher / opening file properties in the file explorer, and those profiles get automatically activated once I focus these windows.

There could be a button for assigning a created profile to an application which would open a file explorer where you just select the executable binary, or input the terminal command for the application.

[xdotool](https://www.semicomplete.com/projects/xdotool/) seems to be able to retrieve the currently focused window so I guess it could run as a daemon that would communicate with this application.

**Comment by stephanlachnit** [comment]
> xdotool seems to be able to retrieve the currently focused window so I guess it could run as a daemon that would communicate with this application.

That wouldn't work with Wayland if I'm not wrong.

**Comment by ElHyperion** [comment]
Seems so, and I couldn't find a way to catch the currently focused window in Wayland either.

I suppose it could be done only for xorg, for now?

**Comment by FFY00** [comment]
Either way, this is out of scope. You can write an app which checks that and uses the DBus API to change the settings.

**Comment by ElHyperion** [comment]
I've got so far no experience in programming applications that interact with the Linux system (or xorg specifically) but I'm up for it. I'm finally moving my primary workstation to Linux and this is about the last thing keeping me worried as this mouse profiling increases my effectiveness by a long shot.

Any recommendations on where to start? I would ideally like to use Python. I can take on some pain with C but only if I -really- have no other option. I can deal with the UI on my own, perhaps make it similar to your Piper, I just need to know how to tell this app to switch to a specific profile.

**Comment by FFY00** [comment]
Yes, Python should be fine. You can have a look at `ratbagctl` to understand how to connect to the DBus API and then you can use [python-libxdo](https://github.com/rshk/python-libxdo) to get the active window.
