### ISSUE TITLE
Support for EVGA X10 Carbon

### ISSUE THREAD

**Issue by fubarhouse** [libratbag/libratbag#941]
I'd like support for my EVGA X10 Carbon.
It's the only reason I have a need to keep Windows around...

**Comment by fubarhouse** [comment]
Hmm... Any pointers for a driver-noob?

**Comment by FFY00** [comment]
You can have a look at https://blog.flozz.fr/2016/03/27/steelseries-rival-100-reverse-engineering-dun-peripherique-usb/ for the rever engineering part. It's in french but google translate should be enough for you to understand.

I want to make an english tutorial but I need to find the time.

For the actual code, it's not that hard if you know C. Just look at the other drivers (pick a simple one).

I can assist if you need help.

**Comment by staticssleever668** [comment]
Since this mouse would require writing a new driver, let's close this until someone volunteers to write one.
