### ISSUE TITLE
Mismatched ratbagd / ratbagctl versions cause errors

### ISSUE THREAD

**Issue by skitt** [libratbag/libratbag#956]
When testing upgades to ratbagd 0.4, I noticed that running ratbagctl 0.4 with an already-running ratbagd 0.2 produces

    event6:    None

and show-device produces

    Traceback (most recent call last):
      File "/usr/bin/ratbagctl", line 202, in <module>
        main(sys.argv[1:])
      File "/usr/bin/ratbagctl", line 199, in main
        cmd.func(r, cmd)
      File "/usr/bin/ratbagctl", line 92, in show_device
        capabilities = [caps[c] for c in d.capabilities]
    TypeError: 'NoneType' object is not iterable

It would be nice if ratbagctl queried ratbagd’s version and complained appropriately.

**Comment by stephanlachnit** [comment]
I'm not sure if this even applies anymore, just moved it from libratbag/ratbagd.

**Comment by FFY00** [comment]
Yeah, this is really old. We don't support it anymore and we have introduced an API to avoid this.
