### ISSUE TITLE
Use lgtm.com

### ISSUE THREAD

**Issue by stephanlachnit** [libratbag/libratbag#957]
What do you think of adding https://lgtm.com for PRs to libratbag and Piper? From what I saw, the hints/warnings don't look to bad. Also it doesn't panic on PRs, meaning it shows the delta of warnings and doesn't fail if no new warnings are introduced.

/cc @FFY00 @whot @bentiss

**Comment by whot** [comment]
A few months ago I had a bunch of fixes submitted to (iirc) libinput but there were quite a lot of false positives. So yes in principal, it's always good to have more checks but it depends on the false positive ratio.

**Comment by FFY00** [comment]
I am fine with this, we can easily remove it in the future if we want to.

**Comment by stephanlachnit** [comment]
> So yes in principal, it's always good to have more checks but it depends on the false positive ratio.

We don't have a lot of warning rn (most of the are FIXME reminders), some of them look irrelevant in our case (like the python `__eq__` warnings).
But there is also a good warning which we didn't spot when merging #951 (88a60f55b441c5c8484c7845e0dcf4a7ad0715f0), `ratbag_device_data_hidpp20_get_led_count()` should be in `libratbag-data.h`. @FFY00 can you fix this btw?

**Comment by stephanlachnit** [comment]
I enabled it now, I pushed #870 to test it if you want to have a look.
