### ISSUE TITLE
Endless loop on startup

### ISSUE THREAD

**Issue by jdz** [libratbag/libratbag#959]
**Information**

- `ratbagd` version (`ratbagd --version`): `0.13` (`ee73434`)
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `Linux 5.6.4-arch1-1 x86_64 GNU/Linux`

**Describe the bug**
Initially I was stuck with `ratbagctl list` only telling me the following:

    Unable to connect to ratbagd: Make sure it is running and your user is in the required groups.

Running `ratbagd` with `--verbose=raw` revealed that it is stuck in an endless loop reading memory page 0.

**To Reproduce**
Start `ratbagctl` when using "Logitech G9x Call of Duty MW3 Edition" mouse.

**Logs**

[ratbagd-shortened.log](https://github.com/libratbag/libratbag/files/4487456/ratbagd-shortened.log)

**Additional context**

Looking at the logs it seems there are problems reading macro data.  At first there are 13 suspicious ` *** macro starts at (0xff, 0x00fe) ***` messages starting on line 782 followed by suspicious all-`0xff` byte profile, then on line 1182 another one: `*** macro starts at (0x00, 0x0000) ***.  After this the loop starts, repeating every 768 lines.  First read seems to read "profiles" and 16 zero bytes, all other are just 15 zero bytes.

**Comment by stephanlachnit** [comment]
Can you to run it #913 merged?

**Comment by FFY00** [comment]
Either way this is awful, even with an incorrect .device file, it should definitelly be fixed.

**Comment by jdz** [comment]
> Can you to run it #913 merged?

Merged, and sadly nothing seems to have changed.  Except the first sequence of zero bytes on line 1188 is now the same as in all other reads (the `profile` part and one ` 00` disappeared):

```
ratbag raw: *** macro starts at (0x00, 0x0000) ***
ratbag raw: Reading memory page 0, offset 0
ratbag raw: hidpp10 tx:  10 | 00 | 83 | a2 | 00 00 00
ratbag raw: hidpp write:  10 00 83 a2 00 00 00
ratbag raw: hidpp read:   11 00 83 a2 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp10 rx:  11 | 00 | 83 | a2 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: ->  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: Reading memory page 0, offset 0xe
```

**Comment by FFY00** [comment]
Can you paste the output with #961?

**Comment by jdz** [comment]
> Can you paste the output with #961?

Here.
[ratbagd-d93894e.log](https://github.com/libratbag/libratbag/files/4487986/ratbagd-d93894e.log)

**Comment by FFY00** [comment]
I pushed a potential fix, could you try?

**Comment by jdz** [comment]
No more endless loop, and `ratbagctl list` shows the device.  Here is the log just in case:

[ratbagd-45e00ac.log](https://github.com/libratbag/libratbag/files/4488130/ratbagd-45e00ac.log)

**Comment by FFY00** [comment]
Looks good :)

**Comment by jdz** [comment]
> Looks good :)

Yes, thank you for the quick fix for this issue.

I'm not quite sure the profiles are read correctly, setting things does not seem to be working.  But that's another issue for another day maybe.  Is there any reference documentation about this or is it all reverse-engineered?

**Comment by FFY00** [comment]
Is it #900? If so you need #950.
