### ISSUE TITLE
G300s: "No supported devices found"

### ISSUE THREAD

**Issue by valeriodean** [libratbag/libratbag#96]
Hi,
these are the steps I have done:
1)
I installed libratbag from this corp:
https://copr.fedorainfracloud.org/coprs/bentiss/libratbag/
2)
Then I make sure the systemd service is enabled:
[valerio@valerio-casa ~]$ sudo systemctl status ratbagd.service 
● ratbagd.service - Daemon to introspect and modify configurable mice
   Loaded: loaded (/usr/lib/systemd/system/ratbagd.service; disabled; vendor preset: disabled
   Active: active (running) since mar 2016-09-06 18:21:48 CEST; 2s ago
 Main PID: 3284 (ratbagd)
    Tasks: 1 (limit: 512)
   CGroup: /system.slice/ratbagd.service
           └─3284 /usr/bin/ratbagd

set 06 18:21:48 valerio-casa systemd[1]: Starting Daemon to introspect and modify configurabl
set 06 18:21:48 valerio-casa systemd[1]: Started Daemon to introspect and modify configurable
3)
Then I anplug-replug the mouse (it is a G300s).
[valerio@valerio-casa ~]$ xinput --list
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Logitech USB Keyboard                     id=9    [slave  pointer  (2)]
⎜   ↳ Logitech G300s Optical Gaming Mouse       id=11   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Power Button                              id=7    [slave  keyboard (3)]
    ↳ Logitech USB Keyboard                     id=8    [slave  keyboard (3)]
    ↳ Logitech USB Keyboard                     id=12   [slave  keyboard (3)]
    ↳ Logitech G300s Optical Gaming Mouse       id=10   [slave  keyboard (3)]

5) 
run the command: ratbag-command list
[valerio@valerio-casa ~]$ sudo ratbag-command list
[sudo] password for valerio: 
**No supported devices found**

What I'm missed or what is wrong with the steps I have done?

Regards,
Valerio

**Comment by cvuchener** [comment]
You did nothing wrong.

libratbag only support devices listed in hwdb/70-libratbag-mouse.hwdb. You could try adding your mouse in it. Although I am not sure which version of HID++ it uses.

**Comment by phomes** [comment]
Hi,

I have the G300s too (or rather the G300 but there are only cosmetic
differences between them). It does not use either HID++ 1.0 or 2.0 but a
completely different protocol. I have figured out the protocol and started
writing the driver. I have the skeleton of driver and the structs for the
profile layout. I just need to fix an issue in the connection to the mouse.
I'll see if I can find some time this weekend to finish it.

Once it is done I will very much appreciate if you would test it.

- Thomas

**Comment by valeriodean** [comment]
Yeah, I'm ready for test and thank you! :-)

**Comment by stnikk** [comment]
I've been checking status of g300(s)-support quite religiously, working driver would be excellent news, esp. since it's a bargain-bin mouse. Thank you for going for it.

**Comment by phomes** [comment]
Hi,

Just a quick update on the G300(s) driver. I am making progress, but from
looking at my calendar I will probably not have time to complete it for a
few weeks.

**Comment by Wolf480pl** [comment]
@phomes could you, like, post what you've figured out so far somewhere on github, so that others (eg. me) can try to help make progress?

**Comment by Wolf480pl** [comment]
Is this fixed by #104 ?

**Comment by whot** [comment]
let's assume so based on the title in the PR :)
please re-open if it's still an issue
