### ISSUE TITLE
Question about button action types

### ISSUE THREAD

**Issue by beatussum** [libratbag/libratbag#973]
I would just like to know whether it is normal that, according to the [DBus API](https://libratbag.github.io/dbus.html#ActionTypes), `Macro` is described as having the value **3** while it seems  to have the value **4** [here](https://github.com/libratbag/libratbag/blob/master/src/libratbag-enums.h#L205).

**Comment by FFY00** [comment]
Yes, you correct, the documentation should be updated.

**Comment by beatussum** [comment]
Therefore, could I know the purpose of [`RATBAG_BUTTON_ACTION_TYPE_KEY`](https://github.com/libratbag/libratbag/blob/master/src/libratbag-enums.h#L201)?

**Comment by FFY00** [comment]
To send remap to simple key events. I don't remember exactly but we might have removed that already, we should be using the macro action instead.
