### ISSUE TITLE
Support For Keyboards/specific Headsets

### ISSUE THREAD

**Issue by UltraBlackLinux** [libratbag/libratbag#977]
**Is your feature request related to a problem? Please describe.**
I want to buy a Logitech Headset, and would love to have support for (Gaming)Keyboards and Headsets (e.g. Logitech G635 -> 3 programmable keys), cause xbindkeys Is quite, well not-gui-ish.

Is there anything discussed rn?

**Comment by FFY00** [comment]
It might be possible. Please try creating a .device file and report back. It should probably use the HID++ 2.0 protocol, you can base your .device file on any recent Logitech device.

See https://github.com/libratbag/libratbag/wiki/Adding-a-device

**Comment by FFY00** [comment]
Agh, sorry. Just re-read your message and I noticed you don't have it yet. There's nothing we can do without the hardware

**Comment by UltraBlackLinux** [comment]
@FFY00 So ill buy it next month. Can u tell me, how I can do this at all? Then i could do that then.

**Comment by UltraBlackLinux** [comment]
@FFY00 I bought the headset now, since my old one broke apart. I actually added the file, but piper doesnt recognize my headset now - how do i do that?

**Comment by FFY00** [comment]
Please paste the log when starting the daemon with verbosity.

Make sure `ratbagd` is not running (`killall ratbagd`).
```
ratbagd --verbose=raw
```

You can also install `hid-tools` and paste the output of `hid-recorder` on each endpoint of your device. When running `hid-recorder` you can ctrl+c right away, I am just interested in the initial information it spits out.

**Comment by UltraBlackLinux** [comment]
https://gist.github.com/UltraBlackLinux/09264003232ada420e66fb34716fc682
Idk what is the part you mean, so thats everything it tells me...

**Comment by FFY00** [comment]
It looks promising. I will have to contact Logitech to get some documentation about this.

**Comment by UltraBlackLinux** [comment]
@FFY00 Thanks four your Effort, highly appreciate that!

**Comment by FFY00** [comment]
Can you remove the `DeviceIndex` entry? (you can remove the `Driver/hidpp20` section altogether)

**Comment by UltraBlackLinux** [comment]
yeheheheeees :D piper recognizes it now, but It wants to set 8 mouse Keys, even though I only have 3 keys on the headset. Solution?

**Comment by FFY00** [comment]
We can overwrite that. Please submit a PR adding the .device file.

Is everything else working as expected?

**Comment by UltraBlackLinux** [comment]
yeah LEDs work as expected. Could be a problem, that you cant set the keys back to mute and stuff (original key pourpose), cause libratbag doesnt support it...
