### ISSUE TITLE
ratbagd error: Failed to start ratbagd: Permission denied

### ISSUE THREAD

**Issue by n3bojs4** [libratbag/libratbag#981]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.13   ( commit 768d93a45a33dbcb6f664c8255587e21c6e7f354 )
- Distribution:  Kali rolling
- Kernel version (ex. `uname -srmo`): `Linux 4.19.0-kali3-amd64 x86_64 GNU/Linux`

Device info (if applicable):
```
$ ratbagctl <device> info
OUTPUT HERE
```

**Describe the bug**
After compiling and installing ratbagd, starting it return this error :

root@XXXX:~# /usr/local/bin/ratbagd --verbose=debug
Initializing libratbag
ratbagd error: Failed to start ratbagd: Permission denied

**To Reproduce**
1. lauch ratbagd as root or via a sudo

**Fix**

I found the fix :  

`cp -p /usr/local/share/dbus-1/system.d/org.freedesktop.ratbag1.conf /usr/share/dbus-1/system.d/`

**Logs**

Initializing libratbag
ratbagd error: Failed to start ratbagd: Permission denied

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
Initializing libratbag
ratbagd error: Failed to start ratbagd: Permission denied
```

**Additional context**
See fix section. The org.freedesktop.ratbag1.conf file is not copied in the good place when launching `sudo ninja -C builddir install`

Now it's working:

```
#:/usr/share/dbus-1/system.d# ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Kingston HyperX 7.1 Audio
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 0951:16a4
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c539
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c539
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c539
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c541
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c541
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c541
DBus server ready
```

**Comment by FFY00** [comment]
Set the prefix when calling meson `--prefix=/usr` otherwise you will have to edit the polkit permissions to spawn the DBus server.

**Comment by n3bojs4** [comment]
Hello,
Yes i just opened the ticket for improve the documentation maybe , at least this is a log for every person in trouble with this error.

**Comment by hfc2x** [comment]
Sorry for necrobumping, but it seems that when building from source, `/usr/share/systemd/system/ratbagd.service` is not created either. Trying to start the libratbagd service throws an error because `libratbagd.service` does not exist.

**Comment by staticssleever668** [comment]
@hfc2x, hi! Service installation directory is controlled by `-Dsystemd-unit-dir`, put it also reacts to `--prefix` and shows a message `systemd unitdir libdir mismatch detected, changing unitdir to.. /usr/lib/systemd/system`.
To get rid of the warning pass e.g. `-Dsystemd-unit-dir=/usr/lib/systemd/system`.

> error because libratbagd.service does not exist.

Could you have wanted to start `ratbagd.service` instead?

---

Regarding the issue itself, it's mentioned in README as `The default prefix is /usr/local`.

**Comment by hfc2x** [comment]
> `-Dsystemd-unit-dir=/usr/lib/systemd/system`

Okay, that worked.
Maybe this should be included in the main instructions.
