### ISSUE TITLE
Logitech G502 Wireless battery level on Ratbag v0.13

### ISSUE THREAD

**Issue by moll** [libratbag/libratbag#982]
Hey,

Thanks for maintaining Ratbag! Is there supposed to be a battery level readout somewhere in `ratbagctl info` or Piper's GUI for the Logitech G502 Wireless version? I'm not spotting one. This with the `usb:046d:407f:` model as reported by `ratbagctl info`.

Thanks in advance!

**Comment by FFY00** [comment]
Your device doesn't support reading the battery percentage, just the voltage. Solaar should be able to do it.

**Comment by moll** [comment]
Ah, thanks. I presumed Ratbag would handle that part, too. So Ratbag's intended only for configuring buttons, DPIs and LEDs, and not for showing auxiliary information about the mouse? Solaar in turn is about handling those Logitech devices that require userspace behavior to work? The G502 here started working straight after plugging it in without Solaar. Does having Solaar help at all then? 

Gave Solaar a try for the battery level and turns out it too doesn't seem to support reading the battery voltage. Merely shows "unknown". I figure I'll have to investigate and possibly open an issue on https://github.com/pwr-Solaar/Solaar for that.

Thanks again!
